import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { UnauthorizedError, ForbiddenError, TooManyRequestsError } from '@pikku/core/errors'

export const SearchInput = z.object({
  q: z.string().describe("Your search query.\n\nYou can narrow down your search using field filters. The available filters are `album`, `artist`, `track`, `year`, `upc`, `tag:hipster`, `tag:new`, `isrc`, and `genre`. Each field filter only applies to certain result types.\n\nThe `artist` and `year` filters can be used while searching albums, artists and tracks. You can filter on a single `year` or a range (e.g. 1955-1960).<br />\nThe `album` filter can be used while searching albums and tracks.<br />\nThe `genre` filter can be used while searching artists and tracks.<br />\nThe `isrc` and `track` filters can be used while searching tracks.<br />\nThe `upc`, `tag:new` and `tag:hipster` filters can only be used while searching albums. The `tag:new` filter will return albums released in the past two weeks and `tag:hipster` can be used to return only albums with the lowest 10% popularity.<br />\n"),
  type: z.array(z.enum(["album", "artist", "playlist", "track", "show", "episode", "audiobook"])).describe("A comma-separated list of item types to search across. Search results include hits\nfrom all the specified item types. For example: `q=abacab&type=album,track` returns\nboth albums and tracks matching \"abacab\".\n"),
  market: z.string().optional().describe("An [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).\n  If a country code is specified, only content that is available in that market will be returned.<br/>\n  If a valid user access token is specified in the request header, the country associated with\n  the user account will take priority over this parameter.<br/>\n  _**Note**: If neither market or user country are provided, the content is considered unavailable for the client._<br/>\n  Users can view the country that is associated with their account in the [account settings](https://www.spotify.com/se/account/overview/).\n"),
  limit: z.number().int().min(1).max(50).optional().default(20).describe("The maximum number of results to return in each item type.\n"),
  offset: z.number().int().min(0).max(1000).optional().default(0).describe("The index of the first result to return. Use\nwith limit to get the next page of search results.\n"),
  include_external: z.literal("audio").optional().describe("If `include_external=audio` is specified it signals that the client can play externally hosted audio content, and marks\nthe content as playable in the response. By default externally hosted audio content is marked as unplayable in the response.\n"),
})

export const SearchOutput = z.object({
  albums: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      album_type: z.enum(["album", "single", "compilation"]).describe("The type of the album.\n"),
      available_markets: z.array(z.string()).describe("The markets in which the album is available: [ISO 3166-1 alpha-2 country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). _**NOTE**: an album is considered available in a market when at least 1 of its tracks is available in that market._\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).describe("Known external URLs for this album.\n"),
      href: z.string().describe("A link to the Web API endpoint providing full details of the album.\n"),
      id: z.string().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the album.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).describe("The cover art for the album in various sizes, widest first.\n"),
      name: z.string().describe("The name of the album. In case of an album takedown, the value may be an empty string.\n"),
      release_date: z.string().describe("The date the album was first released.\n"),
      release_date_precision: z.enum(["year", "month", "day"]).describe("The precision with which `release_date` value is known.\n"),
      restrictions: z.object({
        reason: z.enum(["market", "product", "explicit"]).optional().describe("The reason for the restriction. Albums may be restricted if the content is not available in a given market, to the user's subscription type, or when the user's account is set to not play explicit content.\nAdditional reasons may be added in the future.\n"),
      }).optional().describe("Included in the response when a content restriction is applied.\n"),
      total_tracks: z.number().int().describe("The number of tracks in the album."),
      type: z.literal("album").describe("The object type.\n"),
      uri: z.string().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the album.\n"),
      album_group: z.enum(["album", "single", "compilation", "appears_on"]).optional().describe("The field is present when getting an artist's albums. Compare to album_type this field represents relationship between the artist and the album.\n"),
      artists: z.array(z.object({
        external_urls: z.object({
          spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
        }).optional().describe("Known external URLs for this artist.\n"),
        href: z.string().optional().describe("A link to the Web API endpoint providing full details of the artist.\n"),
        id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
        name: z.string().optional().describe("The name of the artist.\n"),
        type: z.literal("artist").optional().describe("The object type.\n"),
        uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
      })).describe("The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist.\n"),
    })),
  }).optional(),
  artists: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).optional().describe("Known external URLs for this artist.\n"),
      followers: z.object({
        href: z.string().nullable().optional().describe("This will always be set to null, as the Web API does not support it at the moment.\n"),
        total: z.number().int().optional().describe("The total number of followers.\n"),
      }).optional().describe("Information about the followers of the artist.\n"),
      genres: z.array(z.string()).optional().describe("A list of the genres the artist is associated with. If not yet classified, the array is empty.\n"),
      href: z.string().optional().describe("A link to the Web API endpoint providing full details of the artist.\n"),
      id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).optional().describe("Images of the artist in various sizes, widest first.\n"),
      name: z.string().optional().describe("The name of the artist.\n"),
      popularity: z.number().int().optional().describe("The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.\n"),
      type: z.literal("artist").optional().describe("The object type.\n"),
      uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
    })),
  }).optional(),
  audiobooks: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      authors: z.array(z.object({
        name: z.string().optional().describe("The name of the author.\n"),
      })).describe("The author(s) for the audiobook.\n"),
      available_markets: z.array(z.string()).describe("A list of the countries in which the audiobook can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n"),
      copyrights: z.array(z.object({
        text: z.string().optional().describe("The copyright text for this content.\n"),
        type: z.string().optional().describe("The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright.\n"),
      })).describe("The copyright statements of the audiobook.\n"),
      description: z.string().describe("A description of the audiobook. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n"),
      edition: z.string().optional().describe("The edition of the audiobook.\n"),
      explicit: z.boolean().describe("Whether or not the audiobook has explicit content (true = yes it does; false = no it does not OR unknown).\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).describe("External URLs for this audiobook.\n"),
      href: z.string().describe("A link to the Web API endpoint providing full details of the audiobook.\n"),
      html_description: z.string().describe("A description of the audiobook. This field may contain HTML tags.\n"),
      id: z.string().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the audiobook.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).describe("The cover art for the audiobook in various sizes, widest first.\n"),
      languages: z.array(z.string()).describe("A list of the languages used in the audiobook, identified by their [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code.\n"),
      media_type: z.string().describe("The media type of the audiobook.\n"),
      name: z.string().describe("The name of the audiobook.\n"),
      narrators: z.array(z.object({
        name: z.string().optional().describe("The name of the Narrator.\n"),
      })).describe("The narrator(s) for the audiobook.\n"),
      publisher: z.string().describe("The publisher of the audiobook.\n"),
      total_chapters: z.number().int().describe("The number of chapters in this audiobook.\n"),
      type: z.literal("audiobook").describe("The object type.\n"),
      uri: z.string().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the audiobook.\n"),
    })),
  }).optional(),
  episodes: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      audio_preview_url: z.string().describe("A URL to a 30 second preview (MP3 format) of the episode. `null` if not available.\n"),
      description: z.string().describe("A description of the episode. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n"),
      duration_ms: z.number().int().describe("The episode length in milliseconds.\n"),
      explicit: z.boolean().describe("Whether or not the episode has explicit content (true = yes it does; false = no it does not OR unknown).\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).describe("External URLs for this episode.\n"),
      href: z.string().describe("A link to the Web API endpoint providing full details of the episode.\n"),
      html_description: z.string().describe("A description of the episode. This field may contain HTML tags.\n"),
      id: z.string().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the episode.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).describe("The cover art for the episode in various sizes, widest first.\n"),
      is_externally_hosted: z.boolean().describe("True if the episode is hosted outside of Spotify's CDN.\n"),
      is_playable: z.boolean().describe("True if the episode is playable in the given market. Otherwise false.\n"),
      language: z.string().optional().describe("The language used in the episode, identified by a [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code. This field is deprecated and might be removed in the future. Please use the `languages` field instead.\n"),
      languages: z.array(z.string()).describe("A list of the languages used in the episode, identified by their [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639) code.\n"),
      name: z.string().describe("The name of the episode.\n"),
      release_date: z.string().describe("The date the episode was first released, for example `\"1981-12-15\"`. Depending on the precision, it might be shown as `\"1981\"` or `\"1981-12\"`.\n"),
      release_date_precision: z.enum(["year", "month", "day"]).describe("The precision with which `release_date` value is known.\n"),
      restrictions: z.object({
        reason: z.string().optional().describe("The reason for the restriction. Supported values:\n- `market` - The content item is not available in the given market.\n- `product` - The content item is not available for the user's subscription type.\n- `explicit` - The content item is explicit and the user's account is set to not play explicit content.\n\nAdditional reasons may be added in the future.\n**Note**: If you use this field, make sure that your application safely handles unknown values.\n"),
      }).optional().describe("Included in the response when a content restriction is applied.\n"),
      resume_point: z.object({
        fully_played: z.boolean().optional().describe("Whether or not the episode has been fully played by the user.\n"),
        resume_position_ms: z.number().int().optional().describe("The user's most recent position in the episode in milliseconds.\n"),
      }).describe("The user's most recent position in the episode. Set if the supplied access token is a user token and has the scope 'user-read-playback-position'.\n"),
      type: z.literal("episode").describe("The object type.\n"),
      uri: z.string().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the episode.\n"),
    })),
  }).optional(),
  playlists: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      collaborative: z.boolean().optional().describe("`true` if the owner allows other users to modify the playlist.\n"),
      description: z.string().optional().describe("The playlist description. _Only returned for modified, verified playlists, otherwise_ `null`.\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).optional().describe("Known external URLs for this playlist.\n"),
      href: z.string().optional().describe("A link to the Web API endpoint providing full details of the playlist.\n"),
      id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the playlist.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).optional().describe("Images for the playlist. The array may be empty or contain up to three images. The images are returned by size in descending order. See [Working with Playlists](/documentation/general/guides/working-with-playlists/). _**Note**: If returned, the source URL for the image (`url`) is temporary and will expire in less than a day._\n"),
      name: z.string().optional().describe("The name of the playlist.\n"),
      owner: z.unknown().optional().describe("The user who owns the playlist\n"),
      public: z.boolean().optional().describe("The playlist's public/private status: `true` the playlist is public, `false` the playlist is private, `null` the playlist status is not relevant. For more about public/private status, see [Working with Playlists](/documentation/general/guides/working-with-playlists/)\n"),
      snapshot_id: z.string().optional().describe("The version identifier for the current playlist. Can be supplied in other requests to target a specific playlist version\n"),
      tracks: z.object({
        href: z.string().optional().describe("A link to the Web API endpoint where full details of the playlist's tracks can be retrieved.\n"),
        total: z.number().int().optional().describe("Number of tracks in the playlist.\n"),
      }).optional().describe("A collection containing a link ( `href` ) to the Web API endpoint where full details of the playlist's tracks can be retrieved, along with the `total` number of tracks in the playlist. Note, a track object may be `null`. This can happen if a track is no longer available.\n"),
      type: z.string().optional().describe("The object type: \"playlist\"\n"),
      uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the playlist.\n"),
    })),
  }).optional(),
  shows: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      available_markets: z.array(z.string()).describe("A list of the countries in which the show can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n"),
      copyrights: z.array(z.object({
        text: z.string().optional().describe("The copyright text for this content.\n"),
        type: z.string().optional().describe("The type of copyright: `C` = the copyright, `P` = the sound recording (performance) copyright.\n"),
      })).describe("The copyright statements of the show.\n"),
      description: z.string().describe("A description of the show. HTML tags are stripped away from this field, use `html_description` field in case HTML tags are needed.\n"),
      explicit: z.boolean().describe("Whether or not the show has explicit content (true = yes it does; false = no it does not OR unknown).\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).describe("External URLs for this show.\n"),
      href: z.string().describe("A link to the Web API endpoint providing full details of the show.\n"),
      html_description: z.string().describe("A description of the show. This field may contain HTML tags.\n"),
      id: z.string().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the show.\n"),
      images: z.array(z.object({
        height: z.number().int().nullable().describe("The image height in pixels.\n"),
        url: z.string().describe("The source URL of the image.\n"),
        width: z.number().int().nullable().describe("The image width in pixels.\n"),
      })).describe("The cover art for the show in various sizes, widest first.\n"),
      is_externally_hosted: z.boolean().describe("True if all of the shows episodes are hosted outside of Spotify's CDN. This field might be `null` in some cases.\n"),
      languages: z.array(z.string()).describe("A list of the languages used in the show, identified by their [ISO 639](https://en.wikipedia.org/wiki/ISO_639) code.\n"),
      media_type: z.string().describe("The media type of the show.\n"),
      name: z.string().describe("The name of the episode.\n"),
      publisher: z.string().describe("The publisher of the show.\n"),
      total_episodes: z.number().int().describe("The total number of episodes in the show.\n"),
      type: z.literal("show").describe("The object type.\n"),
      uri: z.string().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the show.\n"),
    })),
  }).optional(),
  tracks: z.object({
    href: z.string().describe("A link to the Web API endpoint returning the full result of the request\n"),
    limit: z.number().int().describe("The maximum number of items in the response (as set in the query or by default).\n"),
    next: z.string().nullable().describe("URL to the next page of items. ( `null` if none)\n"),
    offset: z.number().int().describe("The offset of the items returned (as set in the query or by default)\n"),
    previous: z.string().nullable().describe("URL to the previous page of items. ( `null` if none)\n"),
    total: z.number().int().describe("The total number of items available to return.\n"),
    items: z.array(z.object({
      album: z.unknown().optional().describe("The album on which the track appears. The album object includes a link in `href` to full information about the album.\n"),
      artists: z.array(z.object({
        external_urls: z.object({
          spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
        }).optional().describe("Known external URLs for this artist.\n"),
        followers: z.object({
          href: z.string().nullable().optional().describe("This will always be set to null, as the Web API does not support it at the moment.\n"),
          total: z.number().int().optional().describe("The total number of followers.\n"),
        }).optional().describe("Information about the followers of the artist.\n"),
        genres: z.array(z.string()).optional().describe("A list of the genres the artist is associated with. If not yet classified, the array is empty.\n"),
        href: z.string().optional().describe("A link to the Web API endpoint providing full details of the artist.\n"),
        id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
        images: z.array(z.object({
          height: z.number().int().nullable().describe("The image height in pixels.\n"),
          url: z.string().describe("The source URL of the image.\n"),
          width: z.number().int().nullable().describe("The image width in pixels.\n"),
        })).optional().describe("Images of the artist in various sizes, widest first.\n"),
        name: z.string().optional().describe("The name of the artist.\n"),
        popularity: z.number().int().optional().describe("The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.\n"),
        type: z.literal("artist").optional().describe("The object type.\n"),
        uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the artist.\n"),
      })).optional().describe("The artists who performed the track. Each artist object includes a link in `href` to more detailed information about the artist.\n"),
      available_markets: z.array(z.string()).optional().describe("A list of the countries in which the track can be played, identified by their [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code.\n"),
      disc_number: z.number().int().optional().describe("The disc number (usually `1` unless the album consists of more than one disc).\n"),
      duration_ms: z.number().int().optional().describe("The track length in milliseconds.\n"),
      explicit: z.boolean().optional().describe("Whether or not the track has explicit lyrics ( `true` = yes it does; `false` = no it does not OR unknown).\n"),
      external_ids: z.object({
        ean: z.string().optional().describe("[International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)\n"),
        isrc: z.string().optional().describe("[International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)\n"),
        upc: z.string().optional().describe("[Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)\n"),
      }).optional().describe("Known external IDs for the track.\n"),
      external_urls: z.object({
        spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
      }).optional().describe("Known external URLs for this track.\n"),
      href: z.string().optional().describe("A link to the Web API endpoint providing full details of the track.\n"),
      id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the track.\n"),
      is_local: z.boolean().optional().describe("Whether or not the track is from a local file.\n"),
      is_playable: z.boolean().optional().describe("Part of the response when [Track Relinking](/documentation/general/guides/track-relinking-guide/) is applied. If `true`, the track is playable in the given market. Otherwise `false`.\n"),
      linked_from: z.object({
        external_urls: z.object({
          spotify: z.string().optional().describe("The [Spotify URL](/documentation/web-api/#spotify-uris-and-ids) for the object.\n"),
        }).optional().describe("Known external URLs for this track.\n"),
        href: z.string().optional().describe("A link to the Web API endpoint providing full details of the track.\n"),
        id: z.string().optional().describe("The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the track.\n"),
        type: z.string().optional().describe("The object type: \"track\".\n"),
        uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the track.\n"),
      }).optional().describe("Part of the response when [Track Relinking](/documentation/general/guides/track-relinking-guide/) is applied and is only part of the response if the track linking, in fact, exists. The requested track has been replaced with a different track. The track in the `linked_from` object contains information about the originally requested track."),
      name: z.string().optional().describe("The name of the track.\n"),
      popularity: z.number().int().optional().describe("The popularity of the track. The value will be between 0 and 100, with 100 being the most popular.<br/>The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are.<br/>Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past. Duplicate tracks (e.g. the same track from a single and an album) are rated independently. Artist and album popularity is derived mathematically from track popularity. _**Note**: the popularity value may lag actual popularity by a few days: the value is not updated in real time._\n"),
      preview_url: z.string().optional().describe("A link to a 30 second preview (MP3 format) of the track. Can be `null`\n"),
      restrictions: z.object({
        reason: z.string().optional().describe("The reason for the restriction. Supported values:\n- `market` - The content item is not available in the given market.\n- `product` - The content item is not available for the user's subscription type.\n- `explicit` - The content item is explicit and the user's account is set to not play explicit content.\n\nAdditional reasons may be added in the future.\n**Note**: If you use this field, make sure that your application safely handles unknown values.\n"),
      }).optional().describe("Included in the response when a content restriction is applied.\n"),
      track_number: z.number().int().optional().describe("The number of the track. If an album has several discs, the track number is the number on the specified disc.\n"),
      type: z.literal("track").optional().describe("The object type: \"track\".\n"),
      uri: z.string().optional().describe("The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the track.\n"),
    })),
  }).optional(),
})

export const search = pikkuSessionlessFunc({
  description: "Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string.<br />\n**Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**",
  input: SearchInput,
  output: SearchOutput,
  errors: [UnauthorizedError, ForbiddenError, TooManyRequestsError],
  func: async ({ spotify }, data) => {
    return spotify.call("GET", "/search", data) as any
  },
})
