// Machines — This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/machines-resource/) for details about using the Machines resource.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const MachinesCreateInput = z.object({
  app_name: z.string().describe("Fly App Name"),
  config: z.object({
  auto_destroy: z.boolean().optional().describe("Optional boolean telling the Machine to destroy itself once it’s complete (default false)"),
  checks: z.record(z.string(), z.object({
    grace_period: z.object({
      "time.Duration": z.number().int().optional(),
    }).optional().describe("The time to wait after a VM starts before checking its health"),
    headers: z.array(z.object({
      name: z.string().optional().describe("The header name"),
      values: z.array(z.string()).optional().describe("The header value"),
    })).optional(),
    interval: z.object({
      "time.Duration": z.number().int().optional(),
    }).optional().describe("The time between connectivity checks"),
    kind: z.enum(["informational", "readiness"]).optional().describe("Kind of the check (informational, readiness)"),
    method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
    path: z.string().optional().describe("For http checks, the path to send the request to"),
    port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
    protocol: z.string().optional().describe("For http checks, whether to use http or https"),
    timeout: z.object({
      "time.Duration": z.number().int().optional(),
    }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
    tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
    tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
    type: z.string().optional().describe("tcp or http"),
  })).optional().describe("An optional object that defines one or more named top-level checks. The key for each check is the check name."),
  containers: z.array(z.object({
    cmd: z.array(z.string()).optional().describe("CmdOverride is used to override the default command of the image."),
    depends_on: z.array(z.object({
      condition: z.unknown().optional(),
      name: z.string().optional(),
    })).optional().describe("DependsOn can be used to define dependencies between containers. The container will only be\nstarted after all of its dependent conditions have been satisfied."),
    entrypoint: z.array(z.string()).optional().describe("EntrypointOverride is used to override the default entrypoint of the image."),
    env: z.record(z.string(), z.string()).optional().describe("ExtraEnv is used to add additional environment variables to the container."),
    env_from: z.array(z.object({
      env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
      field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
    })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
    exec: z.array(z.string()).optional().describe("Image Config overrides - these fields are used to override the image configuration.\nIf not provided, the image configuration will be used.\nExecOverride is used to override the default command of the image."),
    files: z.array(z.object({
      guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
      image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
      mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
      raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
      secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
    })).optional().describe("Files are files that will be written to the container file system."),
    healthchecks: z.array(z.object({
      exec: z.object({
        command: z.array(z.string()).optional().describe("The command to run to check the health of the container (e.g. [\"cat\", \"/tmp/healthy\"])"),
      }).optional(),
      failure_threshold: z.number().int().optional().describe("The number of times the check must fail before considering the container unhealthy."),
      grace_period: z.number().int().optional().describe("The time in seconds to wait after a container starts before checking its health."),
      http: z.object({
        headers: z.array(z.object({
          name: z.string().optional().describe("The header name"),
          values: z.array(z.string()).optional().describe("The header value"),
        })).optional().describe("Additional headers to send with the request"),
        method: z.string().optional().describe("The HTTP method to use to when making the request"),
        path: z.string().optional().describe("The path to send the request to"),
        port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
        scheme: z.unknown().optional().describe("Whether to use http or https"),
        tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
        tls_skip_verify: z.boolean().optional().describe("If the protocol is https, whether or not to verify the TLS certificate"),
      }).optional(),
      interval: z.number().int().optional().describe("The time in seconds between executing the defined check."),
      kind: z.unknown().optional().describe("Kind of healthcheck (readiness, liveness)"),
      name: z.string().optional().describe("The name of the check. Must be unique within the container."),
      success_threshold: z.number().int().optional().describe("The number of times the check must succeeed before considering the container healthy."),
      tcp: z.object({
        port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
      }).optional(),
      timeout: z.number().int().optional().describe("The time in seconds to wait for the check to complete."),
      unhealthy: z.unknown().optional().describe("Unhealthy policy that determines what action to take if a container is deemed unhealthy"),
    })).optional().describe("Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command."),
    image: z.string().optional().describe("Image is the docker image to run."),
    name: z.string().optional().describe("Name is used to identify the container in the machine."),
    restart: z.object({
      gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
      max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
      policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
    }).optional().describe("Restart is used to define the restart policy for the container. NOTE: spot-price is not\nsupported for containers."),
    secrets: z.array(z.object({
      env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
      name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
    })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
    stop: z.object({
      signal: z.string().optional(),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional(),
    }).optional().describe("Stop is used to define the signal and timeout for stopping the container."),
    user: z.string().optional().describe("UserOverride is used to override the default user of the image."),
  })).optional().describe("Containers are a list of containers that will run in the machine. Currently restricted to\nonly specific organizations."),
  disable_machine_autostart: z.boolean().optional().describe("Deprecated: use Service.Autostart instead"),
  dns: z.object({
    dns_forward_rules: z.array(z.object({
      addr: z.string().optional(),
      basename: z.string().optional(),
    })).optional(),
    hostname: z.string().optional(),
    hostname_fqdn: z.string().optional(),
    nameservers: z.array(z.string()).optional(),
    options: z.array(z.object({
      name: z.string().optional(),
      value: z.string().optional(),
    })).optional(),
    searches: z.array(z.string()).optional(),
    skip_registration: z.boolean().optional(),
  }).optional(),
  env: z.record(z.string(), z.string()).optional().describe("An object filled with key/value pairs to be set as environment variables"),
  files: z.array(z.object({
    guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
    image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
    mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
    raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
    secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
  })).optional(),
  guest: z.object({
    cpu_kind: z.string().optional(),
    cpus: z.number().int().optional(),
    gpu_kind: z.string().optional(),
    gpus: z.number().int().optional(),
    host_dedication_id: z.string().optional(),
    kernel_args: z.array(z.string()).optional(),
    memory_mb: z.number().int().optional(),
    persist_rootfs: z.enum(["never", "always", "restart"]).optional().describe("Deprecated: use MachineConfig.Rootfs instead"),
  }).optional(),
  image: z.string().optional().describe("The docker image to run"),
  init: z.object({
    cmd: z.array(z.string()).optional(),
    entrypoint: z.array(z.string()).optional(),
    exec: z.array(z.string()).optional(),
    kernel_args: z.array(z.string()).optional(),
    swap_size_mb: z.number().int().optional(),
    tty: z.boolean().optional(),
  }).optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  metrics: z.object({
    https: z.boolean().optional(),
    path: z.string().optional(),
    port: z.number().int().optional(),
  }).optional(),
  mounts: z.array(z.object({
    add_size_gb: z.number().int().optional(),
    encrypted: z.boolean().optional(),
    extend_threshold_percent: z.number().int().optional(),
    name: z.string().optional(),
    path: z.string().optional(),
    size_gb: z.number().int().optional(),
    size_gb_limit: z.number().int().optional(),
    volume: z.string().optional(),
  })).optional(),
  processes: z.array(z.object({
    cmd: z.array(z.string()).optional(),
    entrypoint: z.array(z.string()).optional(),
    env: z.record(z.string(), z.string()).optional(),
    env_from: z.array(z.object({
      env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
      field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
    })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
    exec: z.array(z.string()).optional(),
    ignore_app_secrets: z.boolean().optional().describe("IgnoreAppSecrets can be set to true to ignore the secrets for the App the Machine belongs to\nand only use the secrets provided at the process level. The default/legacy behavior is to use\nthe secrets provided at the App level."),
    secrets: z.array(z.object({
      env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
      name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
    })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
    user: z.string().optional(),
  })).optional(),
  restart: z.object({
    gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
    max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
    policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
  }).optional().describe("The Machine restart policy defines whether and how flyd restarts a Machine after its main process exits. See https://fly.io/docs/machines/guides-examples/machine-restart-policy/."),
  rootfs: z.object({
    fs_size_gb: z.number().int().optional(),
    persist: z.enum(["never", "always", "restart"]).optional(),
    size_gb: z.number().int().optional(),
  }).optional(),
  schedule: z.string().optional(),
  services: z.array(z.object({
    autostart: z.boolean().optional(),
    autostop: z.enum(["off", "stop", "suspend"]).optional().describe("Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for \"off\" and \"stop\" in responses.\n* \"off\" or false - Do not autostop the Machine.\n* \"stop\" or true - Automatically stop the Machine.\n* \"suspend\" - Automatically suspend the Machine, falling back to a full stop if this is not possible."),
    checks: z.array(z.object({
      grace_period: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time to wait after a VM starts before checking its health"),
      headers: z.array(z.object({
        name: z.string().optional().describe("The header name"),
        values: z.array(z.string()).optional().describe("The header value"),
      })).optional(),
      interval: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time between connectivity checks"),
      method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
      path: z.string().optional().describe("For http checks, the path to send the request to"),
      port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
      protocol: z.string().optional().describe("For http checks, whether to use http or https"),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
      tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
      tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
      type: z.string().optional().describe("tcp or http"),
    })).optional().describe("An optional list of service checks"),
    concurrency: z.object({
      hard_limit: z.number().int().optional(),
      soft_limit: z.number().int().optional(),
      type: z.string().optional(),
    }).optional(),
    force_instance_description: z.string().optional(),
    force_instance_key: z.string().optional(),
    internal_port: z.number().int().optional(),
    min_machines_running: z.number().int().optional(),
    ports: z.array(z.object({
      end_port: z.number().int().optional(),
      force_https: z.boolean().optional(),
      handlers: z.array(z.string()).optional(),
      http_options: z.object({
        compress: z.boolean().optional(),
        h2_backend: z.boolean().optional(),
        headers_read_timeout: z.number().int().optional(),
        idle_timeout: z.number().int().optional(),
        replay_cache: z.array(z.object({
          allow_bypass: z.boolean().optional(),
          name: z.string().optional().describe("Name of the cookie or header to key the cache on"),
          path_prefix: z.string().optional(),
          ttl_seconds: z.number().int().optional(),
          type: z.enum(["cookie", "header"]).optional().describe("Currently either \"cookie\" or \"header\""),
        })).optional(),
        response: z.object({
          headers: z.record(z.string(), z.record(z.string(), z.unknown())).optional(),
          pristine: z.boolean().optional(),
        }).optional(),
      }).optional(),
      port: z.number().int().optional(),
      proxy_proto_options: z.object({
        version: z.string().optional(),
      }).optional(),
      start_port: z.number().int().optional(),
      tls_options: z.object({
        alpn: z.array(z.string()).optional(),
        default_self_signed: z.boolean().optional(),
        versions: z.array(z.string()).optional(),
      }).optional(),
    })).optional(),
    protocol: z.string().optional(),
  })).optional(),
  size: z.string().optional().describe("Deprecated: use Guest instead"),
  standbys: z.array(z.string()).optional().describe("Standbys enable a machine to be a standby for another. In the event of a hardware failure,\nthe standby machine will be started."),
  statics: z.array(z.object({
    guest_path: z.string(),
    index_document: z.string().optional(),
    tigris_bucket: z.string().optional(),
    url_prefix: z.string(),
  })).optional(),
  stop_config: z.object({
    signal: z.string().optional(),
    timeout: z.object({
      "time.Duration": z.number().int().optional(),
    }).optional(),
  }).optional(),
}).optional().describe("An object defining the Machine configuration").describe("An object defining the Machine configuration"),
  lease_ttl: z.number().int().optional(),
  lsvd: z.boolean().optional(),
  min_secrets_version: z.number().int().optional(),
  name: z.string().optional().describe("Unique name for this Machine. If omitted, one is generated for you").describe("Unique name for this Machine. If omitted, one is generated for you"),
  region: z.string().optional().describe("The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you).").describe("The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you)."),
  skip_launch: z.boolean().optional(),
  skip_secrets: z.boolean().optional(),
  skip_service_registration: z.boolean().optional(),
})

export const MachinesCreateOutput = z.object({
  checks: z.array(z.object({
    name: z.string().optional(),
    output: z.string().optional(),
    status: z.string().optional(),
    updated_at: z.string().optional(),
  })).optional(),
  config: z.object({
    auto_destroy: z.boolean().optional().describe("Optional boolean telling the Machine to destroy itself once it’s complete (default false)"),
    checks: z.record(z.string(), z.object({
      grace_period: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time to wait after a VM starts before checking its health"),
      headers: z.array(z.object({
        name: z.string().optional().describe("The header name"),
        values: z.array(z.string()).optional().describe("The header value"),
      })).optional(),
      interval: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time between connectivity checks"),
      kind: z.enum(["informational", "readiness"]).optional().describe("Kind of the check (informational, readiness)"),
      method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
      path: z.string().optional().describe("For http checks, the path to send the request to"),
      port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
      protocol: z.string().optional().describe("For http checks, whether to use http or https"),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
      tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
      tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
      type: z.string().optional().describe("tcp or http"),
    })).optional().describe("An optional object that defines one or more named top-level checks. The key for each check is the check name."),
    containers: z.array(z.object({
      cmd: z.array(z.string()).optional().describe("CmdOverride is used to override the default command of the image."),
      depends_on: z.array(z.object({
        condition: z.unknown().optional(),
        name: z.string().optional(),
      })).optional().describe("DependsOn can be used to define dependencies between containers. The container will only be\nstarted after all of its dependent conditions have been satisfied."),
      entrypoint: z.array(z.string()).optional().describe("EntrypointOverride is used to override the default entrypoint of the image."),
      env: z.record(z.string(), z.string()).optional().describe("ExtraEnv is used to add additional environment variables to the container."),
      env_from: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
      })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
      exec: z.array(z.string()).optional().describe("Image Config overrides - these fields are used to override the image configuration.\nIf not provided, the image configuration will be used.\nExecOverride is used to override the default command of the image."),
      files: z.array(z.object({
        guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
        image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
        mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
        raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
        secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
      })).optional().describe("Files are files that will be written to the container file system."),
      healthchecks: z.array(z.object({
        exec: z.object({
          command: z.array(z.string()).optional().describe("The command to run to check the health of the container (e.g. [\"cat\", \"/tmp/healthy\"])"),
        }).optional(),
        failure_threshold: z.number().int().optional().describe("The number of times the check must fail before considering the container unhealthy."),
        grace_period: z.number().int().optional().describe("The time in seconds to wait after a container starts before checking its health."),
        http: z.object({
          headers: z.array(z.object({
            name: z.string().optional().describe("The header name"),
            values: z.array(z.string()).optional().describe("The header value"),
          })).optional().describe("Additional headers to send with the request"),
          method: z.string().optional().describe("The HTTP method to use to when making the request"),
          path: z.string().optional().describe("The path to send the request to"),
          port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
          scheme: z.unknown().optional().describe("Whether to use http or https"),
          tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
          tls_skip_verify: z.boolean().optional().describe("If the protocol is https, whether or not to verify the TLS certificate"),
        }).optional(),
        interval: z.number().int().optional().describe("The time in seconds between executing the defined check."),
        kind: z.unknown().optional().describe("Kind of healthcheck (readiness, liveness)"),
        name: z.string().optional().describe("The name of the check. Must be unique within the container."),
        success_threshold: z.number().int().optional().describe("The number of times the check must succeeed before considering the container healthy."),
        tcp: z.object({
          port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
        }).optional(),
        timeout: z.number().int().optional().describe("The time in seconds to wait for the check to complete."),
        unhealthy: z.unknown().optional().describe("Unhealthy policy that determines what action to take if a container is deemed unhealthy"),
      })).optional().describe("Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command."),
      image: z.string().optional().describe("Image is the docker image to run."),
      name: z.string().optional().describe("Name is used to identify the container in the machine."),
      restart: z.object({
        gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
        max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
        policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
      }).optional().describe("Restart is used to define the restart policy for the container. NOTE: spot-price is not\nsupported for containers."),
      secrets: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
      })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
      stop: z.object({
        signal: z.string().optional(),
        timeout: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional(),
      }).optional().describe("Stop is used to define the signal and timeout for stopping the container."),
      user: z.string().optional().describe("UserOverride is used to override the default user of the image."),
    })).optional().describe("Containers are a list of containers that will run in the machine. Currently restricted to\nonly specific organizations."),
    disable_machine_autostart: z.boolean().optional().describe("Deprecated: use Service.Autostart instead"),
    dns: z.object({
      dns_forward_rules: z.array(z.object({
        addr: z.string().optional(),
        basename: z.string().optional(),
      })).optional(),
      hostname: z.string().optional(),
      hostname_fqdn: z.string().optional(),
      nameservers: z.array(z.string()).optional(),
      options: z.array(z.object({
        name: z.string().optional(),
        value: z.string().optional(),
      })).optional(),
      searches: z.array(z.string()).optional(),
      skip_registration: z.boolean().optional(),
    }).optional(),
    env: z.record(z.string(), z.string()).optional().describe("An object filled with key/value pairs to be set as environment variables"),
    files: z.array(z.object({
      guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
      image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
      mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
      raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
      secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
    })).optional(),
    guest: z.object({
      cpu_kind: z.string().optional(),
      cpus: z.number().int().optional(),
      gpu_kind: z.string().optional(),
      gpus: z.number().int().optional(),
      host_dedication_id: z.string().optional(),
      kernel_args: z.array(z.string()).optional(),
      memory_mb: z.number().int().optional(),
      persist_rootfs: z.enum(["never", "always", "restart"]).optional().describe("Deprecated: use MachineConfig.Rootfs instead"),
    }).optional(),
    image: z.string().optional().describe("The docker image to run"),
    init: z.object({
      cmd: z.array(z.string()).optional(),
      entrypoint: z.array(z.string()).optional(),
      exec: z.array(z.string()).optional(),
      kernel_args: z.array(z.string()).optional(),
      swap_size_mb: z.number().int().optional(),
      tty: z.boolean().optional(),
    }).optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    metrics: z.object({
      https: z.boolean().optional(),
      path: z.string().optional(),
      port: z.number().int().optional(),
    }).optional(),
    mounts: z.array(z.object({
      add_size_gb: z.number().int().optional(),
      encrypted: z.boolean().optional(),
      extend_threshold_percent: z.number().int().optional(),
      name: z.string().optional(),
      path: z.string().optional(),
      size_gb: z.number().int().optional(),
      size_gb_limit: z.number().int().optional(),
      volume: z.string().optional(),
    })).optional(),
    processes: z.array(z.object({
      cmd: z.array(z.string()).optional(),
      entrypoint: z.array(z.string()).optional(),
      env: z.record(z.string(), z.string()).optional(),
      env_from: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
      })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
      exec: z.array(z.string()).optional(),
      ignore_app_secrets: z.boolean().optional().describe("IgnoreAppSecrets can be set to true to ignore the secrets for the App the Machine belongs to\nand only use the secrets provided at the process level. The default/legacy behavior is to use\nthe secrets provided at the App level."),
      secrets: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
      })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
      user: z.string().optional(),
    })).optional(),
    restart: z.object({
      gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
      max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
      policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
    }).optional().describe("The Machine restart policy defines whether and how flyd restarts a Machine after its main process exits. See https://fly.io/docs/machines/guides-examples/machine-restart-policy/."),
    rootfs: z.object({
      fs_size_gb: z.number().int().optional(),
      persist: z.enum(["never", "always", "restart"]).optional(),
      size_gb: z.number().int().optional(),
    }).optional(),
    schedule: z.string().optional(),
    services: z.array(z.object({
      autostart: z.boolean().optional(),
      autostop: z.enum(["off", "stop", "suspend"]).optional().describe("Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for \"off\" and \"stop\" in responses.\n* \"off\" or false - Do not autostop the Machine.\n* \"stop\" or true - Automatically stop the Machine.\n* \"suspend\" - Automatically suspend the Machine, falling back to a full stop if this is not possible."),
      checks: z.array(z.object({
        grace_period: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The time to wait after a VM starts before checking its health"),
        headers: z.array(z.object({
          name: z.string().optional().describe("The header name"),
          values: z.array(z.string()).optional().describe("The header value"),
        })).optional(),
        interval: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The time between connectivity checks"),
        method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
        path: z.string().optional().describe("For http checks, the path to send the request to"),
        port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
        protocol: z.string().optional().describe("For http checks, whether to use http or https"),
        timeout: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
        tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
        tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
        type: z.string().optional().describe("tcp or http"),
      })).optional().describe("An optional list of service checks"),
      concurrency: z.object({
        hard_limit: z.number().int().optional(),
        soft_limit: z.number().int().optional(),
        type: z.string().optional(),
      }).optional(),
      force_instance_description: z.string().optional(),
      force_instance_key: z.string().optional(),
      internal_port: z.number().int().optional(),
      min_machines_running: z.number().int().optional(),
      ports: z.array(z.object({
        end_port: z.number().int().optional(),
        force_https: z.boolean().optional(),
        handlers: z.array(z.string()).optional(),
        http_options: z.object({
          compress: z.boolean().optional(),
          h2_backend: z.boolean().optional(),
          headers_read_timeout: z.number().int().optional(),
          idle_timeout: z.number().int().optional(),
          replay_cache: z.array(z.object({
            allow_bypass: z.boolean().optional(),
            name: z.string().optional().describe("Name of the cookie or header to key the cache on"),
            path_prefix: z.string().optional(),
            ttl_seconds: z.number().int().optional(),
            type: z.enum(["cookie", "header"]).optional().describe("Currently either \"cookie\" or \"header\""),
          })).optional(),
          response: z.object({
            headers: z.record(z.string(), z.record(z.string(), z.unknown())).optional(),
            pristine: z.boolean().optional(),
          }).optional(),
        }).optional(),
        port: z.number().int().optional(),
        proxy_proto_options: z.object({
          version: z.string().optional(),
        }).optional(),
        start_port: z.number().int().optional(),
        tls_options: z.object({
          alpn: z.array(z.string()).optional(),
          default_self_signed: z.boolean().optional(),
          versions: z.array(z.string()).optional(),
        }).optional(),
      })).optional(),
      protocol: z.string().optional(),
    })).optional(),
    size: z.string().optional().describe("Deprecated: use Guest instead"),
    standbys: z.array(z.string()).optional().describe("Standbys enable a machine to be a standby for another. In the event of a hardware failure,\nthe standby machine will be started."),
    statics: z.array(z.object({
      guest_path: z.string(),
      index_document: z.string().optional(),
      tigris_bucket: z.string().optional(),
      url_prefix: z.string(),
    })).optional(),
    stop_config: z.object({
      signal: z.string().optional(),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional(),
    }).optional(),
  }).optional(),
  created_at: z.string().optional(),
  events: z.array(z.object({
    id: z.string().optional(),
    request: z.record(z.string(), z.unknown()).optional(),
    source: z.string().optional(),
    status: z.string().optional(),
    timestamp: z.number().int().optional(),
    type: z.string().optional(),
  })).optional(),
  host_status: z.enum(["ok", "unknown", "unreachable"]).optional(),
  id: z.string().optional(),
  image_ref: z.object({
    digest: z.string().optional(),
    labels: z.record(z.string(), z.string()).optional(),
    registry: z.string().optional(),
    repository: z.string().optional(),
    tag: z.string().optional(),
  }).optional(),
  incomplete_config: z.object({
    auto_destroy: z.boolean().optional().describe("Optional boolean telling the Machine to destroy itself once it’s complete (default false)"),
    checks: z.record(z.string(), z.object({
      grace_period: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time to wait after a VM starts before checking its health"),
      headers: z.array(z.object({
        name: z.string().optional().describe("The header name"),
        values: z.array(z.string()).optional().describe("The header value"),
      })).optional(),
      interval: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The time between connectivity checks"),
      kind: z.enum(["informational", "readiness"]).optional().describe("Kind of the check (informational, readiness)"),
      method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
      path: z.string().optional().describe("For http checks, the path to send the request to"),
      port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
      protocol: z.string().optional().describe("For http checks, whether to use http or https"),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
      tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
      tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
      type: z.string().optional().describe("tcp or http"),
    })).optional().describe("An optional object that defines one or more named top-level checks. The key for each check is the check name."),
    containers: z.array(z.object({
      cmd: z.array(z.string()).optional().describe("CmdOverride is used to override the default command of the image."),
      depends_on: z.array(z.object({
        condition: z.unknown().optional(),
        name: z.string().optional(),
      })).optional().describe("DependsOn can be used to define dependencies between containers. The container will only be\nstarted after all of its dependent conditions have been satisfied."),
      entrypoint: z.array(z.string()).optional().describe("EntrypointOverride is used to override the default entrypoint of the image."),
      env: z.record(z.string(), z.string()).optional().describe("ExtraEnv is used to add additional environment variables to the container."),
      env_from: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
      })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
      exec: z.array(z.string()).optional().describe("Image Config overrides - these fields are used to override the image configuration.\nIf not provided, the image configuration will be used.\nExecOverride is used to override the default command of the image."),
      files: z.array(z.object({
        guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
        image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
        mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
        raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
        secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
      })).optional().describe("Files are files that will be written to the container file system."),
      healthchecks: z.array(z.object({
        exec: z.object({
          command: z.array(z.string()).optional().describe("The command to run to check the health of the container (e.g. [\"cat\", \"/tmp/healthy\"])"),
        }).optional(),
        failure_threshold: z.number().int().optional().describe("The number of times the check must fail before considering the container unhealthy."),
        grace_period: z.number().int().optional().describe("The time in seconds to wait after a container starts before checking its health."),
        http: z.object({
          headers: z.array(z.object({
            name: z.string().optional().describe("The header name"),
            values: z.array(z.string()).optional().describe("The header value"),
          })).optional().describe("Additional headers to send with the request"),
          method: z.string().optional().describe("The HTTP method to use to when making the request"),
          path: z.string().optional().describe("The path to send the request to"),
          port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
          scheme: z.unknown().optional().describe("Whether to use http or https"),
          tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
          tls_skip_verify: z.boolean().optional().describe("If the protocol is https, whether or not to verify the TLS certificate"),
        }).optional(),
        interval: z.number().int().optional().describe("The time in seconds between executing the defined check."),
        kind: z.unknown().optional().describe("Kind of healthcheck (readiness, liveness)"),
        name: z.string().optional().describe("The name of the check. Must be unique within the container."),
        success_threshold: z.number().int().optional().describe("The number of times the check must succeeed before considering the container healthy."),
        tcp: z.object({
          port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
        }).optional(),
        timeout: z.number().int().optional().describe("The time in seconds to wait for the check to complete."),
        unhealthy: z.unknown().optional().describe("Unhealthy policy that determines what action to take if a container is deemed unhealthy"),
      })).optional().describe("Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command."),
      image: z.string().optional().describe("Image is the docker image to run."),
      name: z.string().optional().describe("Name is used to identify the container in the machine."),
      restart: z.object({
        gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
        max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
        policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
      }).optional().describe("Restart is used to define the restart policy for the container. NOTE: spot-price is not\nsupported for containers."),
      secrets: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
      })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
      stop: z.object({
        signal: z.string().optional(),
        timeout: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional(),
      }).optional().describe("Stop is used to define the signal and timeout for stopping the container."),
      user: z.string().optional().describe("UserOverride is used to override the default user of the image."),
    })).optional().describe("Containers are a list of containers that will run in the machine. Currently restricted to\nonly specific organizations."),
    disable_machine_autostart: z.boolean().optional().describe("Deprecated: use Service.Autostart instead"),
    dns: z.object({
      dns_forward_rules: z.array(z.object({
        addr: z.string().optional(),
        basename: z.string().optional(),
      })).optional(),
      hostname: z.string().optional(),
      hostname_fqdn: z.string().optional(),
      nameservers: z.array(z.string()).optional(),
      options: z.array(z.object({
        name: z.string().optional(),
        value: z.string().optional(),
      })).optional(),
      searches: z.array(z.string()).optional(),
      skip_registration: z.boolean().optional(),
    }).optional(),
    env: z.record(z.string(), z.string()).optional().describe("An object filled with key/value pairs to be set as environment variables"),
    files: z.array(z.object({
      guest_path: z.string().optional().describe("GuestPath is the path on the machine where the file will be written and must be an absolute path.\nFor example: /full/path/to/file.json"),
      image_config: z.string().optional().describe("The name of an image to use the OCI image config as the file contents."),
      mode: z.number().int().optional().describe("Mode bits used to set permissions on this file as accepted by chmod(2)."),
      raw_value: z.string().optional().describe("The base64 encoded string of the file contents."),
      secret_name: z.string().optional().describe("The name of the secret that contains the base64 encoded file contents."),
    })).optional(),
    guest: z.object({
      cpu_kind: z.string().optional(),
      cpus: z.number().int().optional(),
      gpu_kind: z.string().optional(),
      gpus: z.number().int().optional(),
      host_dedication_id: z.string().optional(),
      kernel_args: z.array(z.string()).optional(),
      memory_mb: z.number().int().optional(),
      persist_rootfs: z.enum(["never", "always", "restart"]).optional().describe("Deprecated: use MachineConfig.Rootfs instead"),
    }).optional(),
    image: z.string().optional().describe("The docker image to run"),
    init: z.object({
      cmd: z.array(z.string()).optional(),
      entrypoint: z.array(z.string()).optional(),
      exec: z.array(z.string()).optional(),
      kernel_args: z.array(z.string()).optional(),
      swap_size_mb: z.number().int().optional(),
      tty: z.boolean().optional(),
    }).optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    metrics: z.object({
      https: z.boolean().optional(),
      path: z.string().optional(),
      port: z.number().int().optional(),
    }).optional(),
    mounts: z.array(z.object({
      add_size_gb: z.number().int().optional(),
      encrypted: z.boolean().optional(),
      extend_threshold_percent: z.number().int().optional(),
      name: z.string().optional(),
      path: z.string().optional(),
      size_gb: z.number().int().optional(),
      size_gb_limit: z.number().int().optional(),
      volume: z.string().optional(),
    })).optional(),
    processes: z.array(z.object({
      cmd: z.array(z.string()).optional(),
      entrypoint: z.array(z.string()).optional(),
      env: z.record(z.string(), z.string()).optional(),
      env_from: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        field_ref: z.enum(["id", "version", "app_name", "private_ip", "region", "image"]).optional().describe("FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image."),
      })).optional().describe("EnvFrom can be provided to set environment variables from machine fields."),
      exec: z.array(z.string()).optional(),
      ignore_app_secrets: z.boolean().optional().describe("IgnoreAppSecrets can be set to true to ignore the secrets for the App the Machine belongs to\nand only use the secrets provided at the process level. The default/legacy behavior is to use\nthe secrets provided at the App level."),
      secrets: z.array(z.object({
        env_var: z.string().optional().describe("EnvVar is required and is the name of the environment variable that will be set from the\nsecret. It must be a valid environment variable name."),
        name: z.string().optional().describe("Name is optional and when provided is used to reference a secret name where the EnvVar is\ndifferent from what was set as the secret name."),
      })).optional().describe("Secrets can be provided at the process level to explicitly indicate which secrets should be\nused for the process. If not provided, the secrets provided at the machine level will be used."),
      user: z.string().optional(),
    })).optional(),
    restart: z.object({
      gpu_bid_price: z.number().optional().describe("GPU bid price for spot Machines."),
      max_retries: z.number().int().optional().describe("When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop."),
      policy: z.enum(["no", "always", "on-failure", "spot-price"]).optional().describe("* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.\n* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.\n* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.\n* spot-price - Starts the Machine only when there is capacity and the spot price is less than or equal to the bid price."),
    }).optional().describe("The Machine restart policy defines whether and how flyd restarts a Machine after its main process exits. See https://fly.io/docs/machines/guides-examples/machine-restart-policy/."),
    rootfs: z.object({
      fs_size_gb: z.number().int().optional(),
      persist: z.enum(["never", "always", "restart"]).optional(),
      size_gb: z.number().int().optional(),
    }).optional(),
    schedule: z.string().optional(),
    services: z.array(z.object({
      autostart: z.boolean().optional(),
      autostop: z.enum(["off", "stop", "suspend"]).optional().describe("Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for \"off\" and \"stop\" in responses.\n* \"off\" or false - Do not autostop the Machine.\n* \"stop\" or true - Automatically stop the Machine.\n* \"suspend\" - Automatically suspend the Machine, falling back to a full stop if this is not possible."),
      checks: z.array(z.object({
        grace_period: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The time to wait after a VM starts before checking its health"),
        headers: z.array(z.object({
          name: z.string().optional().describe("The header name"),
          values: z.array(z.string()).optional().describe("The header value"),
        })).optional(),
        interval: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The time between connectivity checks"),
        method: z.string().optional().describe("For http checks, the HTTP method to use to when making the request"),
        path: z.string().optional().describe("For http checks, the path to send the request to"),
        port: z.number().int().optional().describe("The port to connect to, often the same as internal_port"),
        protocol: z.string().optional().describe("For http checks, whether to use http or https"),
        timeout: z.object({
          "time.Duration": z.number().int().optional(),
        }).optional().describe("The maximum time a connection can take before being reported as failing its health check"),
        tls_server_name: z.string().optional().describe("If the protocol is https, the hostname to use for TLS certificate validation"),
        tls_skip_verify: z.boolean().optional().describe("For http checks with https protocol, whether or not to verify the TLS certificate"),
        type: z.string().optional().describe("tcp or http"),
      })).optional().describe("An optional list of service checks"),
      concurrency: z.object({
        hard_limit: z.number().int().optional(),
        soft_limit: z.number().int().optional(),
        type: z.string().optional(),
      }).optional(),
      force_instance_description: z.string().optional(),
      force_instance_key: z.string().optional(),
      internal_port: z.number().int().optional(),
      min_machines_running: z.number().int().optional(),
      ports: z.array(z.object({
        end_port: z.number().int().optional(),
        force_https: z.boolean().optional(),
        handlers: z.array(z.string()).optional(),
        http_options: z.object({
          compress: z.boolean().optional(),
          h2_backend: z.boolean().optional(),
          headers_read_timeout: z.number().int().optional(),
          idle_timeout: z.number().int().optional(),
          replay_cache: z.array(z.object({
            allow_bypass: z.boolean().optional(),
            name: z.string().optional().describe("Name of the cookie or header to key the cache on"),
            path_prefix: z.string().optional(),
            ttl_seconds: z.number().int().optional(),
            type: z.enum(["cookie", "header"]).optional().describe("Currently either \"cookie\" or \"header\""),
          })).optional(),
          response: z.object({
            headers: z.record(z.string(), z.record(z.string(), z.unknown())).optional(),
            pristine: z.boolean().optional(),
          }).optional(),
        }).optional(),
        port: z.number().int().optional(),
        proxy_proto_options: z.object({
          version: z.string().optional(),
        }).optional(),
        start_port: z.number().int().optional(),
        tls_options: z.object({
          alpn: z.array(z.string()).optional(),
          default_self_signed: z.boolean().optional(),
          versions: z.array(z.string()).optional(),
        }).optional(),
      })).optional(),
      protocol: z.string().optional(),
    })).optional(),
    size: z.string().optional().describe("Deprecated: use Guest instead"),
    standbys: z.array(z.string()).optional().describe("Standbys enable a machine to be a standby for another. In the event of a hardware failure,\nthe standby machine will be started."),
    statics: z.array(z.object({
      guest_path: z.string(),
      index_document: z.string().optional(),
      tigris_bucket: z.string().optional(),
      url_prefix: z.string(),
    })).optional(),
    stop_config: z.object({
      signal: z.string().optional(),
      timeout: z.object({
        "time.Duration": z.number().int().optional(),
      }).optional(),
    }).optional(),
  }).optional(),
  instance_id: z.string().optional().describe("InstanceID is unique for each version of the machine"),
  name: z.string().optional(),
  nonce: z.string().optional().describe("Nonce is only every returned on machine creation if a lease_duration was provided."),
  private_ip: z.string().optional().describe("PrivateIP is the internal 6PN address of the machine."),
  region: z.string().optional(),
  state: z.string().optional(),
  updated_at: z.string().optional(),
})

export const machinesCreate = pikkuSessionlessFunc({
  description: "Create a Machine within a specific app using the details provided in the request body.\n\n**Important**: This request can fail, and you’re responsible for handling that failure. If you ask for a large Machine, or a Machine in a region we happen to be at capacity for, you might need to retry the request, or to fall back to another region. If you’re working directly with the Machines API, you’re taking some responsibility for your own orchestration!",
  input: MachinesCreateInput,
  output: MachinesCreateOutput,
  func: async ({ flyio }, data) => {
    return flyio.call('POST', '/apps/{app_name}/machines', data) as any
  },
})
