// Machines — This site hosts documentation generated from the Fly.io Machines API OpenAPI specification. Visit our complete [Machines API docs](https://fly.io/docs/machines/api/machines-resource/) for details about using the Machines resource.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const MachinesShowLeaseInput = z.object({
  app_name: z.string().describe("Fly App Name"),
  machine_id: z.string().describe("Machine ID"),
})

export const MachinesShowLeaseOutput = z.object({
  description: z.string().optional().describe("Description or reason for the Lease."),
  expires_at: z.number().int().optional().describe("ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid."),
  nonce: z.string().optional().describe("Nonce is the unique ID autogenerated and associated with the Lease."),
  owner: z.string().optional().describe("Owner is the user identifier which acquired the Lease."),
  version: z.string().optional().describe("Machine version"),
})

export const machinesShowLease = pikkuSessionlessFunc({
  description: "Retrieve the current lease of a specific Machine within an app. Machine leases can be used to obtain an exclusive lock on modifying a Machine.",
  input: MachinesShowLeaseInput,
  output: MachinesShowLeaseOutput,
  func: async ({ flyio }, data) => {
    return flyio.call('GET', '/apps/{app_name}/machines/{machine_id}/lease', data) as any
  },
})
