// system — General endpoints for interating with the server, such as configuration and logging.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { ForbiddenError, InternalServerError } from '@pikku/core/errors'

export const CreateEmailTestInput = z.object({
  ServiceSettings: z.object({
  SiteURL: z.string().optional(),
  ListenAddress: z.string().optional(),
  ConnectionSecurity: z.string().optional(),
  TLSCertFile: z.string().optional(),
  TLSKeyFile: z.string().optional(),
  UseLetsEncrypt: z.boolean().optional(),
  LetsEncryptCertificateCacheFile: z.string().optional(),
  Forward80To443: z.boolean().optional(),
  ReadTimeout: z.number().int().optional(),
  WriteTimeout: z.number().int().optional(),
  MaximumLoginAttempts: z.number().int().optional(),
  SegmentDeveloperKey: z.string().optional(),
  GoogleDeveloperKey: z.string().optional(),
  EnableOAuthServiceProvider: z.boolean().optional(),
  EnableIncomingWebhooks: z.boolean().optional(),
  EnableOutgoingWebhooks: z.boolean().optional(),
  EnableCommands: z.boolean().optional(),
  EnableOnlyAdminIntegrations: z.boolean().optional(),
  EnablePostUsernameOverride: z.boolean().optional(),
  EnablePostIconOverride: z.boolean().optional(),
  EnableTesting: z.boolean().optional(),
  EnableDeveloper: z.boolean().optional(),
  EnableSecurityFixAlert: z.boolean().optional(),
  EnableInsecureOutgoingConnections: z.boolean().optional(),
  EnableMultifactorAuthentication: z.boolean().optional(),
  EnforceMultifactorAuthentication: z.boolean().optional(),
  AllowCorsFrom: z.string().optional(),
  SessionLengthWebInDays: z.number().int().optional(),
  SessionLengthMobileInDays: z.number().int().optional(),
  SessionLengthSSOInDays: z.number().int().optional(),
  SessionCacheInMinutes: z.number().int().optional(),
  WebsocketSecurePort: z.number().int().optional(),
  WebsocketPort: z.number().int().optional(),
  WebserverMode: z.string().optional(),
  EnableCustomEmoji: z.boolean().optional(),
  RestrictCustomEmojiCreation: z.string().optional(),
}).optional(),
  TeamSettings: z.object({
  SiteName: z.string().optional(),
  MaxUsersPerTeam: z.number().int().optional(),
  EnableTeamCreation: z.boolean().optional(),
  EnableUserCreation: z.boolean().optional(),
  EnableOpenServer: z.boolean().optional(),
  RestrictCreationToDomains: z.string().optional(),
  EnableCustomBrand: z.boolean().optional(),
  CustomBrandText: z.string().optional(),
  CustomDescriptionText: z.string().optional(),
  RestrictDirectMessage: z.string().optional(),
  RestrictTeamInvite: z.string().optional(),
  RestrictPublicChannelManagement: z.string().optional(),
  RestrictPrivateChannelManagement: z.string().optional(),
  RestrictPublicChannelCreation: z.string().optional(),
  RestrictPrivateChannelCreation: z.string().optional(),
  RestrictPublicChannelDeletion: z.string().optional(),
  RestrictPrivateChannelDeletion: z.string().optional(),
  UserStatusAwayTimeout: z.number().int().optional(),
  MaxChannelsPerTeam: z.number().int().optional(),
  MaxNotificationsPerChannel: z.number().int().optional(),
}).optional(),
  SqlSettings: z.object({
  DriverName: z.string().optional(),
  DataSource: z.string().optional(),
  DataSourceReplicas: z.array(z.string()).optional(),
  MaxIdleConns: z.number().int().optional(),
  MaxOpenConns: z.number().int().optional(),
  Trace: z.boolean().optional(),
  AtRestEncryptKey: z.string().optional(),
}).optional(),
  LogSettings: z.object({
  EnableConsole: z.boolean().optional(),
  ConsoleLevel: z.string().optional(),
  EnableFile: z.boolean().optional(),
  FileLevel: z.string().optional(),
  FileLocation: z.string().optional(),
  EnableWebhookDebugging: z.boolean().optional(),
  EnableDiagnostics: z.boolean().optional(),
}).optional(),
  PasswordSettings: z.object({
  MinimumLength: z.number().int().optional(),
  Lowercase: z.boolean().optional(),
  Number: z.boolean().optional(),
  Uppercase: z.boolean().optional(),
  Symbol: z.boolean().optional(),
}).optional(),
  FileSettings: z.object({
  MaxFileSize: z.number().int().optional(),
  DriverName: z.string().optional(),
  Directory: z.string().optional(),
  EnablePublicLink: z.boolean().optional(),
  PublicLinkSalt: z.string().optional(),
  ThumbnailWidth: z.number().int().optional(),
  ThumbnailHeight: z.number().int().optional(),
  PreviewWidth: z.number().int().optional(),
  PreviewHeight: z.number().int().optional(),
  ProfileWidth: z.number().int().optional(),
  ProfileHeight: z.number().int().optional(),
  InitialFont: z.string().optional(),
  AmazonS3AccessKeyId: z.string().optional(),
  AmazonS3SecretAccessKey: z.string().optional(),
  AmazonS3Bucket: z.string().optional(),
  AmazonS3Region: z.string().optional(),
  AmazonS3Endpoint: z.string().optional(),
  AmazonS3SSL: z.boolean().optional(),
}).optional(),
  EmailSettings: z.object({
  EnableSignUpWithEmail: z.boolean().optional(),
  EnableSignInWithEmail: z.boolean().optional(),
  EnableSignInWithUsername: z.boolean().optional(),
  SendEmailNotifications: z.boolean().optional(),
  RequireEmailVerification: z.boolean().optional(),
  FeedbackName: z.string().optional(),
  FeedbackEmail: z.string().optional(),
  FeedbackOrganization: z.string().optional(),
  SMTPUsername: z.string().optional(),
  SMTPPassword: z.string().optional(),
  SMTPServer: z.string().optional(),
  SMTPPort: z.string().optional(),
  ConnectionSecurity: z.string().optional(),
  InviteSalt: z.string().optional(),
  PasswordResetSalt: z.string().optional(),
  SendPushNotifications: z.boolean().optional(),
  PushNotificationServer: z.string().optional(),
  PushNotificationContents: z.string().optional(),
  EnableEmailBatching: z.boolean().optional(),
  EmailBatchingBufferSize: z.number().int().optional(),
  EmailBatchingInterval: z.number().int().optional(),
}).optional(),
  RateLimitSettings: z.object({
  Enable: z.boolean().optional(),
  PerSec: z.number().int().optional(),
  MaxBurst: z.number().int().optional(),
  MemoryStoreSize: z.number().int().optional(),
  VaryByRemoteAddr: z.boolean().optional(),
  VaryByHeader: z.string().optional(),
}).optional(),
  PrivacySettings: z.object({
  ShowEmailAddress: z.boolean().optional(),
  ShowFullName: z.boolean().optional(),
}).optional(),
  SupportSettings: z.object({
  TermsOfServiceLink: z.string().optional(),
  PrivacyPolicyLink: z.string().optional(),
  AboutLink: z.string().optional(),
  HelpLink: z.string().optional(),
  ReportAProblemLink: z.string().optional(),
  SupportEmail: z.string().optional(),
}).optional(),
  GitLabSettings: z.object({
  Enable: z.boolean().optional(),
  Secret: z.string().optional(),
  Id: z.string().optional(),
  Scope: z.string().optional(),
  AuthEndpoint: z.string().optional(),
  TokenEndpoint: z.string().optional(),
  UserApiEndpoint: z.string().optional(),
}).optional(),
  GoogleSettings: z.object({
  Enable: z.boolean().optional(),
  Secret: z.string().optional(),
  Id: z.string().optional(),
  Scope: z.string().optional(),
  AuthEndpoint: z.string().optional(),
  TokenEndpoint: z.string().optional(),
  UserApiEndpoint: z.string().optional(),
}).optional(),
  Office365Settings: z.object({
  Enable: z.boolean().optional(),
  Secret: z.string().optional(),
  Id: z.string().optional(),
  Scope: z.string().optional(),
  AuthEndpoint: z.string().optional(),
  TokenEndpoint: z.string().optional(),
  UserApiEndpoint: z.string().optional(),
}).optional(),
  LdapSettings: z.object({
  Enable: z.boolean().optional(),
  LdapServer: z.string().optional(),
  LdapPort: z.number().int().optional(),
  ConnectionSecurity: z.string().optional(),
  BaseDN: z.string().optional(),
  BindUsername: z.string().optional(),
  BindPassword: z.string().optional(),
  UserFilter: z.string().optional(),
  FirstNameAttribute: z.string().optional(),
  LastNameAttribute: z.string().optional(),
  EmailAttribute: z.string().optional(),
  UsernameAttribute: z.string().optional(),
  NicknameAttribute: z.string().optional(),
  IdAttribute: z.string().optional(),
  PositionAttribute: z.string().optional(),
  SyncIntervalMinutes: z.number().int().optional(),
  SkipCertificateVerification: z.boolean().optional(),
  QueryTimeout: z.number().int().optional(),
  MaxPageSize: z.number().int().optional(),
  LoginFieldName: z.string().optional(),
}).optional(),
  ComplianceSettings: z.object({
  Enable: z.boolean().optional(),
  Directory: z.string().optional(),
  EnableDaily: z.boolean().optional(),
}).optional(),
  LocalizationSettings: z.object({
  DefaultServerLocale: z.string().optional(),
  DefaultClientLocale: z.string().optional(),
  AvailableLocales: z.string().optional(),
}).optional(),
  SamlSettings: z.object({
  Enable: z.boolean().optional(),
  Verify: z.boolean().optional(),
  Encrypt: z.boolean().optional(),
  IdpUrl: z.string().optional(),
  IdpDescriptorUrl: z.string().optional(),
  AssertionConsumerServiceURL: z.string().optional(),
  IdpCertificateFile: z.string().optional(),
  PublicCertificateFile: z.string().optional(),
  PrivateKeyFile: z.string().optional(),
  FirstNameAttribute: z.string().optional(),
  LastNameAttribute: z.string().optional(),
  EmailAttribute: z.string().optional(),
  UsernameAttribute: z.string().optional(),
  NicknameAttribute: z.string().optional(),
  LocaleAttribute: z.string().optional(),
  PositionAttribute: z.string().optional(),
  LoginButtonText: z.string().optional(),
}).optional(),
  NativeAppSettings: z.object({
  AppDownloadLink: z.string().optional(),
  AndroidAppDownloadLink: z.string().optional(),
  IosAppDownloadLink: z.string().optional(),
}).optional(),
  ClusterSettings: z.object({
  Enable: z.boolean().optional(),
  InterNodeListenAddress: z.string().optional(),
  InterNodeUrls: z.array(z.string()).optional(),
}).optional(),
  MetricsSettings: z.object({
  Enable: z.boolean().optional(),
  BlockProfileRate: z.number().int().optional(),
  ListenAddress: z.string().optional(),
}).optional(),
  AnalyticsSettings: z.object({
  MaxUsersForStatistics: z.number().int().optional(),
}).optional(),
})

export const CreateEmailTestOutput = z.object({
  status: z.string().optional().describe("Will contain \"ok\" if the request was successful and there was nothing else to return"),
})

export const createEmailTest = pikkuSessionlessFunc({
  description: "Send a test email to make sure you have your email settings configured correctly. Optionally provide a configuration in the request body to test. If no valid configuration is present in the request body the current server configuration will be tested.\n##### Permissions\nMust have `manage_system` permission.",
  input: CreateEmailTestInput,
  output: CreateEmailTestOutput,
  errors: [ForbiddenError, InternalServerError],
  func: async ({ mattermost }, data) => {
    return mattermost.call("POST", "/email/test", data) as any
  },
})
