// system — General endpoints for interating with the server, such as configuration and logging.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { BadRequestError, UnauthorizedError, ForbiddenError } from '@pikku/core/errors'

export const ListConfigEnvironmentOutput = z.object({
  ServiceSettings: z.object({
    SiteURL: z.boolean().optional(),
    ListenAddress: z.boolean().optional(),
    ConnectionSecurity: z.boolean().optional(),
    TLSCertFile: z.boolean().optional(),
    TLSKeyFile: z.boolean().optional(),
    UseLetsEncrypt: z.boolean().optional(),
    LetsEncryptCertificateCacheFile: z.boolean().optional(),
    Forward80To443: z.boolean().optional(),
    ReadTimeout: z.boolean().optional(),
    WriteTimeout: z.boolean().optional(),
    MaximumLoginAttempts: z.boolean().optional(),
    SegmentDeveloperKey: z.boolean().optional(),
    GoogleDeveloperKey: z.boolean().optional(),
    EnableOAuthServiceProvider: z.boolean().optional(),
    EnableIncomingWebhooks: z.boolean().optional(),
    EnableOutgoingWebhooks: z.boolean().optional(),
    EnableCommands: z.boolean().optional(),
    EnableOnlyAdminIntegrations: z.boolean().optional(),
    EnablePostUsernameOverride: z.boolean().optional(),
    EnablePostIconOverride: z.boolean().optional(),
    EnableTesting: z.boolean().optional(),
    EnableDeveloper: z.boolean().optional(),
    EnableSecurityFixAlert: z.boolean().optional(),
    EnableInsecureOutgoingConnections: z.boolean().optional(),
    EnableMultifactorAuthentication: z.boolean().optional(),
    EnforceMultifactorAuthentication: z.boolean().optional(),
    AllowCorsFrom: z.boolean().optional(),
    SessionLengthWebInDays: z.boolean().optional(),
    SessionLengthMobileInDays: z.boolean().optional(),
    SessionLengthSSOInDays: z.boolean().optional(),
    SessionCacheInMinutes: z.boolean().optional(),
    WebsocketSecurePort: z.boolean().optional(),
    WebsocketPort: z.boolean().optional(),
    WebserverMode: z.boolean().optional(),
    EnableCustomEmoji: z.boolean().optional(),
    RestrictCustomEmojiCreation: z.boolean().optional(),
  }).optional(),
  TeamSettings: z.object({
    SiteName: z.boolean().optional(),
    MaxUsersPerTeam: z.boolean().optional(),
    EnableTeamCreation: z.boolean().optional(),
    EnableUserCreation: z.boolean().optional(),
    EnableOpenServer: z.boolean().optional(),
    RestrictCreationToDomains: z.boolean().optional(),
    EnableCustomBrand: z.boolean().optional(),
    CustomBrandText: z.boolean().optional(),
    CustomDescriptionText: z.boolean().optional(),
    RestrictDirectMessage: z.boolean().optional(),
    RestrictTeamInvite: z.boolean().optional(),
    RestrictPublicChannelManagement: z.boolean().optional(),
    RestrictPrivateChannelManagement: z.boolean().optional(),
    RestrictPublicChannelCreation: z.boolean().optional(),
    RestrictPrivateChannelCreation: z.boolean().optional(),
    RestrictPublicChannelDeletion: z.boolean().optional(),
    RestrictPrivateChannelDeletion: z.boolean().optional(),
    UserStatusAwayTimeout: z.boolean().optional(),
    MaxChannelsPerTeam: z.boolean().optional(),
    MaxNotificationsPerChannel: z.boolean().optional(),
  }).optional(),
  SqlSettings: z.object({
    DriverName: z.boolean().optional(),
    DataSource: z.boolean().optional(),
    DataSourceReplicas: z.boolean().optional(),
    MaxIdleConns: z.boolean().optional(),
    MaxOpenConns: z.boolean().optional(),
    Trace: z.boolean().optional(),
    AtRestEncryptKey: z.boolean().optional(),
  }).optional(),
  LogSettings: z.object({
    EnableConsole: z.boolean().optional(),
    ConsoleLevel: z.boolean().optional(),
    EnableFile: z.boolean().optional(),
    FileLevel: z.boolean().optional(),
    FileLocation: z.boolean().optional(),
    EnableWebhookDebugging: z.boolean().optional(),
    EnableDiagnostics: z.boolean().optional(),
  }).optional(),
  PasswordSettings: z.object({
    MinimumLength: z.boolean().optional(),
    Lowercase: z.boolean().optional(),
    Number: z.boolean().optional(),
    Uppercase: z.boolean().optional(),
    Symbol: z.boolean().optional(),
  }).optional(),
  FileSettings: z.object({
    MaxFileSize: z.boolean().optional(),
    DriverName: z.boolean().optional(),
    Directory: z.boolean().optional(),
    EnablePublicLink: z.boolean().optional(),
    PublicLinkSalt: z.boolean().optional(),
    ThumbnailWidth: z.boolean().optional(),
    ThumbnailHeight: z.boolean().optional(),
    PreviewWidth: z.boolean().optional(),
    PreviewHeight: z.boolean().optional(),
    ProfileWidth: z.boolean().optional(),
    ProfileHeight: z.boolean().optional(),
    InitialFont: z.boolean().optional(),
    AmazonS3AccessKeyId: z.boolean().optional(),
    AmazonS3SecretAccessKey: z.boolean().optional(),
    AmazonS3Bucket: z.boolean().optional(),
    AmazonS3Region: z.boolean().optional(),
    AmazonS3Endpoint: z.boolean().optional(),
    AmazonS3SSL: z.boolean().optional(),
  }).optional(),
  EmailSettings: z.object({
    EnableSignUpWithEmail: z.boolean().optional(),
    EnableSignInWithEmail: z.boolean().optional(),
    EnableSignInWithUsername: z.boolean().optional(),
    SendEmailNotifications: z.boolean().optional(),
    RequireEmailVerification: z.boolean().optional(),
    FeedbackName: z.boolean().optional(),
    FeedbackEmail: z.boolean().optional(),
    FeedbackOrganization: z.boolean().optional(),
    SMTPUsername: z.boolean().optional(),
    SMTPPassword: z.boolean().optional(),
    SMTPServer: z.boolean().optional(),
    SMTPPort: z.boolean().optional(),
    ConnectionSecurity: z.boolean().optional(),
    InviteSalt: z.boolean().optional(),
    PasswordResetSalt: z.boolean().optional(),
    SendPushNotifications: z.boolean().optional(),
    PushNotificationServer: z.boolean().optional(),
    PushNotificationContents: z.boolean().optional(),
    EnableEmailBatching: z.boolean().optional(),
    EmailBatchingBufferSize: z.boolean().optional(),
    EmailBatchingInterval: z.boolean().optional(),
  }).optional(),
  RateLimitSettings: z.object({
    Enable: z.boolean().optional(),
    PerSec: z.boolean().optional(),
    MaxBurst: z.boolean().optional(),
    MemoryStoreSize: z.boolean().optional(),
    VaryByRemoteAddr: z.boolean().optional(),
    VaryByHeader: z.boolean().optional(),
  }).optional(),
  PrivacySettings: z.object({
    ShowEmailAddress: z.boolean().optional(),
    ShowFullName: z.boolean().optional(),
  }).optional(),
  SupportSettings: z.object({
    TermsOfServiceLink: z.boolean().optional(),
    PrivacyPolicyLink: z.boolean().optional(),
    AboutLink: z.boolean().optional(),
    HelpLink: z.boolean().optional(),
    ReportAProblemLink: z.boolean().optional(),
    SupportEmail: z.boolean().optional(),
  }).optional(),
  GitLabSettings: z.object({
    Enable: z.boolean().optional(),
    Secret: z.boolean().optional(),
    Id: z.boolean().optional(),
    Scope: z.boolean().optional(),
    AuthEndpoint: z.boolean().optional(),
    TokenEndpoint: z.boolean().optional(),
    UserApiEndpoint: z.boolean().optional(),
  }).optional(),
  GoogleSettings: z.object({
    Enable: z.boolean().optional(),
    Secret: z.boolean().optional(),
    Id: z.boolean().optional(),
    Scope: z.boolean().optional(),
    AuthEndpoint: z.boolean().optional(),
    TokenEndpoint: z.boolean().optional(),
    UserApiEndpoint: z.boolean().optional(),
  }).optional(),
  Office365Settings: z.object({
    Enable: z.boolean().optional(),
    Secret: z.boolean().optional(),
    Id: z.boolean().optional(),
    Scope: z.boolean().optional(),
    AuthEndpoint: z.boolean().optional(),
    TokenEndpoint: z.boolean().optional(),
    UserApiEndpoint: z.boolean().optional(),
  }).optional(),
  LdapSettings: z.object({
    Enable: z.boolean().optional(),
    LdapServer: z.boolean().optional(),
    LdapPort: z.boolean().optional(),
    ConnectionSecurity: z.boolean().optional(),
    BaseDN: z.boolean().optional(),
    BindUsername: z.boolean().optional(),
    BindPassword: z.boolean().optional(),
    UserFilter: z.boolean().optional(),
    FirstNameAttribute: z.boolean().optional(),
    LastNameAttribute: z.boolean().optional(),
    EmailAttribute: z.boolean().optional(),
    UsernameAttribute: z.boolean().optional(),
    NicknameAttribute: z.boolean().optional(),
    IdAttribute: z.boolean().optional(),
    PositionAttribute: z.boolean().optional(),
    SyncIntervalMinutes: z.boolean().optional(),
    SkipCertificateVerification: z.boolean().optional(),
    QueryTimeout: z.boolean().optional(),
    MaxPageSize: z.boolean().optional(),
    LoginFieldName: z.boolean().optional(),
  }).optional(),
  ComplianceSettings: z.object({
    Enable: z.boolean().optional(),
    Directory: z.boolean().optional(),
    EnableDaily: z.boolean().optional(),
  }).optional(),
  LocalizationSettings: z.object({
    DefaultServerLocale: z.boolean().optional(),
    DefaultClientLocale: z.boolean().optional(),
    AvailableLocales: z.boolean().optional(),
  }).optional(),
  SamlSettings: z.object({
    Enable: z.boolean().optional(),
    Verify: z.boolean().optional(),
    Encrypt: z.boolean().optional(),
    IdpUrl: z.boolean().optional(),
    IdpDescriptorUrl: z.boolean().optional(),
    AssertionConsumerServiceURL: z.boolean().optional(),
    IdpCertificateFile: z.boolean().optional(),
    PublicCertificateFile: z.boolean().optional(),
    PrivateKeyFile: z.boolean().optional(),
    FirstNameAttribute: z.boolean().optional(),
    LastNameAttribute: z.boolean().optional(),
    EmailAttribute: z.boolean().optional(),
    UsernameAttribute: z.boolean().optional(),
    NicknameAttribute: z.boolean().optional(),
    LocaleAttribute: z.boolean().optional(),
    PositionAttribute: z.boolean().optional(),
    LoginButtonText: z.boolean().optional(),
  }).optional(),
  NativeAppSettings: z.object({
    AppDownloadLink: z.boolean().optional(),
    AndroidAppDownloadLink: z.boolean().optional(),
    IosAppDownloadLink: z.boolean().optional(),
  }).optional(),
  ClusterSettings: z.object({
    Enable: z.boolean().optional(),
    InterNodeListenAddress: z.boolean().optional(),
    InterNodeUrls: z.boolean().optional(),
  }).optional(),
  MetricsSettings: z.object({
    Enable: z.boolean().optional(),
    BlockProfileRate: z.boolean().optional(),
    ListenAddress: z.boolean().optional(),
  }).optional(),
  AnalyticsSettings: z.object({
    MaxUsersForStatistics: z.boolean().optional(),
  }).optional(),
})

export const listConfigEnvironment = pikkuSessionlessFunc({
  description: "Retrieve a json object mirroring the server configuration where fields are set to true\nif the corresponding config setting is set through an environment variable. Settings\nthat haven't been set through environment variables will be missing from the object.\n\n__Minimum server version__: 4.10\n\n##### Permissions\nMust have `manage_system` permission.",
  output: ListConfigEnvironmentOutput,
  errors: [BadRequestError, UnauthorizedError, ForbiddenError],
  func: async ({ mattermost }) => {
    return mattermost.call("GET", "/config/environment") as any
  },
})
