import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const MessageSchema = z.object({
  role: z.enum(['system', 'user', 'assistant']).describe('The role of the messages author'),
  content: z.string().describe('The contents of the message'),
})

export const ChatCompleteInput = z.object({
  model: z.string().describe('ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API.'),
  messages: z.array(MessageSchema).describe('A list of messages comprising the conversation so far'),
  frequency_penalty: z.number().min(-2).max(2).optional().describe('Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model\'s likelihood to repeat the same line verbatim.'),
  max_tokens: z.number().optional().describe('The maximum number of tokens that can be generated in the chat completion.'),
  n: z.number().optional().describe('How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices.'),
  presence_penalty: z.number().min(-2).max(2).optional().describe('Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model\'s likelihood to talk about new topics.'),
  temperature: z.number().min(0).max(2).optional().describe('What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.'),
  top_p: z.number().optional().describe('An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass.'),
})

export const ChoiceSchema = z.object({
  index: z.number().describe('The index of the choice in the list of choices'),
  message: z.object({
    role: z.string().describe('The role of the author of this message'),
    content: z.string().nullable().describe('The contents of the message'),
  }).describe('A chat completion message generated by the model'),
  finish_reason: z.string().nullable().describe('The reason the model stopped generating tokens'),
})

export const UsageSchema = z.object({
  prompt_tokens: z.number().describe('Number of tokens in the prompt'),
  completion_tokens: z.number().describe('Number of tokens in the generated completion'),
  total_tokens: z.number().describe('Total number of tokens used in the request'),
})

export const ChatCompleteOutput = z.object({
  id: z.string().describe('A unique identifier for the chat completion'),
  object: z.literal('chat.completion').describe('The object type, which is always chat.completion'),
  created: z.number().describe('The Unix timestamp (in seconds) of when the chat completion was created'),
  model: z.string().describe('The model used for the chat completion'),
  choices: z.array(ChoiceSchema).describe('A list of chat completion choices'),
  usage: UsageSchema.optional().describe('Usage statistics for the completion request'),
})

type Input = z.infer<typeof ChatCompleteInput>
type Output = z.infer<typeof ChatCompleteOutput>

export const chatComplete = pikkuSessionlessFunc({
  description: 'Creates a model response for the given chat conversation',
  node: { displayName: 'Chat Completion', category: 'Chat', type: 'action' },
  input: ChatCompleteInput,
  output: ChatCompleteOutput,
  func: async ({ openai }, data) => {
    return await openai.chat.completions.create(data as Input) as unknown as Output
  },
})
