import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const TextEmbeddingInput = z.object({
  input: z.union([z.string(), z.array(z.string())]).describe('Input text to embed, encoded as a string or array of strings. To embed multiple inputs in a single request, pass an array of strings.'),
  model: z.string().describe('ID of the model to use. You can use text-embedding-ada-002, text-embedding-3-small, or text-embedding-3-large.'),
  encoding_format: z.enum(['float', 'base64']).optional().describe('The format to return the embeddings in. Can be either float or base64.'),
  dimensions: z.number().optional().describe('The number of dimensions the resulting output embeddings should have. Only supported in text-embedding-3 and later models.'),
})

export const EmbeddingSchema = z.object({
  object: z.literal('embedding').describe('The object type, which is always "embedding"'),
  embedding: z.array(z.number()).describe('The embedding vector, which is a list of floats'),
  index: z.number().describe('The index of the embedding in the list of embeddings'),
})

export const UsageSchema = z.object({
  prompt_tokens: z.number().describe('The number of tokens used by the prompt'),
  total_tokens: z.number().describe('The total number of tokens used by the request'),
})

export const TextEmbeddingOutput = z.object({
  object: z.literal('list').describe('The object type, which is always "list"'),
  data: z.array(EmbeddingSchema).describe('The list of embeddings generated by the model'),
  model: z.string().describe('The name of the model used to generate the embedding'),
  usage: UsageSchema.describe('The usage information for the request'),
})

type Input = z.infer<typeof TextEmbeddingInput>
type Output = z.infer<typeof TextEmbeddingOutput>

export const textEmbedding = pikkuSessionlessFunc({
  description: 'Creates an embedding vector representing the input text',
  node: { displayName: 'Create Embedding', category: 'Text', type: 'action' },
  input: TextEmbeddingInput,
  output: TextEmbeddingOutput,
  func: async ({ openai }, data) => {
    return await openai.embeddings.create(data as Input) as unknown as Output
  },
})
