import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { BadRequestError } from '@pikku/core/errors'

export const BaseCreateInput = z.object({
  "xc-auth": z.string().describe("Auth Token is a JWT Token generated based on the logged-in user. By default, the token is only valid for 10 hours. However, you can change the value by defining it using environment variable NC_JWT_EXPIRES_IN."),
  body: z.object({
  sources: z.array(z.object({
    alias: z.string().max(128).optional().describe("Source Name - Default BASE will be null by default"),
    config: z.unknown().optional().describe("Source Configuration"),
    inflection_column: z.string().optional().describe("Inflection for columns"),
    inflection_table: z.string().optional().describe("Inflection for tables"),
    is_meta: z.boolean().optional().describe("Is the data source connected externally"),
    is_local: z.boolean().optional().describe("Is the data source minimal db"),
    is_schema_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source schema readonly"),
    is_data_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source data readonly"),
    type: z.enum(["mysql", "mysql2", "oracledb", "pg", "snowflake", "sqlite3", "databricks"]).optional().describe("DB Type"),
    fk_integration_id: z.string().optional(),
  })).optional().describe("Array of Bases"),
  color: z.string().max(50).optional().describe("Primary Theme Color"),
  description: z.string().optional().describe("Base Description"),
  title: z.string().min(1).max(50).describe("Base Title"),
  status: z.union([z.string(), z.unknown()]).optional().describe("Base Status"),
  type: z.enum(["database", "documentation", "dashboard"]).optional(),
  meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Base Meta"),
  external: z.boolean().optional().default(false).describe("If true, the base will us an external database else it will use the root database"),
}),
})

export const BaseCreateOutput = z.object({
  sources: z.array(z.object({
    alias: z.union([z.string(), z.unknown()]).optional().describe("Source Name"),
    integration_title: z.union([z.string(), z.unknown()]).optional().describe("Integration Name"),
    fk_integration_id: z.union([z.string(), z.unknown()]).optional().describe("Integration Id"),
    config: z.unknown().optional().describe("Source Configuration"),
    enabled: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this source enabled"),
    id: z.string().optional().describe("Unique Source ID"),
    inflection_column: z.string().optional().describe("Inflection for columns"),
    inflection_table: z.string().optional().describe("Inflection for tables"),
    is_meta: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source connected externally"),
    is_local: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source minimal db"),
    is_schema_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source schema readonly"),
    is_data_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source data readonly"),
    order: z.number().optional().describe("The order of the list of sources"),
    base_id: z.string().optional().describe("The base ID that this source belongs to"),
    type: z.enum(["mysql", "mysql2", "oracledb", "pg", "snowflake", "sqlite3", "databricks"]).optional().describe("DB Type"),
  })).optional().describe("List of source models"),
  color: z.string().optional().describe("Primary Theme Color"),
  deleted: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the base deleted"),
  description: z.string().optional().describe("Base Description"),
  id: z.string().optional().describe("Unique Base ID"),
  fk_workspace_id: z.string().optional().describe("Workspace ID"),
  is_meta: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
  meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info such as theme colors"),
  order: z.number().optional().describe("The order in base list"),
  prefix: z.string().optional().describe("Base prefix. Used in XCDB only."),
  type: z.enum(["database", "documentation", "dashboard"]).optional(),
  linked_db_projects: z.array(z.object({
    sources: z.array(z.object({
      alias: z.union([z.string(), z.unknown()]).optional().describe("Source Name"),
      integration_title: z.union([z.string(), z.unknown()]).optional().describe("Integration Name"),
      fk_integration_id: z.union([z.string(), z.unknown()]).optional().describe("Integration Id"),
      config: z.unknown().optional().describe("Source Configuration"),
      enabled: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this source enabled"),
      id: z.string().optional().describe("Unique Source ID"),
      inflection_column: z.string().optional().describe("Inflection for columns"),
      inflection_table: z.string().optional().describe("Inflection for tables"),
      is_meta: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source connected externally"),
      is_local: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source minimal db"),
      is_schema_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source schema readonly"),
      is_data_readonly: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the data source data readonly"),
      order: z.number().optional().describe("The order of the list of sources"),
      base_id: z.string().optional().describe("The base ID that this source belongs to"),
      type: z.enum(["mysql", "mysql2", "oracledb", "pg", "snowflake", "sqlite3", "databricks"]).optional().describe("DB Type"),
    })).optional().describe("List of source models"),
    color: z.string().optional().describe("Primary Theme Color"),
    deleted: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is the base deleted"),
    description: z.string().optional().describe("Base Description"),
    id: z.string().optional().describe("Unique Base ID"),
    fk_workspace_id: z.string().optional().describe("Workspace ID"),
    is_meta: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info such as theme colors"),
    order: z.number().optional().describe("The order in base list"),
    prefix: z.string().optional().describe("Base prefix. Used in XCDB only."),
    type: z.enum(["database", "documentation", "dashboard"]).optional(),
    linked_db_projects: z.any().optional().describe("List of linked Database Projects that this base has access to (only used in Dashboard bases so far)"),
    status: z.string().optional(),
    title: z.string().optional().describe("Base Title"),
    fk_custom_url_id: z.union([z.string(), z.unknown()]).optional().describe("ID of custom url"),
    permissions: z.array(z.object({
      id: z.string().optional().describe("Permission id"),
      entity: z.string().describe("Permission entity"),
      entity_id: z.string().describe("ID of the entity"),
      permission: z.string().describe("Permission key"),
      granted_type: z.string().describe("Type of permission granted"),
      granted_role: z.string().nullable().optional().describe("Role to which permission is granted"),
      subjects: z.array(z.object({
        type: z.enum(["user", "team"]).describe("Type of the subject"),
        id: z.string().describe("ID of the subject"),
      })).optional().describe("List of subjects (users or groups) for the permission"),
    })).optional().describe("List of permissions for the base"),
    is_sandbox: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Indicates if the base is a sandbox"),
    is_sandbox_master: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Indicates if the base is a sandbox master"),
  })).optional().describe("List of linked Database Projects that this base has access to (only used in Dashboard bases so far)"),
  status: z.string().optional(),
  title: z.string().optional().describe("Base Title"),
  fk_custom_url_id: z.union([z.string(), z.unknown()]).optional().describe("ID of custom url"),
  permissions: z.array(z.object({
    id: z.string().optional().describe("Permission id"),
    entity: z.string().describe("Permission entity"),
    entity_id: z.string().describe("ID of the entity"),
    permission: z.string().describe("Permission key"),
    granted_type: z.string().describe("Type of permission granted"),
    granted_role: z.string().nullable().optional().describe("Role to which permission is granted"),
    subjects: z.array(z.object({
      type: z.enum(["user", "team"]).describe("Type of the subject"),
      id: z.string().describe("ID of the subject"),
    })).optional().describe("List of subjects (users or groups) for the permission"),
  })).optional().describe("List of permissions for the base"),
  is_sandbox: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Indicates if the base is a sandbox"),
  is_sandbox_master: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Indicates if the base is a sandbox master"),
}).describe("Model for Base")

export const baseCreate = pikkuSessionlessFunc({
  description: "Create a new base",
  input: BaseCreateInput,
  output: BaseCreateOutput,
  errors: [BadRequestError],
  func: async ({ nocodb }, data) => {
    return nocodb.call("POST", "/api/v1/db/meta/projects/", data) as any
  },
})
