import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { BadRequestError } from '@pikku/core/errors'

export const DbViewFormCreateInput = z.object({
  tableId: z.string().min(0).max(20).describe("Model for ID").describe("Unique Table ID"),
  "xc-auth": z.string().describe("Auth Token is a JWT Token generated based on the logged-in user. By default, the token is only valid for 10 hours. However, you can change the value by defining it using environment variable NC_JWT_EXPIRES_IN."),
  title: z.string().describe("View Title"),
  type: z.number().optional().describe("View Type"),
  copy_from_id: z.union([z.string(), z.unknown()]).optional().describe("ID of view to be copied from. Used in Copy View."),
  fk_grp_col_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to Grouping Column. Used in creating Kanban View."),
  fk_geo_data_col_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to Geo Data Column. Used in creating Map View."),
  calendar_range: z.union([z.unknown(), z.array(z.object({
  fk_from_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
  fk_view_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to View"),
  label: z.string().optional().describe("Base ID"),
}))]).optional().describe("Calendar Range or Null"),
  description: z.union([z.string(), z.unknown()]).optional().describe("Description of the view."),
})

export const DbViewFormCreateOutput = z.object({
  source_id: z.string().min(0).max(20).optional().describe("Unique Source ID"),
  fk_model_id: z.string().min(0).max(20).describe("Unique Model ID"),
  id: z.string().min(0).max(20).optional().describe("Unique ID for View"),
  lock_type: z.enum(["collaborative", "locked", "personal"]).optional().describe("Lock Type of the view"),
  meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta data for this view"),
  order: z.number().optional().describe("The rder of the list of views"),
  description: z.union([z.string(), z.unknown()]).optional().describe("View Description"),
  password: z.union([z.string(), z.unknown()]).optional().describe("Password for protecting the view"),
  base_id: z.string().min(0).max(20).optional().describe("Unique Base ID"),
  show: z.union([z.number().int(), z.boolean(), z.unknown()]).describe("If this view is shown?"),
  show_system_fields: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Should show system fields in this view?"),
  title: z.string().describe("View Title"),
  type: z.number().describe("View Type"),
  uuid: z.union([z.string(), z.unknown()]).optional().describe("UUID of the view"),
  view: z.union([z.object({
    id: z.string().min(0).max(20).optional().describe("Unique ID"),
    banner_image_url: z.union([z.object({
      mimetype: z.string().optional().describe("The mimetype of the attachment"),
      path: z.string().optional().describe("The attachment stored path"),
      size: z.number().optional().describe("The size of the attachment"),
      title: z.string().optional().describe("The title of the attachment used in UI"),
      url: z.string().optional().describe("The attachment stored url"),
      signedPath: z.string().optional().describe("Attachment signedPath will allow to access attachment directly"),
      signedUrl: z.string().optional().describe("Attachment signedUrl will allow to access attachment directly"),
    }), z.unknown()]).optional().describe("Banner Image URL"),
    columns: z.array(z.object({
      id: z.string().min(0).max(20).optional().describe("Unique ID"),
      description: z.union([z.string(), z.unknown()]).optional().describe("Form Column Description"),
      fk_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
      fk_view_id: z.string().min(0).max(20).optional().describe("Foreign Key to View"),
      help: z.union([z.string(), z.unknown()]).optional().describe("Form Column Help Text (Not in use)"),
      label: z.union([z.string(), z.unknown()]).optional().describe("Form Column Label"),
      meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info"),
      order: z.number().optional().describe("The order among all the columns in the form"),
      required: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this form column required in submission?"),
      show: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown in Form?"),
      enable_scanner: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Indicates whether the 'Fill by scan' button is visible for this column or not."),
      uuid: z.union([z.string(), z.unknown()]).optional().describe("Form Column UUID (Not in use)"),
    })).optional().describe("Form Columns"),
    email: z.union([z.string(), z.unknown()]).optional().describe("Email to sned after form is submitted"),
    fk_model_id: z.string().optional().describe("Foreign Key to Model"),
    source_id: z.string().optional().describe("Source ID"),
    heading: z.string().optional().describe("The heading of the form"),
    lock_type: z.enum(["collaborative", "locked", "personal"]).optional().describe("Lock Type of this view"),
    logo_url: z.union([z.object({
      mimetype: z.string().optional().describe("The mimetype of the attachment"),
      path: z.string().optional().describe("The attachment stored path"),
      size: z.number().optional().describe("The size of the attachment"),
      title: z.string().optional().describe("The title of the attachment used in UI"),
      url: z.string().optional().describe("The attachment stored url"),
      signedPath: z.string().optional().describe("Attachment signedPath will allow to access attachment directly"),
      signedUrl: z.string().optional().describe("Attachment signedUrl will allow to access attachment directly"),
    }), z.unknown()]).optional().describe("Logo URL"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info for this view"),
    redirect_after_secs: z.union([z.string(), z.unknown()]).optional().describe("The numbers of seconds to redirect after form submission"),
    redirect_url: z.union([z.string(), z.unknown()]).optional().describe("URL to redirect after submission"),
    show_blank_form: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Show `Blank Form` after 5 seconds"),
    subheading: z.union([z.string(), z.unknown()]).optional().describe("The subheading of the form"),
    submit_another_form: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Show `Submit Another Form` button"),
    success_msg: z.union([z.string(), z.unknown()]).optional().describe("Custom message after the form is successfully submitted"),
    title: z.string().optional().describe("Form View Title"),
  }), z.object({
    alias: z.string().optional(),
    columns: z.array(z.object({
      fk_col_id: z.string().optional(),
      fk_gallery_id: z.string().optional(),
      help: z.string().optional(),
      id: z.string().min(0).max(20).optional().describe("Unique ID"),
      label: z.string().optional(),
    })).optional(),
    cover_image: z.string().optional(),
    cover_image_idx: z.number().int().optional(),
    deleted: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
    fk_cover_image_col_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to Cover Image Column"),
    fk_model_id: z.string().optional().describe("Foreign Key to Model"),
    fk_view_id: z.string().optional().describe("Foreign Key to View"),
    lock_type: z.enum(["collaborative", "locked", "personal"]).optional(),
    next_enabled: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
    order: z.number().optional().describe("Order of Gallery"),
    prev_enabled: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
    restrict_number: z.string().optional(),
    restrict_size: z.string().optional(),
    restrict_types: z.string().optional(),
    title: z.string().optional(),
  }), z.object({
    id: z.string().min(0).max(20).optional().describe("Unique ID"),
    base_id: z.string().min(0).max(20).optional().describe("Base ID"),
    source_id: z.string().min(0).max(20).optional().describe("Source ID"),
    fk_view_id: z.string().min(0).max(20).optional().describe("Foreign Key to View"),
    row_height: z.number().optional().describe("Row Height"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta info for Grid Model"),
    columns: z.array(z.object({
      id: z.string().min(0).max(20).optional().describe("Unique ID"),
      fk_view_id: z.string().min(0).max(20).optional().describe("Foreign Key to View"),
      fk_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
      base_id: z.string().min(0).max(20).optional().describe("Base ID"),
      source_id: z.string().min(0).max(20).optional().describe("Source ID"),
      show: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Model for Bool"),
      order: z.number().optional().describe("Grid Column Order"),
      width: z.string().optional().describe("Column Width"),
      help: z.union([z.string(), z.unknown()]).optional().describe("Column Help Text"),
      group_by: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Group By"),
      group_by_order: z.number().optional().describe("Group By Order"),
      group_by_sort: z.union([z.string(), z.unknown()]).optional().describe("Group By Sort"),
      aggregation: z.union([z.string(), z.unknown()]).optional().describe("Aggregation Type"),
    })).optional().describe("Grid View Columns"),
  }), z.object({
    id: z.string().min(0).max(20).optional().describe("Unique ID"),
    fk_grp_col_id: z.union([z.string(), z.unknown()]).optional().describe("Grouping Field Column ID"),
    fk_view_id: z.string().min(0).max(20).optional().describe("View ID"),
    fk_cover_image_col_id: z.union([z.string(), z.unknown()]).optional().describe("Cover Image Column ID"),
    columns: z.array(z.object({
      id: z.string().min(0).max(20).optional().describe("Unique ID"),
      fk_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
      fk_view_id: z.string().min(0).max(20).optional().describe("Foreign Key to View"),
      source_id: z.string().min(0).max(20).optional().describe("Baes ID\n"),
      base_id: z.string().min(0).max(20).optional().describe("Base ID"),
      title: z.string().optional().describe("Base ID"),
      show: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown?"),
      order: z.number().optional().describe("Column Order"),
    })).optional().describe("Kanban Columns"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info for Kanban"),
    title: z.string().optional().describe("Kanban Title"),
  }), z.object({
    source_id: z.string().optional().describe("The ID of the source that this view belongs to"),
    columns: z.array(z.object({
      source_id: z.string().optional().describe("The ID of the source that this map column belongs to"),
      fk_column_id: z.string().optional().describe("Foreign Key to Column"),
      fk_view_id: z.string().optional().describe("Foreign Key to View"),
      id: z.string().optional().describe("Unique ID of Map Column"),
      order: z.number().optional().describe("the order in the list of map columns"),
      base_id: z.string().optional().describe("The ID of the base that this map column belongs to"),
      show: z.number().optional().describe("Whether to show this column or not"),
    })).optional().describe("Columns in this view"),
    fk_geo_data_col_id: z.string().optional().describe("Foreign Key to GeoData Column"),
    fk_view_id: z.string().optional().describe("Unique ID for Map"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta data for this view"),
    order: z.number().optional().describe("The order of the map list"),
    base_id: z.string().optional().describe("The ID of the base that this view belongs to"),
    show: z.boolean().optional().describe("To show this Map or not"),
    title: z.string().optional().describe("Title of Map View"),
  }), z.object({
    id: z.string().min(0).max(20).optional().describe("Unique ID"),
    fk_view_id: z.string().min(0).max(20).optional().describe("View ID"),
    fk_cover_image_col_id: z.union([z.string(), z.unknown()]).optional().describe("Cover Image Column ID"),
    columns: z.array(z.object({
      id: z.string().min(0).max(20).optional().describe("Unique ID"),
      fk_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
      fk_view_id: z.string().min(0).max(20).optional().describe("Foreign Key to View"),
      source_id: z.string().min(0).max(20).optional().describe("Baes ID\n"),
      base_id: z.string().min(0).max(20).optional().describe("Base ID"),
      title: z.string().optional().describe("Base ID"),
      show: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown?"),
      bold: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown as bold?"),
      italic: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown as italic?"),
      underline: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Is this column shown underlines?"),
      order: z.number().optional().describe("Column Order"),
    })).optional().describe("Calendar Columns"),
    calendar_range: z.array(z.object({
      fk_from_column_id: z.string().min(0).max(20).optional().describe("Foreign Key to Column"),
      fk_view_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to View"),
      label: z.string().optional().describe("Base ID"),
    })).optional().describe("Calendar Date Range"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta Info for Kanban"),
    title: z.string().optional().describe("Kanban Title"),
  }), z.object({
    source_id: z.string().optional().describe("The ID of the source that this view belongs to"),
    columns: z.array(z.object({
      source_id: z.string().optional().describe("The ID of the source"),
      fk_column_id: z.string().optional().describe("Foreign Key to Column"),
      fk_view_id: z.string().optional().describe("Foreign Key to View"),
      fk_level_id: z.string().optional().describe("Foreign Key to Level"),
      id: z.string().optional().describe("Unique ID of List Column"),
      order: z.number().optional().describe("The order in the list of columns"),
      base_id: z.string().optional().describe("The ID of the base"),
      show: z.number().optional().describe("Whether to show this column or not"),
      width: z.string().optional().describe("Column width"),
    })).optional().describe("Columns in this view"),
    fk_view_id: z.string().optional().describe("Foreign Key to View"),
    meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta data for this view"),
    order: z.number().optional().describe("The order of the list"),
    base_id: z.string().optional().describe("The ID of the base that this view belongs to"),
    show: z.boolean().optional().describe("To show this view or not"),
    title: z.string().optional().describe("Title of List View"),
    show_empty_parents: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Show empty parent sections"),
    row_height: z.number().optional().describe("Row height for this list view"),
    fk_prefix_column_id: z.union([z.string(), z.unknown()]).optional().describe("Foreign Key to Prefix Column"),
    levels: z.array(z.object({
      id: z.string().optional().describe("Unique ID for Level"),
      fk_view_id: z.string().optional().describe("Foreign Key to View"),
      level: z.number().optional().describe("Level number (1, 2, or 3)"),
      fk_model_id: z.string().optional().describe("Foreign Key to Model (table) for this level"),
      fk_link_column_id: z.string().optional().describe("Foreign Key to Link Column connecting levels"),
      enable_nested_records: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Enable nested records (Level 1 only)"),
      fk_self_link_column_id: z.string().optional().describe("Foreign Key to Self-Link Column"),
      wrap_headers: z.union([z.number().int(), z.boolean(), z.unknown()]).optional().describe("Wrap column headers in this level"),
      meta: z.union([z.unknown(), z.record(z.string(), z.unknown()), z.string()]).optional().describe("Meta data for this level"),
    })).optional().describe("Levels configuration for this list view"),
  })]).optional().describe("Associated View Model"),
  owned_by: z.string().min(0).max(20).optional().describe("ID of view owner user"),
  row_coloring_mode: z.enum(["filter", "select"]).optional().describe("The row coloring mode whether it is select, condition or not set"),
  fk_custom_url_id: z.union([z.string(), z.unknown()]).optional().describe("ID of custom url"),
}).describe("Model for View")

export const dbViewFormCreate = pikkuSessionlessFunc({
  description: "Create a new form view in a given Table",
  input: DbViewFormCreateInput,
  output: DbViewFormCreateOutput,
  errors: [BadRequestError],
  func: async ({ nocodb }, data) => {
    return nocodb.call("POST", "/api/v1/db/meta/tables/{tableId}/forms", data) as any
  },
})
