import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const ChatPostMessageInput = z.object({
  token: z.string().describe("Authentication token. Requires scope: `chat:write`"),
  as_user: z.string().optional().describe("Pass true to post the message as the authed user, instead of as a bot. Defaults to false. See [authorship](#authorship) below."),
  attachments: z.string().optional().describe("A JSON-based array of structured attachments, presented as a URL-encoded string."),
  blocks: z.string().optional().describe("A JSON-based array of structured blocks, presented as a URL-encoded string."),
  channel: z.string().describe("Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name. See [below](#channels) for more details."),
  icon_emoji: z.string().optional().describe("Emoji to use as the icon for this message. Overrides `icon_url`. Must be used in conjunction with `as_user` set to `false`, otherwise ignored. See [authorship](#authorship) below."),
  icon_url: z.string().optional().describe("URL to an image to use as the icon for this message. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below."),
  link_names: z.boolean().optional().describe("Find and link channel names and usernames."),
  mrkdwn: z.boolean().optional().describe("Disable Slack markup parsing by setting to `false`. Enabled by default."),
  parse: z.string().optional().describe("Change how messages are treated. Defaults to `none`. See [below](#formatting)."),
  reply_broadcast: z.boolean().optional().describe("Used in conjunction with `thread_ts` and indicates whether reply should be made visible to everyone in the channel or conversation. Defaults to `false`."),
  text: z.string().optional().describe("How this field works and whether it is required depends on other fields you use in your API call. [See below](#text_usage) for more detail."),
  thread_ts: z.string().optional().describe("Provide another message's `ts` value to make this message a reply. Avoid using a reply's `ts` value; use its parent instead."),
  unfurl_links: z.boolean().optional().describe("Pass true to enable unfurling of primarily text-based content."),
  unfurl_media: z.boolean().optional().describe("Pass false to disable unfurling of media content."),
  username: z.string().optional().describe("Set your bot's user name. Must be used in conjunction with `as_user` set to false, otherwise ignored. See [authorship](#authorship) below."),
})

export const ChatPostMessageOutput = z.object({
  channel: z.string().regex(new RegExp("^[CGD][A-Z0-9]{8,}$")),
  message: z.object({
    attachments: z.array(z.object({
      fallback: z.string().optional(),
      id: z.number().int(),
      image_bytes: z.number().int().optional(),
      image_height: z.number().int().optional(),
      image_url: z.string().optional(),
      image_width: z.number().int().optional(),
    })).min(1).optional(),
    blocks: z.array(z.object({
      type: z.string(),
    })).optional().describe("This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace."),
    bot_id: z.unknown().optional(),
    bot_profile: z.object({
      app_id: z.string().regex(new RegExp("^A[A-Z0-9]{1,}$")),
      deleted: z.boolean(),
      icons: z.object({
        image_36: z.string().url(),
        image_48: z.string().url(),
        image_72: z.string().url(),
      }),
      id: z.string().regex(new RegExp("^B[A-Z0-9]{8,}$")),
      name: z.string(),
      team_id: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")),
      updated: z.number().int(),
    }).optional(),
    client_msg_id: z.string().optional(),
    comment: z.object({
      comment: z.string(),
      created: z.number().int(),
      id: z.string().regex(new RegExp("^Fc[A-Z0-9]{8,}$")),
      is_intro: z.boolean(),
      is_starred: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      timestamp: z.number().int(),
      user: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")),
    }).optional(),
    display_as_bot: z.boolean().optional(),
    file: z.object({
      channels: z.array(z.string()).optional(),
      comments_count: z.number().int().optional(),
      created: z.number().int().optional(),
      date_delete: z.number().int().optional(),
      display_as_bot: z.boolean().optional(),
      editable: z.boolean().optional(),
      editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      external_id: z.string().optional(),
      external_type: z.string().optional(),
      external_url: z.string().url().optional(),
      filetype: z.string().optional(),
      groups: z.array(z.string()).optional(),
      has_rich_preview: z.boolean().optional(),
      id: z.string().regex(new RegExp("^[F][A-Z0-9]{8,}$")).optional(),
      image_exif_rotation: z.number().int().optional(),
      ims: z.array(z.string()).optional(),
      is_external: z.boolean().optional(),
      is_public: z.boolean().optional(),
      is_starred: z.boolean().optional(),
      is_tombstoned: z.boolean().optional(),
      last_editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      mimetype: z.string().optional(),
      mode: z.string().optional(),
      name: z.string().optional(),
      non_owner_editable: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      original_h: z.number().int().optional(),
      original_w: z.number().int().optional(),
      permalink: z.string().url().optional(),
      permalink_public: z.string().url().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      pretty_type: z.string().optional(),
      preview: z.string().optional(),
      public_url_shared: z.boolean().optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      shares: z.object({
        private: z.unknown().optional(),
        public: z.unknown().optional(),
      }).optional(),
      size: z.number().int().optional(),
      source_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      state: z.string().optional(),
      thumb_1024: z.string().url().optional(),
      thumb_1024_h: z.number().int().optional(),
      thumb_1024_w: z.number().int().optional(),
      thumb_160: z.string().url().optional(),
      thumb_360: z.string().url().optional(),
      thumb_360_h: z.number().int().optional(),
      thumb_360_w: z.number().int().optional(),
      thumb_480: z.string().url().optional(),
      thumb_480_h: z.number().int().optional(),
      thumb_480_w: z.number().int().optional(),
      thumb_64: z.string().url().optional(),
      thumb_720: z.string().url().optional(),
      thumb_720_h: z.number().int().optional(),
      thumb_720_w: z.number().int().optional(),
      thumb_80: z.string().url().optional(),
      thumb_800: z.string().url().optional(),
      thumb_800_h: z.number().int().optional(),
      thumb_800_w: z.number().int().optional(),
      thumb_960: z.string().url().optional(),
      thumb_960_h: z.number().int().optional(),
      thumb_960_w: z.number().int().optional(),
      thumb_tiny: z.string().optional(),
      timestamp: z.number().int().optional(),
      title: z.string().optional(),
      updated: z.number().int().optional(),
      url_private: z.string().url().optional(),
      url_private_download: z.string().url().optional(),
      user: z.string().optional(),
      user_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      username: z.string().optional(),
    }).optional(),
    files: z.array(z.object({
      channels: z.array(z.string()).optional(),
      comments_count: z.number().int().optional(),
      created: z.number().int().optional(),
      date_delete: z.number().int().optional(),
      display_as_bot: z.boolean().optional(),
      editable: z.boolean().optional(),
      editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      external_id: z.string().optional(),
      external_type: z.string().optional(),
      external_url: z.string().url().optional(),
      filetype: z.string().optional(),
      groups: z.array(z.string()).optional(),
      has_rich_preview: z.boolean().optional(),
      id: z.string().regex(new RegExp("^[F][A-Z0-9]{8,}$")).optional(),
      image_exif_rotation: z.number().int().optional(),
      ims: z.array(z.string()).optional(),
      is_external: z.boolean().optional(),
      is_public: z.boolean().optional(),
      is_starred: z.boolean().optional(),
      is_tombstoned: z.boolean().optional(),
      last_editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      mimetype: z.string().optional(),
      mode: z.string().optional(),
      name: z.string().optional(),
      non_owner_editable: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      original_h: z.number().int().optional(),
      original_w: z.number().int().optional(),
      permalink: z.string().url().optional(),
      permalink_public: z.string().url().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      pretty_type: z.string().optional(),
      preview: z.string().optional(),
      public_url_shared: z.boolean().optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      shares: z.object({
        private: z.unknown().optional(),
        public: z.unknown().optional(),
      }).optional(),
      size: z.number().int().optional(),
      source_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      state: z.string().optional(),
      thumb_1024: z.string().url().optional(),
      thumb_1024_h: z.number().int().optional(),
      thumb_1024_w: z.number().int().optional(),
      thumb_160: z.string().url().optional(),
      thumb_360: z.string().url().optional(),
      thumb_360_h: z.number().int().optional(),
      thumb_360_w: z.number().int().optional(),
      thumb_480: z.string().url().optional(),
      thumb_480_h: z.number().int().optional(),
      thumb_480_w: z.number().int().optional(),
      thumb_64: z.string().url().optional(),
      thumb_720: z.string().url().optional(),
      thumb_720_h: z.number().int().optional(),
      thumb_720_w: z.number().int().optional(),
      thumb_80: z.string().url().optional(),
      thumb_800: z.string().url().optional(),
      thumb_800_h: z.number().int().optional(),
      thumb_800_w: z.number().int().optional(),
      thumb_960: z.string().url().optional(),
      thumb_960_h: z.number().int().optional(),
      thumb_960_w: z.number().int().optional(),
      thumb_tiny: z.string().optional(),
      timestamp: z.number().int().optional(),
      title: z.string().optional(),
      updated: z.number().int().optional(),
      url_private: z.string().url().optional(),
      url_private_download: z.string().url().optional(),
      user: z.string().optional(),
      user_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      username: z.string().optional(),
    })).min(1).optional(),
    icons: z.object({
      emoji: z.string().optional(),
      image_64: z.string().url().optional(),
    }).optional(),
    inviter: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    is_delayed_message: z.boolean().optional(),
    is_intro: z.boolean().optional(),
    is_starred: z.boolean().optional(),
    last_read: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    latest_reply: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    name: z.string().optional(),
    old_name: z.string().optional(),
    parent_user_id: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    permalink: z.string().url().optional(),
    pinned_to: z.array(z.string()).optional(),
    purpose: z.string().optional(),
    reactions: z.array(z.object({
      count: z.number().int(),
      name: z.string(),
      users: z.array(z.string()),
    })).optional(),
    reply_count: z.number().int().optional(),
    reply_users: z.array(z.string()).min(1).optional(),
    reply_users_count: z.number().int().optional(),
    source_team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    subscribed: z.boolean().optional(),
    subtype: z.string().optional(),
    team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    text: z.string(),
    thread_ts: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    topic: z.string().optional(),
    ts: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")),
    type: z.string(),
    unread_count: z.number().int().optional(),
    upload: z.boolean().optional(),
    user: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    user_profile: z.object({
      avatar_hash: z.string(),
      display_name: z.string(),
      display_name_normalized: z.string().optional(),
      first_name: z.string().nullable(),
      image_72: z.string().url(),
      is_restricted: z.boolean(),
      is_ultra_restricted: z.boolean(),
      name: z.string(),
      real_name: z.string(),
      real_name_normalized: z.string().optional(),
      team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")),
    }).optional(),
    user_team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    username: z.string().optional(),
  }),
  ok: z.literal(true),
  ts: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")),
}).describe("Schema for successful response of chat.postMessage method")

export const chatPostMessage = pikkuSessionlessFunc({
  description: "Sends a message to a channel.",
  input: ChatPostMessageInput,
  output: ChatPostMessageOutput,
  func: async ({ slack }, data) => {
    return slack.call("POST", "/chat.postMessage", data) as any
  },
})
