import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const ConversationsHistoryInput = z.object({
  token: z.string().optional().describe("Authentication token. Requires scope: `conversations:history`"),
  channel: z.string().optional().describe("Conversation ID to fetch history for."),
  latest: z.number().optional().describe("End of time range of messages to include in results."),
  oldest: z.number().optional().describe("Start of time range of messages to include in results."),
  inclusive: z.boolean().optional().describe("Include messages with latest or oldest timestamp in results only when either timestamp is specified."),
  limit: z.number().int().optional().describe("The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the users list hasn't been reached."),
  cursor: z.string().optional().describe("Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request's `response_metadata`. Default value fetches the first \"page\" of the collection. See [pagination](/docs/pagination) for more detail."),
})

export const ConversationsHistoryOutput = z.object({
  channel_actions_count: z.number().int(),
  channel_actions_ts: z.unknown(),
  has_more: z.boolean(),
  messages: z.array(z.object({
    attachments: z.array(z.object({
      fallback: z.string().optional(),
      id: z.number().int(),
      image_bytes: z.number().int().optional(),
      image_height: z.number().int().optional(),
      image_url: z.string().optional(),
      image_width: z.number().int().optional(),
    })).min(1).optional(),
    blocks: z.array(z.object({
      type: z.string(),
    })).optional().describe("This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace."),
    bot_id: z.unknown().optional(),
    bot_profile: z.object({
      app_id: z.string().regex(new RegExp("^A[A-Z0-9]{1,}$")),
      deleted: z.boolean(),
      icons: z.object({
        image_36: z.string().url(),
        image_48: z.string().url(),
        image_72: z.string().url(),
      }),
      id: z.string().regex(new RegExp("^B[A-Z0-9]{8,}$")),
      name: z.string(),
      team_id: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")),
      updated: z.number().int(),
    }).optional(),
    client_msg_id: z.string().optional(),
    comment: z.object({
      comment: z.string(),
      created: z.number().int(),
      id: z.string().regex(new RegExp("^Fc[A-Z0-9]{8,}$")),
      is_intro: z.boolean(),
      is_starred: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      timestamp: z.number().int(),
      user: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")),
    }).optional(),
    display_as_bot: z.boolean().optional(),
    file: z.object({
      channels: z.array(z.string()).optional(),
      comments_count: z.number().int().optional(),
      created: z.number().int().optional(),
      date_delete: z.number().int().optional(),
      display_as_bot: z.boolean().optional(),
      editable: z.boolean().optional(),
      editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      external_id: z.string().optional(),
      external_type: z.string().optional(),
      external_url: z.string().url().optional(),
      filetype: z.string().optional(),
      groups: z.array(z.string()).optional(),
      has_rich_preview: z.boolean().optional(),
      id: z.string().regex(new RegExp("^[F][A-Z0-9]{8,}$")).optional(),
      image_exif_rotation: z.number().int().optional(),
      ims: z.array(z.string()).optional(),
      is_external: z.boolean().optional(),
      is_public: z.boolean().optional(),
      is_starred: z.boolean().optional(),
      is_tombstoned: z.boolean().optional(),
      last_editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      mimetype: z.string().optional(),
      mode: z.string().optional(),
      name: z.string().optional(),
      non_owner_editable: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      original_h: z.number().int().optional(),
      original_w: z.number().int().optional(),
      permalink: z.string().url().optional(),
      permalink_public: z.string().url().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      pretty_type: z.string().optional(),
      preview: z.string().optional(),
      public_url_shared: z.boolean().optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      shares: z.object({
        private: z.unknown().optional(),
        public: z.unknown().optional(),
      }).optional(),
      size: z.number().int().optional(),
      source_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      state: z.string().optional(),
      thumb_1024: z.string().url().optional(),
      thumb_1024_h: z.number().int().optional(),
      thumb_1024_w: z.number().int().optional(),
      thumb_160: z.string().url().optional(),
      thumb_360: z.string().url().optional(),
      thumb_360_h: z.number().int().optional(),
      thumb_360_w: z.number().int().optional(),
      thumb_480: z.string().url().optional(),
      thumb_480_h: z.number().int().optional(),
      thumb_480_w: z.number().int().optional(),
      thumb_64: z.string().url().optional(),
      thumb_720: z.string().url().optional(),
      thumb_720_h: z.number().int().optional(),
      thumb_720_w: z.number().int().optional(),
      thumb_80: z.string().url().optional(),
      thumb_800: z.string().url().optional(),
      thumb_800_h: z.number().int().optional(),
      thumb_800_w: z.number().int().optional(),
      thumb_960: z.string().url().optional(),
      thumb_960_h: z.number().int().optional(),
      thumb_960_w: z.number().int().optional(),
      thumb_tiny: z.string().optional(),
      timestamp: z.number().int().optional(),
      title: z.string().optional(),
      updated: z.number().int().optional(),
      url_private: z.string().url().optional(),
      url_private_download: z.string().url().optional(),
      user: z.string().optional(),
      user_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      username: z.string().optional(),
    }).optional(),
    files: z.array(z.object({
      channels: z.array(z.string()).optional(),
      comments_count: z.number().int().optional(),
      created: z.number().int().optional(),
      date_delete: z.number().int().optional(),
      display_as_bot: z.boolean().optional(),
      editable: z.boolean().optional(),
      editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      external_id: z.string().optional(),
      external_type: z.string().optional(),
      external_url: z.string().url().optional(),
      filetype: z.string().optional(),
      groups: z.array(z.string()).optional(),
      has_rich_preview: z.boolean().optional(),
      id: z.string().regex(new RegExp("^[F][A-Z0-9]{8,}$")).optional(),
      image_exif_rotation: z.number().int().optional(),
      ims: z.array(z.string()).optional(),
      is_external: z.boolean().optional(),
      is_public: z.boolean().optional(),
      is_starred: z.boolean().optional(),
      is_tombstoned: z.boolean().optional(),
      last_editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
      mimetype: z.string().optional(),
      mode: z.string().optional(),
      name: z.string().optional(),
      non_owner_editable: z.boolean().optional(),
      num_stars: z.number().int().optional(),
      original_h: z.number().int().optional(),
      original_w: z.number().int().optional(),
      permalink: z.string().url().optional(),
      permalink_public: z.string().url().optional(),
      pinned_info: z.record(z.string(), z.unknown()).optional(),
      pinned_to: z.array(z.string()).optional(),
      pretty_type: z.string().optional(),
      preview: z.string().optional(),
      public_url_shared: z.boolean().optional(),
      reactions: z.array(z.object({
        count: z.number().int(),
        name: z.string(),
        users: z.array(z.string()),
      })).optional(),
      shares: z.object({
        private: z.unknown().optional(),
        public: z.unknown().optional(),
      }).optional(),
      size: z.number().int().optional(),
      source_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      state: z.string().optional(),
      thumb_1024: z.string().url().optional(),
      thumb_1024_h: z.number().int().optional(),
      thumb_1024_w: z.number().int().optional(),
      thumb_160: z.string().url().optional(),
      thumb_360: z.string().url().optional(),
      thumb_360_h: z.number().int().optional(),
      thumb_360_w: z.number().int().optional(),
      thumb_480: z.string().url().optional(),
      thumb_480_h: z.number().int().optional(),
      thumb_480_w: z.number().int().optional(),
      thumb_64: z.string().url().optional(),
      thumb_720: z.string().url().optional(),
      thumb_720_h: z.number().int().optional(),
      thumb_720_w: z.number().int().optional(),
      thumb_80: z.string().url().optional(),
      thumb_800: z.string().url().optional(),
      thumb_800_h: z.number().int().optional(),
      thumb_800_w: z.number().int().optional(),
      thumb_960: z.string().url().optional(),
      thumb_960_h: z.number().int().optional(),
      thumb_960_w: z.number().int().optional(),
      thumb_tiny: z.string().optional(),
      timestamp: z.number().int().optional(),
      title: z.string().optional(),
      updated: z.number().int().optional(),
      url_private: z.string().url().optional(),
      url_private_download: z.string().url().optional(),
      user: z.string().optional(),
      user_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
      username: z.string().optional(),
    })).min(1).optional(),
    icons: z.object({
      emoji: z.string().optional(),
      image_64: z.string().url().optional(),
    }).optional(),
    inviter: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    is_delayed_message: z.boolean().optional(),
    is_intro: z.boolean().optional(),
    is_starred: z.boolean().optional(),
    last_read: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    latest_reply: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    name: z.string().optional(),
    old_name: z.string().optional(),
    parent_user_id: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    permalink: z.string().url().optional(),
    pinned_to: z.array(z.string()).optional(),
    purpose: z.string().optional(),
    reactions: z.array(z.object({
      count: z.number().int(),
      name: z.string(),
      users: z.array(z.string()),
    })).optional(),
    reply_count: z.number().int().optional(),
    reply_users: z.array(z.string()).min(1).optional(),
    reply_users_count: z.number().int().optional(),
    source_team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    subscribed: z.boolean().optional(),
    subtype: z.string().optional(),
    team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    text: z.string(),
    thread_ts: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")).optional(),
    topic: z.string().optional(),
    ts: z.string().regex(new RegExp("^\\d{10}\\.\\d{6}$")),
    type: z.string(),
    unread_count: z.number().int().optional(),
    upload: z.boolean().optional(),
    user: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    user_profile: z.object({
      avatar_hash: z.string(),
      display_name: z.string(),
      display_name_normalized: z.string().optional(),
      first_name: z.string().nullable(),
      image_72: z.string().url(),
      is_restricted: z.boolean(),
      is_ultra_restricted: z.boolean(),
      name: z.string(),
      real_name: z.string(),
      real_name_normalized: z.string().optional(),
      team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")),
    }).optional(),
    user_team: z.string().regex(new RegExp("^[TE][A-Z0-9]{8,}$")).optional(),
    username: z.string().optional(),
  })).min(1),
  ok: z.literal(true),
  pin_count: z.number().int(),
}).describe("Schema for successful response from conversations.history method")

export const conversationsHistory = pikkuSessionlessFunc({
  description: "Fetches a conversation's history of messages and events.",
  input: ConversationsHistoryInput,
  output: ConversationsHistoryOutput,
  func: async ({ slack }, data) => {
    return slack.call("GET", "/conversations.history", data) as any
  },
})
