import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const FilesListInput = z.object({
  token: z.string().optional().describe("Authentication token. Requires scope: `files:read`"),
  user: z.string().optional().describe("Filter files created by a single user."),
  channel: z.string().optional().describe("Filter files appearing in a specific channel, indicated by its ID."),
  ts_from: z.number().optional().describe("Filter files created after this timestamp (inclusive)."),
  ts_to: z.number().optional().describe("Filter files created before this timestamp (inclusive)."),
  types: z.string().optional().describe("Filter files by type ([see below](#file_types)). You can pass multiple values in the types argument, like `types=spaces,snippets`.The default value is `all`, which does not filter the list."),
  count: z.string().optional(),
  page: z.string().optional(),
  show_files_hidden_by_limit: z.boolean().optional().describe("Show truncated file info for files hidden due to being too old, and the team who owns the file being over the file limit."),
})

export const FilesListOutput = z.object({
  files: z.array(z.object({
    channels: z.array(z.string()).optional(),
    comments_count: z.number().int().optional(),
    created: z.number().int().optional(),
    date_delete: z.number().int().optional(),
    display_as_bot: z.boolean().optional(),
    editable: z.boolean().optional(),
    editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    external_id: z.string().optional(),
    external_type: z.string().optional(),
    external_url: z.string().url().optional(),
    filetype: z.string().optional(),
    groups: z.array(z.string()).optional(),
    has_rich_preview: z.boolean().optional(),
    id: z.string().regex(new RegExp("^[F][A-Z0-9]{8,}$")).optional(),
    image_exif_rotation: z.number().int().optional(),
    ims: z.array(z.string()).optional(),
    is_external: z.boolean().optional(),
    is_public: z.boolean().optional(),
    is_starred: z.boolean().optional(),
    is_tombstoned: z.boolean().optional(),
    last_editor: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")).optional(),
    mimetype: z.string().optional(),
    mode: z.string().optional(),
    name: z.string().optional(),
    non_owner_editable: z.boolean().optional(),
    num_stars: z.number().int().optional(),
    original_h: z.number().int().optional(),
    original_w: z.number().int().optional(),
    permalink: z.string().url().optional(),
    permalink_public: z.string().url().optional(),
    pinned_info: z.record(z.string(), z.unknown()).optional(),
    pinned_to: z.array(z.string()).optional(),
    pretty_type: z.string().optional(),
    preview: z.string().optional(),
    public_url_shared: z.boolean().optional(),
    reactions: z.array(z.object({
      count: z.number().int(),
      name: z.string(),
      users: z.array(z.string()),
    })).optional(),
    shares: z.object({
      private: z.unknown().optional(),
      public: z.unknown().optional(),
    }).optional(),
    size: z.number().int().optional(),
    source_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
    state: z.string().optional(),
    thumb_1024: z.string().url().optional(),
    thumb_1024_h: z.number().int().optional(),
    thumb_1024_w: z.number().int().optional(),
    thumb_160: z.string().url().optional(),
    thumb_360: z.string().url().optional(),
    thumb_360_h: z.number().int().optional(),
    thumb_360_w: z.number().int().optional(),
    thumb_480: z.string().url().optional(),
    thumb_480_h: z.number().int().optional(),
    thumb_480_w: z.number().int().optional(),
    thumb_64: z.string().url().optional(),
    thumb_720: z.string().url().optional(),
    thumb_720_h: z.number().int().optional(),
    thumb_720_w: z.number().int().optional(),
    thumb_80: z.string().url().optional(),
    thumb_800: z.string().url().optional(),
    thumb_800_h: z.number().int().optional(),
    thumb_800_w: z.number().int().optional(),
    thumb_960: z.string().url().optional(),
    thumb_960_h: z.number().int().optional(),
    thumb_960_w: z.number().int().optional(),
    thumb_tiny: z.string().optional(),
    timestamp: z.number().int().optional(),
    title: z.string().optional(),
    updated: z.number().int().optional(),
    url_private: z.string().url().optional(),
    url_private_download: z.string().url().optional(),
    user: z.string().optional(),
    user_team: z.string().regex(new RegExp("^[T][A-Z0-9]{2,}$")).optional(),
    username: z.string().optional(),
  })).min(0),
  ok: z.literal(true),
  paging: z.object({
    count: z.number().int().optional(),
    page: z.number().int(),
    pages: z.number().int().optional(),
    per_page: z.number().int().optional(),
    spill: z.number().int().optional(),
    total: z.number().int(),
  }),
}).describe("Schema for successful response from files.list method")

export const filesList = pikkuSessionlessFunc({
  description: "List for a team, in a channel, or from a user with applied filters.",
  input: FilesListInput,
  output: FilesListOutput,
  func: async ({ slack }, data) => {
    return slack.call("GET", "/files.list", data) as any
  },
})
