import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const TeamIntegrationLogsInput = z.object({
  token: z.string().describe("Authentication token. Requires scope: `admin`"),
  app_id: z.string().optional().describe("Filter logs to this Slack app. Defaults to all logs."),
  change_type: z.string().optional().describe("Filter logs with this change type. Defaults to all logs."),
  count: z.string().optional(),
  page: z.string().optional(),
  service_id: z.string().optional().describe("Filter logs to this service. Defaults to all logs."),
  user: z.string().optional().describe("Filter logs generated by this user’s actions. Defaults to all logs."),
})

export const TeamIntegrationLogsOutput = z.object({
  logs: z.array(z.object({
    admin_app_id: z.string().regex(new RegExp("^A[A-Z0-9]{1,}$")).optional(),
    app_id: z.string().regex(new RegExp("^A[A-Z0-9]{1,}$")),
    app_type: z.string(),
    change_type: z.string(),
    channel: z.string().regex(new RegExp("^[CGD][A-Z0-9]{8,}$")).optional(),
    date: z.string(),
    scope: z.string(),
    service_id: z.string().optional(),
    service_type: z.string().optional(),
    user_id: z.string().regex(new RegExp("^[UW][A-Z0-9]{2,}$")),
    user_name: z.string(),
  })).min(1),
  ok: z.literal(true),
  paging: z.object({
    count: z.number().int().optional(),
    page: z.number().int(),
    pages: z.number().int().optional(),
    per_page: z.number().int().optional(),
    spill: z.number().int().optional(),
    total: z.number().int(),
  }),
}).describe("Schema for successful response from team.integrationLogs method")

export const teamIntegrationLogs = pikkuSessionlessFunc({
  description: "Gets the integration logs for the current team.",
  input: TeamIntegrationLogsInput,
  output: TeamIntegrationLogsOutput,
  func: async ({ slack }, data) => {
    return slack.call("GET", "/team.integrationLogs", data) as any
  },
})
