// Issues — This resource represents Jira issues. Use it to: * create or edit issues, individually or in bulk. * retrieve metadata about the options for creating or editing issues. * delete an issue. * assign a user to an issue. * get issue changelogs. * send notifications about an issue. * get details of the transitions available for an issue. * transition an issue.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { UnauthorizedError, NotFoundError } from '@pikku/core/errors'

export const GetIssueInput = z.object({
  issueIdOrKey: z.string().describe("The ID or key of the issue."),
  fields: z.array(z.string()).optional().describe("A list of fields to return for the issue. This parameter accepts a comma-separated list. Use it to retrieve a subset of fields. Allowed values:\n\n *  `*all` Returns all fields.\n *  `*navigable` Returns navigable fields.\n *  Any issue field, prefixed with a minus to exclude.\n\nExamples:\n\n *  `summary,comment` Returns only the summary and comments fields.\n *  `-description` Returns all (default) fields except description.\n *  `*navigable,-comment` Returns all navigable fields except comment.\n\nThis parameter may be specified multiple times. For example, `fields=field1,field2& fields=field3`.\n\nNote: All fields are returned by default. This differs from [Search for issues using JQL (GET)](#api-rest-api-3-search-get) and [Search for issues using JQL (POST)](#api-rest-api-3-search-post) where the default is all navigable fields."),
  fieldsByKeys: z.boolean().optional().default(false).describe("Whether fields in `fields` are referenced by keys rather than IDs. This parameter is useful where fields have been added by a connect app and a field's key may differ from its ID."),
  expand: z.string().optional().describe("Use [expand](#expansion) to include additional information about the issues in the response. This parameter accepts a comma-separated list. Expand options include:\n\n *  `renderedFields` Returns field values rendered in HTML format.\n *  `names` Returns the display name of each field.\n *  `schema` Returns the schema describing a field type.\n *  `transitions` Returns all possible transitions for the issue.\n *  `editmeta` Returns information about how each field can be edited.\n *  `changelog` Returns a list of recent updates to an issue, sorted by date, starting from the most recent.\n *  `versionedRepresentations` Returns a JSON array for each version of a field's value, with the highest number representing the most recent version. Note: When included in the request, the `fields` parameter is ignored."),
  properties: z.array(z.string()).optional().describe("A list of issue properties to return for the issue. This parameter accepts a comma-separated list. Allowed values:\n\n *  `*all` Returns all issue properties.\n *  Any issue property key, prefixed with a minus to exclude.\n\nExamples:\n\n *  `*all` Returns all properties.\n *  `*all,-prop1` Returns all properties except `prop1`.\n *  `prop1,prop2` Returns `prop1` and `prop2` properties.\n\nThis parameter may be specified multiple times. For example, `properties=prop1,prop2& properties=prop3`."),
  updateHistory: z.boolean().optional().default(false).describe("Whether the project in which the issue is created is added to the user's **Recently viewed** project list, as shown under **Projects** in Jira. This also populates the [JQL issues search](#api-rest-api-3-search-get) `lastViewed` field."),
})

export const GetIssueOutput = z.object({
  changelog: z.object({
    histories: z.array(z.object({
      author: z.object({
        accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
        accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
        active: z.boolean().optional().describe("Whether the user is active."),
        avatarUrls: z.object({
          "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
          "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
          "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
          "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
        }).optional().describe("The avatars of the user."),
        displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
        emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
        key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        self: z.string().optional().describe("The URL of the user."),
        timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
      }).optional().describe("The user who made the change."),
      created: z.string().datetime().optional().describe("The date on which the change took place."),
      historyMetadata: z.object({
        activityDescription: z.string().optional().describe("The activity described in the history record."),
        activityDescriptionKey: z.string().optional().describe("The key of the activity described in the history record."),
        actor: z.object({
          avatarUrl: z.string().optional().describe("The URL to an avatar for the user or system associated with a history record."),
          displayName: z.string().optional().describe("The display name of the user or system associated with a history record."),
          displayNameKey: z.string().optional().describe("The key of the display name of the user or system associated with a history record."),
          id: z.string().optional().describe("The ID of the user or system associated with a history record."),
          type: z.string().optional().describe("The type of the user or system associated with a history record."),
          url: z.string().optional().describe("The URL of the user or system associated with a history record."),
        }).optional().describe("Details of the user whose action created the history record."),
        cause: z.object({
          avatarUrl: z.string().optional().describe("The URL to an avatar for the user or system associated with a history record."),
          displayName: z.string().optional().describe("The display name of the user or system associated with a history record."),
          displayNameKey: z.string().optional().describe("The key of the display name of the user or system associated with a history record."),
          id: z.string().optional().describe("The ID of the user or system associated with a history record."),
          type: z.string().optional().describe("The type of the user or system associated with a history record."),
          url: z.string().optional().describe("The URL of the user or system associated with a history record."),
        }).optional().describe("Details of the cause that triggered the creation the history record."),
        description: z.string().optional().describe("The description of the history record."),
        descriptionKey: z.string().optional().describe("The description key of the history record."),
        emailDescription: z.string().optional().describe("The description of the email address associated the history record."),
        emailDescriptionKey: z.string().optional().describe("The description key of the email address associated the history record."),
        extraData: z.record(z.string(), z.string()).optional().describe("Additional arbitrary information about the history record."),
        generator: z.object({
          avatarUrl: z.string().optional().describe("The URL to an avatar for the user or system associated with a history record."),
          displayName: z.string().optional().describe("The display name of the user or system associated with a history record."),
          displayNameKey: z.string().optional().describe("The key of the display name of the user or system associated with a history record."),
          id: z.string().optional().describe("The ID of the user or system associated with a history record."),
          type: z.string().optional().describe("The type of the user or system associated with a history record."),
          url: z.string().optional().describe("The URL of the user or system associated with a history record."),
        }).optional().describe("Details of the system that generated the history record."),
        type: z.string().optional().describe("The type of the history record."),
      }).optional().describe("The history metadata associated with the changed."),
      id: z.string().optional().describe("The ID of the changelog."),
      items: z.array(z.object({
        field: z.string().optional().describe("The name of the field changed."),
        fieldId: z.string().optional().describe("The ID of the field changed."),
        fieldtype: z.string().optional().describe("The type of the field changed."),
        from: z.string().optional().describe("The details of the original value."),
        fromString: z.string().optional().describe("The details of the original value as a string."),
        to: z.string().optional().describe("The details of the new value."),
      })).optional().describe("The list of items changed."),
    })).optional().describe("The list of changelogs."),
    maxResults: z.number().int().optional().describe("The maximum number of results that could be on the page."),
    startAt: z.number().int().optional().describe("The index of the first item returned on the page."),
    total: z.number().int().optional().describe("The number of results on the page."),
  }).optional().describe("Details of changelogs associated with the issue."),
  editmeta: z.object({
    fields: z.record(z.string(), z.object({
      allowedValues: z.array(z.unknown()).optional().describe("The list of values allowed in the field."),
      autoCompleteUrl: z.string().optional().describe("The URL that can be used to automatically complete the field."),
      configuration: z.record(z.string(), z.unknown()).optional().describe("The configuration properties."),
      defaultValue: z.unknown().optional().describe("The default value of the field."),
      hasDefaultValue: z.boolean().optional().describe("Whether the field has a default value."),
      key: z.string().describe("The key of the field."),
      name: z.string().describe("The name of the field."),
      operations: z.array(z.string()).describe("The list of operations that can be performed on the field."),
      required: z.boolean().describe("Whether the field is required."),
      schema: z.object({
        configuration: z.record(z.string(), z.unknown()).optional().describe("If the field is a custom field, the configuration of the field."),
        custom: z.string().optional().describe("If the field is a custom field, the URI of the field."),
        customId: z.number().int().optional().describe("If the field is a custom field, the custom ID of the field."),
        items: z.string().optional().describe("When the data type is an array, the name of the field items within the array."),
        system: z.string().optional().describe("If the field is a system field, the name of the field."),
        type: z.string().describe("The data type of the field."),
      }).describe("The data type of the field."),
    }).describe("The metadata describing an issue field.")).optional(),
  }).optional().describe("The metadata for the fields on the issue that can be amended."),
  expand: z.string().optional().describe("Expand options that include additional issue details in the response."),
  fields: z.record(z.string(), z.unknown()).optional(),
  fieldsToInclude: z.object({
    actuallyIncluded: z.array(z.string()).optional(),
    excluded: z.array(z.string()).optional(),
    included: z.array(z.string()).optional(),
  }).optional(),
  id: z.string().optional().describe("The ID of the issue."),
  key: z.string().optional().describe("The key of the issue."),
  names: z.record(z.string(), z.string()).optional().describe("The ID and name of each field present on the issue."),
  operations: z.object({
    linkGroups: z.array(z.object({
      groups: z.array(z.object({
        groups: z.any().optional(),
        header: z.object({
          href: z.string().optional(),
          iconClass: z.string().optional(),
          id: z.string().optional(),
          label: z.string().optional(),
          styleClass: z.string().optional(),
          title: z.string().optional(),
          weight: z.number().int().optional(),
        }).optional().describe("Details about the operations available in this version."),
        id: z.string().optional(),
        links: z.array(z.object({
          href: z.string().optional(),
          iconClass: z.string().optional(),
          id: z.string().optional(),
          label: z.string().optional(),
          styleClass: z.string().optional(),
          title: z.string().optional(),
          weight: z.number().int().optional(),
        })).optional(),
        styleClass: z.string().optional(),
        weight: z.number().int().optional(),
      })).optional(),
      header: z.object({
        href: z.string().optional(),
        iconClass: z.string().optional(),
        id: z.string().optional(),
        label: z.string().optional(),
        styleClass: z.string().optional(),
        title: z.string().optional(),
        weight: z.number().int().optional(),
      }).optional().describe("Details about the operations available in this version."),
      id: z.string().optional(),
      links: z.array(z.object({
        href: z.string().optional(),
        iconClass: z.string().optional(),
        id: z.string().optional(),
        label: z.string().optional(),
        styleClass: z.string().optional(),
        title: z.string().optional(),
        weight: z.number().int().optional(),
      })).optional(),
      styleClass: z.string().optional(),
      weight: z.number().int().optional(),
    })).optional().describe("Details of the link groups defining issue operations."),
  }).optional().describe("The operations that can be performed on the issue."),
  properties: z.record(z.string(), z.unknown()).optional().describe("Details of the issue properties identified in the request."),
  renderedFields: z.record(z.string(), z.unknown()).optional().describe("The rendered value of each field present on the issue."),
  schema: z.record(z.string(), z.object({
    configuration: z.record(z.string(), z.unknown()).optional().describe("If the field is a custom field, the configuration of the field."),
    custom: z.string().optional().describe("If the field is a custom field, the URI of the field."),
    customId: z.number().int().optional().describe("If the field is a custom field, the custom ID of the field."),
    items: z.string().optional().describe("When the data type is an array, the name of the field items within the array."),
    system: z.string().optional().describe("If the field is a system field, the name of the field."),
    type: z.string().describe("The data type of the field."),
  }).describe("The schema of a field.")).optional().describe("The schema describing each field present on the issue."),
  self: z.string().url().optional().describe("The URL of the issue details."),
  transitions: z.array(z.object({
    expand: z.string().optional().describe("Expand options that include additional transition details in the response."),
    fields: z.record(z.string(), z.object({
      allowedValues: z.array(z.unknown()).optional().describe("The list of values allowed in the field."),
      autoCompleteUrl: z.string().optional().describe("The URL that can be used to automatically complete the field."),
      configuration: z.record(z.string(), z.unknown()).optional().describe("The configuration properties."),
      defaultValue: z.unknown().optional().describe("The default value of the field."),
      hasDefaultValue: z.boolean().optional().describe("Whether the field has a default value."),
      key: z.string().describe("The key of the field."),
      name: z.string().describe("The name of the field."),
      operations: z.array(z.string()).describe("The list of operations that can be performed on the field."),
      required: z.boolean().describe("Whether the field is required."),
      schema: z.object({
        configuration: z.record(z.string(), z.unknown()).optional().describe("If the field is a custom field, the configuration of the field."),
        custom: z.string().optional().describe("If the field is a custom field, the URI of the field."),
        customId: z.number().int().optional().describe("If the field is a custom field, the custom ID of the field."),
        items: z.string().optional().describe("When the data type is an array, the name of the field items within the array."),
        system: z.string().optional().describe("If the field is a system field, the name of the field."),
        type: z.string().describe("The data type of the field."),
      }).describe("The data type of the field."),
    }).describe("The metadata describing an issue field.")).optional().describe("Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request."),
    hasScreen: z.boolean().optional().describe("Whether there is a screen associated with the issue transition."),
    id: z.string().optional().describe("The ID of the issue transition. Required when specifying a transition to undertake."),
    isAvailable: z.boolean().optional().describe("Whether the transition is available to be performed."),
    isConditional: z.boolean().optional().describe("Whether the issue has to meet criteria before the issue transition is applied."),
    isGlobal: z.boolean().optional().describe("Whether the issue transition is global, that is, the transition is applied to issues regardless of their status."),
    isInitial: z.boolean().optional().describe("Whether this is the initial issue transition for the workflow."),
    looped: z.boolean().optional(),
    name: z.string().optional().describe("The name of the issue transition."),
    to: z.object({
      description: z.string().optional().describe("The description of the status."),
      iconUrl: z.string().optional().describe("The URL of the icon used to represent the status."),
      id: z.string().optional().describe("The ID of the status."),
      name: z.string().optional().describe("The name of the status."),
      self: z.string().optional().describe("The URL of the status."),
      statusCategory: z.object({
        colorName: z.string().optional().describe("The name of the color used to represent the status category."),
        id: z.number().int().optional().describe("The ID of the status category."),
        key: z.string().optional().describe("The key of the status category."),
        name: z.string().optional().describe("The name of the status category."),
        self: z.string().optional().describe("The URL of the status category."),
      }).optional().describe("The category assigned to the status."),
    }).optional().describe("Details of the issue status after the transition."),
  })).optional().describe("The transitions that can be performed on the issue."),
  versionedRepresentations: z.record(z.string(), z.record(z.string(), z.unknown())).optional().describe("The versions of each field on the issue."),
}).describe("Details about an issue.")

export const getIssue = pikkuSessionlessFunc({
  description: "Returns the details for an issue.\n\nThe issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned. The issue key returned in the response is the key of the issue found.\n\nThis operation can be accessed anonymously.\n\n**[Permissions](#permissions) required:**\n\n *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.\n *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.",
  input: GetIssueInput,
  output: GetIssueOutput,
  errors: [UnauthorizedError, NotFoundError],
  func: async ({ jira }, data) => {
    return jira.call("GET", "/rest/api/3/issue/{issueIdOrKey}", data) as any
  },
})
