// Issue links — This resource represents links between issues. Use it to get, create, and delete links between issues. To use it, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { BadRequestError, UnauthorizedError, NotFoundError } from '@pikku/core/errors'

export const GetIssueLinkInput = z.object({
  linkId: z.string().describe("The ID of the issue link."),
})

export const GetIssueLinkOutput = z.object({
  id: z.string().optional().describe("The ID of the issue link."),
  inwardIssue: z.object({
    fields: z.object({
      assignee: z.object({
        accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
        accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
        active: z.boolean().optional().describe("Whether the user is active."),
        avatarUrls: z.object({
          "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
          "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
          "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
          "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
        }).optional().describe("The avatars of the user."),
        displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
        emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
        key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        self: z.string().optional().describe("The URL of the user."),
        timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
      }).optional().describe("The assignee of the linked issue."),
      issueType: z.object({
        avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
        description: z.string().optional().describe("The description of the issue type."),
        entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
        hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
        iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
        id: z.string().optional().describe("The ID of the issue type."),
        name: z.string().optional().describe("The name of the issue type."),
        scope: z.object({
          project: z.object({
            avatarUrls: z.object({
              "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
              "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
              "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
              "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
            }).optional().describe("The URLs of the project's avatars."),
            id: z.string().optional().describe("The ID of the project."),
            key: z.string().optional().describe("The key of the project."),
            name: z.string().optional().describe("The name of the project."),
            projectCategory: z.object({
              description: z.string().optional().describe("The name of the project category."),
              id: z.string().optional().describe("The ID of the project category."),
              name: z.string().optional().describe("The description of the project category."),
              self: z.string().optional().describe("The URL of the project category."),
            }).optional().describe("The category the project belongs to."),
            projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
            self: z.string().optional().describe("The URL of the project details."),
            simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
          }).optional().describe("The project the item has scope in."),
          type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
        }).optional().describe("Details of the next-gen projects the issue type is available in."),
        self: z.string().optional().describe("The URL of these issue type details."),
        subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
      }).optional().describe("The type of the linked issue."),
      issuetype: z.object({
        avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
        description: z.string().optional().describe("The description of the issue type."),
        entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
        hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
        iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
        id: z.string().optional().describe("The ID of the issue type."),
        name: z.string().optional().describe("The name of the issue type."),
        scope: z.object({
          project: z.object({
            avatarUrls: z.object({
              "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
              "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
              "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
              "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
            }).optional().describe("The URLs of the project's avatars."),
            id: z.string().optional().describe("The ID of the project."),
            key: z.string().optional().describe("The key of the project."),
            name: z.string().optional().describe("The name of the project."),
            projectCategory: z.object({
              description: z.string().optional().describe("The name of the project category."),
              id: z.string().optional().describe("The ID of the project category."),
              name: z.string().optional().describe("The description of the project category."),
              self: z.string().optional().describe("The URL of the project category."),
            }).optional().describe("The category the project belongs to."),
            projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
            self: z.string().optional().describe("The URL of the project details."),
            simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
          }).optional().describe("The project the item has scope in."),
          type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
        }).optional().describe("Details of the next-gen projects the issue type is available in."),
        self: z.string().optional().describe("The URL of these issue type details."),
        subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
      }).optional().describe("The type of the linked issue."),
      priority: z.object({
        description: z.string().optional().describe("The description of the issue priority."),
        iconUrl: z.string().optional().describe("The URL of the icon for the issue priority."),
        id: z.string().optional().describe("The ID of the issue priority."),
        isDefault: z.boolean().optional().describe("Whether this priority is the default."),
        name: z.string().optional().describe("The name of the issue priority."),
        self: z.string().optional().describe("The URL of the issue priority."),
        statusColor: z.string().optional().describe("The color used to indicate the issue priority."),
      }).optional().describe("The priority of the linked issue."),
      status: z.object({
        description: z.string().optional().describe("The description of the status."),
        iconUrl: z.string().optional().describe("The URL of the icon used to represent the status."),
        id: z.string().optional().describe("The ID of the status."),
        name: z.string().optional().describe("The name of the status."),
        self: z.string().optional().describe("The URL of the status."),
        statusCategory: z.object({
          colorName: z.string().optional().describe("The name of the color used to represent the status category."),
          id: z.number().int().optional().describe("The ID of the status category."),
          key: z.string().optional().describe("The key of the status category."),
          name: z.string().optional().describe("The name of the status category."),
          self: z.string().optional().describe("The URL of the status category."),
        }).optional().describe("The category assigned to the status."),
      }).optional().describe("The status of the linked issue."),
      summary: z.string().optional().describe("The summary description of the linked issue."),
      timetracking: z.object({
        originalEstimate: z.string().optional().describe("The original estimate of time needed for this issue in readable format."),
        originalEstimateSeconds: z.number().int().optional().describe("The original estimate of time needed for this issue in seconds."),
        remainingEstimate: z.string().optional().describe("The remaining estimate of time needed for this issue in readable format."),
        remainingEstimateSeconds: z.number().int().optional().describe("The remaining estimate of time needed for this issue in seconds."),
        timeSpent: z.string().optional().describe("Time worked on this issue in readable format."),
        timeSpentSeconds: z.number().int().optional().describe("Time worked on this issue in seconds."),
      }).optional().describe("The time tracking of the linked issue."),
    }).optional().describe("The fields associated with the issue."),
    id: z.string().optional().describe("The ID of an issue. Required if `key` isn't provided."),
    key: z.string().optional().describe("The key of an issue. Required if `id` isn't provided."),
    self: z.string().url().optional().describe("The URL of the issue."),
  }).describe("Provides details about the linked issue. If presenting this link in a user interface, use the `inward` field of the issue link type to label the link."),
  outwardIssue: z.object({
    fields: z.object({
      assignee: z.object({
        accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
        accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
        active: z.boolean().optional().describe("Whether the user is active."),
        avatarUrls: z.object({
          "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
          "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
          "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
          "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
        }).optional().describe("The avatars of the user."),
        displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
        emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
        key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
        self: z.string().optional().describe("The URL of the user."),
        timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
      }).optional().describe("The assignee of the linked issue."),
      issueType: z.object({
        avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
        description: z.string().optional().describe("The description of the issue type."),
        entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
        hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
        iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
        id: z.string().optional().describe("The ID of the issue type."),
        name: z.string().optional().describe("The name of the issue type."),
        scope: z.object({
          project: z.object({
            avatarUrls: z.object({
              "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
              "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
              "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
              "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
            }).optional().describe("The URLs of the project's avatars."),
            id: z.string().optional().describe("The ID of the project."),
            key: z.string().optional().describe("The key of the project."),
            name: z.string().optional().describe("The name of the project."),
            projectCategory: z.object({
              description: z.string().optional().describe("The name of the project category."),
              id: z.string().optional().describe("The ID of the project category."),
              name: z.string().optional().describe("The description of the project category."),
              self: z.string().optional().describe("The URL of the project category."),
            }).optional().describe("The category the project belongs to."),
            projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
            self: z.string().optional().describe("The URL of the project details."),
            simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
          }).optional().describe("The project the item has scope in."),
          type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
        }).optional().describe("Details of the next-gen projects the issue type is available in."),
        self: z.string().optional().describe("The URL of these issue type details."),
        subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
      }).optional().describe("The type of the linked issue."),
      issuetype: z.object({
        avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
        description: z.string().optional().describe("The description of the issue type."),
        entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
        hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
        iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
        id: z.string().optional().describe("The ID of the issue type."),
        name: z.string().optional().describe("The name of the issue type."),
        scope: z.object({
          project: z.object({
            avatarUrls: z.object({
              "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
              "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
              "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
              "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
            }).optional().describe("The URLs of the project's avatars."),
            id: z.string().optional().describe("The ID of the project."),
            key: z.string().optional().describe("The key of the project."),
            name: z.string().optional().describe("The name of the project."),
            projectCategory: z.object({
              description: z.string().optional().describe("The name of the project category."),
              id: z.string().optional().describe("The ID of the project category."),
              name: z.string().optional().describe("The description of the project category."),
              self: z.string().optional().describe("The URL of the project category."),
            }).optional().describe("The category the project belongs to."),
            projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
            self: z.string().optional().describe("The URL of the project details."),
            simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
          }).optional().describe("The project the item has scope in."),
          type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
        }).optional().describe("Details of the next-gen projects the issue type is available in."),
        self: z.string().optional().describe("The URL of these issue type details."),
        subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
      }).optional().describe("The type of the linked issue."),
      priority: z.object({
        description: z.string().optional().describe("The description of the issue priority."),
        iconUrl: z.string().optional().describe("The URL of the icon for the issue priority."),
        id: z.string().optional().describe("The ID of the issue priority."),
        isDefault: z.boolean().optional().describe("Whether this priority is the default."),
        name: z.string().optional().describe("The name of the issue priority."),
        self: z.string().optional().describe("The URL of the issue priority."),
        statusColor: z.string().optional().describe("The color used to indicate the issue priority."),
      }).optional().describe("The priority of the linked issue."),
      status: z.object({
        description: z.string().optional().describe("The description of the status."),
        iconUrl: z.string().optional().describe("The URL of the icon used to represent the status."),
        id: z.string().optional().describe("The ID of the status."),
        name: z.string().optional().describe("The name of the status."),
        self: z.string().optional().describe("The URL of the status."),
        statusCategory: z.object({
          colorName: z.string().optional().describe("The name of the color used to represent the status category."),
          id: z.number().int().optional().describe("The ID of the status category."),
          key: z.string().optional().describe("The key of the status category."),
          name: z.string().optional().describe("The name of the status category."),
          self: z.string().optional().describe("The URL of the status category."),
        }).optional().describe("The category assigned to the status."),
      }).optional().describe("The status of the linked issue."),
      summary: z.string().optional().describe("The summary description of the linked issue."),
      timetracking: z.object({
        originalEstimate: z.string().optional().describe("The original estimate of time needed for this issue in readable format."),
        originalEstimateSeconds: z.number().int().optional().describe("The original estimate of time needed for this issue in seconds."),
        remainingEstimate: z.string().optional().describe("The remaining estimate of time needed for this issue in readable format."),
        remainingEstimateSeconds: z.number().int().optional().describe("The remaining estimate of time needed for this issue in seconds."),
        timeSpent: z.string().optional().describe("Time worked on this issue in readable format."),
        timeSpentSeconds: z.number().int().optional().describe("Time worked on this issue in seconds."),
      }).optional().describe("The time tracking of the linked issue."),
    }).optional().describe("The fields associated with the issue."),
    id: z.string().optional().describe("The ID of an issue. Required if `key` isn't provided."),
    key: z.string().optional().describe("The key of an issue. Required if `id` isn't provided."),
    self: z.string().url().optional().describe("The URL of the issue."),
  }).describe("Provides details about the linked issue. If presenting this link in a user interface, use the `outward` field of the issue link type to label the link."),
  self: z.string().url().optional().describe("The URL of the issue link."),
  type: z.object({
    id: z.string().optional().describe("The ID of the issue link type and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is the type of issue link. Required on create when `name` isn't provided. Otherwise, read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is read only."),
    inward: z.string().optional().describe("The description of the issue link type inward link and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
    name: z.string().optional().describe("The name of the issue link type and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is the type of issue link. Required on create when `id` isn't provided. Otherwise, read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
    outward: z.string().optional().describe("The description of the issue link type outward link and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
    self: z.string().url().optional().describe("The URL of the issue link type. Read only."),
  }).describe("The type of link between the issues."),
}).describe("Details of a link between issues.")

export const getIssueLink = pikkuSessionlessFunc({
  description: "Returns an issue link.\n\nThis operation can be accessed anonymously.\n\n**[Permissions](#permissions) required:**\n\n *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the linked issues.\n *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, permission to view both of the issues.",
  input: GetIssueLinkInput,
  output: GetIssueLinkOutput,
  errors: [BadRequestError, UnauthorizedError, NotFoundError],
  func: async ({ jira }, data) => {
    return jira.call("GET", "/rest/api/3/issueLink/{linkId}", data) as any
  },
})
