// Project components — This resource represents project components. Use it to get, create, update, and delete project components. Also get components for project and get a count of issues by component.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { UnauthorizedError, NotFoundError } from '@pikku/core/errors'

export const GetProjectComponentsPaginatedInput = z.object({
  projectIdOrKey: z.string().describe("The project ID or project key (case sensitive)."),
  startAt: z.number().int().optional().default(0).describe("The index of the first item to return in a page of results (page offset)."),
  maxResults: z.number().int().optional().default(50).describe("The maximum number of items to return per page."),
  orderBy: z.enum(["description", "-description", "+description", "issueCount", "-issueCount", "+issueCount", "lead", "-lead", "+lead", "name", "-name", "+name"]).optional().describe("[Order](#ordering) the results by a field:\n\n *  `description` Sorts by the component description.\n *  `issueCount` Sorts by the count of issues associated with the component.\n *  `lead` Sorts by the user key of the component's project lead.\n *  `name` Sorts by component name."),
  query: z.string().optional().describe("Filter the results using a literal string. Components with a matching `name` or `description` are returned (case insensitive)."),
})

export const GetProjectComponentsPaginatedOutput = z.object({
  isLast: z.boolean().optional().describe("Whether this is the last page."),
  maxResults: z.number().int().optional().describe("The maximum number of items that could be returned."),
  nextPage: z.string().url().optional().describe("If there is another page of results, the URL of the next page."),
  self: z.string().url().optional().describe("The URL of the page."),
  startAt: z.number().int().optional().describe("The index of the first item returned."),
  total: z.number().int().optional().describe("The number of items returned."),
  values: z.array(z.object({
    assignee: z.object({
      accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
      accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
      active: z.boolean().optional().describe("Whether the user is active."),
      applicationRoles: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
          defaultGroupsDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups that are granted default access for this application role."),
          defined: z.boolean().optional().describe("Deprecated."),
          groupDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups associated with the application role."),
          groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
          hasUnlimitedSeats: z.boolean().optional(),
          key: z.string().optional().describe("The key of the application role."),
          name: z.string().optional().describe("The display name of the application role."),
          numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
          platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
          remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
          selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
          userCount: z.number().int().optional().describe("The number of users counting against your license."),
          userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The application roles the user is assigned to."),
      avatarUrls: z.object({
        "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
        "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
        "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
        "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
      }).optional().describe("The avatars of the user."),
      displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
      emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
      expand: z.string().optional().describe("Expand options that include additional user details in the response."),
      groups: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The groups that the user belongs to."),
      key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
      name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      self: z.string().url().optional().describe("The URL of the user."),
      timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
    }).optional().describe("The details of the user associated with `assigneeType`, if any. See `realAssignee` for details of the user assigned to issues created with this component."),
    assigneeType: z.enum(["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]).optional().describe("The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Takes the following values:\n\n *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.\n *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.\n *  `UNASSIGNED` an assignee is not set for issues created with this component.\n *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in."),
    description: z.string().optional().describe("The description for the component."),
    id: z.string().optional().describe("The unique identifier for the component."),
    isAssigneeTypeValid: z.boolean().optional().describe("Whether a user is associated with `assigneeType`. For example, if the `assigneeType` is set to `COMPONENT_LEAD` but the component lead is not set, then `false` is returned."),
    issueCount: z.number().int().optional().describe("Count of issues for the component."),
    lead: z.object({
      accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
      accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
      active: z.boolean().optional().describe("Whether the user is active."),
      applicationRoles: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
          defaultGroupsDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups that are granted default access for this application role."),
          defined: z.boolean().optional().describe("Deprecated."),
          groupDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups associated with the application role."),
          groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
          hasUnlimitedSeats: z.boolean().optional(),
          key: z.string().optional().describe("The key of the application role."),
          name: z.string().optional().describe("The display name of the application role."),
          numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
          platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
          remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
          selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
          userCount: z.number().int().optional().describe("The number of users counting against your license."),
          userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The application roles the user is assigned to."),
      avatarUrls: z.object({
        "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
        "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
        "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
        "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
      }).optional().describe("The avatars of the user."),
      displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
      emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
      expand: z.string().optional().describe("Expand options that include additional user details in the response."),
      groups: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The groups that the user belongs to."),
      key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
      name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      self: z.string().url().optional().describe("The URL of the user."),
      timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
    }).optional().describe("The user details for the component's lead user."),
    name: z.string().optional().describe("The name for the component."),
    project: z.string().optional().describe("The key of the project to which the component is assigned."),
    projectId: z.number().int().optional().describe("Not used."),
    realAssignee: z.object({
      accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
      accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
      active: z.boolean().optional().describe("Whether the user is active."),
      applicationRoles: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
          defaultGroupsDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups that are granted default access for this application role."),
          defined: z.boolean().optional().describe("Deprecated."),
          groupDetails: z.array(z.object({
            groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
            name: z.string().optional().describe("The name of group."),
            self: z.string().url().optional().describe("The URL for these group details."),
          })).optional().describe("The groups associated with the application role."),
          groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
          hasUnlimitedSeats: z.boolean().optional(),
          key: z.string().optional().describe("The key of the application role."),
          name: z.string().optional().describe("The display name of the application role."),
          numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
          platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
          remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
          selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
          userCount: z.number().int().optional().describe("The number of users counting against your license."),
          userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The application roles the user is assigned to."),
      avatarUrls: z.object({
        "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
        "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
        "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
        "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
      }).optional().describe("The avatars of the user."),
      displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
      emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
      expand: z.string().optional().describe("Expand options that include additional user details in the response."),
      groups: z.object({
        callback: z.record(z.string(), z.unknown()).optional(),
        items: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional(),
        "max-results": z.number().int().optional(),
        pagingCallback: z.record(z.string(), z.unknown()).optional(),
        size: z.number().int().optional(),
      }).optional().describe("The groups that the user belongs to."),
      key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
      name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      self: z.string().url().optional().describe("The URL of the user."),
      timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
    }).optional().describe("The user assigned to issues created with this component, when `assigneeType` does not identify a valid assignee."),
    realAssigneeType: z.enum(["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]).optional().describe("The type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:\n\n *  `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in.\n *  `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in.\n *  `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues.\n *  `PROJECT_DEFAULT` when none of the preceding cases are true."),
    self: z.string().url().optional().describe("The URL for this count of the issues contained in the component."),
  })).optional().describe("The list of items."),
}).describe("A page of items.")

export const getProjectComponentsPaginated = pikkuSessionlessFunc({
  description: "Returns a [paginated](#pagination) list of all components in a project. See the [Get project components](#api-rest-api-3-project-projectIdOrKey-components-get) resource if you want to get a full list of versions without pagination.\n\nThis operation can be accessed anonymously.\n\n**[Permissions](#permissions) required:** *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.",
  input: GetProjectComponentsPaginatedInput,
  output: GetProjectComponentsPaginatedOutput,
  errors: [UnauthorizedError, NotFoundError],
  func: async ({ jira }, data) => {
    return jira.call("GET", "/rest/api/3/project/{projectIdOrKey}/component", data) as any
  },
})
