// Issue links — This resource represents links between issues. Use it to get, create, and delete links between issues. To use it, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { BadRequestError, UnauthorizedError, NotFoundError } from '@pikku/core/errors'

export const LinkIssuesInput = z.object({
  comment: z.object({
  author: z.object({
    accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
    accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
    active: z.boolean().optional().describe("Whether the user is active."),
    avatarUrls: z.object({
      "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
      "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
      "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
      "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
    }).optional().describe("The avatars of the user."),
    displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
    emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
    key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    self: z.string().optional().describe("The URL of the user."),
    timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
  }).optional().describe("The ID of the user who created the comment."),
  body: z.unknown().optional().describe("The comment text in [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/)."),
  created: z.string().datetime().optional().describe("The date and time at which the comment was created."),
  id: z.string().optional().describe("The ID of the comment."),
  jsdAuthorCanSeeRequest: z.boolean().optional().describe("Whether the comment was added from an email sent by a person who is not part of the issue. See [Allow external emails to be added as comments on issues](https://support.atlassian.com/jira-service-management-cloud/docs/allow-external-emails-to-be-added-as-comments-on-issues/)for information on setting up this feature."),
  jsdPublic: z.boolean().optional().describe("Whether the comment is visible in Jira Service Desk. Defaults to true when comments are created in the Jira Cloud Platform. This includes when the site doesn't use Jira Service Desk or the project isn't a Jira Service Desk project and, therefore, there is no Jira Service Desk for the issue to be visible on. To create a comment with its visibility in Jira Service Desk set to false, use the Jira Service Desk REST API [Create request comment](https://developer.atlassian.com/cloud/jira/service-desk/rest/#api-rest-servicedeskapi-request-issueIdOrKey-comment-post) operation."),
  properties: z.array(z.object({
    key: z.string().optional().describe("The key of the property. Required on create and update."),
    value: z.unknown().optional().describe("The value of the property. Required on create and update."),
  })).optional().describe("A list of comment properties. Optional on create and update."),
  renderedBody: z.string().optional().describe("The rendered version of the comment."),
  self: z.string().optional().describe("The URL of the comment."),
  updateAuthor: z.object({
    accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
    accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
    active: z.boolean().optional().describe("Whether the user is active."),
    avatarUrls: z.object({
      "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
      "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
      "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
      "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
    }).optional().describe("The avatars of the user."),
    displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
    emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
    key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    self: z.string().optional().describe("The URL of the user."),
    timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
  }).optional().describe("The ID of the user who updated the comment last."),
  updated: z.string().datetime().optional().describe("The date and time at which the comment was updated last."),
  visibility: z.object({
    identifier: z.string().nullable().optional().describe("The ID of the group or the name of the role that visibility of this item is restricted to."),
    type: z.enum(["group", "role"]).optional().describe("Whether visibility of this item is restricted to a group or role."),
    value: z.string().optional().describe("The name of the group or role that visibility of this item is restricted to. Please note that the name of a group is mutable, to reliably identify a group use `identifier`."),
  }).optional().describe("The group or role to which this comment is visible. Optional on create and update."),
}).optional().describe("A comment."),
  inwardIssue: z.object({
  fields: z.object({
    assignee: z.object({
      accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
      accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
      active: z.boolean().optional().describe("Whether the user is active."),
      avatarUrls: z.object({
        "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
        "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
        "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
        "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
      }).optional().describe("The avatars of the user."),
      displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
      emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
      key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      self: z.string().optional().describe("The URL of the user."),
      timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
    }).optional().describe("The assignee of the linked issue."),
    issueType: z.object({
      avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
      description: z.string().optional().describe("The description of the issue type."),
      entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
      hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
      iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
      id: z.string().optional().describe("The ID of the issue type."),
      name: z.string().optional().describe("The name of the issue type."),
      scope: z.object({
        project: z.object({
          avatarUrls: z.object({
            "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
            "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
            "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
            "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
          }).optional().describe("The URLs of the project's avatars."),
          id: z.string().optional().describe("The ID of the project."),
          key: z.string().optional().describe("The key of the project."),
          name: z.string().optional().describe("The name of the project."),
          projectCategory: z.object({
            description: z.string().optional().describe("The name of the project category."),
            id: z.string().optional().describe("The ID of the project category."),
            name: z.string().optional().describe("The description of the project category."),
            self: z.string().optional().describe("The URL of the project category."),
          }).optional().describe("The category the project belongs to."),
          projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
          self: z.string().optional().describe("The URL of the project details."),
          simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
        }).optional().describe("The project the item has scope in."),
        type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
      }).optional().describe("Details of the next-gen projects the issue type is available in."),
      self: z.string().optional().describe("The URL of these issue type details."),
      subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
    }).optional().describe("The type of the linked issue."),
    issuetype: z.object({
      avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
      description: z.string().optional().describe("The description of the issue type."),
      entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
      hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
      iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
      id: z.string().optional().describe("The ID of the issue type."),
      name: z.string().optional().describe("The name of the issue type."),
      scope: z.object({
        project: z.object({
          avatarUrls: z.object({
            "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
            "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
            "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
            "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
          }).optional().describe("The URLs of the project's avatars."),
          id: z.string().optional().describe("The ID of the project."),
          key: z.string().optional().describe("The key of the project."),
          name: z.string().optional().describe("The name of the project."),
          projectCategory: z.object({
            description: z.string().optional().describe("The name of the project category."),
            id: z.string().optional().describe("The ID of the project category."),
            name: z.string().optional().describe("The description of the project category."),
            self: z.string().optional().describe("The URL of the project category."),
          }).optional().describe("The category the project belongs to."),
          projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
          self: z.string().optional().describe("The URL of the project details."),
          simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
        }).optional().describe("The project the item has scope in."),
        type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
      }).optional().describe("Details of the next-gen projects the issue type is available in."),
      self: z.string().optional().describe("The URL of these issue type details."),
      subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
    }).optional().describe("The type of the linked issue."),
    priority: z.object({
      description: z.string().optional().describe("The description of the issue priority."),
      iconUrl: z.string().optional().describe("The URL of the icon for the issue priority."),
      id: z.string().optional().describe("The ID of the issue priority."),
      isDefault: z.boolean().optional().describe("Whether this priority is the default."),
      name: z.string().optional().describe("The name of the issue priority."),
      self: z.string().optional().describe("The URL of the issue priority."),
      statusColor: z.string().optional().describe("The color used to indicate the issue priority."),
    }).optional().describe("The priority of the linked issue."),
    status: z.object({
      description: z.string().optional().describe("The description of the status."),
      iconUrl: z.string().optional().describe("The URL of the icon used to represent the status."),
      id: z.string().optional().describe("The ID of the status."),
      name: z.string().optional().describe("The name of the status."),
      self: z.string().optional().describe("The URL of the status."),
      statusCategory: z.object({
        colorName: z.string().optional().describe("The name of the color used to represent the status category."),
        id: z.number().int().optional().describe("The ID of the status category."),
        key: z.string().optional().describe("The key of the status category."),
        name: z.string().optional().describe("The name of the status category."),
        self: z.string().optional().describe("The URL of the status category."),
      }).optional().describe("The category assigned to the status."),
    }).optional().describe("The status of the linked issue."),
    summary: z.string().optional().describe("The summary description of the linked issue."),
    timetracking: z.object({
      originalEstimate: z.string().optional().describe("The original estimate of time needed for this issue in readable format."),
      originalEstimateSeconds: z.number().int().optional().describe("The original estimate of time needed for this issue in seconds."),
      remainingEstimate: z.string().optional().describe("The remaining estimate of time needed for this issue in readable format."),
      remainingEstimateSeconds: z.number().int().optional().describe("The remaining estimate of time needed for this issue in seconds."),
      timeSpent: z.string().optional().describe("Time worked on this issue in readable format."),
      timeSpentSeconds: z.number().int().optional().describe("Time worked on this issue in seconds."),
    }).optional().describe("The time tracking of the linked issue."),
  }).optional().describe("The fields associated with the issue."),
  id: z.string().optional().describe("The ID of an issue. Required if `key` isn't provided."),
  key: z.string().optional().describe("The key of an issue. Required if `id` isn't provided."),
  self: z.string().url().optional().describe("The URL of the issue."),
}).describe("The ID or key of a linked issue."),
  outwardIssue: z.object({
  fields: z.object({
    assignee: z.object({
      accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
      accountType: z.string().optional().describe("The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)"),
      active: z.boolean().optional().describe("Whether the user is active."),
      avatarUrls: z.object({
        "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
        "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
        "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
        "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
      }).optional().describe("The avatars of the user."),
      displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy settings, this may return an alternative value."),
      emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy settings, this may be returned as null."),
      key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
      self: z.string().optional().describe("The URL of the user."),
      timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null."),
    }).optional().describe("The assignee of the linked issue."),
    issueType: z.object({
      avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
      description: z.string().optional().describe("The description of the issue type."),
      entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
      hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
      iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
      id: z.string().optional().describe("The ID of the issue type."),
      name: z.string().optional().describe("The name of the issue type."),
      scope: z.object({
        project: z.object({
          avatarUrls: z.object({
            "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
            "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
            "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
            "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
          }).optional().describe("The URLs of the project's avatars."),
          id: z.string().optional().describe("The ID of the project."),
          key: z.string().optional().describe("The key of the project."),
          name: z.string().optional().describe("The name of the project."),
          projectCategory: z.object({
            description: z.string().optional().describe("The name of the project category."),
            id: z.string().optional().describe("The ID of the project category."),
            name: z.string().optional().describe("The description of the project category."),
            self: z.string().optional().describe("The URL of the project category."),
          }).optional().describe("The category the project belongs to."),
          projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
          self: z.string().optional().describe("The URL of the project details."),
          simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
        }).optional().describe("The project the item has scope in."),
        type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
      }).optional().describe("Details of the next-gen projects the issue type is available in."),
      self: z.string().optional().describe("The URL of these issue type details."),
      subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
    }).optional().describe("The type of the linked issue."),
    issuetype: z.object({
      avatarId: z.number().int().optional().describe("The ID of the issue type's avatar."),
      description: z.string().optional().describe("The description of the issue type."),
      entityId: z.string().uuid().optional().describe("Unique ID for next-gen projects."),
      hierarchyLevel: z.number().int().optional().describe("Hierarchy level of the issue type."),
      iconUrl: z.string().optional().describe("The URL of the issue type's avatar."),
      id: z.string().optional().describe("The ID of the issue type."),
      name: z.string().optional().describe("The name of the issue type."),
      scope: z.object({
        project: z.object({
          avatarUrls: z.object({
            "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
            "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
            "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
            "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
          }).optional().describe("The URLs of the project's avatars."),
          id: z.string().optional().describe("The ID of the project."),
          key: z.string().optional().describe("The key of the project."),
          name: z.string().optional().describe("The name of the project."),
          projectCategory: z.object({
            description: z.string().optional().describe("The name of the project category."),
            id: z.string().optional().describe("The ID of the project category."),
            name: z.string().optional().describe("The description of the project category."),
            self: z.string().optional().describe("The URL of the project category."),
          }).optional().describe("The category the project belongs to."),
          projectTypeKey: z.enum(["software", "service_desk", "business"]).optional().describe("The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project."),
          self: z.string().optional().describe("The URL of the project details."),
          simplified: z.boolean().optional().describe("Whether or not the project is simplified."),
        }).optional().describe("The project the item has scope in."),
        type: z.enum(["PROJECT", "TEMPLATE"]).optional().describe("The type of scope."),
      }).optional().describe("Details of the next-gen projects the issue type is available in."),
      self: z.string().optional().describe("The URL of these issue type details."),
      subtask: z.boolean().optional().describe("Whether this issue type is used to create subtasks."),
    }).optional().describe("The type of the linked issue."),
    priority: z.object({
      description: z.string().optional().describe("The description of the issue priority."),
      iconUrl: z.string().optional().describe("The URL of the icon for the issue priority."),
      id: z.string().optional().describe("The ID of the issue priority."),
      isDefault: z.boolean().optional().describe("Whether this priority is the default."),
      name: z.string().optional().describe("The name of the issue priority."),
      self: z.string().optional().describe("The URL of the issue priority."),
      statusColor: z.string().optional().describe("The color used to indicate the issue priority."),
    }).optional().describe("The priority of the linked issue."),
    status: z.object({
      description: z.string().optional().describe("The description of the status."),
      iconUrl: z.string().optional().describe("The URL of the icon used to represent the status."),
      id: z.string().optional().describe("The ID of the status."),
      name: z.string().optional().describe("The name of the status."),
      self: z.string().optional().describe("The URL of the status."),
      statusCategory: z.object({
        colorName: z.string().optional().describe("The name of the color used to represent the status category."),
        id: z.number().int().optional().describe("The ID of the status category."),
        key: z.string().optional().describe("The key of the status category."),
        name: z.string().optional().describe("The name of the status category."),
        self: z.string().optional().describe("The URL of the status category."),
      }).optional().describe("The category assigned to the status."),
    }).optional().describe("The status of the linked issue."),
    summary: z.string().optional().describe("The summary description of the linked issue."),
    timetracking: z.object({
      originalEstimate: z.string().optional().describe("The original estimate of time needed for this issue in readable format."),
      originalEstimateSeconds: z.number().int().optional().describe("The original estimate of time needed for this issue in seconds."),
      remainingEstimate: z.string().optional().describe("The remaining estimate of time needed for this issue in readable format."),
      remainingEstimateSeconds: z.number().int().optional().describe("The remaining estimate of time needed for this issue in seconds."),
      timeSpent: z.string().optional().describe("Time worked on this issue in readable format."),
      timeSpentSeconds: z.number().int().optional().describe("Time worked on this issue in seconds."),
    }).optional().describe("The time tracking of the linked issue."),
  }).optional().describe("The fields associated with the issue."),
  id: z.string().optional().describe("The ID of an issue. Required if `key` isn't provided."),
  key: z.string().optional().describe("The key of an issue. Required if `id` isn't provided."),
  self: z.string().url().optional().describe("The URL of the issue."),
}).describe("The ID or key of a linked issue."),
  type: z.object({
  id: z.string().optional().describe("The ID of the issue link type and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is the type of issue link. Required on create when `name` isn't provided. Otherwise, read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is read only."),
  inward: z.string().optional().describe("The description of the issue link type inward link and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
  name: z.string().optional().describe("The name of the issue link type and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is the type of issue link. Required on create when `id` isn't provided. Otherwise, read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
  outward: z.string().optional().describe("The description of the issue link type outward link and is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it is read only.\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it is required on create and optional on update. Otherwise, read only."),
  self: z.string().url().optional().describe("The URL of the issue link type. Read only."),
}).describe("This object is used as follows:\n\n *  In the [ issueLink](#api-rest-api-3-issueLink-post) resource it defines and reports on the type of link between the issues. Find a list of issue link types with [Get issue link types](#api-rest-api-3-issueLinkType-get).\n *  In the [ issueLinkType](#api-rest-api-3-issueLinkType-post) resource it defines and reports on issue link types."),
})

export const LinkIssuesOutput = z.unknown()

export const linkIssues = pikkuSessionlessFunc({
  description: "Creates a link between two issues. Use this operation to indicate a relationship between two issues and optionally add a comment to the from (outward) issue. To use this resource the site must have [Issue Linking](https://confluence.atlassian.com/x/yoXKM) enabled.\n\nThis resource returns nothing on the creation of an issue link. To obtain the ID of the issue link, use `https://your-domain.atlassian.net/rest/api/3/issue/[linked issue key]?fields=issuelinks`.\n\nIf the link request duplicates a link, the response indicates that the issue link was created. If the request included a comment, the comment is added.\n\nThis operation can be accessed anonymously.\n\n**[Permissions](#permissions) required:**\n\n *  *Browse project* [project permission](https://confluence.atlassian.com/x/yodKLg) for all the projects containing the issues to be linked,\n *  *Link issues* [project permission](https://confluence.atlassian.com/x/yodKLg) on the project containing the from (outward) issue,\n *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.\n *  If the comment has visibility restrictions, belongs to the group or has the role visibility is restricted to.",
  input: LinkIssuesInput,
  output: LinkIssuesOutput,
  errors: [BadRequestError, UnauthorizedError, NotFoundError],
  func: async ({ jira }, data) => {
    return jira.call("POST", "/rest/api/3/issueLink", data) as any
  },
})
