// Project components — This resource represents project components. Use it to get, create, update, and delete project components. Also get components for project and get a count of issues by component.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { BadRequestError, UnauthorizedError, ForbiddenError, NotFoundError } from '@pikku/core/errors'

export const UpdateComponentInput = z.object({
  id: z.string().describe("The ID of the component."),
  assigneeType: z.enum(["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]).optional().describe("The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Can take the following values:\n\n *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.\n *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.\n *  `UNASSIGNED` an assignee is not set for issues created with this component.\n *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.\n\nDefault value: `PROJECT_DEFAULT`.  \nOptional when creating or updating a component."),
  description: z.string().optional().describe("The description for the component. Optional when creating or updating a component."),
  leadAccountId: z.string().max(128).optional().describe("The accountId of the component's lead user. The accountId uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*."),
  leadUserName: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
  name: z.string().optional().describe("The unique name for the component in the project. Required when creating a component. Optional when updating a component. The maximum length is 255 characters."),
  project: z.string().optional().describe("The key of the project the component is assigned to. Required when creating a component. Can't be updated."),
})

export const UpdateComponentOutput = z.object({
  assignee: z.object({
    accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
    accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
    active: z.boolean().optional().describe("Whether the user is active."),
    applicationRoles: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
        defaultGroupsDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups that are granted default access for this application role."),
        defined: z.boolean().optional().describe("Deprecated."),
        groupDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups associated with the application role."),
        groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
        hasUnlimitedSeats: z.boolean().optional(),
        key: z.string().optional().describe("The key of the application role."),
        name: z.string().optional().describe("The display name of the application role."),
        numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
        platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
        remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
        selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
        userCount: z.number().int().optional().describe("The number of users counting against your license."),
        userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The application roles the user is assigned to."),
    avatarUrls: z.object({
      "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
      "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
      "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
      "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
    }).optional().describe("The avatars of the user."),
    displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
    emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
    expand: z.string().optional().describe("Expand options that include additional user details in the response."),
    groups: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
        name: z.string().optional().describe("The name of group."),
        self: z.string().url().optional().describe("The URL for these group details."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The groups that the user belongs to."),
    key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
    name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    self: z.string().url().optional().describe("The URL of the user."),
    timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
  }).optional().describe("The details of the user associated with `assigneeType`, if any. See `realAssignee` for details of the user assigned to issues created with this component."),
  assigneeType: z.enum(["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]).optional().describe("The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Can take the following values:\n\n *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.\n *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.\n *  `UNASSIGNED` an assignee is not set for issues created with this component.\n *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.\n\nDefault value: `PROJECT_DEFAULT`.  \nOptional when creating or updating a component."),
  description: z.string().optional().describe("The description for the component. Optional when creating or updating a component."),
  id: z.string().optional().describe("The unique identifier for the component."),
  isAssigneeTypeValid: z.boolean().optional().describe("Whether a user is associated with `assigneeType`. For example, if the `assigneeType` is set to `COMPONENT_LEAD` but the component lead is not set, then `false` is returned."),
  lead: z.object({
    accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
    accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
    active: z.boolean().optional().describe("Whether the user is active."),
    applicationRoles: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
        defaultGroupsDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups that are granted default access for this application role."),
        defined: z.boolean().optional().describe("Deprecated."),
        groupDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups associated with the application role."),
        groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
        hasUnlimitedSeats: z.boolean().optional(),
        key: z.string().optional().describe("The key of the application role."),
        name: z.string().optional().describe("The display name of the application role."),
        numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
        platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
        remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
        selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
        userCount: z.number().int().optional().describe("The number of users counting against your license."),
        userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The application roles the user is assigned to."),
    avatarUrls: z.object({
      "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
      "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
      "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
      "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
    }).optional().describe("The avatars of the user."),
    displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
    emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
    expand: z.string().optional().describe("Expand options that include additional user details in the response."),
    groups: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
        name: z.string().optional().describe("The name of group."),
        self: z.string().url().optional().describe("The URL for these group details."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The groups that the user belongs to."),
    key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
    name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    self: z.string().url().optional().describe("The URL of the user."),
    timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
  }).optional().describe("The user details for the component's lead user."),
  leadUserName: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
  name: z.string().optional().describe("The unique name for the component in the project. Required when creating a component. Optional when updating a component. The maximum length is 255 characters."),
  project: z.string().optional().describe("The key of the project the component is assigned to. Required when creating a component. Can't be updated."),
  projectId: z.number().int().optional().describe("The ID of the project the component is assigned to."),
  realAssignee: z.object({
    accountId: z.string().max(128).optional().describe("The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests."),
    accountType: z.enum(["atlassian", "app", "customer", "unknown"]).optional().describe("The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk"),
    active: z.boolean().optional().describe("Whether the user is active."),
    applicationRoles: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        defaultGroups: z.array(z.string()).optional().describe("The groups that are granted default access for this application role. As a group's name can change, use of `defaultGroupsDetails` is recommended to identify a groups."),
        defaultGroupsDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups that are granted default access for this application role."),
        defined: z.boolean().optional().describe("Deprecated."),
        groupDetails: z.array(z.object({
          groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
          name: z.string().optional().describe("The name of group."),
          self: z.string().url().optional().describe("The URL for these group details."),
        })).optional().describe("The groups associated with the application role."),
        groups: z.array(z.string()).optional().describe("The groups associated with the application role. As a group's name can change, use of `groupDetails` is recommended to identify a groups."),
        hasUnlimitedSeats: z.boolean().optional(),
        key: z.string().optional().describe("The key of the application role."),
        name: z.string().optional().describe("The display name of the application role."),
        numberOfSeats: z.number().int().optional().describe("The maximum count of users on your license."),
        platform: z.boolean().optional().describe("Indicates if the application role belongs to Jira platform (`jira-core`)."),
        remainingSeats: z.number().int().optional().describe("The count of users remaining on your license."),
        selectedByDefault: z.boolean().optional().describe("Determines whether this application role should be selected by default on user creation."),
        userCount: z.number().int().optional().describe("The number of users counting against your license."),
        userCountDescription: z.string().optional().describe("The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The application roles the user is assigned to."),
    avatarUrls: z.object({
      "16x16": z.string().url().optional().describe("The URL of the item's 16x16 pixel avatar."),
      "24x24": z.string().url().optional().describe("The URL of the item's 24x24 pixel avatar."),
      "32x32": z.string().url().optional().describe("The URL of the item's 32x32 pixel avatar."),
      "48x48": z.string().url().optional().describe("The URL of the item's 48x48 pixel avatar."),
    }).optional().describe("The avatars of the user."),
    displayName: z.string().optional().describe("The display name of the user. Depending on the user’s privacy setting, this may return an alternative value."),
    emailAddress: z.string().optional().describe("The email address of the user. Depending on the user’s privacy setting, this may be returned as null."),
    expand: z.string().optional().describe("Expand options that include additional user details in the response."),
    groups: z.object({
      callback: z.record(z.string(), z.unknown()).optional(),
      items: z.array(z.object({
        groupId: z.string().nullable().optional().describe("The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*."),
        name: z.string().optional().describe("The name of group."),
        self: z.string().url().optional().describe("The URL for these group details."),
      })).optional(),
      "max-results": z.number().int().optional(),
      pagingCallback: z.record(z.string(), z.unknown()).optional(),
      size: z.number().int().optional(),
    }).optional().describe("The groups that the user belongs to."),
    key: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    locale: z.string().optional().describe("The locale of the user. Depending on the user’s privacy setting, this may be returned as null."),
    name: z.string().optional().describe("This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details."),
    self: z.string().url().optional().describe("The URL of the user."),
    timeZone: z.string().optional().describe("The time zone specified in the user's profile. Depending on the user’s privacy setting, this may be returned as null."),
  }).optional().describe("The user assigned to issues created with this component, when `assigneeType` does not identify a valid assignee."),
  realAssigneeType: z.enum(["PROJECT_DEFAULT", "COMPONENT_LEAD", "PROJECT_LEAD", "UNASSIGNED"]).optional().describe("The type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:\n\n *  `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in.\n *  `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in.\n *  `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues.\n *  `PROJECT_DEFAULT` when none of the preceding cases are true."),
  self: z.string().url().optional().describe("The URL of the component."),
}).describe("Details about a project component.")

export const updateComponent = pikkuSessionlessFunc({
  description: "Updates a component. Any fields included in the request are overwritten. If `leadAccountId` is an empty string (\"\") the component lead is removed.\n\nThis operation can be accessed anonymously.\n\n**[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the component or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).",
  input: UpdateComponentInput,
  output: UpdateComponentOutput,
  errors: [BadRequestError, UnauthorizedError, ForbiddenError, NotFoundError],
  func: async ({ jira }, data) => {
    return jira.call("PUT", "/rest/api/3/component/{id}", data) as any
  },
})
