import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const YoutubeVideosListInput = z.object({
  "$.xgafv": z.enum(["1", "2"]).optional().describe("V1 error format."),
  access_token: z.string().optional().describe("OAuth access token."),
  alt: z.enum(["json", "media", "proto"]).optional().describe("Data format for response."),
  callback: z.string().optional().describe("JSONP"),
  fields: z.string().optional().describe("Selector specifying which fields to include in a partial response."),
  key: z.string().optional().describe("API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token."),
  oauth_token: z.string().optional().describe("OAuth 2.0 token for the current user."),
  prettyPrint: z.boolean().optional().describe("Returns response with indentations and line breaks."),
  quotaUser: z.string().optional().describe("Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters."),
  upload_protocol: z.string().optional().describe("Upload protocol for media (e.g. \"raw\", \"multipart\")."),
  uploadType: z.string().optional().describe("Legacy upload protocol for media (e.g. \"media\", \"multipart\")."),
  part: z.array(z.string()).describe("The *part* parameter specifies a comma-separated list of one or more video resource properties that the API response will include. If the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a video resource, the snippet property contains the channelId, title, description, tags, and categoryId properties. As such, if you set *part=snippet*, the API response will contain all of those properties."),
  chart: z.enum(["chartUnspecified", "mostPopular"]).optional().describe("Return the videos that are in the specified chart."),
  hl: z.string().optional().describe("Stands for \"host language\". Specifies the localization language of the metadata to be filled into snippet.localized. The field is filled with the default metadata if there is no localization in the specified language. The parameter value must be a language code included in the list returned by the i18nLanguages.list method (e.g. en_US, es_MX)."),
  id: z.array(z.string()).optional().describe("Return videos with the given ids."),
  locale: z.string().optional(),
  maxHeight: z.number().int().min(72).max(8192).optional(),
  maxResults: z.number().int().min(1).max(50).optional().describe("The *maxResults* parameter specifies the maximum number of items that should be returned in the result set. *Note:* This parameter is supported for use in conjunction with the myRating and chart parameters, but it is not supported for use in conjunction with the id parameter."),
  maxWidth: z.number().int().min(72).max(8192).optional().describe("Return the player with maximum height specified in"),
  myRating: z.enum(["none", "like", "dislike"]).optional().describe("Return videos liked/disliked by the authenticated user. Does not support RateType.RATED_TYPE_NONE."),
  onBehalfOfContentOwner: z.string().optional().describe("*Note:* This parameter is intended exclusively for YouTube content partners. The *onBehalfOfContentOwner* parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The CMS account that the user authenticates with must be linked to the specified YouTube content owner."),
  pageToken: z.string().optional().describe("The *pageToken* parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved. *Note:* This parameter is supported for use in conjunction with the myRating and chart parameters, but it is not supported for use in conjunction with the id parameter."),
  regionCode: z.string().optional().describe("Use a chart that is specific to the specified region"),
  videoCategoryId: z.string().optional().describe("Use chart that is specific to the specified video category"),
})

export const YoutubeVideosListOutput = z.object({
  etag: z.string().optional().describe("Etag of this resource."),
  eventId: z.string().optional().describe("Serialized EventId of the request which produced this response."),
  items: z.array(z.object({
    ageGating: z.object({
      alcoholContent: z.boolean().optional().describe("Indicates whether or not the video has alcoholic beverage content. Only users of legal purchasing age in a particular country, as identified by ICAP, can view the content."),
      restricted: z.boolean().optional().describe("Age-restricted trailers. For redband trailers and adult-rated video-games. Only users aged 18+ can view the content. The the field is true the content is restricted to viewers aged 18+. Otherwise The field won't be present."),
      videoGameRating: z.enum(["anyone", "m15Plus", "m16Plus", "m17Plus"]).optional().describe("Video game rating, if any."),
    }).optional().describe("Age restriction details related to a video. This data can only be retrieved by the video owner."),
    contentDetails: z.object({
      caption: z.enum(["true", "false"]).optional().describe("The value of captions indicates whether the video has captions or not."),
      contentRating: z.object({
        acbRating: z.enum(["acbUnspecified", "acbE", "acbP", "acbC", "acbG", "acbPg", "acbM", "acbMa15plus", "acbR18plus", "acbUnrated"]).optional().describe("The video's Australian Classification Board (ACB) or Australian Communications and Media Authority (ACMA) rating. ACMA ratings are used to classify children's television programming."),
        agcomRating: z.enum(["agcomUnspecified", "agcomT", "agcomVm14", "agcomVm18", "agcomUnrated"]).optional().describe("The video's rating from Italy's Autorità per le Garanzie nelle Comunicazioni (AGCOM)."),
        anatelRating: z.enum(["anatelUnspecified", "anatelF", "anatelI", "anatelI7", "anatelI10", "anatelI12", "anatelR", "anatelA", "anatelUnrated"]).optional().describe("The video's Anatel (Asociación Nacional de Televisión) rating for Chilean television."),
        bbfcRating: z.enum(["bbfcUnspecified", "bbfcU", "bbfcPg", "bbfc12a", "bbfc12", "bbfc15", "bbfc18", "bbfcR18", "bbfcUnrated"]).optional().describe("The video's British Board of Film Classification (BBFC) rating."),
        bfvcRating: z.enum(["bfvcUnspecified", "bfvcG", "bfvcE", "bfvc13", "bfvc15", "bfvc18", "bfvc20", "bfvcB", "bfvcUnrated"]).optional().describe("The video's rating from Thailand's Board of Film and Video Censors."),
        bmukkRating: z.enum(["bmukkUnspecified", "bmukkAa", "bmukk6", "bmukk8", "bmukk10", "bmukk12", "bmukk14", "bmukk16", "bmukkUnrated"]).optional().describe("The video's rating from the Austrian Board of Media Classification (Bundesministerium für Unterricht, Kunst und Kultur)."),
        catvRating: z.enum(["catvUnspecified", "catvC", "catvC8", "catvG", "catvPg", "catv14plus", "catv18plus", "catvUnrated", "catvE"]).optional().describe("Rating system for Canadian TV - Canadian TV Classification System The video's rating from the Canadian Radio-Television and Telecommunications Commission (CRTC) for Canadian English-language broadcasts. For more information, see the Canadian Broadcast Standards Council website."),
        catvfrRating: z.enum(["catvfrUnspecified", "catvfrG", "catvfr8plus", "catvfr13plus", "catvfr16plus", "catvfr18plus", "catvfrUnrated", "catvfrE"]).optional().describe("The video's rating from the Canadian Radio-Television and Telecommunications Commission (CRTC) for Canadian French-language broadcasts. For more information, see the Canadian Broadcast Standards Council website."),
        cbfcRating: z.enum(["cbfcUnspecified", "cbfcU", "cbfcUA", "cbfcUA7plus", "cbfcUA13plus", "cbfcUA16plus", "cbfcA", "cbfcS", "cbfcUnrated"]).optional().describe("The video's Central Board of Film Certification (CBFC - India) rating."),
        cccRating: z.enum(["cccUnspecified", "cccTe", "ccc6", "ccc14", "ccc18", "ccc18v", "ccc18s", "cccUnrated"]).optional().describe("The video's Consejo de Calificación Cinematográfica (Chile) rating."),
        cceRating: z.enum(["cceUnspecified", "cceM4", "cceM6", "cceM12", "cceM16", "cceM18", "cceUnrated", "cceM14"]).optional().describe("The video's rating from Portugal's Comissão de Classificação de Espect´culos."),
        chfilmRating: z.enum(["chfilmUnspecified", "chfilm0", "chfilm6", "chfilm12", "chfilm16", "chfilm18", "chfilmUnrated"]).optional().describe("The video's rating in Switzerland."),
        chvrsRating: z.enum(["chvrsUnspecified", "chvrsG", "chvrsPg", "chvrs14a", "chvrs18a", "chvrsR", "chvrsE", "chvrsUnrated"]).optional().describe("The video's Canadian Home Video Rating System (CHVRS) rating."),
        cicfRating: z.enum(["cicfUnspecified", "cicfE", "cicfKtEa", "cicfKntEna", "cicfUnrated"]).optional().describe("The video's rating from the Commission de Contrôle des Films (Belgium)."),
        cnaRating: z.enum(["cnaUnspecified", "cnaAp", "cna12", "cna15", "cna18", "cna18plus", "cnaUnrated"]).optional().describe("The video's rating from Romania's CONSILIUL NATIONAL AL AUDIOVIZUALULUI (CNA)."),
        cncRating: z.enum(["cncUnspecified", "cncT", "cnc10", "cnc12", "cnc16", "cnc18", "cncE", "cncInterdiction", "cncUnrated"]).optional().describe("Rating system in France - Commission de classification cinematographique"),
        csaRating: z.enum(["csaUnspecified", "csaT", "csa10", "csa12", "csa16", "csa18", "csaInterdiction", "csaUnrated"]).optional().describe("The video's rating from France's Conseil supérieur de l’audiovisuel, which rates broadcast content."),
        cscfRating: z.enum(["cscfUnspecified", "cscfAl", "cscfA", "cscf6", "cscf9", "cscf12", "cscf16", "cscf18", "cscfUnrated"]).optional().describe("The video's rating from Luxembourg's Commission de surveillance de la classification des films (CSCF)."),
        czfilmRating: z.enum(["czfilmUnspecified", "czfilmU", "czfilm12", "czfilm14", "czfilm18", "czfilmUnrated"]).optional().describe("The video's rating in the Czech Republic."),
        djctqRating: z.enum(["djctqUnspecified", "djctqL", "djctq10", "djctq12", "djctq14", "djctq16", "djctq18", "djctqEr", "djctqL10", "djctqL12", "djctqL14", "djctqL16", "djctqL18", "djctq1012", "djctq1014", "djctq1016", "djctq1018", "djctq1214", "djctq1216", "djctq1218", "djctq1416", "djctq1418", "djctq1618", "djctqUnrated"]).optional().describe("The video's Departamento de Justiça, Classificação, Qualificação e Títulos (DJCQT - Brazil) rating."),
        djctqRatingReasons: z.array(z.enum(["djctqRatingReasonUnspecified", "djctqViolence", "djctqExtremeViolence", "djctqSexualContent", "djctqNudity", "djctqSex", "djctqExplicitSex", "djctqDrugs", "djctqLegalDrugs", "djctqIllegalDrugs", "djctqInappropriateLanguage", "djctqCriminalActs", "djctqImpactingContent"])).optional().describe("Reasons that explain why the video received its DJCQT (Brazil) rating."),
        ecbmctRating: z.enum(["ecbmctUnspecified", "ecbmctG", "ecbmct7a", "ecbmct7plus", "ecbmct13a", "ecbmct13plus", "ecbmct15a", "ecbmct15plus", "ecbmct18plus", "ecbmctUnrated"]).optional().describe("Rating system in Turkey - Evaluation and Classification Board of the Ministry of Culture and Tourism"),
        eefilmRating: z.enum(["eefilmUnspecified", "eefilmPere", "eefilmL", "eefilmMs6", "eefilmK6", "eefilmMs12", "eefilmK12", "eefilmK14", "eefilmK16", "eefilmUnrated"]).optional().describe("The video's rating in Estonia."),
        egfilmRating: z.enum(["egfilmUnspecified", "egfilmGn", "egfilm18", "egfilmBn", "egfilmUnrated"]).optional().describe("The video's rating in Egypt."),
        eirinRating: z.enum(["eirinUnspecified", "eirinG", "eirinPg12", "eirinR15plus", "eirinR18plus", "eirinUnrated"]).optional().describe("The video's Eirin (映倫) rating. Eirin is the Japanese rating system."),
        fcbmRating: z.enum(["fcbmUnspecified", "fcbmU", "fcbmPg13", "fcbmP13", "fcbm18", "fcbm18sx", "fcbm18pa", "fcbm18sg", "fcbm18pl", "fcbmUnrated"]).optional().describe("The video's rating from Malaysia's Film Censorship Board."),
        fcoRating: z.enum(["fcoUnspecified", "fcoI", "fcoIia", "fcoIib", "fcoIi", "fcoIii", "fcoUnrated"]).optional().describe("The video's rating from Hong Kong's Office for Film, Newspaper and Article Administration."),
        fmocRating: z.enum(["fmocUnspecified", "fmocU", "fmoc10", "fmoc12", "fmoc16", "fmoc18", "fmocE", "fmocUnrated"]).optional().describe("This property has been deprecated. Use the contentDetails.contentRating.cncRating instead."),
        fpbRating: z.enum(["fpbUnspecified", "fpbA", "fpbPg", "fpb79Pg", "fpb1012Pg", "fpb13", "fpb16", "fpb18", "fpbX18", "fpbXx", "fpbUnrated", "fpb10"]).optional().describe("The video's rating from South Africa's Film and Publication Board."),
        fpbRatingReasons: z.array(z.enum(["fpbRatingReasonUnspecified", "fpbBlasphemy", "fpbLanguage", "fpbNudity", "fpbPrejudice", "fpbSex", "fpbViolence", "fpbDrugs", "fpbSexualViolence", "fpbHorror", "fpbCriminalTechniques", "fpbImitativeActsTechniques"])).optional().describe("Reasons that explain why the video received its FPB (South Africa) rating."),
        fskRating: z.enum(["fskUnspecified", "fsk0", "fsk6", "fsk12", "fsk16", "fsk18", "fskUnrated"]).optional().describe("The video's Freiwillige Selbstkontrolle der Filmwirtschaft (FSK - Germany) rating."),
        grfilmRating: z.enum(["grfilmUnspecified", "grfilmK", "grfilmE", "grfilmK12", "grfilmK13", "grfilmK15", "grfilmK17", "grfilmK18", "grfilmUnrated"]).optional().describe("The video's rating in Greece."),
        icaaRating: z.enum(["icaaUnspecified", "icaaApta", "icaa7", "icaa12", "icaa13", "icaa16", "icaa18", "icaaX", "icaaUnrated"]).optional().describe("The video's Instituto de la Cinematografía y de las Artes Audiovisuales (ICAA - Spain) rating."),
        ifcoRating: z.enum(["ifcoUnspecified", "ifcoG", "ifcoPg", "ifco12", "ifco12a", "ifco15", "ifco15a", "ifco16", "ifco18", "ifcoUnrated"]).optional().describe("The video's Irish Film Classification Office (IFCO - Ireland) rating. See the IFCO website for more information."),
        ilfilmRating: z.enum(["ilfilmUnspecified", "ilfilmAa", "ilfilm12", "ilfilm14", "ilfilm16", "ilfilm18", "ilfilmUnrated"]).optional().describe("The video's rating in Israel."),
        incaaRating: z.enum(["incaaUnspecified", "incaaAtp", "incaaSam13", "incaaSam16", "incaaSam18", "incaaC", "incaaUnrated"]).optional().describe("The video's INCAA (Instituto Nacional de Cine y Artes Audiovisuales - Argentina) rating."),
        kfcbRating: z.enum(["kfcbUnspecified", "kfcbG", "kfcbPg", "kfcb16plus", "kfcbR", "kfcbUnrated"]).optional().describe("The video's rating from the Kenya Film Classification Board."),
        kijkwijzerRating: z.enum(["kijkwijzerUnspecified", "kijkwijzerAl", "kijkwijzer6", "kijkwijzer9", "kijkwijzer12", "kijkwijzer16", "kijkwijzer18", "kijkwijzerUnrated"]).optional().describe("The video's NICAM/Kijkwijzer rating from the Nederlands Instituut voor de Classificatie van Audiovisuele Media (Netherlands)."),
        kmrbRating: z.enum(["kmrbUnspecified", "kmrbAll", "kmrb12plus", "kmrb15plus", "kmrbTeenr", "kmrbR", "kmrbUnrated"]).optional().describe("The video's Korea Media Rating Board (영상물등급위원회) rating. The KMRB rates videos in South Korea."),
        lsfRating: z.enum(["lsfUnspecified", "lsfSu", "lsfA", "lsfBo", "lsf13", "lsfR", "lsf17", "lsfD", "lsf21", "lsfUnrated"]).optional().describe("The video's rating from Indonesia's Lembaga Sensor Film."),
        mccaaRating: z.enum(["mccaaUnspecified", "mccaaU", "mccaaPg", "mccaa12a", "mccaa12", "mccaa14", "mccaa15", "mccaa16", "mccaa18", "mccaaUnrated"]).optional().describe("The video's rating from Malta's Film Age-Classification Board."),
        mccypRating: z.enum(["mccypUnspecified", "mccypA", "mccyp7", "mccyp11", "mccyp15", "mccypUnrated"]).optional().describe("The video's rating from the Danish Film Institute's (Det Danske Filminstitut) Media Council for Children and Young People."),
        mcstRating: z.enum(["mcstUnspecified", "mcstP", "mcst0", "mcstC13", "mcstC16", "mcst16plus", "mcstC18", "mcstGPg", "mcstUnrated"]).optional().describe("The video's rating system for Vietnam - MCST"),
        mdaRating: z.enum(["mdaUnspecified", "mdaG", "mdaPg", "mdaPg13", "mdaNc16", "mdaM18", "mdaR21", "mdaUnrated"]).optional().describe("The video's rating from Singapore's Media Development Authority (MDA) and, specifically, it's Board of Film Censors (BFC)."),
        medietilsynetRating: z.enum(["medietilsynetUnspecified", "medietilsynetA", "medietilsynet6", "medietilsynet7", "medietilsynet9", "medietilsynet11", "medietilsynet12", "medietilsynet15", "medietilsynet18", "medietilsynetUnrated"]).optional().describe("The video's rating from Medietilsynet, the Norwegian Media Authority."),
        mekuRating: z.enum(["mekuUnspecified", "mekuS", "meku7", "meku12", "meku16", "meku18", "mekuUnrated"]).optional().describe("The video's rating from Finland's Kansallinen Audiovisuaalinen Instituutti (National Audiovisual Institute)."),
        menaMpaaRating: z.enum(["menaMpaaUnspecified", "menaMpaaG", "menaMpaaPg", "menaMpaaPg13", "menaMpaaR", "menaMpaaUnrated"]).optional().describe("The rating system for MENA countries, a clone of MPAA. It is needed to prevent titles go live w/o additional QC check, since some of them can be inappropriate for the countries at all. See b/33408548 for more details."),
        mibacRating: z.enum(["mibacUnspecified", "mibacT", "mibacVap", "mibacVm6", "mibacVm12", "mibacVm14", "mibacVm16", "mibacVm18", "mibacUnrated"]).optional().describe("The video's rating from the Ministero dei Beni e delle Attività Culturali e del Turismo (Italy)."),
        mocRating: z.enum(["mocUnspecified", "mocE", "mocT", "moc7", "moc12", "moc15", "moc18", "mocX", "mocBanned", "mocUnrated"]).optional().describe("The video's Ministerio de Cultura (Colombia) rating."),
        moctwRating: z.enum(["moctwUnspecified", "moctwG", "moctwP", "moctwPg", "moctwR", "moctwUnrated", "moctwR12", "moctwR15"]).optional().describe("The video's rating from Taiwan's Ministry of Culture (文化部)."),
        mpaaRating: z.enum(["mpaaUnspecified", "mpaaG", "mpaaPg", "mpaaPg13", "mpaaR", "mpaaNc17", "mpaaX", "mpaaUnrated"]).optional().describe("The video's Motion Picture Association of America (MPAA) rating."),
        mpaatRating: z.enum(["mpaatUnspecified", "mpaatGb", "mpaatRb"]).optional().describe("The rating system for trailer, DVD, and Ad in the US. See http://movielabs.com/md/ratings/v2.3/html/US_MPAAT_Ratings.html."),
        mtrcbRating: z.enum(["mtrcbUnspecified", "mtrcbG", "mtrcbPg", "mtrcbR13", "mtrcbR16", "mtrcbR18", "mtrcbX", "mtrcbUnrated"]).optional().describe("The video's rating from the Movie and Television Review and Classification Board (Philippines)."),
        nbcRating: z.enum(["nbcUnspecified", "nbcG", "nbcPg", "nbc12plus", "nbc15plus", "nbc18plus", "nbc18plusr", "nbcPu", "nbcUnrated"]).optional().describe("The video's rating from the Maldives National Bureau of Classification."),
        nbcplRating: z.enum(["nbcplUnspecified", "nbcplI", "nbcplIi", "nbcplIii", "nbcplIv", "nbcpl18plus", "nbcplUnrated"]).optional().describe("The video's rating in Poland."),
        nfrcRating: z.enum(["nfrcUnspecified", "nfrcA", "nfrcB", "nfrcC", "nfrcD", "nfrcX", "nfrcUnrated"]).optional().describe("The video's rating from the Bulgarian National Film Center."),
        nfvcbRating: z.enum(["nfvcbUnspecified", "nfvcbG", "nfvcbPg", "nfvcb12", "nfvcb12a", "nfvcb15", "nfvcb18", "nfvcbRe", "nfvcbUnrated"]).optional().describe("The video's rating from Nigeria's National Film and Video Censors Board."),
        nkclvRating: z.enum(["nkclvUnspecified", "nkclvU", "nkclv7plus", "nkclv12plus", "nkclv16plus", "nkclv18plus", "nkclvUnrated"]).optional().describe("The video's rating from the Nacionãlais Kino centrs (National Film Centre of Latvia)."),
        nmcRating: z.enum(["nmcUnspecified", "nmcG", "nmcPg", "nmcPg13", "nmcPg15", "nmc15plus", "nmc18plus", "nmc18tc", "nmcUnrated"]).optional().describe("The National Media Council ratings system for United Arab Emirates."),
        oflcRating: z.enum(["oflcUnspecified", "oflcG", "oflcPg", "oflcM", "oflcR13", "oflcR15", "oflcR16", "oflcR18", "oflcUnrated", "oflcRp13", "oflcRp16", "oflcRp18"]).optional().describe("The video's Office of Film and Literature Classification (OFLC - New Zealand) rating."),
        pefilmRating: z.enum(["pefilmUnspecified", "pefilmPt", "pefilmPg", "pefilm14", "pefilm18", "pefilmUnrated"]).optional().describe("The video's rating in Peru."),
        rcnofRating: z.enum(["rcnofUnspecified", "rcnofI", "rcnofIi", "rcnofIii", "rcnofIv", "rcnofV", "rcnofVi", "rcnofUnrated"]).optional().describe("The video's rating from the Hungarian Nemzeti Filmiroda, the Rating Committee of the National Office of Film."),
        resorteviolenciaRating: z.enum(["resorteviolenciaUnspecified", "resorteviolenciaA", "resorteviolenciaB", "resorteviolenciaC", "resorteviolenciaD", "resorteviolenciaE", "resorteviolenciaUnrated"]).optional().describe("The video's rating in Venezuela."),
        rtcRating: z.enum(["rtcUnspecified", "rtcAa", "rtcA", "rtcB", "rtcB15", "rtcC", "rtcD", "rtcUnrated"]).optional().describe("The video's General Directorate of Radio, Television and Cinematography (Mexico) rating."),
        rteRating: z.enum(["rteUnspecified", "rteGa", "rteCh", "rtePs", "rteMa", "rteUnrated"]).optional().describe("The video's rating from Ireland's Raidió Teilifís Éireann."),
        russiaRating: z.enum(["russiaUnspecified", "russia0", "russia6", "russia12", "russia16", "russia18", "russiaUnrated"]).optional().describe("The video's National Film Registry of the Russian Federation (MKRF - Russia) rating."),
        skfilmRating: z.enum(["skfilmUnspecified", "skfilmG", "skfilmP2", "skfilmP5", "skfilmP8", "skfilmUnrated"]).optional().describe("The video's rating in Slovakia."),
        smaisRating: z.enum(["smaisUnspecified", "smaisL", "smais7", "smais12", "smais14", "smais16", "smais18", "smaisUnrated"]).optional().describe("The video's rating in Iceland."),
        smsaRating: z.enum(["smsaUnspecified", "smsaA", "smsa7", "smsa11", "smsa15", "smsaUnrated"]).optional().describe("The video's rating from Statens medieråd (Sweden's National Media Council)."),
        tvpgRating: z.enum(["tvpgUnspecified", "tvpgY", "tvpgY7", "tvpgY7Fv", "tvpgG", "tvpgPg", "pg14", "tvpgMa", "tvpgUnrated"]).optional().describe("The video's TV Parental Guidelines (TVPG) rating."),
        ytRating: z.enum(["ytUnspecified", "ytAgeRestricted"]).optional().describe("A rating that YouTube uses to identify age-restricted content."),
      }).optional().describe("Specifies the ratings that the video received under various rating schemes."),
      countryRestriction: z.object({
        allowed: z.boolean().optional().describe("The value of allowed indicates whether the access to the policy is allowed or denied by default."),
        exception: z.array(z.string()).optional().describe("A list of region codes that identify countries where the default policy do not apply."),
      }).optional().describe("The countryRestriction object contains information about the countries where a video is (or is not) viewable."),
      definition: z.enum(["sd", "hd"]).optional().describe("The value of definition indicates whether the video is available in high definition or only in standard definition."),
      dimension: z.string().optional().describe("The value of dimension indicates whether the video is available in 3D or in 2D."),
      duration: z.string().optional().describe("The length of the video. The tag value is an ISO 8601 duration in the format PT#M#S, in which the letters PT indicate that the value specifies a period of time, and the letters M and S refer to length in minutes and seconds, respectively. The # characters preceding the M and S letters are both integers that specify the number of minutes (or seconds) of the video. For example, a value of PT15M51S indicates that the video is 15 minutes and 51 seconds long."),
      hasCustomThumbnail: z.boolean().optional().describe("Indicates whether the video uploader has provided a custom thumbnail image for the video. This property is only visible to the video uploader."),
      licensedContent: z.boolean().optional().describe("The value of is_license_content indicates whether the video is licensed content."),
      projection: z.enum(["rectangular", "360"]).optional().describe("Specifies the projection format of the video."),
      regionRestriction: z.object({
        allowed: z.array(z.string()).optional().describe("A list of region codes that identify countries where the video is viewable. If this property is present and a country is not listed in its value, then the video is blocked from appearing in that country. If this property is present and contains an empty list, the video is blocked in all countries."),
        blocked: z.array(z.string()).optional().describe("A list of region codes that identify countries where the video is blocked. If this property is present and a country is not listed in its value, then the video is viewable in that country. If this property is present and contains an empty list, the video is viewable in all countries."),
      }).optional().describe("The regionRestriction object contains information about the countries where a video is (or is not) viewable. The object will contain either the contentDetails.regionRestriction.allowed property or the contentDetails.regionRestriction.blocked property."),
    }).optional().describe("The contentDetails object contains information about the video content, including the length of the video and its aspect ratio."),
    etag: z.string().optional().describe("Etag of this resource."),
    fileDetails: z.object({
      audioStreams: z.array(z.object({
        bitrateBps: z.string().optional().describe("The audio stream's bitrate, in bits per second."),
        channelCount: z.number().int().optional().describe("The number of audio channels that the stream contains."),
        codec: z.string().optional().describe("The audio codec that the stream uses."),
        vendor: z.string().optional().describe("A value that uniquely identifies a video vendor. Typically, the value is a four-letter vendor code."),
      })).optional().describe("A list of audio streams contained in the uploaded video file. Each item in the list contains detailed metadata about an audio stream."),
      bitrateBps: z.string().optional().describe("The uploaded video file's combined (video and audio) bitrate in bits per second."),
      container: z.string().optional().describe("The uploaded video file's container format."),
      creationTime: z.string().optional().describe("The date and time when the uploaded video file was created. The value is specified in ISO 8601 format. Currently, the following ISO 8601 formats are supported: - Date only: YYYY-MM-DD - Naive time: YYYY-MM-DDTHH:MM:SS - Time with timezone: YYYY-MM-DDTHH:MM:SS+HH:MM "),
      durationMs: z.string().optional().describe("The length of the uploaded video in milliseconds."),
      fileName: z.string().optional().describe("The uploaded file's name. This field is present whether a video file or another type of file was uploaded."),
      fileSize: z.string().optional().describe("The uploaded file's size in bytes. This field is present whether a video file or another type of file was uploaded."),
      fileType: z.enum(["video", "audio", "image", "archive", "document", "project", "other"]).optional().describe("The uploaded file's type as detected by YouTube's video processing engine. Currently, YouTube only processes video files, but this field is present whether a video file or another type of file was uploaded."),
      videoStreams: z.array(z.object({
        aspectRatio: z.number().optional().describe("The video content's display aspect ratio, which specifies the aspect ratio in which the video should be displayed."),
        bitrateBps: z.string().optional().describe("The video stream's bitrate, in bits per second."),
        codec: z.string().optional().describe("The video codec that the stream uses."),
        frameRateFps: z.number().optional().describe("The video stream's frame rate, in frames per second."),
        heightPixels: z.number().int().optional().describe("The encoded video content's height in pixels."),
        rotation: z.enum(["none", "clockwise", "upsideDown", "counterClockwise", "other"]).optional().describe("The amount that YouTube needs to rotate the original source content to properly display the video."),
        vendor: z.string().optional().describe("A value that uniquely identifies a video vendor. Typically, the value is a four-letter vendor code."),
        widthPixels: z.number().int().optional().describe("The encoded video content's width in pixels. You can calculate the video's encoding aspect ratio as width_pixels / height_pixels."),
      })).optional().describe("A list of video streams contained in the uploaded video file. Each item in the list contains detailed metadata about a video stream."),
    }).optional().describe("The fileDetails object encapsulates information about the video file that was uploaded to YouTube, including the file's resolution, duration, audio and video codecs, stream bitrates, and more. This data can only be retrieved by the video owner."),
    id: z.string().optional().describe("The ID that YouTube uses to uniquely identify the video."),
    kind: z.string().optional().default("youtube#video").describe("Identifies what kind of resource this is. Value: the fixed string \"youtube#video\"."),
    liveStreamingDetails: z.object({
      activeLiveChatId: z.string().optional().describe("The ID of the currently active live chat attached to this video. This field is filled only if the video is a currently live broadcast that has live chat. Once the broadcast transitions to complete this field will be removed and the live chat closed down. For persistent broadcasts that live chat id will no longer be tied to this video but rather to the new video being displayed at the persistent page."),
      actualEndTime: z.string().datetime().optional().describe("The time that the broadcast actually ended. This value will not be available until the broadcast is over."),
      actualStartTime: z.string().datetime().optional().describe("The time that the broadcast actually started. This value will not be available until the broadcast begins."),
      concurrentViewers: z.string().optional().describe("The number of viewers currently watching the broadcast. The property and its value will be present if the broadcast has current viewers and the broadcast owner has not hidden the viewcount for the video. Note that YouTube stops tracking the number of concurrent viewers for a broadcast when the broadcast ends. So, this property would not identify the number of viewers watching an archived video of a live broadcast that already ended."),
      scheduledEndTime: z.string().datetime().optional().describe("The time that the broadcast is scheduled to end. If the value is empty or the property is not present, then the broadcast is scheduled to contiue indefinitely."),
      scheduledStartTime: z.string().datetime().optional().describe("The time that the broadcast is scheduled to begin."),
    }).optional().describe("The liveStreamingDetails object contains metadata about a live video broadcast. The object will only be present in a video resource if the video is an upcoming, live, or completed live broadcast."),
    localizations: z.record(z.string(), z.object({
      description: z.string().optional().describe("Localized version of the video's description."),
      title: z.string().optional().describe("Localized version of the video's title."),
    }).describe("Localized versions of certain video properties (e.g. title).")).optional().describe("The localizations object contains localized versions of the basic details about the video, such as its title and description."),
    monetizationDetails: z.object({
      access: z.object({
        allowed: z.boolean().optional().describe("The value of allowed indicates whether the access to the policy is allowed or denied by default."),
        exception: z.array(z.string()).optional().describe("A list of region codes that identify countries where the default policy do not apply."),
      }).optional().describe("The value of access indicates whether the video can be monetized or not."),
    }).optional().describe("The monetizationDetails object encapsulates information about the monetization status of the video."),
    player: z.object({
      embedHeight: z.string().optional(),
      embedHtml: z.string().optional().describe("An <iframe> tag that embeds a player that will play the video."),
      embedWidth: z.string().optional().describe("The embed width"),
    }).optional().describe("The player object contains information that you would use to play the video in an embedded player."),
    processingDetails: z.object({
      editorSuggestionsAvailability: z.string().optional().describe("This value indicates whether video editing suggestions, which might improve video quality or the playback experience, are available for the video. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request."),
      fileDetailsAvailability: z.string().optional().describe("This value indicates whether file details are available for the uploaded video. You can retrieve a video's file details by requesting the fileDetails part in your videos.list() request."),
      processingFailureReason: z.enum(["uploadFailed", "transcodeFailed", "streamingFailed", "other"]).optional().describe("The reason that YouTube failed to process the video. This property will only have a value if the processingStatus property's value is failed."),
      processingIssuesAvailability: z.string().optional().describe("This value indicates whether the video processing engine has generated suggestions that might improve YouTube's ability to process the the video, warnings that explain video processing problems, or errors that cause video processing problems. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request."),
      processingProgress: z.object({
        partsProcessed: z.string().optional().describe("The number of parts of the video that YouTube has already processed. You can estimate the percentage of the video that YouTube has already processed by calculating: 100 * parts_processed / parts_total Note that since the estimated number of parts could increase without a corresponding increase in the number of parts that have already been processed, it is possible that the calculated progress could periodically decrease while YouTube processes a video."),
        partsTotal: z.string().optional().describe("An estimate of the total number of parts that need to be processed for the video. The number may be updated with more precise estimates while YouTube processes the video."),
        timeLeftMs: z.string().optional().describe("An estimate of the amount of time, in millseconds, that YouTube needs to finish processing the video."),
      }).optional().describe("The processingProgress object contains information about the progress YouTube has made in processing the video. The values are really only relevant if the video's processing status is processing."),
      processingStatus: z.enum(["processing", "succeeded", "failed", "terminated"]).optional().describe("The video's processing status. This value indicates whether YouTube was able to process the video or if the video is still being processed."),
      tagSuggestionsAvailability: z.string().optional().describe("This value indicates whether keyword (tag) suggestions are available for the video. Tags can be added to a video's metadata to make it easier for other users to find the video. You can retrieve these suggestions by requesting the suggestions part in your videos.list() request."),
      thumbnailsAvailability: z.string().optional().describe("This value indicates whether thumbnail images have been generated for the video."),
    }).optional().describe("The processingDetails object encapsulates information about YouTube's progress in processing the uploaded video file. The properties in the object identify the current processing status and an estimate of the time remaining until YouTube finishes processing the video. This part also indicates whether different types of data or content, such as file details or thumbnail images, are available for the video. The processingProgress object is designed to be polled so that the video uploaded can track the progress that YouTube has made in processing the uploaded video file. This data can only be retrieved by the video owner."),
    projectDetails: z.record(z.string(), z.unknown()).optional().describe("The projectDetails object contains information about the project specific video metadata. b/157517979: This part was never populated after it was added. However, it sees non-zero traffic because there is generated client code in the wild that refers to it [1]. We keep this field and do NOT remove it because otherwise V3 would return an error when this part gets requested [2]. [1] https://developers.google.com/resources/api-libraries/documentation/youtube/v3/csharp/latest/classGoogle_1_1Apis_1_1YouTube_1_1v3_1_1Data_1_1VideoProjectDetails.html [2] http://google3/video/youtube/src/python/servers/data_api/common.py?l=1565-1569&rcl=344141677"),
    recordingDetails: z.object({
      location: z.object({
        altitude: z.number().optional().describe("Altitude above the reference ellipsoid, in meters."),
        latitude: z.number().optional().describe("Latitude in degrees."),
        longitude: z.number().optional().describe("Longitude in degrees."),
      }).optional().describe("The geolocation information associated with the video."),
      locationDescription: z.string().optional().describe("The text description of the location where the video was recorded."),
      recordingDate: z.string().datetime().optional().describe("The date and time when the video was recorded."),
    }).optional().describe("The recordingDetails object encapsulates information about the location, date and address where the video was recorded."),
    snippet: z.object({
      categoryId: z.string().optional().describe("The YouTube video category associated with the video."),
      channelId: z.string().optional().describe("The ID that YouTube uses to uniquely identify the channel that the video was uploaded to."),
      channelTitle: z.string().optional().describe("Channel title for the channel that the video belongs to."),
      defaultAudioLanguage: z.string().optional().describe("The default_audio_language property specifies the language spoken in the video's default audio track."),
      defaultLanguage: z.string().optional().describe("The language of the videos's default snippet."),
      description: z.string().optional().describe("The video's description. @mutable youtube.videos.insert youtube.videos.update"),
      liveBroadcastContent: z.enum(["none", "upcoming", "live", "completed"]).optional().describe("Indicates if the video is an upcoming/active live broadcast. Or it's \"none\" if the video is not an upcoming/active live broadcast."),
      localized: z.object({
        description: z.string().optional().describe("Localized version of the video's description."),
        title: z.string().optional().describe("Localized version of the video's title."),
      }).optional().describe("Localized snippet selected with the hl parameter. If no such localization exists, this field is populated with the default snippet. (Read-only)"),
      publishedAt: z.string().datetime().optional().describe("The date and time when the video was uploaded."),
      tags: z.array(z.string()).optional().describe("A list of keyword tags associated with the video. Tags may contain spaces."),
      thumbnails: z.object({
        high: z.object({
          height: z.number().int().optional().describe("(Optional) Height of the thumbnail image."),
          url: z.string().optional().describe("The thumbnail image's URL."),
          width: z.number().int().optional().describe("(Optional) Width of the thumbnail image."),
        }).optional().describe("The high quality image for this resource."),
        maxres: z.object({
          height: z.number().int().optional().describe("(Optional) Height of the thumbnail image."),
          url: z.string().optional().describe("The thumbnail image's URL."),
          width: z.number().int().optional().describe("(Optional) Width of the thumbnail image."),
        }).optional().describe("The maximum resolution quality image for this resource."),
        medium: z.object({
          height: z.number().int().optional().describe("(Optional) Height of the thumbnail image."),
          url: z.string().optional().describe("The thumbnail image's URL."),
          width: z.number().int().optional().describe("(Optional) Width of the thumbnail image."),
        }).optional().describe("The medium quality image for this resource."),
        standard: z.object({
          height: z.number().int().optional().describe("(Optional) Height of the thumbnail image."),
          url: z.string().optional().describe("The thumbnail image's URL."),
          width: z.number().int().optional().describe("(Optional) Width of the thumbnail image."),
        }).optional().describe("The standard quality image for this resource."),
      }).optional().describe("A map of thumbnail images associated with the video. For each object in the map, the key is the name of the thumbnail image, and the value is an object that contains other information about the thumbnail."),
      title: z.string().optional().describe("The video's title. @mutable youtube.videos.insert youtube.videos.update"),
    }).optional().describe("The snippet object contains basic details about the video, such as its title, description, and category."),
    statistics: z.object({
      commentCount: z.string().optional().describe("The number of comments for the video."),
      dislikeCount: z.string().optional().describe("The number of users who have indicated that they disliked the video by giving it a negative rating."),
      favoriteCount: z.string().optional().describe("The number of users who currently have the video marked as a favorite video."),
      likeCount: z.string().optional().describe("The number of users who have indicated that they liked the video by giving it a positive rating."),
      viewCount: z.string().optional().describe("The number of times the video has been viewed."),
    }).optional().describe("The statistics object contains statistics about the video."),
    status: z.object({
      embeddable: z.boolean().optional().describe("This value indicates if the video can be embedded on another website. @mutable youtube.videos.insert youtube.videos.update"),
      failureReason: z.enum(["conversion", "invalidFile", "emptyFile", "tooSmall", "codec", "uploadAborted"]).optional().describe("This value explains why a video failed to upload. This property is only present if the uploadStatus property indicates that the upload failed."),
      license: z.enum(["youtube", "creativeCommon"]).optional().describe("The video's license. @mutable youtube.videos.insert youtube.videos.update"),
      madeForKids: z.boolean().optional(),
      privacyStatus: z.enum(["public", "unlisted", "private"]).optional().describe("The video's privacy status."),
      publicStatsViewable: z.boolean().optional().describe("This value indicates if the extended video statistics on the watch page can be viewed by everyone. Note that the view count, likes, etc will still be visible if this is disabled. @mutable youtube.videos.insert youtube.videos.update"),
      publishAt: z.string().datetime().optional().describe("The date and time when the video is scheduled to publish. It can be set only if the privacy status of the video is private.."),
      rejectionReason: z.enum(["copyright", "inappropriate", "duplicate", "termsOfUse", "uploaderAccountSuspended", "length", "claim", "uploaderAccountClosed", "trademark", "legal"]).optional().describe("This value explains why YouTube rejected an uploaded video. This property is only present if the uploadStatus property indicates that the upload was rejected."),
      selfDeclaredMadeForKids: z.boolean().optional(),
      uploadStatus: z.enum(["uploaded", "processed", "failed", "rejected", "deleted"]).optional().describe("The status of the uploaded video."),
    }).optional().describe("The status object contains information about the video's uploading, processing, and privacy statuses."),
    suggestions: z.object({
      editorSuggestions: z.array(z.enum(["videoAutoLevels", "videoStabilize", "videoCrop", "audioQuietAudioSwap"])).optional().describe("A list of video editing operations that might improve the video quality or playback experience of the uploaded video."),
      processingErrors: z.array(z.enum(["audioFile", "imageFile", "projectFile", "notAVideoFile", "docFile", "archiveFile", "unsupportedSpatialAudioLayout"])).optional().describe("A list of errors that will prevent YouTube from successfully processing the uploaded video video. These errors indicate that, regardless of the video's current processing status, eventually, that status will almost certainly be failed."),
      processingHints: z.array(z.enum(["nonStreamableMov", "sendBestQualityVideo", "sphericalVideo", "spatialAudio", "vrVideo", "hdrVideo"])).optional().describe("A list of suggestions that may improve YouTube's ability to process the video."),
      processingWarnings: z.array(z.enum(["unknownContainer", "unknownVideoCodec", "unknownAudioCodec", "inconsistentResolution", "hasEditlist", "problematicVideoCodec", "problematicAudioCodec", "unsupportedVrStereoMode", "unsupportedSphericalProjectionType", "unsupportedHdrPixelFormat", "unsupportedHdrColorMetadata", "problematicHdrLookupTable"])).optional().describe("A list of reasons why YouTube may have difficulty transcoding the uploaded video or that might result in an erroneous transcoding. These warnings are generated before YouTube actually processes the uploaded video file. In addition, they identify issues that are unlikely to cause the video processing to fail but that might cause problems such as sync issues, video artifacts, or a missing audio track."),
      tagSuggestions: z.array(z.object({
        categoryRestricts: z.array(z.string()).optional().describe("A set of video categories for which the tag is relevant. You can use this information to display appropriate tag suggestions based on the video category that the video uploader associates with the video. By default, tag suggestions are relevant for all categories if there are no restricts defined for the keyword."),
        tag: z.string().optional().describe("The keyword tag suggested for the video."),
      })).optional().describe("A list of keyword tags that could be added to the video's metadata to increase the likelihood that users will locate your video when searching or browsing on YouTube."),
    }).optional().describe("The suggestions object encapsulates suggestions that identify opportunities to improve the video quality or the metadata for the uploaded video. This data can only be retrieved by the video owner."),
    topicDetails: z.object({
      relevantTopicIds: z.array(z.string()).optional().describe("Similar to topic_id, except that these topics are merely relevant to the video. These are topics that may be mentioned in, or appear in the video. You can retrieve information about each topic using Freebase Topic API."),
      topicCategories: z.array(z.string()).optional().describe("A list of Wikipedia URLs that provide a high-level description of the video's content."),
      topicIds: z.array(z.string()).optional().describe("A list of Freebase topic IDs that are centrally associated with the video. These are topics that are centrally featured in the video, and it can be said that the video is mainly about each of these. You can retrieve information about each topic using the < a href=\"http://wiki.freebase.com/wiki/Topic_API\">Freebase Topic API."),
    }).optional().describe("The topicDetails object encapsulates information about Freebase topics associated with the video."),
  })).optional(),
  kind: z.string().optional().default("youtube#videoListResponse").describe("Identifies what kind of resource this is. Value: the fixed string \"youtube#videoListResponse\"."),
  nextPageToken: z.string().optional().describe("The token that can be used as the value of the pageToken parameter to retrieve the next page in the result set."),
  pageInfo: z.object({
    resultsPerPage: z.number().int().optional().describe("The number of results included in the API response."),
    totalResults: z.number().int().optional().describe("The total number of results in the result set."),
  }).optional().describe("General pagination information."),
  prevPageToken: z.string().optional().describe("The token that can be used as the value of the pageToken parameter to retrieve the previous page in the result set."),
  tokenPagination: z.record(z.string(), z.unknown()).optional().describe("Stub token pagination template to suppress results."),
  visitorId: z.string().optional().describe("The visitorId identifies the visitor."),
})

export const youtubeVideosList = pikkuSessionlessFunc({
  description: "Retrieves a list of resources, possibly filtered.",
  input: YoutubeVideosListInput,
  output: YoutubeVideosListOutput,
  func: async ({ youtube }, data) => {
    return youtube.call("GET", "/youtube/v3/videos", data) as any
  },
})
