// actions — Endpoints to manage GitHub Actions using the REST API.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const ActionsGetWorkflowRunInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  run_id: z.number().int().describe("The unique identifier of the workflow run."),
  exclude_pull_requests: z.boolean().optional().default(false).describe("If `true` pull requests are omitted from the response (empty array)."),
})

export const ActionsGetWorkflowRunOutput = z.object({
  actor: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).optional().describe("A GitHub user."),
  artifacts_url: z.string().describe("The URL to the artifacts for the workflow run."),
  cancel_url: z.string().describe("The URL to cancel the workflow run."),
  check_suite_id: z.number().int().optional().describe("The ID of the associated check suite."),
  check_suite_node_id: z.string().optional().describe("The node ID of the associated check suite."),
  check_suite_url: z.string().describe("The URL to the associated check suite."),
  conclusion: z.string().nullable(),
  created_at: z.string().datetime(),
  display_title: z.string().describe("The event-specific title associated with the run or the run-name if set, or the value of `run-name` if it is set in the workflow."),
  event: z.string(),
  head_branch: z.string().nullable(),
  head_commit: z.object({
    author: z.object({
      email: z.string(),
      name: z.string(),
    }).nullable(),
    committer: z.object({
      email: z.string(),
      name: z.string(),
    }).nullable(),
    id: z.string(),
    message: z.string(),
    timestamp: z.string().datetime(),
    tree_id: z.string(),
  }).nullable().describe("A commit."),
  head_repository: z.object({
    allow_forking: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean().optional(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string().optional(),
    code_of_conduct: z.object({
      body: z.string().optional(),
      html_url: z.string().url().nullable(),
      key: z.string(),
      name: z.string(),
      url: z.string().url(),
    }).optional().describe("Code Of Conduct"),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable().optional(),
    default_branch: z.string().optional(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().optional(),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int().optional(),
    forks_count: z.number().int().optional(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string().optional(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean().optional(),
    has_issues: z.boolean().optional(),
    has_pages: z.boolean().optional(),
    has_projects: z.boolean().optional(),
    has_wiki: z.boolean().optional(),
    homepage: z.string().nullable().optional(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable().optional(),
    languages_url: z.string().url(),
    license: z.object({
      key: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      spdx_id: z.string().optional(),
      url: z.string().optional(),
    }).nullable().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().nullable().optional(),
    name: z.string(),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int().optional(),
    open_issues_count: z.number().int().optional(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean().optional(),
      maintain: z.boolean().optional(),
      pull: z.boolean().optional(),
      push: z.boolean().optional(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable().optional(),
    releases_url: z.string(),
    role_name: z.string().optional(),
    security_and_analysis: z.object({
      advanced_security: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning_push_protection: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
    }).nullable().optional(),
    size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    ssh_url: z.string().optional(),
    stargazers_count: z.number().int().optional(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().optional(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable().optional(),
    url: z.string().url(),
    visibility: z.string().optional(),
    watchers: z.number().int().optional(),
    watchers_count: z.number().int().optional(),
    web_commit_signoff_required: z.boolean().optional(),
  }).describe("Minimal Repository"),
  head_repository_id: z.number().int().optional(),
  head_sha: z.string().describe("The SHA of the head commit that points to the version of the workflow being run."),
  html_url: z.string(),
  id: z.number().int().describe("The ID of the workflow run."),
  jobs_url: z.string().describe("The URL to the jobs for the workflow run."),
  logs_url: z.string().describe("The URL to download the logs for the workflow run."),
  name: z.string().nullable().optional().describe("The name of the workflow run."),
  node_id: z.string(),
  path: z.string().describe("The full path of the workflow"),
  previous_attempt_url: z.string().nullable().optional().describe("The URL to the previous attempted run of this workflow, if one exists."),
  pull_requests: z.array(z.object({
    base: z.object({
      ref: z.string(),
      repo: z.object({
        id: z.number().int(),
        name: z.string(),
        url: z.string(),
      }),
      sha: z.string(),
    }),
    head: z.object({
      ref: z.string(),
      repo: z.object({
        id: z.number().int(),
        name: z.string(),
        url: z.string(),
      }),
      sha: z.string(),
    }),
    id: z.number().int(),
    number: z.number().int(),
    url: z.string(),
  })).nullable(),
  referenced_workflows: z.array(z.object({
    path: z.string(),
    ref: z.string().optional(),
    sha: z.string(),
  })).nullable().optional(),
  repository: z.object({
    allow_forking: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean().optional(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string().optional(),
    code_of_conduct: z.object({
      body: z.string().optional(),
      html_url: z.string().url().nullable(),
      key: z.string(),
      name: z.string(),
      url: z.string().url(),
    }).optional().describe("Code Of Conduct"),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable().optional(),
    default_branch: z.string().optional(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().optional(),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int().optional(),
    forks_count: z.number().int().optional(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string().optional(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean().optional(),
    has_issues: z.boolean().optional(),
    has_pages: z.boolean().optional(),
    has_projects: z.boolean().optional(),
    has_wiki: z.boolean().optional(),
    homepage: z.string().nullable().optional(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable().optional(),
    languages_url: z.string().url(),
    license: z.object({
      key: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      spdx_id: z.string().optional(),
      url: z.string().optional(),
    }).nullable().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().nullable().optional(),
    name: z.string(),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int().optional(),
    open_issues_count: z.number().int().optional(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean().optional(),
      maintain: z.boolean().optional(),
      pull: z.boolean().optional(),
      push: z.boolean().optional(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable().optional(),
    releases_url: z.string(),
    role_name: z.string().optional(),
    security_and_analysis: z.object({
      advanced_security: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning_push_protection: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
    }).nullable().optional(),
    size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    ssh_url: z.string().optional(),
    stargazers_count: z.number().int().optional(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().optional(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable().optional(),
    url: z.string().url(),
    visibility: z.string().optional(),
    watchers: z.number().int().optional(),
    watchers_count: z.number().int().optional(),
    web_commit_signoff_required: z.boolean().optional(),
  }).describe("Minimal Repository"),
  rerun_url: z.string().describe("The URL to rerun the workflow run."),
  run_attempt: z.number().int().optional().describe("Attempt number of the run, 1 for first attempt and higher if the workflow was re-run."),
  run_number: z.number().int().describe("The auto incrementing run number for the workflow run."),
  run_started_at: z.string().datetime().optional().describe("The start time of the latest run. Resets on re-run."),
  status: z.string().nullable(),
  triggering_actor: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).optional().describe("A GitHub user."),
  updated_at: z.string().datetime(),
  url: z.string().describe("The URL to the workflow run."),
  workflow_id: z.number().int().describe("The ID of the parent workflow."),
  workflow_url: z.string().describe("The URL to the workflow."),
}).describe("An invocation of a workflow")

export const actionsGetWorkflowRun = pikkuSessionlessFunc({
  description: "Gets a specific workflow run. Anyone with read access to the repository can use this endpoint. If the repository is private you must use an access token with the `repo` scope. GitHub Apps must have the `actions:read` permission to use this endpoint.",
  input: ActionsGetWorkflowRunInput,
  output: ActionsGetWorkflowRunOutput,
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/actions/runs/{run_id}", data) as any
  },
})
