// apps — Information for integrations and installations.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { UnauthorizedError, ForbiddenError, NotFoundError, UnprocessableContentError } from '@pikku/core/errors'

export const AppsCreateInstallationAccessTokenInput = z.object({
  installation_id: z.number().int().describe("The unique identifier of the installation."),
  permissions: z.object({
  actions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts."),
  administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation."),
  checks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for checks on code."),
  contents: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges."),
  deployments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for deployments and deployment statuses."),
  environments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for managing repository environments."),
  issues: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for issues and related comments, assignees, labels, and milestones."),
  members: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization teams and members."),
  metadata: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata."),
  organization_administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage access to an organization."),
  organization_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for an organization."),
  organization_custom_roles: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for custom repository roles management. This property is in beta and is subject to change."),
  organization_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for an organization."),
  organization_packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization packages published to GitHub Packages."),
  organization_plan: z.literal("read").optional().describe("The level of permission to grant the access token for viewing an organization's plan."),
  organization_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage organization projects and projects beta (where available)."),
  organization_secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage organization secrets."),
  organization_self_hosted_runners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage GitHub Actions self-hosted runners available to an organization."),
  organization_user_blocking: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage users blocked by the organization."),
  packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for packages published to GitHub Packages."),
  pages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to retrieve Pages statuses, configuration, and builds, as well as create new builds."),
  pull_requests: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges."),
  repository_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for a repository."),
  repository_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for a repository."),
  repository_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage repository projects, columns, and cards."),
  secret_scanning_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage secret scanning alerts."),
  secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage repository secrets."),
  security_events: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage security events like code scanning alerts."),
  single_file: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage just a single file."),
  statuses: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for commit statuses."),
  team_discussions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage team discussions and related comments."),
  vulnerability_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage Dependabot alerts."),
  workflows: z.literal("write").optional().describe("The level of permission to grant the access token to update GitHub Actions workflow files."),
}).optional().describe("The permissions granted to the user-to-server access token."),
  repositories: z.array(z.string()).optional().describe("List of repository names that the token should have access to"),
  repository_ids: z.array(z.number().int()).optional().describe("List of repository IDs that the token should have access to"),
})

export const AppsCreateInstallationAccessTokenOutput = z.object({
  expires_at: z.string(),
  has_multiple_single_files: z.boolean().optional(),
  permissions: z.object({
    actions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts."),
    administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation."),
    checks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for checks on code."),
    contents: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges."),
    deployments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for deployments and deployment statuses."),
    environments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for managing repository environments."),
    issues: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for issues and related comments, assignees, labels, and milestones."),
    members: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization teams and members."),
    metadata: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata."),
    organization_administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage access to an organization."),
    organization_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for an organization."),
    organization_custom_roles: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for custom repository roles management. This property is in beta and is subject to change."),
    organization_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for an organization."),
    organization_packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization packages published to GitHub Packages."),
    organization_plan: z.literal("read").optional().describe("The level of permission to grant the access token for viewing an organization's plan."),
    organization_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage organization projects and projects beta (where available)."),
    organization_secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage organization secrets."),
    organization_self_hosted_runners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage GitHub Actions self-hosted runners available to an organization."),
    organization_user_blocking: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage users blocked by the organization."),
    packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for packages published to GitHub Packages."),
    pages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to retrieve Pages statuses, configuration, and builds, as well as create new builds."),
    pull_requests: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges."),
    repository_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for a repository."),
    repository_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for a repository."),
    repository_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage repository projects, columns, and cards."),
    secret_scanning_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage secret scanning alerts."),
    secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage repository secrets."),
    security_events: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage security events like code scanning alerts."),
    single_file: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage just a single file."),
    statuses: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for commit statuses."),
    team_discussions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage team discussions and related comments."),
    vulnerability_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage Dependabot alerts."),
    workflows: z.literal("write").optional().describe("The level of permission to grant the access token to update GitHub Actions workflow files."),
  }).optional().describe("The permissions granted to the user-to-server access token."),
  repositories: z.array(z.object({
    allow_auto_merge: z.boolean().optional().default(false).describe("Whether to allow Auto-merge to be used on pull requests."),
    allow_forking: z.boolean().optional().describe("Whether to allow forking this repo"),
    allow_merge_commit: z.boolean().optional().default(true).describe("Whether to allow merge commits for pull requests."),
    allow_rebase_merge: z.boolean().optional().default(true).describe("Whether to allow rebase merges for pull requests."),
    allow_squash_merge: z.boolean().optional().default(true).describe("Whether to allow squash merges for pull requests."),
    allow_update_branch: z.boolean().optional().default(false).describe("Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging."),
    anonymous_access_enabled: z.boolean().optional().describe("Whether anonymous git access is enabled for this repository"),
    archive_url: z.string(),
    archived: z.boolean().default(false).describe("Whether the repository is archived."),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string(),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable(),
    default_branch: z.string().describe("The default branch of the repository."),
    delete_branch_on_merge: z.boolean().optional().default(false).describe("Whether to delete head branches when pull requests are merged"),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().describe("Returns whether or not this repository disabled."),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int(),
    forks_count: z.number().int(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string(),
    has_discussions: z.boolean().optional().default(false).describe("Whether discussions are enabled."),
    has_downloads: z.boolean().default(true).describe("Whether downloads are enabled."),
    has_issues: z.boolean().default(true).describe("Whether issues are enabled."),
    has_pages: z.boolean(),
    has_projects: z.boolean().default(true).describe("Whether projects are enabled."),
    has_wiki: z.boolean().default(true).describe("Whether the wiki is enabled."),
    homepage: z.string().url().nullable(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the repository"),
    is_template: z.boolean().optional().default(false).describe("Whether this repository acts as a template that can be used to generate new repositories."),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable(),
    languages_url: z.string().url(),
    license: z.object({
      html_url: z.string().url().optional(),
      key: z.string(),
      name: z.string(),
      node_id: z.string(),
      spdx_id: z.string().nullable(),
      url: z.string().url().nullable(),
    }).nullable().describe("License Simple"),
    master_branch: z.string().optional(),
    merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
    merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().url().nullable(),
    name: z.string().describe("The name of the repository."),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int(),
    open_issues_count: z.number().int(),
    organization: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().optional().describe("A GitHub user."),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean(),
      maintain: z.boolean().optional(),
      pull: z.boolean(),
      push: z.boolean(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean().default(false).describe("Whether the repository is private or public."),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable(),
    releases_url: z.string(),
    size: z.number().int().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
    squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
    ssh_url: z.string(),
    stargazers_count: z.number().int(),
    stargazers_url: z.string().url(),
    starred_at: z.string().optional(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().url(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    template_repository: z.object({
      allow_auto_merge: z.boolean().optional(),
      allow_merge_commit: z.boolean().optional(),
      allow_rebase_merge: z.boolean().optional(),
      allow_squash_merge: z.boolean().optional(),
      allow_update_branch: z.boolean().optional(),
      archive_url: z.string().optional(),
      archived: z.boolean().optional(),
      assignees_url: z.string().optional(),
      blobs_url: z.string().optional(),
      branches_url: z.string().optional(),
      clone_url: z.string().optional(),
      collaborators_url: z.string().optional(),
      comments_url: z.string().optional(),
      commits_url: z.string().optional(),
      compare_url: z.string().optional(),
      contents_url: z.string().optional(),
      contributors_url: z.string().optional(),
      created_at: z.string().optional(),
      default_branch: z.string().optional(),
      delete_branch_on_merge: z.boolean().optional(),
      deployments_url: z.string().optional(),
      description: z.string().optional(),
      disabled: z.boolean().optional(),
      downloads_url: z.string().optional(),
      events_url: z.string().optional(),
      fork: z.boolean().optional(),
      forks_count: z.number().int().optional(),
      forks_url: z.string().optional(),
      full_name: z.string().optional(),
      git_commits_url: z.string().optional(),
      git_refs_url: z.string().optional(),
      git_tags_url: z.string().optional(),
      git_url: z.string().optional(),
      has_downloads: z.boolean().optional(),
      has_issues: z.boolean().optional(),
      has_pages: z.boolean().optional(),
      has_projects: z.boolean().optional(),
      has_wiki: z.boolean().optional(),
      homepage: z.string().optional(),
      hooks_url: z.string().optional(),
      html_url: z.string().optional(),
      id: z.number().int().optional(),
      is_template: z.boolean().optional(),
      issue_comment_url: z.string().optional(),
      issue_events_url: z.string().optional(),
      issues_url: z.string().optional(),
      keys_url: z.string().optional(),
      labels_url: z.string().optional(),
      language: z.string().optional(),
      languages_url: z.string().optional(),
      merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
      merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
      merges_url: z.string().optional(),
      milestones_url: z.string().optional(),
      mirror_url: z.string().optional(),
      name: z.string().optional(),
      network_count: z.number().int().optional(),
      node_id: z.string().optional(),
      notifications_url: z.string().optional(),
      open_issues_count: z.number().int().optional(),
      owner: z.object({
        avatar_url: z.string().optional(),
        events_url: z.string().optional(),
        followers_url: z.string().optional(),
        following_url: z.string().optional(),
        gists_url: z.string().optional(),
        gravatar_id: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        login: z.string().optional(),
        node_id: z.string().optional(),
        organizations_url: z.string().optional(),
        received_events_url: z.string().optional(),
        repos_url: z.string().optional(),
        site_admin: z.boolean().optional(),
        starred_url: z.string().optional(),
        subscriptions_url: z.string().optional(),
        type: z.string().optional(),
        url: z.string().optional(),
      }).optional(),
      permissions: z.object({
        admin: z.boolean().optional(),
        maintain: z.boolean().optional(),
        pull: z.boolean().optional(),
        push: z.boolean().optional(),
        triage: z.boolean().optional(),
      }).optional(),
      private: z.boolean().optional(),
      pulls_url: z.string().optional(),
      pushed_at: z.string().optional(),
      releases_url: z.string().optional(),
      size: z.number().int().optional(),
      squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
      squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
      ssh_url: z.string().optional(),
      stargazers_count: z.number().int().optional(),
      stargazers_url: z.string().optional(),
      statuses_url: z.string().optional(),
      subscribers_count: z.number().int().optional(),
      subscribers_url: z.string().optional(),
      subscription_url: z.string().optional(),
      svn_url: z.string().optional(),
      tags_url: z.string().optional(),
      teams_url: z.string().optional(),
      temp_clone_token: z.string().optional(),
      topics: z.array(z.string()).optional(),
      trees_url: z.string().optional(),
      updated_at: z.string().optional(),
      url: z.string().optional(),
      use_squash_pr_title_as_default: z.boolean().optional(),
      visibility: z.string().optional(),
      watchers_count: z.number().int().optional(),
    }).nullable().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable(),
    url: z.string().url(),
    use_squash_pr_title_as_default: z.boolean().optional().default(false).describe("Whether a squash merge commit can use the pull request title as default. **This property has been deprecated. Please use `squash_merge_commit_title` instead."),
    visibility: z.string().optional().default("public").describe("The repository visibility: public, private, or internal."),
    watchers: z.number().int(),
    watchers_count: z.number().int(),
    web_commit_signoff_required: z.boolean().optional().default(false).describe("Whether to require contributors to sign off on web-based commits"),
  })).optional(),
  repository_selection: z.enum(["all", "selected"]).optional(),
  single_file: z.string().optional(),
  single_file_paths: z.array(z.string()).optional(),
  token: z.string(),
}).describe("Authentication token for a GitHub App installed on a user or org.")

export const appsCreateInstallationAccessToken = pikkuSessionlessFunc({
  description: "Creates an installation access token that enables a GitHub App to make authenticated API requests for the app's installation on an organization or individual account. Installation tokens expire one hour from the time you create them. Using an expired token produces a status code of `401 - Unauthorized`, and requires creating a new installation token. By default the installation token has access to all repositories that the installation can access. To restrict the access to specific repositories, you can provide the `repository_ids` when creating the token. When you omit `repository_ids`, the response does not contain the `repositories` key.\n\nYou must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.",
  input: AppsCreateInstallationAccessTokenInput,
  output: AppsCreateInstallationAccessTokenOutput,
  errors: [UnauthorizedError, ForbiddenError, NotFoundError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("POST", "/app/installations/{installation_id}/access_tokens", data) as any
  },
})
