// apps — Information for integrations and installations.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { UnauthorizedError, ForbiddenError } from '@pikku/core/errors'

export const AppsListInstallationsForAuthenticatedUserInput = z.object({
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
})

export const AppsListInstallationsForAuthenticatedUserOutput = z.object({
  installations: z.array(z.object({
    access_tokens_url: z.string().url(),
    account: z.union([z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }), z.object({
      avatar_url: z.string().url(),
      created_at: z.string().datetime().nullable(),
      description: z.string().nullable().optional().describe("A short description of the enterprise."),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the enterprise"),
      name: z.string().describe("The name of the enterprise."),
      node_id: z.string(),
      slug: z.string().describe("The slug url identifier for the enterprise."),
      updated_at: z.string().datetime().nullable(),
      website_url: z.string().url().nullable().optional().describe("The enterprise's website URL."),
    })]).nullable(),
    app_id: z.number().int(),
    app_slug: z.string(),
    contact_email: z.string().nullable().optional(),
    created_at: z.string().datetime(),
    events: z.array(z.string()),
    has_multiple_single_files: z.boolean().optional(),
    html_url: z.string().url(),
    id: z.number().int().describe("The ID of the installation."),
    permissions: z.object({
      actions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts."),
      administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation."),
      checks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for checks on code."),
      contents: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges."),
      deployments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for deployments and deployment statuses."),
      environments: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for managing repository environments."),
      issues: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for issues and related comments, assignees, labels, and milestones."),
      members: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization teams and members."),
      metadata: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata."),
      organization_administration: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage access to an organization."),
      organization_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for an organization."),
      organization_custom_roles: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for custom repository roles management. This property is in beta and is subject to change."),
      organization_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for an organization."),
      organization_packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for organization packages published to GitHub Packages."),
      organization_plan: z.literal("read").optional().describe("The level of permission to grant the access token for viewing an organization's plan."),
      organization_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage organization projects and projects beta (where available)."),
      organization_secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage organization secrets."),
      organization_self_hosted_runners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage GitHub Actions self-hosted runners available to an organization."),
      organization_user_blocking: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage users blocked by the organization."),
      packages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for packages published to GitHub Packages."),
      pages: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to retrieve Pages statuses, configuration, and builds, as well as create new builds."),
      pull_requests: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges."),
      repository_announcement_banners: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage announcement banners for a repository."),
      repository_hooks: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage the post-receive hooks for a repository."),
      repository_projects: z.enum(["read", "write", "admin"]).optional().describe("The level of permission to grant the access token to manage repository projects, columns, and cards."),
      secret_scanning_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage secret scanning alerts."),
      secrets: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage repository secrets."),
      security_events: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to view and manage security events like code scanning alerts."),
      single_file: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage just a single file."),
      statuses: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token for commit statuses."),
      team_discussions: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage team discussions and related comments."),
      vulnerability_alerts: z.enum(["read", "write"]).optional().describe("The level of permission to grant the access token to manage Dependabot alerts."),
      workflows: z.literal("write").optional().describe("The level of permission to grant the access token to update GitHub Actions workflow files."),
    }).describe("The permissions granted to the user-to-server access token."),
    repositories_url: z.string().url(),
    repository_selection: z.enum(["all", "selected"]).describe("Describe whether all repositories have been selected or there's a selection involved"),
    single_file_name: z.string().nullable(),
    single_file_paths: z.array(z.string()).optional(),
    suspended_at: z.string().datetime().nullable(),
    suspended_by: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    target_id: z.number().int().describe("The ID of the user or organization this token is being scoped to."),
    target_type: z.string(),
    updated_at: z.string().datetime(),
  })),
  total_count: z.number().int(),
})

export const appsListInstallationsForAuthenticatedUser = pikkuSessionlessFunc({
  description: "Lists installations of your GitHub App that the authenticated user has explicit permission (`:read`, `:write`, or `:admin`) to access.\n\nYou must use a [user-to-server OAuth access token](https://docs.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/#identifying-users-on-your-site), created for a user who has authorized your GitHub App, to access this endpoint.\n\nThe authenticated user has explicit permission to access repositories they own, repositories where they are a collaborator, and repositories that they can access through an organization membership.\n\nYou can find the permissions for the installation under the `permissions` key.",
  input: AppsListInstallationsForAuthenticatedUserInput,
  output: AppsListInstallationsForAuthenticatedUserOutput,
  errors: [UnauthorizedError, ForbiddenError],
  func: async ({ github }, data) => {
    return github.call("GET", "/user/installations", data) as any
  },
})
