// checks — Rich interactions with checks run by your integrations.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const ChecksListForSuiteInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  check_suite_id: z.number().int().describe("The unique identifier of the check suite."),
  check_name: z.string().optional().describe("Returns check runs with the specified `name`."),
  status: z.enum(["queued", "in_progress", "completed"]).optional().describe("Returns check runs with the specified `status`."),
  filter: z.enum(["latest", "all"]).optional().default("latest").describe("Filters check runs by their `completed_at` timestamp. `latest` returns the most recent check runs."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
})

export const ChecksListForSuiteOutput = z.object({
  check_runs: z.array(z.object({
    app: z.object({
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      events: z.array(z.string()).describe("The list of events for the GitHub app"),
      external_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the GitHub app"),
      installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
      name: z.string().describe("The name of the GitHub app"),
      node_id: z.string(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      pem: z.string().optional(),
      permissions: z.object({
        checks: z.string().optional(),
        contents: z.string().optional(),
        deployments: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
      }).describe("The set of permissions for the GitHub app"),
      slug: z.string().optional().describe("The slug name of the GitHub app"),
      updated_at: z.string().datetime(),
      webhook_secret: z.string().nullable().optional(),
    }).nullable().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
    check_suite: z.object({
      id: z.number().int(),
    }).nullable(),
    completed_at: z.string().datetime().nullable(),
    conclusion: z.enum(["success", "failure", "neutral", "cancelled", "skipped", "timed_out", "action_required"]).nullable(),
    deployment: z.object({
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      environment: z.string().describe("Name for the target deployment environment."),
      id: z.number().int().describe("Unique identifier of the deployment"),
      node_id: z.string(),
      original_environment: z.string().optional(),
      performed_via_github_app: z.object({
        client_id: z.string().optional(),
        client_secret: z.string().optional(),
        created_at: z.string().datetime(),
        description: z.string().nullable(),
        events: z.array(z.string()).describe("The list of events for the GitHub app"),
        external_url: z.string().url(),
        html_url: z.string().url(),
        id: z.number().int().describe("Unique identifier of the GitHub app"),
        installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
        name: z.string().describe("The name of the GitHub app"),
        node_id: z.string(),
        owner: z.object({
          avatar_url: z.string().url(),
          email: z.string().nullable().optional(),
          events_url: z.string(),
          followers_url: z.string().url(),
          following_url: z.string(),
          gists_url: z.string(),
          gravatar_id: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          login: z.string(),
          name: z.string().nullable().optional(),
          node_id: z.string(),
          organizations_url: z.string().url(),
          received_events_url: z.string().url(),
          repos_url: z.string().url(),
          site_admin: z.boolean(),
          starred_at: z.string().optional(),
          starred_url: z.string(),
          subscriptions_url: z.string().url(),
          type: z.string(),
          url: z.string().url(),
        }).nullable().describe("A GitHub user."),
        pem: z.string().optional(),
        permissions: z.object({
          checks: z.string().optional(),
          contents: z.string().optional(),
          deployments: z.string().optional(),
          issues: z.string().optional(),
          metadata: z.string().optional(),
        }).describe("The set of permissions for the GitHub app"),
        slug: z.string().optional().describe("The slug name of the GitHub app"),
        updated_at: z.string().datetime(),
        webhook_secret: z.string().nullable().optional(),
      }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
      production_environment: z.boolean().optional().describe("Specifies if the given environment is one that end-users directly interact with. Default: false."),
      repository_url: z.string().url(),
      statuses_url: z.string().url(),
      task: z.string().describe("Parameter to specify a task to execute"),
      transient_environment: z.boolean().optional().describe("Specifies if the given environment is will no longer exist at some point in the future. Default: false."),
      updated_at: z.string().datetime(),
      url: z.string().url(),
    }).optional().describe("A deployment created as the result of an Actions check run from a workflow that references an environment"),
    details_url: z.string().nullable(),
    external_id: z.string().nullable(),
    head_sha: z.string().describe("The SHA of the commit that is being checked."),
    html_url: z.string().nullable(),
    id: z.number().int().describe("The id of the check."),
    name: z.string().describe("The name of the check."),
    node_id: z.string(),
    output: z.object({
      annotations_count: z.number().int(),
      annotations_url: z.string().url(),
      summary: z.string().nullable(),
      text: z.string().nullable(),
      title: z.string().nullable(),
    }),
    pull_requests: z.array(z.object({
      base: z.object({
        ref: z.string(),
        repo: z.object({
          id: z.number().int(),
          name: z.string(),
          url: z.string(),
        }),
        sha: z.string(),
      }),
      head: z.object({
        ref: z.string(),
        repo: z.object({
          id: z.number().int(),
          name: z.string(),
          url: z.string(),
        }),
        sha: z.string(),
      }),
      id: z.number().int(),
      number: z.number().int(),
      url: z.string(),
    })),
    started_at: z.string().datetime().nullable(),
    status: z.enum(["queued", "in_progress", "completed"]).describe("The phase of the lifecycle that the check is currently in."),
    url: z.string(),
  })),
  total_count: z.number().int(),
})

export const checksListForSuite = pikkuSessionlessFunc({
  description: "**Note:** The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty `pull_requests` array.\n\nLists check runs for a check suite using its `id`. GitHub Apps must have the `checks:read` permission on a private repository or pull access to a public repository to get check runs. OAuth Apps and authenticated users must have the `repo` scope to get check runs in a private repository.",
  input: ChecksListForSuiteInput,
  output: ChecksListForSuiteOutput,
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs", data) as any
  },
})
