// checks — Rich interactions with checks run by your integrations.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const ChecksCreateInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  actions: z.array(z.object({
  description: z.string().max(40).describe("A short explanation of what this action would do. The maximum size is 40 characters."),
  identifier: z.string().max(20).describe("A reference for the action on the integrator's system. The maximum size is 20 characters."),
  label: z.string().max(20).describe("The text to be displayed on a button in the web UI. The maximum size is 20 characters."),
})).max(3).optional().describe("Displays a button on GitHub that can be clicked to alert your app to do additional tasks. For example, a code linting app can display a button that automatically fixes detected errors. The button created in this object is displayed after the check run completes. When a user clicks the button, GitHub sends the [`check_run.requested_action` webhook](https://docs.github.com/webhooks/event-payloads/#check_run) to your app. Each action includes a `label`, `identifier` and `description`. A maximum of three actions are accepted. To learn more about check runs and requested actions, see \"[Check runs and requested actions](https://docs.github.com/rest/reference/checks#check-runs-and-requested-actions).\""),
  completed_at: z.string().datetime().optional().describe("The time the check completed. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
  conclusion: z.enum(["action_required", "cancelled", "failure", "neutral", "success", "skipped", "stale", "timed_out"]).optional().describe("**Required if you provide `completed_at` or a `status` of `completed`**. The final conclusion of the check. \n**Note:** Providing `conclusion` will automatically set the `status` parameter to `completed`. You cannot change a check run conclusion to `stale`, only GitHub can set this."),
  details_url: z.string().optional().describe("The URL of the integrator's site that has the full details of the check. If the integrator does not provide this, then the homepage of the GitHub app is used."),
  external_id: z.string().optional().describe("A reference for the run on the integrator's system."),
  head_sha: z.string().describe("The SHA of the commit."),
  name: z.string().describe("The name of the check. For example, \"code-coverage\"."),
  output: z.object({
  annotations: z.array(z.object({
    annotation_level: z.enum(["notice", "warning", "failure"]).describe("The level of the annotation."),
    end_column: z.number().int().optional().describe("The end column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values."),
    end_line: z.number().int().describe("The end line of the annotation."),
    message: z.string().describe("A short description of the feedback for these lines of code. The maximum size is 64 KB."),
    path: z.string().describe("The path of the file to add an annotation to. For example, `assets/css/main.css`."),
    raw_details: z.string().optional().describe("Details about this annotation. The maximum size is 64 KB."),
    start_column: z.number().int().optional().describe("The start column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values. Column numbers start at 1."),
    start_line: z.number().int().describe("The start line of the annotation. Line numbers start at 1."),
    title: z.string().optional().describe("The title that represents the annotation. The maximum size is 255 characters."),
  })).max(50).optional().describe("Adds information from your analysis to specific lines of code. Annotations are visible on GitHub in the **Checks** and **Files changed** tab of the pull request. The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the [Update a check run](https://docs.github.com/rest/reference/checks#update-a-check-run) endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see \"[About status checks](https://docs.github.com/articles/about-status-checks#checks)\"."),
  images: z.array(z.object({
    alt: z.string().describe("The alternative text for the image."),
    caption: z.string().optional().describe("A short image description."),
    image_url: z.string().describe("The full URL of the image."),
  })).optional().describe("Adds images to the output displayed in the GitHub pull request UI."),
  summary: z.string().max(65535).describe("The summary of the check run. This parameter supports Markdown. **Maximum length**: 65535 characters."),
  text: z.string().max(65535).optional().describe("The details of the check run. This parameter supports Markdown. **Maximum length**: 65535 characters."),
  title: z.string().describe("The title of the check run."),
}).optional().describe("Check runs can accept a variety of data in the `output` object, including a `title` and `summary` and can optionally provide descriptive details about the run."),
  started_at: z.string().datetime().optional().describe("The time that the check run began. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
  status: z.enum(["queued", "in_progress", "completed"]).optional().default("queued").describe("The current status."),
})

export const ChecksCreateOutput = z.object({
  app: z.object({
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    events: z.array(z.string()).describe("The list of events for the GitHub app"),
    external_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the GitHub app"),
    installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
    name: z.string().describe("The name of the GitHub app"),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    pem: z.string().optional(),
    permissions: z.object({
      checks: z.string().optional(),
      contents: z.string().optional(),
      deployments: z.string().optional(),
      issues: z.string().optional(),
      metadata: z.string().optional(),
    }).describe("The set of permissions for the GitHub app"),
    slug: z.string().optional().describe("The slug name of the GitHub app"),
    updated_at: z.string().datetime(),
    webhook_secret: z.string().nullable().optional(),
  }).nullable().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
  check_suite: z.object({
    id: z.number().int(),
  }).nullable(),
  completed_at: z.string().datetime().nullable(),
  conclusion: z.enum(["success", "failure", "neutral", "cancelled", "skipped", "timed_out", "action_required"]).nullable(),
  deployment: z.object({
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    environment: z.string().describe("Name for the target deployment environment."),
    id: z.number().int().describe("Unique identifier of the deployment"),
    node_id: z.string(),
    original_environment: z.string().optional(),
    performed_via_github_app: z.object({
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      events: z.array(z.string()).describe("The list of events for the GitHub app"),
      external_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the GitHub app"),
      installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
      name: z.string().describe("The name of the GitHub app"),
      node_id: z.string(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      pem: z.string().optional(),
      permissions: z.object({
        checks: z.string().optional(),
        contents: z.string().optional(),
        deployments: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
      }).describe("The set of permissions for the GitHub app"),
      slug: z.string().optional().describe("The slug name of the GitHub app"),
      updated_at: z.string().datetime(),
      webhook_secret: z.string().nullable().optional(),
    }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
    production_environment: z.boolean().optional().describe("Specifies if the given environment is one that end-users directly interact with. Default: false."),
    repository_url: z.string().url(),
    statuses_url: z.string().url(),
    task: z.string().describe("Parameter to specify a task to execute"),
    transient_environment: z.boolean().optional().describe("Specifies if the given environment is will no longer exist at some point in the future. Default: false."),
    updated_at: z.string().datetime(),
    url: z.string().url(),
  }).optional().describe("A deployment created as the result of an Actions check run from a workflow that references an environment"),
  details_url: z.string().nullable(),
  external_id: z.string().nullable(),
  head_sha: z.string().describe("The SHA of the commit that is being checked."),
  html_url: z.string().nullable(),
  id: z.number().int().describe("The id of the check."),
  name: z.string().describe("The name of the check."),
  node_id: z.string(),
  output: z.object({
    annotations_count: z.number().int(),
    annotations_url: z.string().url(),
    summary: z.string().nullable(),
    text: z.string().nullable(),
    title: z.string().nullable(),
  }),
  pull_requests: z.array(z.object({
    base: z.object({
      ref: z.string(),
      repo: z.object({
        id: z.number().int(),
        name: z.string(),
        url: z.string(),
      }),
      sha: z.string(),
    }),
    head: z.object({
      ref: z.string(),
      repo: z.object({
        id: z.number().int(),
        name: z.string(),
        url: z.string(),
      }),
      sha: z.string(),
    }),
    id: z.number().int(),
    number: z.number().int(),
    url: z.string(),
  })),
  started_at: z.string().datetime().nullable(),
  status: z.enum(["queued", "in_progress", "completed"]).describe("The phase of the lifecycle that the check is currently in."),
  url: z.string(),
}).describe("A check performed on the code of a given code change")

export const checksCreate = pikkuSessionlessFunc({
  description: "**Note:** The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty `pull_requests` array.\n\nCreates a new check run for a specific commit in a repository. Your GitHub App must have the `checks:write` permission to create check runs.\n\nIn a check suite, GitHub limits the number of check runs with the same name to 1000. Once these check runs exceed 1000, GitHub will start to automatically delete older check runs.",
  input: ChecksCreateInput,
  output: ChecksCreateOutput,
  func: async ({ github }, data) => {
    return github.call("POST", "/repos/{owner}/{repo}/check-runs", data) as any
  },
})
