// code-scanning — Retrieve code scanning alerts from a repository.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'
import { codescanninganalysistoolguidSchema, codescanninganalysistoolnameSchema } from '../github.types.js'

export const CodeScanningListAlertsForOrgInput = z.object({
  org: z.string().describe("The organization name. The name is not case sensitive."),
  tool_name: codescanninganalysistoolnameSchema.optional().describe("The name of a code scanning tool. Only results by this tool will be listed. You can specify the tool by using either `tool_name` or `tool_guid`, but not both."),
  tool_guid: codescanninganalysistoolguidSchema.optional().describe("The GUID of a code scanning tool. Only results by this tool will be listed. Note that some code scanning tools may not include a GUID in their analysis data. You can specify the tool by using either `tool_guid` or `tool_name`, but not both."),
  before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/overview/resources-in-the-rest-api#link-header). If specified, the query only searches for results before this cursor."),
  after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/overview/resources-in-the-rest-api#link-header). If specified, the query only searches for results after this cursor."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  direction: z.enum(["asc", "desc"]).optional().default("desc").describe("The direction to sort the results by."),
  state: z.enum(["open", "closed", "dismissed", "fixed"]).optional().describe("State of a code scanning alert.").describe("If specified, only code scanning alerts with this state will be returned."),
  sort: z.enum(["created", "updated"]).optional().default("created").describe("The property by which to sort the results."),
  severity: z.enum(["critical", "high", "medium", "low", "warning", "note", "error"]).optional().describe("Severity of a code scanning alert.").describe("If specified, only code scanning alerts with this severity will be returned."),
})

export const CodeScanningListAlertsForOrgOutput = z.array(z.object({
  created_at: z.string().datetime().describe("The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  dismissed_at: z.string().datetime().nullable().describe("The time that the alert was dismissed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  dismissed_by: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  dismissed_comment: z.string().max(280).nullable().optional().describe("The dismissal comment associated with the dismissal of the alert."),
  dismissed_reason: z.union([z.literal(null), z.literal("false positive"), z.literal("won't fix"), z.literal("used in tests")]).nullable().describe("**Required when the state is dismissed.** The reason for dismissing or closing the alert."),
  fixed_at: z.string().datetime().nullable().optional().describe("The time that the alert was no longer detected and was considered fixed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  html_url: z.string().url().describe("The GitHub URL of the alert resource."),
  instances_url: z.string().url().describe("The REST API URL for fetching the list of instances for an alert."),
  most_recent_instance: z.object({
    analysis_key: z.string().optional().describe("Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this includes the workflow filename and job name."),
    category: z.string().optional().describe("Identifies the configuration under which the analysis was executed. Used to distinguish between multiple analyses for the same tool and commit, but performed on different languages or different parts of the code."),
    classifications: z.array(z.enum(["source", "generated", "test", "library"])).optional().describe("Classifications that have been applied to the file that triggered the alert.\nFor example identifying it as documentation, or a generated file."),
    commit_sha: z.string().optional(),
    environment: z.string().optional().describe("Identifies the variable values associated with the environment in which the analysis that generated this alert instance was performed, such as the language that was analyzed."),
    html_url: z.string().optional(),
    location: z.object({
      end_column: z.number().int().optional(),
      end_line: z.number().int().optional(),
      path: z.string().optional(),
      start_column: z.number().int().optional(),
      start_line: z.number().int().optional(),
    }).optional().describe("Describe a region within a file for the alert."),
    message: z.object({
      text: z.string().optional(),
    }).optional(),
    ref: z.string().optional().describe("The full Git reference, formatted as `refs/heads/<branch name>`,\n`refs/pull/<number>/merge`, or `refs/pull/<number>/head`."),
    state: z.enum(["open", "closed", "dismissed", "fixed"]).optional().describe("State of a code scanning alert."),
  }),
  number: z.number().int().describe("The security alert number."),
  repository: z.object({
    archive_url: z.string().describe("A template for the API URL to download the repository as an archive."),
    assignees_url: z.string().describe("A template for the API URL to list the available assignees for issues in the repository."),
    blobs_url: z.string().describe("A template for the API URL to create or retrieve a raw Git blob in the repository."),
    branches_url: z.string().describe("A template for the API URL to get information about branches in the repository."),
    collaborators_url: z.string().describe("A template for the API URL to get information about collaborators of the repository."),
    comments_url: z.string().describe("A template for the API URL to get information about comments on the repository."),
    commits_url: z.string().describe("A template for the API URL to get information about commits on the repository."),
    compare_url: z.string().describe("A template for the API URL to compare two commits or refs."),
    contents_url: z.string().describe("A template for the API URL to get the contents of the repository."),
    contributors_url: z.string().url().describe("A template for the API URL to list the contributors to the repository."),
    deployments_url: z.string().url().describe("The API URL to list the deployments of the repository."),
    description: z.string().nullable().describe("The repository description."),
    downloads_url: z.string().url().describe("The API URL to list the downloads on the repository."),
    events_url: z.string().url().describe("The API URL to list the events of the repository."),
    fork: z.boolean().describe("Whether the repository is a fork."),
    forks_url: z.string().url().describe("The API URL to list the forks of the repository."),
    full_name: z.string().describe("The full, globally unique, name of the repository."),
    git_commits_url: z.string().describe("A template for the API URL to get information about Git commits of the repository."),
    git_refs_url: z.string().describe("A template for the API URL to get information about Git refs of the repository."),
    git_tags_url: z.string().describe("A template for the API URL to get information about Git tags of the repository."),
    hooks_url: z.string().url().describe("The API URL to list the hooks on the repository."),
    html_url: z.string().url().describe("The URL to view the repository on GitHub.com."),
    id: z.number().int().describe("A unique identifier of the repository."),
    issue_comment_url: z.string().describe("A template for the API URL to get information about issue comments on the repository."),
    issue_events_url: z.string().describe("A template for the API URL to get information about issue events on the repository."),
    issues_url: z.string().describe("A template for the API URL to get information about issues on the repository."),
    keys_url: z.string().describe("A template for the API URL to get information about deploy keys on the repository."),
    labels_url: z.string().describe("A template for the API URL to get information about labels of the repository."),
    languages_url: z.string().url().describe("The API URL to get information about the languages of the repository."),
    merges_url: z.string().url().describe("The API URL to merge branches in the repository."),
    milestones_url: z.string().describe("A template for the API URL to get information about milestones of the repository."),
    name: z.string().describe("The name of the repository."),
    node_id: z.string().describe("The GraphQL identifier of the repository."),
    notifications_url: z.string().describe("A template for the API URL to get information about notifications on the repository."),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    private: z.boolean().describe("Whether the repository is private."),
    pulls_url: z.string().describe("A template for the API URL to get information about pull requests on the repository."),
    releases_url: z.string().describe("A template for the API URL to get information about releases on the repository."),
    stargazers_url: z.string().url().describe("The API URL to list the stargazers on the repository."),
    statuses_url: z.string().describe("A template for the API URL to get information about statuses of a commit."),
    subscribers_url: z.string().url().describe("The API URL to list the subscribers on the repository."),
    subscription_url: z.string().url().describe("The API URL to subscribe to notifications for this repository."),
    tags_url: z.string().url().describe("The API URL to get information about tags on the repository."),
    teams_url: z.string().url().describe("The API URL to list the teams on the repository."),
    trees_url: z.string().describe("A template for the API URL to create or retrieve a raw Git tree of the repository."),
    url: z.string().url().describe("The URL to get more information about the repository from the GitHub API."),
  }).describe("A GitHub repository."),
  rule: z.object({
    description: z.string().optional().describe("A short description of the rule used to detect the alert."),
    full_description: z.string().optional().describe("description of the rule used to detect the alert."),
    help: z.string().nullable().optional().describe("Detailed documentation for the rule as GitHub Flavored Markdown."),
    help_uri: z.string().nullable().optional().describe("A link to the documentation for the rule used to detect the alert."),
    id: z.string().nullable().optional().describe("A unique identifier for the rule used to detect the alert."),
    name: z.string().optional().describe("The name of the rule used to detect the alert."),
    security_severity_level: z.enum(["low", "medium", "high", "critical"]).nullable().optional().describe("The security severity of the alert."),
    severity: z.enum(["none", "note", "warning", "error"]).nullable().optional().describe("The severity of the alert."),
    tags: z.array(z.string()).nullable().optional().describe("A set of tags applicable for the rule."),
  }),
  state: z.enum(["open", "closed", "dismissed", "fixed"]).describe("State of a code scanning alert."),
  tool: z.object({
    guid: z.string().nullable().optional().describe("The GUID of the tool used to generate the code scanning analysis, if provided in the uploaded SARIF data."),
    name: z.string().optional().describe("The name of the tool used to generate the code scanning analysis."),
    version: z.string().nullable().optional().describe("The version of the tool used to generate the code scanning analysis."),
  }),
  updated_at: z.string().datetime().optional().describe("The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  url: z.string().url().describe("The REST API URL of the alert resource."),
}))

export const codeScanningListAlertsForOrg = pikkuSessionlessFunc({
  description: "Lists code scanning alerts for the default branch for all eligible repositories in an organization. Eligible repositories are repositories that are owned by organizations that you own or for which you are a security manager. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nTo use this endpoint, you must be an owner or security manager for the organization, and you must use an access token with the `repo` scope or `security_events` scope.\n\nFor public repositories, you may instead use the `public_repo` scope.\n\nGitHub Apps must have the `security_events` read permission to use this endpoint.",
  input: CodeScanningListAlertsForOrgInput,
  output: CodeScanningListAlertsForOrgOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/orgs/{org}/code-scanning/alerts", data) as any
  },
})
