// codespaces — Endpoints to manage Codespaces using the REST API.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { UnauthorizedError, ForbiddenError, NotFoundError, InternalServerError } from '@pikku/core/errors'

export const CodespacesStopForAuthenticatedUserInput = z.object({
  codespace_name: z.string().describe("The name of the codespace."),
})

export const CodespacesStopForAuthenticatedUserOutput = z.object({
  billable_owner: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).describe("A GitHub user."),
  created_at: z.string().datetime(),
  devcontainer_path: z.string().nullable().optional().describe("Path to devcontainer.json from repo root used to create Codespace."),
  display_name: z.string().nullable().optional().describe("Display name for this codespace."),
  environment_id: z.string().nullable().describe("UUID identifying this codespace's environment."),
  git_status: z.object({
    ahead: z.number().int().optional().describe("The number of commits the local repository is ahead of the remote."),
    behind: z.number().int().optional().describe("The number of commits the local repository is behind the remote."),
    has_uncommitted_changes: z.boolean().optional().describe("Whether the local repository has uncommitted changes."),
    has_unpushed_changes: z.boolean().optional().describe("Whether the local repository has unpushed changes."),
    ref: z.string().optional().describe("The current branch (or SHA if in detached HEAD state) of the local repository."),
  }).describe("Details about the codespace's git repository."),
  id: z.number().int(),
  idle_timeout_minutes: z.number().int().nullable().describe("The number of minutes of inactivity after which this codespace will be automatically stopped."),
  idle_timeout_notice: z.string().nullable().optional().describe("Text to show user when codespace idle timeout minutes has been overriden by an organization policy"),
  last_known_stop_notice: z.string().nullable().optional().describe("The text to display to a user when a codespace has been stopped for a potentially actionable reason."),
  last_used_at: z.string().datetime().describe("Last known time this codespace was started."),
  location: z.enum(["EastUs", "SouthEastAsia", "WestEurope", "WestUs2"]).describe("The Azure region where this codespace is located."),
  machine: z.object({
    cpus: z.number().int().describe("How many cores are available to the codespace."),
    display_name: z.string().describe("The display name of the machine includes cores, memory, and storage."),
    memory_in_bytes: z.number().int().describe("How much memory is available to the codespace."),
    name: z.string().describe("The name of the machine."),
    operating_system: z.string().describe("The operating system of the machine."),
    prebuild_availability: z.enum(["none", "ready", "in_progress"]).nullable().describe("Whether a prebuild is currently available when creating a codespace for this machine and repository. If a branch was not specified as a ref, the default branch will be assumed. Value will be \"null\" if prebuilds are not supported or prebuild availability could not be determined. Value will be \"none\" if no prebuild is available. Latest values \"ready\" and \"in_progress\" indicate the prebuild availability status."),
    storage_in_bytes: z.number().int().describe("How much storage is available to the codespace."),
  }).nullable().describe("A description of the machine powering a codespace."),
  machines_url: z.string().url().describe("API URL to access available alternate machine types for this codespace."),
  name: z.string().describe("Automatically generated name of this codespace."),
  owner: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).describe("A GitHub user."),
  pending_operation: z.boolean().nullable().optional().describe("Whether or not a codespace has a pending async operation. This would mean that the codespace is temporarily unavailable. The only thing that you can do with a codespace in this state is delete it."),
  pending_operation_disabled_reason: z.string().nullable().optional().describe("Text to show user when codespace is disabled by a pending operation"),
  prebuild: z.boolean().nullable().describe("Whether the codespace was created from a prebuild."),
  publish_url: z.string().url().nullable().optional().describe("API URL to publish this codespace to a new repository."),
  pulls_url: z.string().url().nullable().describe("API URL for the Pull Request associated with this codespace, if any."),
  recent_folders: z.array(z.string()),
  repository: z.object({
    allow_forking: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean().optional(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string().optional(),
    code_of_conduct: z.object({
      body: z.string().optional(),
      html_url: z.string().url().nullable(),
      key: z.string(),
      name: z.string(),
      url: z.string().url(),
    }).optional().describe("Code Of Conduct"),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable().optional(),
    default_branch: z.string().optional(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().optional(),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int().optional(),
    forks_count: z.number().int().optional(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string().optional(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean().optional(),
    has_issues: z.boolean().optional(),
    has_pages: z.boolean().optional(),
    has_projects: z.boolean().optional(),
    has_wiki: z.boolean().optional(),
    homepage: z.string().nullable().optional(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable().optional(),
    languages_url: z.string().url(),
    license: z.object({
      key: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      spdx_id: z.string().optional(),
      url: z.string().optional(),
    }).nullable().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().nullable().optional(),
    name: z.string(),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int().optional(),
    open_issues_count: z.number().int().optional(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean().optional(),
      maintain: z.boolean().optional(),
      pull: z.boolean().optional(),
      push: z.boolean().optional(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable().optional(),
    releases_url: z.string(),
    role_name: z.string().optional(),
    security_and_analysis: z.object({
      advanced_security: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning_push_protection: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
    }).nullable().optional(),
    size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    ssh_url: z.string().optional(),
    stargazers_count: z.number().int().optional(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().optional(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable().optional(),
    url: z.string().url(),
    visibility: z.string().optional(),
    watchers: z.number().int().optional(),
    watchers_count: z.number().int().optional(),
    web_commit_signoff_required: z.boolean().optional(),
  }).describe("Minimal Repository"),
  retention_expires_at: z.string().datetime().nullable().optional().describe("When a codespace will be auto-deleted based on the \"retention_period_minutes\" and \"last_used_at\""),
  retention_period_minutes: z.number().int().nullable().optional().describe("Duration in minutes after codespace has gone idle in which it will be deleted. Must be integer minutes between 0 and 43200 (30 days)."),
  runtime_constraints: z.object({
    allowed_port_privacy_settings: z.array(z.string()).nullable().optional().describe("The privacy settings a user can select from when forwarding a port."),
  }).optional(),
  start_url: z.string().url().describe("API URL to start this codespace."),
  state: z.enum(["Unknown", "Created", "Queued", "Provisioning", "Available", "Awaiting", "Unavailable", "Deleted", "Moved", "Shutdown", "Archived", "Starting", "ShuttingDown", "Failed", "Exporting", "Updating", "Rebuilding"]).describe("State of this codespace."),
  stop_url: z.string().url().describe("API URL to stop this codespace."),
  updated_at: z.string().datetime(),
  url: z.string().url().describe("API URL for this codespace."),
  web_url: z.string().url().describe("URL to access this codespace on the web."),
}).describe("A codespace.")

export const codespacesStopForAuthenticatedUser = pikkuSessionlessFunc({
  description: "Stops a user's codespace.\n\nYou must authenticate using an access token with the `codespace` scope to use this endpoint.\n\nGitHub Apps must have write access to the `codespaces_lifecycle_admin` repository permission to use this endpoint.",
  input: CodespacesStopForAuthenticatedUserInput,
  output: CodespacesStopForAuthenticatedUserOutput,
  errors: [UnauthorizedError, ForbiddenError, NotFoundError, InternalServerError],
  func: async ({ github }, data) => {
    return github.call("POST", "/user/codespaces/{codespace_name}/stop", data) as any
  },
})
