// gists — View, modify your gists.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError, UnprocessableContentError } from '@pikku/core/errors'

export const GistsUpdateInput = z.object({
  gist_id: z.string().describe("The unique identifier of the gist."),
  description: z.string().optional().describe("The description of the gist."),
  files: z.record(z.string(), z.union([z.unknown(), z.unknown(), z.record(z.string(), z.unknown())]).nullable()).optional().describe("The gist files to be updated, renamed, or deleted. Each `key` must match the current filename\n(including extension) of the targeted gist file. For example: `hello.py`.\n\nTo delete a file, set the whole file to null. For example: `hello.py : null`."),
})

export const GistsUpdateOutput = z.object({
  comments: z.number().int().optional(),
  comments_url: z.string().optional(),
  commits_url: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().nullable().optional(),
  files: z.record(z.string(), z.object({
    content: z.string().optional(),
    filename: z.string().optional(),
    language: z.string().optional(),
    raw_url: z.string().optional(),
    size: z.number().int().optional(),
    truncated: z.boolean().optional(),
    type: z.string().optional(),
  }).nullable()).optional(),
  fork_of: z.object({
    comments: z.number().int(),
    comments_url: z.string().url(),
    commits_url: z.string().url(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    files: z.record(z.string(), z.object({
      filename: z.string().optional(),
      language: z.string().optional(),
      raw_url: z.string().optional(),
      size: z.number().int().optional(),
      type: z.string().optional(),
    })),
    forks: z.array(z.unknown()).optional(),
    forks_url: z.string().url(),
    git_pull_url: z.string().url(),
    git_push_url: z.string().url(),
    history: z.array(z.unknown()).optional(),
    html_url: z.string().url(),
    id: z.string(),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().optional().describe("A GitHub user."),
    public: z.boolean(),
    truncated: z.boolean().optional(),
    updated_at: z.string().datetime(),
    url: z.string().url(),
    user: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
  }).nullable().optional().describe("Gist"),
  forks: z.array(z.object({
    created_at: z.string().datetime().optional(),
    id: z.string().optional(),
    updated_at: z.string().datetime().optional(),
    url: z.string().url().optional(),
    user: z.object({
      avatar_url: z.string().url(),
      bio: z.string().nullable(),
      blog: z.string().nullable(),
      collaborators: z.number().int().optional(),
      company: z.string().nullable(),
      created_at: z.string().datetime(),
      disk_usage: z.number().int().optional(),
      email: z.string().email().nullable(),
      events_url: z.string(),
      followers: z.number().int(),
      followers_url: z.string().url(),
      following: z.number().int(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      hireable: z.boolean().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      location: z.string().nullable(),
      login: z.string(),
      name: z.string().nullable(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      owned_private_repos: z.number().int().optional(),
      plan: z.object({
        collaborators: z.number().int(),
        name: z.string(),
        private_repos: z.number().int(),
        space: z.number().int(),
      }).optional(),
      private_gists: z.number().int().optional(),
      public_gists: z.number().int(),
      public_repos: z.number().int(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      suspended_at: z.string().datetime().nullable().optional(),
      total_private_repos: z.number().int().optional(),
      twitter_username: z.string().nullable().optional(),
      type: z.string(),
      updated_at: z.string().datetime(),
      url: z.string().url(),
    }).optional().describe("Public User"),
  })).nullable().optional(),
  forks_url: z.string().optional(),
  git_pull_url: z.string().optional(),
  git_push_url: z.string().optional(),
  history: z.array(z.object({
    change_status: z.object({
      additions: z.number().int().optional(),
      deletions: z.number().int().optional(),
      total: z.number().int().optional(),
    }).optional(),
    committed_at: z.string().datetime().optional(),
    url: z.string().url().optional(),
    user: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().optional().describe("A GitHub user."),
    version: z.string().optional(),
  })).nullable().optional(),
  html_url: z.string().optional(),
  id: z.string().optional(),
  node_id: z.string().optional(),
  owner: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).optional().describe("A GitHub user."),
  public: z.boolean().optional(),
  truncated: z.boolean().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
  user: z.string().nullable().optional(),
}).describe("Gist Simple")

export const gistsUpdate = pikkuSessionlessFunc({
  description: "Allows you to update a gist's description and to update, delete, or rename gist files. Files from the previous version of the gist that aren't explicitly changed during an edit are unchanged.",
  input: GistsUpdateInput,
  output: GistsUpdateOutput,
  errors: [NotFoundError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("PATCH", "/gists/{gist_id}", data) as any
  },
})
