// issues — Interact with GitHub Issues.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const IssuesGetCommentInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  comment_id: z.number().int().describe("The unique identifier of the comment."),
})

export const IssuesGetCommentOutput = z.object({
  author_association: z.enum(["COLLABORATOR", "CONTRIBUTOR", "FIRST_TIMER", "FIRST_TIME_CONTRIBUTOR", "MANNEQUIN", "MEMBER", "NONE", "OWNER"]).describe("How the author is associated with the repository."),
  body: z.string().optional().describe("Contents of the issue comment"),
  body_html: z.string().optional(),
  body_text: z.string().optional(),
  created_at: z.string().datetime(),
  html_url: z.string().url(),
  id: z.number().int().describe("Unique identifier of the issue comment"),
  issue_url: z.string().url(),
  node_id: z.string(),
  performed_via_github_app: z.object({
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    events: z.array(z.string()).describe("The list of events for the GitHub app"),
    external_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the GitHub app"),
    installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
    name: z.string().describe("The name of the GitHub app"),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    pem: z.string().optional(),
    permissions: z.object({
      checks: z.string().optional(),
      contents: z.string().optional(),
      deployments: z.string().optional(),
      issues: z.string().optional(),
      metadata: z.string().optional(),
    }).describe("The set of permissions for the GitHub app"),
    slug: z.string().optional().describe("The slug name of the GitHub app"),
    updated_at: z.string().datetime(),
    webhook_secret: z.string().nullable().optional(),
  }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
  reactions: z.object({
    "+1": z.number().int(),
    "-1": z.number().int(),
    confused: z.number().int(),
    eyes: z.number().int(),
    heart: z.number().int(),
    hooray: z.number().int(),
    laugh: z.number().int(),
    rocket: z.number().int(),
    total_count: z.number().int(),
    url: z.string().url(),
  }).optional(),
  updated_at: z.string().datetime(),
  url: z.string().url().describe("URL for the issue comment"),
  user: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
}).describe("Comments provide a way for people to collaborate on an issue.")

export const issuesGetComment = pikkuSessionlessFunc({
  input: IssuesGetCommentInput,
  output: IssuesGetCommentOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/issues/comments/{comment_id}", data) as any
  },
})
