// orgs — Interact with GitHub Orgs.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ConflictError, UnprocessableContentError } from '@pikku/core/errors'

export const OrgsUpdateInput = z.object({
  org: z.string().describe("The organization name. The name is not case sensitive."),
  advanced_security_enabled_for_new_repositories: z.boolean().optional().describe("Whether GitHub Advanced Security is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  billing_email: z.string().optional().describe("Billing email address. This address is not publicized."),
  blog: z.string().optional(),
  company: z.string().optional().describe("The company name."),
  default_repository_permission: z.enum(["read", "write", "admin", "none"]).optional().default("read").describe("Default permission level members have for organization repositories."),
  dependabot_alerts_enabled_for_new_repositories: z.boolean().optional().describe("Whether Dependabot alerts is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  dependabot_security_updates_enabled_for_new_repositories: z.boolean().optional().describe("Whether Dependabot security updates is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  dependency_graph_enabled_for_new_repositories: z.boolean().optional().describe("Whether dependency graph is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  description: z.string().optional().describe("The description of the company."),
  email: z.string().optional().describe("The publicly visible email address."),
  has_organization_projects: z.boolean().optional().describe("Whether an organization can use organization projects."),
  has_repository_projects: z.boolean().optional().describe("Whether repositories that belong to the organization can use repository projects."),
  location: z.string().optional().describe("The location."),
  members_allowed_repository_creation_type: z.enum(["all", "private", "none"]).optional().describe("Specifies which types of repositories non-admin organization members can create. `private` is only available to repositories that are part of an organization on GitHub Enterprise Cloud. \n**Note:** This parameter is deprecated and will be removed in the future. Its return value ignores internal repositories. Using this parameter overrides values set in `members_can_create_repositories`. See the parameter deprecation notice in the operation description for details."),
  members_can_create_internal_repositories: z.boolean().optional().describe("Whether organization members can create internal repositories, which are visible to all enterprise members. You can only allow members to create internal repositories if your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation."),
  members_can_create_pages: z.boolean().optional().default(true).describe("Whether organization members can create GitHub Pages sites. Existing published sites will not be impacted."),
  members_can_create_private_pages: z.boolean().optional().default(true).describe("Whether organization members can create private GitHub Pages sites. Existing published sites will not be impacted."),
  members_can_create_private_repositories: z.boolean().optional().describe("Whether organization members can create private repositories, which are visible to organization members with permission. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation."),
  members_can_create_public_pages: z.boolean().optional().default(true).describe("Whether organization members can create public GitHub Pages sites. Existing published sites will not be impacted."),
  members_can_create_public_repositories: z.boolean().optional().describe("Whether organization members can create public repositories, which are visible to anyone. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation."),
  members_can_create_repositories: z.boolean().optional().default(true).describe("Whether of non-admin organization members can create repositories. **Note:** A parameter can override this parameter. See `members_allowed_repository_creation_type` in this table for details."),
  members_can_fork_private_repositories: z.boolean().optional().default(false).describe("Whether organization members can fork private organization repositories."),
  name: z.string().optional().describe("The shorthand name of the company."),
  secret_scanning_enabled_for_new_repositories: z.boolean().optional().describe("Whether secret scanning is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  secret_scanning_push_protection_custom_link: z.string().optional().describe("If `secret_scanning_push_protection_custom_link_enabled` is true, the URL that will be displayed to contributors who are blocked from pushing a secret."),
  secret_scanning_push_protection_custom_link_enabled: z.boolean().optional().describe("Whether a custom link is shown to contributors who are blocked from pushing a secret by push protection."),
  secret_scanning_push_protection_enabled_for_new_repositories: z.boolean().optional().describe("Whether secret scanning push protection is automatically enabled for new repositories.\n\nTo use this parameter, you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository. For more information, see \"[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization).\"\n\nYou can check which security and analysis features are currently enabled by using a `GET /orgs/{org}` request."),
  twitter_username: z.string().optional().describe("The Twitter username of the company."),
  web_commit_signoff_required: z.boolean().optional().default(false).describe("Whether contributors to organization repositories are required to sign off on commits they make through GitHub's web interface."),
})

export const OrgsUpdateOutput = z.object({
  advanced_security_enabled_for_new_repositories: z.boolean().optional().describe("Whether GitHub Advanced Security is enabled for new repositories and repositories transferred to this organization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  avatar_url: z.string(),
  billing_email: z.string().email().nullable().optional(),
  blog: z.string().url().optional(),
  collaborators: z.number().int().nullable().optional(),
  company: z.string().optional(),
  created_at: z.string().datetime(),
  default_repository_permission: z.string().nullable().optional(),
  dependabot_alerts_enabled_for_new_repositories: z.boolean().optional().describe("Whether GitHub Advanced Security is automatically enabled for new repositories and repositories transferred to\nthis organization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  dependabot_security_updates_enabled_for_new_repositories: z.boolean().optional().describe("Whether dependabot security updates are automatically enabled for new repositories and repositories transferred\nto this organization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  dependency_graph_enabled_for_new_repositories: z.boolean().optional().describe("Whether dependency graph is automatically enabled for new repositories and repositories transferred to this\norganization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  description: z.string().nullable(),
  disk_usage: z.number().int().nullable().optional(),
  email: z.string().email().optional(),
  events_url: z.string().url(),
  followers: z.number().int(),
  following: z.number().int(),
  has_organization_projects: z.boolean(),
  has_repository_projects: z.boolean(),
  hooks_url: z.string(),
  html_url: z.string().url(),
  id: z.number().int(),
  is_verified: z.boolean().optional(),
  issues_url: z.string(),
  location: z.string().optional(),
  login: z.string(),
  members_allowed_repository_creation_type: z.string().optional(),
  members_can_create_internal_repositories: z.boolean().optional(),
  members_can_create_pages: z.boolean().optional(),
  members_can_create_private_pages: z.boolean().optional(),
  members_can_create_private_repositories: z.boolean().optional(),
  members_can_create_public_pages: z.boolean().optional(),
  members_can_create_public_repositories: z.boolean().optional(),
  members_can_create_repositories: z.boolean().nullable().optional(),
  members_can_fork_private_repositories: z.boolean().nullable().optional(),
  members_url: z.string(),
  name: z.string().optional(),
  node_id: z.string(),
  owned_private_repos: z.number().int().optional(),
  plan: z.object({
    filled_seats: z.number().int().optional(),
    name: z.string(),
    private_repos: z.number().int(),
    seats: z.number().int().optional(),
    space: z.number().int(),
  }).optional(),
  private_gists: z.number().int().nullable().optional(),
  public_gists: z.number().int(),
  public_members_url: z.string(),
  public_repos: z.number().int(),
  repos_url: z.string().url(),
  secret_scanning_enabled_for_new_repositories: z.boolean().optional().describe("Whether secret scanning is automatically enabled for new repositories and repositories transferred to this\norganization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  secret_scanning_push_protection_custom_link: z.string().nullable().optional().describe("An optional URL string to display to contributors who are blocked from pushing a secret."),
  secret_scanning_push_protection_custom_link_enabled: z.boolean().optional().describe("Whether a custom link is shown to contributors who are blocked from pushing a secret by push protection."),
  secret_scanning_push_protection_enabled_for_new_repositories: z.boolean().optional().describe("Whether secret scanning push protection is automatically enabled for new repositories and repositories\ntransferred to this organization.\n\nThis field is only visible to organization owners or members of a team with the security manager role."),
  total_private_repos: z.number().int().optional(),
  twitter_username: z.string().nullable().optional(),
  two_factor_requirement_enabled: z.boolean().nullable().optional(),
  type: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url(),
  web_commit_signoff_required: z.boolean().optional(),
}).describe("Organization Full")

export const orgsUpdate = pikkuSessionlessFunc({
  description: "**Parameter Deprecation Notice:** GitHub will replace and discontinue `members_allowed_repository_creation_type` in favor of more granular permissions. The new input parameters are `members_can_create_public_repositories`, `members_can_create_private_repositories` for all organizations and `members_can_create_internal_repositories` for organizations associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. For more information, see the [blog post](https://developer.github.com/changes/2019-12-03-internal-visibility-changes).\n\nEnables an authenticated organization owner with the `admin:org` scope to update the organization's profile and member privileges.",
  input: OrgsUpdateInput,
  output: OrgsUpdateOutput,
  errors: [ConflictError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("PATCH", "/orgs/{org}", data) as any
  },
})
