// packages — Manage packages for authenticated users and organizations.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const PackagesGetPackageForOrganizationInput = z.object({
  package_type: z.enum(["npm", "maven", "rubygems", "docker", "nuget", "container"]).describe("The type of supported package. Packages in GitHub's Gradle registry have the type `maven`. Docker images pushed to GitHub's Container registry (`ghcr.io`) have the type `container`. You can use the type `docker` to find images that were pushed to GitHub's Docker registry (`docker.pkg.github.com`), even if these have now been migrated to the Container registry."),
  package_name: z.string().describe("The name of the package."),
  org: z.string().describe("The organization name. The name is not case sensitive."),
})

export const PackagesGetPackageForOrganizationOutput = z.object({
  created_at: z.string().datetime(),
  html_url: z.string(),
  id: z.number().int().describe("Unique identifier of the package."),
  name: z.string().describe("The name of the package."),
  owner: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().optional().describe("A GitHub user."),
  package_type: z.enum(["npm", "maven", "rubygems", "docker", "nuget", "container"]),
  repository: z.object({
    allow_forking: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean().optional(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string().optional(),
    code_of_conduct: z.object({
      body: z.string().optional(),
      html_url: z.string().url().nullable(),
      key: z.string(),
      name: z.string(),
      url: z.string().url(),
    }).optional().describe("Code Of Conduct"),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable().optional(),
    default_branch: z.string().optional(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().optional(),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int().optional(),
    forks_count: z.number().int().optional(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string().optional(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean().optional(),
    has_issues: z.boolean().optional(),
    has_pages: z.boolean().optional(),
    has_projects: z.boolean().optional(),
    has_wiki: z.boolean().optional(),
    homepage: z.string().nullable().optional(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable().optional(),
    languages_url: z.string().url(),
    license: z.object({
      key: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      spdx_id: z.string().optional(),
      url: z.string().optional(),
    }).nullable().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().nullable().optional(),
    name: z.string(),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int().optional(),
    open_issues_count: z.number().int().optional(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean().optional(),
      maintain: z.boolean().optional(),
      pull: z.boolean().optional(),
      push: z.boolean().optional(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable().optional(),
    releases_url: z.string(),
    role_name: z.string().optional(),
    security_and_analysis: z.object({
      advanced_security: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning_push_protection: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
    }).nullable().optional(),
    size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    ssh_url: z.string().optional(),
    stargazers_count: z.number().int().optional(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().optional(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable().optional(),
    url: z.string().url(),
    visibility: z.string().optional(),
    watchers: z.number().int().optional(),
    watchers_count: z.number().int().optional(),
    web_commit_signoff_required: z.boolean().optional(),
  }).nullable().optional().describe("Minimal Repository"),
  updated_at: z.string().datetime(),
  url: z.string(),
  version_count: z.number().int().describe("The number of versions of the package."),
  visibility: z.enum(["private", "public"]),
}).describe("A software package")

export const packagesGetPackageForOrganization = pikkuSessionlessFunc({
  description: "Gets a specific package in an organization.\n\nTo use this endpoint, you must authenticate using an access token with the `read:packages` scope. If the `package_type` belongs to a GitHub Packages registry that only supports repository-scoped permissions, your token must also include the `repo` scope. For the list of GitHub Packages registries that only support repository-scoped permissions, see \"[About permissions for GitHub Packages](https://docs.github.com/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages).\"",
  input: PackagesGetPackageForOrganizationInput,
  output: PackagesGetPackageForOrganizationOutput,
  func: async ({ github }, data) => {
    return github.call("GET", "/orgs/{org}/packages/{package_type}/{package_name}", data) as any
  },
})
