// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const ReposGetReleaseInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  release_id: z.number().int().describe("The unique identifier of the release."),
})

export const ReposGetReleaseOutput = z.object({
  assets: z.array(z.object({
    browser_download_url: z.string().url(),
    content_type: z.string(),
    created_at: z.string().datetime(),
    download_count: z.number().int(),
    id: z.number().int(),
    label: z.string().nullable(),
    name: z.string().describe("The file name of the asset."),
    node_id: z.string(),
    size: z.number().int(),
    state: z.enum(["uploaded", "open"]).describe("State of the release asset."),
    updated_at: z.string().datetime(),
    uploader: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    url: z.string().url(),
  })),
  assets_url: z.string().url(),
  author: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).describe("A GitHub user."),
  body: z.string().nullable().optional(),
  body_html: z.string().optional(),
  body_text: z.string().optional(),
  created_at: z.string().datetime(),
  discussion_url: z.string().url().optional().describe("The URL of the release discussion."),
  draft: z.boolean().describe("true to create a draft (unpublished) release, false to create a published one."),
  html_url: z.string().url(),
  id: z.number().int(),
  mentions_count: z.number().int().optional(),
  name: z.string().nullable(),
  node_id: z.string(),
  prerelease: z.boolean().describe("Whether to identify the release as a prerelease or a full release."),
  published_at: z.string().datetime().nullable(),
  reactions: z.object({
    "+1": z.number().int(),
    "-1": z.number().int(),
    confused: z.number().int(),
    eyes: z.number().int(),
    heart: z.number().int(),
    hooray: z.number().int(),
    laugh: z.number().int(),
    rocket: z.number().int(),
    total_count: z.number().int(),
    url: z.string().url(),
  }).optional(),
  tag_name: z.string().describe("The name of the tag."),
  tarball_url: z.string().url().nullable(),
  target_commitish: z.string().describe("Specifies the commitish value that determines where the Git tag is created from."),
  upload_url: z.string(),
  url: z.string().url(),
  zipball_url: z.string().url().nullable(),
}).describe("A release.")

export const reposGetRelease = pikkuSessionlessFunc({
  description: "**Note:** This returns an `upload_url` key corresponding to the endpoint for uploading release assets. This key is a [hypermedia resource](https://docs.github.com/rest/overview/resources-in-the-rest-api#hypermedia).",
  input: ReposGetReleaseInput,
  output: ReposGetReleaseOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/releases/{release_id}", data) as any
  },
})
