// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ForbiddenError, NotFoundError, UnprocessableContentError } from '@pikku/core/errors'

export const ReposUpdateBranchProtectionInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  branch: z.string().describe("The name of the branch. Cannot contain wildcard characters. To use wildcard characters in branch names, use [the GraphQL API](https://docs.github.com/graphql)."),
  allow_deletions: z.boolean().optional().describe("Allows deletion of the protected branch by anyone with write access to the repository. Set to `false` to prevent deletion of the protected branch. Default: `false`. For more information, see \"[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)\" in the GitHub Help documentation."),
  allow_force_pushes: z.boolean().nullable().optional().describe("Permits force pushes to the protected branch by anyone with write access to the repository. Set to `true` to allow force pushes. Set to `false` or `null` to block force pushes. Default: `false`. For more information, see \"[Enabling force pushes to a protected branch](https://docs.github.com/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch)\" in the GitHub Help documentation.\""),
  allow_fork_syncing: z.boolean().optional().default(false).describe("Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing. Default: `false`."),
  block_creations: z.boolean().optional().describe("If set to `true`, the `restrictions` branch protection settings which limits who can push will also block pushes which create new branches, unless the push is initiated by a user, team, or app which has the ability to push. Set to `true` to restrict new branch creation. Default: `false`."),
  enforce_admins: z.boolean().nullable().describe("Enforce all configured restrictions for administrators. Set to `true` to enforce required status checks for repository administrators. Set to `null` to disable."),
  lock_branch: z.boolean().optional().default(false).describe("Whether to set the branch as read-only. If this is true, users will not be able to push to the branch. Default: `false`."),
  required_conversation_resolution: z.boolean().optional().describe("Requires all conversations on code to be resolved before a pull request can be merged into a branch that matches this rule. Set to `false` to disable. Default: `false`."),
  required_linear_history: z.boolean().optional().describe("Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to `true` to enforce a linear commit history. Set to `false` to disable a linear commit Git history. Your repository must allow squash merging or rebase merging before you can enable a linear commit history. Default: `false`. For more information, see \"[Requiring a linear commit history](https://docs.github.com/github/administering-a-repository/requiring-a-linear-commit-history)\" in the GitHub Help documentation."),
  required_pull_request_reviews: z.object({
  bypass_pull_request_allowances: z.object({
    apps: z.array(z.string()).optional().describe("The list of app `slug`s allowed to bypass pull request requirements."),
    teams: z.array(z.string()).optional().describe("The list of team `slug`s allowed to bypass pull request requirements."),
    users: z.array(z.string()).optional().describe("The list of user `login`s allowed to bypass pull request requirements."),
  }).optional().describe("Allow specific users, teams, or apps to bypass pull request requirements."),
  dismiss_stale_reviews: z.boolean().optional().describe("Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit."),
  dismissal_restrictions: z.object({
    apps: z.array(z.string()).optional().describe("The list of app `slug`s with dismissal access"),
    teams: z.array(z.string()).optional().describe("The list of team `slug`s with dismissal access"),
    users: z.array(z.string()).optional().describe("The list of user `login`s with dismissal access"),
  }).optional().describe("Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories."),
  require_code_owner_reviews: z.boolean().optional().describe("Blocks merging pull requests until [code owners](https://docs.github.com/articles/about-code-owners/) review them."),
  require_last_push_approval: z.boolean().optional().default(false).describe("Whether the most recent push must be approved by someone other than the person who pushed it. Default: `false`."),
  required_approving_review_count: z.number().int().optional().describe("Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers."),
}).nullable().describe("Require at least one approving review on a pull request, before merging. Set to `null` to disable."),
  required_status_checks: z.object({
  checks: z.array(z.object({
    app_id: z.number().int().optional().describe("The ID of the GitHub App that must provide this check. Omit this field to automatically select the GitHub App that has recently provided this check, or any app if it was not set by a GitHub App. Pass -1 to explicitly allow any app to set the status."),
    context: z.string().describe("The name of the required check"),
  })).optional().describe("The list of status checks to require in order to merge into this branch."),
  contexts: z.array(z.string()).describe("**Deprecated**: The list of status checks to require in order to merge into this branch. If any of these checks have recently been set by a particular GitHub App, they will be required to come from that app in future for the branch to merge. Use `checks` instead of `contexts` for more fine-grained control.\n"),
  strict: z.boolean().describe("Require branches to be up to date before merging."),
}).nullable().describe("Require status checks to pass before merging. Set to `null` to disable."),
  restrictions: z.object({
  apps: z.array(z.string()).optional().describe("The list of app `slug`s with push access"),
  teams: z.array(z.string()).describe("The list of team `slug`s with push access"),
  users: z.array(z.string()).describe("The list of user `login`s with push access"),
}).nullable().describe("Restrict who can push to the protected branch. User, app, and team `restrictions` are only available for organization-owned repositories. Set to `null` to disable."),
})

export const ReposUpdateBranchProtectionOutput = z.object({
  allow_deletions: z.object({
    enabled: z.boolean(),
  }).optional(),
  allow_force_pushes: z.object({
    enabled: z.boolean(),
  }).optional(),
  allow_fork_syncing: z.object({
    enabled: z.boolean().optional().default(false),
  }).optional().describe("Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing."),
  block_creations: z.object({
    enabled: z.boolean(),
  }).optional(),
  enforce_admins: z.object({
    enabled: z.boolean(),
    url: z.string().url(),
  }).optional(),
  lock_branch: z.object({
    enabled: z.boolean().optional().default(false),
  }).optional().describe("Whether to set the branch as read-only. If this is true, users will not be able to push to the branch."),
  required_conversation_resolution: z.object({
    enabled: z.boolean().optional(),
  }).optional(),
  required_linear_history: z.object({
    enabled: z.boolean(),
  }).optional(),
  required_pull_request_reviews: z.object({
    bypass_pull_request_allowances: z.object({
      apps: z.array(z.object({
        client_id: z.string().optional(),
        client_secret: z.string().optional(),
        created_at: z.string().datetime(),
        description: z.string().nullable(),
        events: z.array(z.string()).describe("The list of events for the GitHub app"),
        external_url: z.string().url(),
        html_url: z.string().url(),
        id: z.number().int().describe("Unique identifier of the GitHub app"),
        installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
        name: z.string().describe("The name of the GitHub app"),
        node_id: z.string(),
        owner: z.object({
          avatar_url: z.string().url(),
          email: z.string().nullable().optional(),
          events_url: z.string(),
          followers_url: z.string().url(),
          following_url: z.string(),
          gists_url: z.string(),
          gravatar_id: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          login: z.string(),
          name: z.string().nullable().optional(),
          node_id: z.string(),
          organizations_url: z.string().url(),
          received_events_url: z.string().url(),
          repos_url: z.string().url(),
          site_admin: z.boolean(),
          starred_at: z.string().optional(),
          starred_url: z.string(),
          subscriptions_url: z.string().url(),
          type: z.string(),
          url: z.string().url(),
        }).nullable().describe("A GitHub user."),
        pem: z.string().optional(),
        permissions: z.object({
          checks: z.string().optional(),
          contents: z.string().optional(),
          deployments: z.string().optional(),
          issues: z.string().optional(),
          metadata: z.string().optional(),
        }).describe("The set of permissions for the GitHub app"),
        slug: z.string().optional().describe("The slug name of the GitHub app"),
        updated_at: z.string().datetime(),
        webhook_secret: z.string().nullable().optional(),
      })).optional(),
      teams: z.array(z.object({
        description: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        members_url: z.string(),
        name: z.string(),
        node_id: z.string(),
        parent: z.object({
          description: z.string().nullable().describe("Description of the team"),
          html_url: z.string().url(),
          id: z.number().int().describe("Unique identifier of the team"),
          ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
          members_url: z.string(),
          name: z.string().describe("Name of the team"),
          node_id: z.string(),
          permission: z.string().describe("Permission that the team will have for its repositories"),
          privacy: z.string().optional().describe("The level of privacy this team should have"),
          repositories_url: z.string().url(),
          slug: z.string(),
          url: z.string().url().describe("URL for the team"),
        }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
        permission: z.string(),
        permissions: z.object({
          admin: z.boolean(),
          maintain: z.boolean(),
          pull: z.boolean(),
          push: z.boolean(),
          triage: z.boolean(),
        }).optional(),
        privacy: z.string().optional(),
        repositories_url: z.string().url(),
        slug: z.string(),
        url: z.string().url(),
      })),
      users: z.array(z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      })),
    }).optional(),
    dismiss_stale_reviews: z.boolean().optional(),
    dismissal_restrictions: z.object({
      apps: z.array(z.object({
        client_id: z.string().optional(),
        client_secret: z.string().optional(),
        created_at: z.string().datetime(),
        description: z.string().nullable(),
        events: z.array(z.string()).describe("The list of events for the GitHub app"),
        external_url: z.string().url(),
        html_url: z.string().url(),
        id: z.number().int().describe("Unique identifier of the GitHub app"),
        installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
        name: z.string().describe("The name of the GitHub app"),
        node_id: z.string(),
        owner: z.object({
          avatar_url: z.string().url(),
          email: z.string().nullable().optional(),
          events_url: z.string(),
          followers_url: z.string().url(),
          following_url: z.string(),
          gists_url: z.string(),
          gravatar_id: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          login: z.string(),
          name: z.string().nullable().optional(),
          node_id: z.string(),
          organizations_url: z.string().url(),
          received_events_url: z.string().url(),
          repos_url: z.string().url(),
          site_admin: z.boolean(),
          starred_at: z.string().optional(),
          starred_url: z.string(),
          subscriptions_url: z.string().url(),
          type: z.string(),
          url: z.string().url(),
        }).nullable().describe("A GitHub user."),
        pem: z.string().optional(),
        permissions: z.object({
          checks: z.string().optional(),
          contents: z.string().optional(),
          deployments: z.string().optional(),
          issues: z.string().optional(),
          metadata: z.string().optional(),
        }).describe("The set of permissions for the GitHub app"),
        slug: z.string().optional().describe("The slug name of the GitHub app"),
        updated_at: z.string().datetime(),
        webhook_secret: z.string().nullable().optional(),
      })).optional(),
      teams: z.array(z.object({
        description: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        members_url: z.string(),
        name: z.string(),
        node_id: z.string(),
        parent: z.object({
          description: z.string().nullable().describe("Description of the team"),
          html_url: z.string().url(),
          id: z.number().int().describe("Unique identifier of the team"),
          ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
          members_url: z.string(),
          name: z.string().describe("Name of the team"),
          node_id: z.string(),
          permission: z.string().describe("Permission that the team will have for its repositories"),
          privacy: z.string().optional().describe("The level of privacy this team should have"),
          repositories_url: z.string().url(),
          slug: z.string(),
          url: z.string().url().describe("URL for the team"),
        }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
        permission: z.string(),
        permissions: z.object({
          admin: z.boolean(),
          maintain: z.boolean(),
          pull: z.boolean(),
          push: z.boolean(),
          triage: z.boolean(),
        }).optional(),
        privacy: z.string().optional(),
        repositories_url: z.string().url(),
        slug: z.string(),
        url: z.string().url(),
      })),
      teams_url: z.string().url(),
      url: z.string().url(),
      users: z.array(z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      })),
      users_url: z.string().url(),
    }).optional(),
    require_code_owner_reviews: z.boolean().optional(),
    require_last_push_approval: z.boolean().optional().default(false).describe("Whether the most recent push must be approved by someone other than the person who pushed it."),
    required_approving_review_count: z.number().int().optional(),
    url: z.string().url(),
  }).optional(),
  required_signatures: z.object({
    enabled: z.boolean(),
    url: z.string().url(),
  }).optional(),
  required_status_checks: z.object({
    checks: z.array(z.object({
      app_id: z.number().int().nullable(),
      context: z.string(),
    })),
    contexts: z.array(z.string()),
    contexts_url: z.string().url(),
    strict: z.boolean(),
    url: z.string().url(),
  }).optional().describe("Status Check Policy"),
  restrictions: z.object({
    apps: z.array(z.object({
      created_at: z.string().optional(),
      description: z.string().optional(),
      events: z.array(z.string()).optional(),
      external_url: z.string().optional(),
      html_url: z.string().optional(),
      id: z.number().int().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      owner: z.object({
        avatar_url: z.string().optional(),
        description: z.string().optional(),
        events_url: z.string().optional(),
        followers_url: z.string().optional(),
        following_url: z.string().optional(),
        gists_url: z.string().optional(),
        gravatar_id: z.string().optional(),
        hooks_url: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        issues_url: z.string().optional(),
        login: z.string().optional(),
        members_url: z.string().optional(),
        node_id: z.string().optional(),
        organizations_url: z.string().optional(),
        public_members_url: z.string().optional(),
        received_events_url: z.string().optional(),
        repos_url: z.string().optional(),
        site_admin: z.boolean().optional(),
        starred_url: z.string().optional(),
        subscriptions_url: z.string().optional(),
        type: z.string().optional(),
        url: z.string().optional(),
      }).optional(),
      permissions: z.object({
        contents: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
        single_file: z.string().optional(),
      }).optional(),
      slug: z.string().optional(),
      updated_at: z.string().optional(),
    })),
    apps_url: z.string().url(),
    teams: z.array(z.object({
      description: z.string().nullable().optional(),
      html_url: z.string().optional(),
      id: z.number().int().optional(),
      members_url: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      parent: z.string().nullable().optional(),
      permission: z.string().optional(),
      privacy: z.string().optional(),
      repositories_url: z.string().optional(),
      slug: z.string().optional(),
      url: z.string().optional(),
    })),
    teams_url: z.string().url(),
    url: z.string().url(),
    users: z.array(z.object({
      avatar_url: z.string().optional(),
      events_url: z.string().optional(),
      followers_url: z.string().optional(),
      following_url: z.string().optional(),
      gists_url: z.string().optional(),
      gravatar_id: z.string().optional(),
      html_url: z.string().optional(),
      id: z.number().int().optional(),
      login: z.string().optional(),
      node_id: z.string().optional(),
      organizations_url: z.string().optional(),
      received_events_url: z.string().optional(),
      repos_url: z.string().optional(),
      site_admin: z.boolean().optional(),
      starred_url: z.string().optional(),
      subscriptions_url: z.string().optional(),
      type: z.string().optional(),
      url: z.string().optional(),
    })),
    users_url: z.string().url(),
  }).optional().describe("Branch Restriction Policy"),
  url: z.string().url(),
}).describe("Branch protections protect branches")

export const reposUpdateBranchProtection = pikkuSessionlessFunc({
  description: "Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.\n\nProtecting a branch requires admin or owner permissions to the repository.\n\n**Note**: Passing new arrays of `users` and `teams` replaces their previous values.\n\n**Note**: The list of users, apps, and teams in total is limited to 100 items.",
  input: ReposUpdateBranchProtectionInput,
  output: ReposUpdateBranchProtectionOutput,
  errors: [ForbiddenError, NotFoundError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("PUT", "/repos/{owner}/{repo}/branches/{branch}/protection", data) as any
  },
})
