// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ConflictError, UnprocessableContentError } from '@pikku/core/errors'

export const ReposCreateDeploymentInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  auto_merge: z.boolean().optional().default(true).describe("Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch."),
  description: z.string().nullable().optional().default("").describe("Short description of the deployment."),
  environment: z.string().optional().default("production").describe("Name for the target deployment environment (e.g., `production`, `staging`, `qa`)."),
  payload: z.union([z.record(z.string(), z.unknown()), z.string()]).optional(),
  production_environment: z.boolean().optional().describe("Specifies if the given environment is one that end-users directly interact with. Default: `true` when `environment` is `production` and `false` otherwise."),
  ref: z.string().describe("The ref to deploy. This can be a branch, tag, or SHA."),
  required_contexts: z.array(z.string()).optional().describe("The [status](https://docs.github.com/rest/commits/statuses) contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass an empty array. Defaults to all unique contexts."),
  task: z.string().optional().default("deploy").describe("Specifies a task to execute (e.g., `deploy` or `deploy:migrations`)."),
  transient_environment: z.boolean().optional().default(false).describe("Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future. Default: `false`"),
})

export const ReposCreateDeploymentOutput = z.object({
  created_at: z.string().datetime(),
  creator: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  description: z.string().nullable(),
  environment: z.string().describe("Name for the target deployment environment."),
  id: z.number().int().describe("Unique identifier of the deployment"),
  node_id: z.string(),
  original_environment: z.string().optional(),
  payload: z.union([z.record(z.string(), z.unknown()), z.string()]),
  performed_via_github_app: z.object({
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    events: z.array(z.string()).describe("The list of events for the GitHub app"),
    external_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the GitHub app"),
    installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
    name: z.string().describe("The name of the GitHub app"),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    pem: z.string().optional(),
    permissions: z.object({
      checks: z.string().optional(),
      contents: z.string().optional(),
      deployments: z.string().optional(),
      issues: z.string().optional(),
      metadata: z.string().optional(),
    }).describe("The set of permissions for the GitHub app"),
    slug: z.string().optional().describe("The slug name of the GitHub app"),
    updated_at: z.string().datetime(),
    webhook_secret: z.string().nullable().optional(),
  }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
  production_environment: z.boolean().optional().describe("Specifies if the given environment is one that end-users directly interact with. Default: false."),
  ref: z.string().describe("The ref to deploy. This can be a branch, tag, or sha."),
  repository_url: z.string().url(),
  sha: z.string(),
  statuses_url: z.string().url(),
  task: z.string().describe("Parameter to specify a task to execute"),
  transient_environment: z.boolean().optional().describe("Specifies if the given environment is will no longer exist at some point in the future. Default: false."),
  updated_at: z.string().datetime(),
  url: z.string().url(),
}).describe("A request for a specific ref(branch,sha,tag) to be deployed")

export const reposCreateDeployment = pikkuSessionlessFunc({
  description: "Deployments offer a few configurable parameters with certain defaults.\n\nThe `ref` parameter can be any named branch, tag, or SHA. At GitHub we often deploy branches and verify them\nbefore we merge a pull request.\n\nThe `environment` parameter allows deployments to be issued to different runtime environments. Teams often have\nmultiple environments for verifying their applications, such as `production`, `staging`, and `qa`. This parameter\nmakes it easier to track which environments have requested deployments. The default environment is `production`.\n\nThe `auto_merge` parameter is used to ensure that the requested ref is not behind the repository's default branch. If\nthe ref _is_ behind the default branch for the repository, we will attempt to merge it for you. If the merge succeeds,\nthe API will return a successful merge commit. If merge conflicts prevent the merge from succeeding, the API will\nreturn a failure response.\n\nBy default, [commit statuses](https://docs.github.com/rest/commits/statuses) for every submitted context must be in a `success`\nstate. The `required_contexts` parameter allows you to specify a subset of contexts that must be `success`, or to\nspecify contexts that have not yet been submitted. You are not required to use commit statuses to deploy. If you do\nnot require any contexts or create any commit statuses, the deployment will always succeed.\n\nThe `payload` parameter is available for any extra information that a deployment system might need. It is a JSON text\nfield that will be passed on when a deployment event is dispatched.\n\nThe `task` parameter is used by the deployment system to allow different execution paths. In the web world this might\nbe `deploy:migrations` to run schema changes on the system. In the compiled world this could be a flag to compile an\napplication with debugging enabled.\n\nUsers with `repo` or `repo_deployment` scopes can create a deployment for a given ref.\n\n#### Merged branch response\nYou will see this response when GitHub automatically merges the base branch into the topic branch instead of creating\na deployment. This auto-merge happens when:\n*   Auto-merge option is enabled in the repository\n*   Topic branch does not include the latest changes on the base branch, which is `master` in the response example\n*   There are no merge conflicts\n\nIf there are no new commits in the base branch, a new request to create a deployment should give a successful\nresponse.\n\n#### Merge conflict response\nThis error happens when the `auto_merge` option is enabled and when the default branch (in this case `master`), can't\nbe merged into the branch that's being deployed (in this case `topic-branch`), due to merge conflicts.\n\n#### Failed commit status checks\nThis error happens when the `required_contexts` parameter indicates that one or more contexts need to have a `success`\nstatus for the commit to be deployed, but one or more of the required contexts do not have a state of `success`.",
  input: ReposCreateDeploymentInput,
  output: ReposCreateDeploymentOutput,
  errors: [ConflictError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("POST", "/repos/{owner}/{repo}/deployments", data) as any
  },
})
