// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const ReposUpdateReleaseInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  release_id: z.number().int().describe("The unique identifier of the release."),
  body: z.string().optional().describe("Text describing the contents of the tag."),
  discussion_category_name: z.string().optional().describe("If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored. For more information, see \"[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository).\""),
  draft: z.boolean().optional().describe("`true` makes the release a draft, and `false` publishes the release."),
  make_latest: z.enum(["true", "false", "legacy"]).optional().describe("Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version."),
  name: z.string().optional().describe("The name of the release."),
  prerelease: z.boolean().optional().describe("`true` to identify the release as a prerelease, `false` to identify the release as a full release."),
  tag_name: z.string().optional().describe("The name of the tag."),
  target_commitish: z.string().optional().describe("Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch (usually `master`)."),
})

export const ReposUpdateReleaseOutput = z.object({
  assets: z.array(z.object({
    browser_download_url: z.string().url(),
    content_type: z.string(),
    created_at: z.string().datetime(),
    download_count: z.number().int(),
    id: z.number().int(),
    label: z.string().nullable(),
    name: z.string().describe("The file name of the asset."),
    node_id: z.string(),
    size: z.number().int(),
    state: z.enum(["uploaded", "open"]).describe("State of the release asset."),
    updated_at: z.string().datetime(),
    uploader: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    url: z.string().url(),
  })),
  assets_url: z.string().url(),
  author: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).describe("A GitHub user."),
  body: z.string().nullable().optional(),
  body_html: z.string().optional(),
  body_text: z.string().optional(),
  created_at: z.string().datetime(),
  discussion_url: z.string().url().optional().describe("The URL of the release discussion."),
  draft: z.boolean().describe("true to create a draft (unpublished) release, false to create a published one."),
  html_url: z.string().url(),
  id: z.number().int(),
  mentions_count: z.number().int().optional(),
  name: z.string().nullable(),
  node_id: z.string(),
  prerelease: z.boolean().describe("Whether to identify the release as a prerelease or a full release."),
  published_at: z.string().datetime().nullable(),
  reactions: z.object({
    "+1": z.number().int(),
    "-1": z.number().int(),
    confused: z.number().int(),
    eyes: z.number().int(),
    heart: z.number().int(),
    hooray: z.number().int(),
    laugh: z.number().int(),
    rocket: z.number().int(),
    total_count: z.number().int(),
    url: z.string().url(),
  }).optional(),
  tag_name: z.string().describe("The name of the tag."),
  tarball_url: z.string().url().nullable(),
  target_commitish: z.string().describe("Specifies the commitish value that determines where the Git tag is created from."),
  upload_url: z.string(),
  url: z.string().url(),
  zipball_url: z.string().url().nullable(),
}).describe("A release.")

export const reposUpdateRelease = pikkuSessionlessFunc({
  description: "Users with push access to the repository can edit a release.",
  input: ReposUpdateReleaseInput,
  output: ReposUpdateReleaseOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("PATCH", "/repos/{owner}/{repo}/releases/{release_id}", data) as any
  },
})
