// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const ReposGetDeploymentStatusInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  deployment_id: z.number().int().describe("deployment_id parameter"),
  status_id: z.number().int(),
})

export const ReposGetDeploymentStatusOutput = z.object({
  created_at: z.string().datetime(),
  creator: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  deployment_url: z.string().url(),
  description: z.string().max(140).default("").describe("A short description of the status."),
  environment: z.string().optional().default("").describe("The environment of the deployment that the status is for."),
  environment_url: z.string().url().optional().default("").describe("The URL for accessing your environment."),
  id: z.number().int(),
  log_url: z.string().url().optional().default("").describe("The URL to associate with this status."),
  node_id: z.string(),
  performed_via_github_app: z.object({
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    events: z.array(z.string()).describe("The list of events for the GitHub app"),
    external_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the GitHub app"),
    installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
    name: z.string().describe("The name of the GitHub app"),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    pem: z.string().optional(),
    permissions: z.object({
      checks: z.string().optional(),
      contents: z.string().optional(),
      deployments: z.string().optional(),
      issues: z.string().optional(),
      metadata: z.string().optional(),
    }).describe("The set of permissions for the GitHub app"),
    slug: z.string().optional().describe("The slug name of the GitHub app"),
    updated_at: z.string().datetime(),
    webhook_secret: z.string().nullable().optional(),
  }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
  repository_url: z.string().url(),
  state: z.enum(["error", "failure", "inactive", "pending", "success", "queued", "in_progress"]).describe("The state of the status."),
  target_url: z.string().url().default("").describe("Deprecated: the URL to associate with this status."),
  updated_at: z.string().datetime(),
  url: z.string().url(),
}).describe("The status of a deployment.")

export const reposGetDeploymentStatus = pikkuSessionlessFunc({
  description: "Users with pull access can view a deployment status for a deployment:",
  input: ReposGetDeploymentStatusInput,
  output: ReposGetDeploymentStatusOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/deployments/{deployment_id}/statuses/{status_id}", data) as any
  },
})
