// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { NotFoundError, UnprocessableContentError } from '@pikku/core/errors'

export const ReposCreateReleaseInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  body: z.string().optional().describe("Text describing the contents of the tag."),
  discussion_category_name: z.string().optional().describe("If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see \"[Managing categories for discussions in your repository](https://docs.github.com/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository).\""),
  draft: z.boolean().optional().default(false).describe("`true` to create a draft (unpublished) release, `false` to create a published one."),
  generate_release_notes: z.boolean().optional().default(false).describe("Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes."),
  make_latest: z.enum(["true", "false", "legacy"]).optional().describe("Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version."),
  name: z.string().optional().describe("The name of the release."),
  prerelease: z.boolean().optional().default(false).describe("`true` to identify the release as a prerelease. `false` to identify the release as a full release."),
  tag_name: z.string().describe("The name of the tag."),
  target_commitish: z.string().optional().describe("Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch (usually `master`)."),
})

export const ReposCreateReleaseOutput = z.object({
  assets: z.array(z.object({
    browser_download_url: z.string().url(),
    content_type: z.string(),
    created_at: z.string().datetime(),
    download_count: z.number().int(),
    id: z.number().int(),
    label: z.string().nullable(),
    name: z.string().describe("The file name of the asset."),
    node_id: z.string(),
    size: z.number().int(),
    state: z.enum(["uploaded", "open"]).describe("State of the release asset."),
    updated_at: z.string().datetime(),
    uploader: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    url: z.string().url(),
  })),
  assets_url: z.string().url(),
  author: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).describe("A GitHub user."),
  body: z.string().nullable().optional(),
  body_html: z.string().optional(),
  body_text: z.string().optional(),
  created_at: z.string().datetime(),
  discussion_url: z.string().url().optional().describe("The URL of the release discussion."),
  draft: z.boolean().describe("true to create a draft (unpublished) release, false to create a published one."),
  html_url: z.string().url(),
  id: z.number().int(),
  mentions_count: z.number().int().optional(),
  name: z.string().nullable(),
  node_id: z.string(),
  prerelease: z.boolean().describe("Whether to identify the release as a prerelease or a full release."),
  published_at: z.string().datetime().nullable(),
  reactions: z.object({
    "+1": z.number().int(),
    "-1": z.number().int(),
    confused: z.number().int(),
    eyes: z.number().int(),
    heart: z.number().int(),
    hooray: z.number().int(),
    laugh: z.number().int(),
    rocket: z.number().int(),
    total_count: z.number().int(),
    url: z.string().url(),
  }).optional(),
  tag_name: z.string().describe("The name of the tag."),
  tarball_url: z.string().url().nullable(),
  target_commitish: z.string().describe("Specifies the commitish value that determines where the Git tag is created from."),
  upload_url: z.string(),
  url: z.string().url(),
  zipball_url: z.string().url().nullable(),
}).describe("A release.")

export const reposCreateRelease = pikkuSessionlessFunc({
  description: "Users with push access to the repository can create a release.\n\nThis endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in secondary rate limiting. See \"[Secondary rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits)\" and \"[Dealing with secondary rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits)\" for details.",
  input: ReposCreateReleaseInput,
  output: ReposCreateReleaseOutput,
  errors: [NotFoundError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("POST", "/repos/{owner}/{repo}/releases", data) as any
  },
})
