// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { ForbiddenError, NotFoundError, UnprocessableContentError } from '@pikku/core/errors'

export const ReposRenameBranchInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  branch: z.string().describe("The name of the branch. Cannot contain wildcard characters. To use wildcard characters in branch names, use [the GraphQL API](https://docs.github.com/graphql)."),
  new_name: z.string().describe("The new name of the branch."),
})

export const ReposRenameBranchOutput = z.object({
  _links: z.object({
    html: z.string(),
    self: z.string().url(),
  }),
  commit: z.object({
    author: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    comments_url: z.string().url(),
    commit: z.object({
      author: z.object({
        date: z.string().optional(),
        email: z.string().optional(),
        name: z.string().optional(),
      }).nullable().describe("Metaproperties for Git author/committer information."),
      comment_count: z.number().int(),
      committer: z.object({
        date: z.string().optional(),
        email: z.string().optional(),
        name: z.string().optional(),
      }).nullable().describe("Metaproperties for Git author/committer information."),
      message: z.string(),
      tree: z.object({
        sha: z.string(),
        url: z.string().url(),
      }),
      url: z.string().url(),
      verification: z.object({
        payload: z.string().nullable(),
        reason: z.string(),
        signature: z.string().nullable(),
        verified: z.boolean(),
      }).optional(),
    }),
    committer: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    files: z.array(z.object({
      additions: z.number().int(),
      blob_url: z.string().url(),
      changes: z.number().int(),
      contents_url: z.string().url(),
      deletions: z.number().int(),
      filename: z.string(),
      patch: z.string().optional(),
      previous_filename: z.string().optional(),
      raw_url: z.string().url(),
      sha: z.string(),
      status: z.enum(["added", "removed", "modified", "renamed", "copied", "changed", "unchanged"]),
    })).optional(),
    html_url: z.string().url(),
    node_id: z.string(),
    parents: z.array(z.object({
      html_url: z.string().url().optional(),
      sha: z.string(),
      url: z.string().url(),
    })),
    sha: z.string(),
    stats: z.object({
      additions: z.number().int().optional(),
      deletions: z.number().int().optional(),
      total: z.number().int().optional(),
    }).optional(),
    url: z.string().url(),
  }).describe("Commit"),
  name: z.string(),
  pattern: z.string().optional(),
  protected: z.boolean(),
  protection: z.object({
    allow_deletions: z.object({
      enabled: z.boolean().optional(),
    }).optional(),
    allow_force_pushes: z.object({
      enabled: z.boolean().optional(),
    }).optional(),
    allow_fork_syncing: z.object({
      enabled: z.boolean().optional().default(false),
    }).optional().describe("Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing."),
    block_creations: z.object({
      enabled: z.boolean().optional(),
    }).optional(),
    enabled: z.boolean().optional(),
    enforce_admins: z.object({
      enabled: z.boolean(),
      url: z.string().url(),
    }).optional().describe("Protected Branch Admin Enforced"),
    lock_branch: z.object({
      enabled: z.boolean().optional().default(false),
    }).optional().describe("Whether to set the branch as read-only. If this is true, users will not be able to push to the branch."),
    name: z.string().optional(),
    protection_url: z.string().optional(),
    required_conversation_resolution: z.object({
      enabled: z.boolean().optional(),
    }).optional(),
    required_linear_history: z.object({
      enabled: z.boolean().optional(),
    }).optional(),
    required_pull_request_reviews: z.object({
      bypass_pull_request_allowances: z.object({
        apps: z.array(z.object({
          client_id: z.string().optional(),
          client_secret: z.string().optional(),
          created_at: z.string().datetime(),
          description: z.string().nullable(),
          events: z.array(z.string()).describe("The list of events for the GitHub app"),
          external_url: z.string().url(),
          html_url: z.string().url(),
          id: z.number().int().describe("Unique identifier of the GitHub app"),
          installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
          name: z.string().describe("The name of the GitHub app"),
          node_id: z.string(),
          owner: z.object({
            avatar_url: z.string().url(),
            email: z.string().nullable().optional(),
            events_url: z.string(),
            followers_url: z.string().url(),
            following_url: z.string(),
            gists_url: z.string(),
            gravatar_id: z.string().nullable(),
            html_url: z.string().url(),
            id: z.number().int(),
            login: z.string(),
            name: z.string().nullable().optional(),
            node_id: z.string(),
            organizations_url: z.string().url(),
            received_events_url: z.string().url(),
            repos_url: z.string().url(),
            site_admin: z.boolean(),
            starred_at: z.string().optional(),
            starred_url: z.string(),
            subscriptions_url: z.string().url(),
            type: z.string(),
            url: z.string().url(),
          }).nullable().describe("A GitHub user."),
          pem: z.string().optional(),
          permissions: z.object({
            checks: z.string().optional(),
            contents: z.string().optional(),
            deployments: z.string().optional(),
            issues: z.string().optional(),
            metadata: z.string().optional(),
          }).describe("The set of permissions for the GitHub app"),
          slug: z.string().optional().describe("The slug name of the GitHub app"),
          updated_at: z.string().datetime(),
          webhook_secret: z.string().nullable().optional(),
        })).optional().describe("The list of apps allowed to bypass pull request requirements."),
        teams: z.array(z.object({
          description: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          members_url: z.string(),
          name: z.string(),
          node_id: z.string(),
          parent: z.object({
            description: z.string().nullable().describe("Description of the team"),
            html_url: z.string().url(),
            id: z.number().int().describe("Unique identifier of the team"),
            ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
            members_url: z.string(),
            name: z.string().describe("Name of the team"),
            node_id: z.string(),
            permission: z.string().describe("Permission that the team will have for its repositories"),
            privacy: z.string().optional().describe("The level of privacy this team should have"),
            repositories_url: z.string().url(),
            slug: z.string(),
            url: z.string().url().describe("URL for the team"),
          }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
          permission: z.string(),
          permissions: z.object({
            admin: z.boolean(),
            maintain: z.boolean(),
            pull: z.boolean(),
            push: z.boolean(),
            triage: z.boolean(),
          }).optional(),
          privacy: z.string().optional(),
          repositories_url: z.string().url(),
          slug: z.string(),
          url: z.string().url(),
        })).optional().describe("The list of teams allowed to bypass pull request requirements."),
        users: z.array(z.object({
          avatar_url: z.string().url(),
          email: z.string().nullable().optional(),
          events_url: z.string(),
          followers_url: z.string().url(),
          following_url: z.string(),
          gists_url: z.string(),
          gravatar_id: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          login: z.string(),
          name: z.string().nullable().optional(),
          node_id: z.string(),
          organizations_url: z.string().url(),
          received_events_url: z.string().url(),
          repos_url: z.string().url(),
          site_admin: z.boolean(),
          starred_at: z.string().optional(),
          starred_url: z.string(),
          subscriptions_url: z.string().url(),
          type: z.string(),
          url: z.string().url(),
        })).optional().describe("The list of users allowed to bypass pull request requirements."),
      }).optional().describe("Allow specific users, teams, or apps to bypass pull request requirements."),
      dismiss_stale_reviews: z.boolean(),
      dismissal_restrictions: z.object({
        apps: z.array(z.object({
          client_id: z.string().optional(),
          client_secret: z.string().optional(),
          created_at: z.string().datetime(),
          description: z.string().nullable(),
          events: z.array(z.string()).describe("The list of events for the GitHub app"),
          external_url: z.string().url(),
          html_url: z.string().url(),
          id: z.number().int().describe("Unique identifier of the GitHub app"),
          installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
          name: z.string().describe("The name of the GitHub app"),
          node_id: z.string(),
          owner: z.object({
            avatar_url: z.string().url(),
            email: z.string().nullable().optional(),
            events_url: z.string(),
            followers_url: z.string().url(),
            following_url: z.string(),
            gists_url: z.string(),
            gravatar_id: z.string().nullable(),
            html_url: z.string().url(),
            id: z.number().int(),
            login: z.string(),
            name: z.string().nullable().optional(),
            node_id: z.string(),
            organizations_url: z.string().url(),
            received_events_url: z.string().url(),
            repos_url: z.string().url(),
            site_admin: z.boolean(),
            starred_at: z.string().optional(),
            starred_url: z.string(),
            subscriptions_url: z.string().url(),
            type: z.string(),
            url: z.string().url(),
          }).nullable().describe("A GitHub user."),
          pem: z.string().optional(),
          permissions: z.object({
            checks: z.string().optional(),
            contents: z.string().optional(),
            deployments: z.string().optional(),
            issues: z.string().optional(),
            metadata: z.string().optional(),
          }).describe("The set of permissions for the GitHub app"),
          slug: z.string().optional().describe("The slug name of the GitHub app"),
          updated_at: z.string().datetime(),
          webhook_secret: z.string().nullable().optional(),
        })).optional().describe("The list of apps with review dismissal access."),
        teams: z.array(z.object({
          description: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          members_url: z.string(),
          name: z.string(),
          node_id: z.string(),
          parent: z.object({
            description: z.string().nullable().describe("Description of the team"),
            html_url: z.string().url(),
            id: z.number().int().describe("Unique identifier of the team"),
            ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
            members_url: z.string(),
            name: z.string().describe("Name of the team"),
            node_id: z.string(),
            permission: z.string().describe("Permission that the team will have for its repositories"),
            privacy: z.string().optional().describe("The level of privacy this team should have"),
            repositories_url: z.string().url(),
            slug: z.string(),
            url: z.string().url().describe("URL for the team"),
          }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
          permission: z.string(),
          permissions: z.object({
            admin: z.boolean(),
            maintain: z.boolean(),
            pull: z.boolean(),
            push: z.boolean(),
            triage: z.boolean(),
          }).optional(),
          privacy: z.string().optional(),
          repositories_url: z.string().url(),
          slug: z.string(),
          url: z.string().url(),
        })).optional().describe("The list of teams with review dismissal access."),
        teams_url: z.string().optional(),
        url: z.string().optional(),
        users: z.array(z.object({
          avatar_url: z.string().url(),
          email: z.string().nullable().optional(),
          events_url: z.string(),
          followers_url: z.string().url(),
          following_url: z.string(),
          gists_url: z.string(),
          gravatar_id: z.string().nullable(),
          html_url: z.string().url(),
          id: z.number().int(),
          login: z.string(),
          name: z.string().nullable().optional(),
          node_id: z.string(),
          organizations_url: z.string().url(),
          received_events_url: z.string().url(),
          repos_url: z.string().url(),
          site_admin: z.boolean(),
          starred_at: z.string().optional(),
          starred_url: z.string(),
          subscriptions_url: z.string().url(),
          type: z.string(),
          url: z.string().url(),
        })).optional().describe("The list of users with review dismissal access."),
        users_url: z.string().optional(),
      }).optional(),
      require_code_owner_reviews: z.boolean(),
      require_last_push_approval: z.boolean().optional().default(false).describe("Whether the most recent push must be approved by someone other than the person who pushed it."),
      required_approving_review_count: z.number().int().min(0).max(6).optional(),
      url: z.string().url().optional(),
    }).optional().describe("Protected Branch Pull Request Review"),
    required_signatures: z.object({
      enabled: z.boolean(),
      url: z.string().url(),
    }).optional(),
    required_status_checks: z.object({
      checks: z.array(z.object({
        app_id: z.number().int().nullable(),
        context: z.string(),
      })),
      contexts: z.array(z.string()),
      contexts_url: z.string().optional(),
      enforcement_level: z.string().optional(),
      strict: z.boolean().optional(),
      url: z.string().optional(),
    }).optional().describe("Protected Branch Required Status Check"),
    restrictions: z.object({
      apps: z.array(z.object({
        created_at: z.string().optional(),
        description: z.string().optional(),
        events: z.array(z.string()).optional(),
        external_url: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        name: z.string().optional(),
        node_id: z.string().optional(),
        owner: z.object({
          avatar_url: z.string().optional(),
          description: z.string().optional(),
          events_url: z.string().optional(),
          followers_url: z.string().optional(),
          following_url: z.string().optional(),
          gists_url: z.string().optional(),
          gravatar_id: z.string().optional(),
          hooks_url: z.string().optional(),
          html_url: z.string().optional(),
          id: z.number().int().optional(),
          issues_url: z.string().optional(),
          login: z.string().optional(),
          members_url: z.string().optional(),
          node_id: z.string().optional(),
          organizations_url: z.string().optional(),
          public_members_url: z.string().optional(),
          received_events_url: z.string().optional(),
          repos_url: z.string().optional(),
          site_admin: z.boolean().optional(),
          starred_url: z.string().optional(),
          subscriptions_url: z.string().optional(),
          type: z.string().optional(),
          url: z.string().optional(),
        }).optional(),
        permissions: z.object({
          contents: z.string().optional(),
          issues: z.string().optional(),
          metadata: z.string().optional(),
          single_file: z.string().optional(),
        }).optional(),
        slug: z.string().optional(),
        updated_at: z.string().optional(),
      })),
      apps_url: z.string().url(),
      teams: z.array(z.object({
        description: z.string().nullable().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        members_url: z.string().optional(),
        name: z.string().optional(),
        node_id: z.string().optional(),
        parent: z.string().nullable().optional(),
        permission: z.string().optional(),
        privacy: z.string().optional(),
        repositories_url: z.string().optional(),
        slug: z.string().optional(),
        url: z.string().optional(),
      })),
      teams_url: z.string().url(),
      url: z.string().url(),
      users: z.array(z.object({
        avatar_url: z.string().optional(),
        events_url: z.string().optional(),
        followers_url: z.string().optional(),
        following_url: z.string().optional(),
        gists_url: z.string().optional(),
        gravatar_id: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        login: z.string().optional(),
        node_id: z.string().optional(),
        organizations_url: z.string().optional(),
        received_events_url: z.string().optional(),
        repos_url: z.string().optional(),
        site_admin: z.boolean().optional(),
        starred_url: z.string().optional(),
        subscriptions_url: z.string().optional(),
        type: z.string().optional(),
        url: z.string().optional(),
      })),
      users_url: z.string().url(),
    }).optional().describe("Branch Restriction Policy"),
    url: z.string().optional(),
  }).describe("Branch Protection"),
  protection_url: z.string().url(),
  required_approving_review_count: z.number().int().optional(),
}).describe("Branch With Protection")

export const reposRenameBranch = pikkuSessionlessFunc({
  description: "Renames a branch in a repository.\n\n**Note:** Although the API responds immediately, the branch rename process might take some extra time to complete in the background. You won't be able to push to the old branch name while the rename process is in progress. For more information, see \"[Renaming a branch](https://docs.github.com/github/administering-a-repository/renaming-a-branch)\".\n\nThe permissions required to use this endpoint depends on whether you are renaming the default branch.\n\nTo rename a non-default branch:\n\n* Users must have push access.\n* GitHub Apps must have the `contents:write` repository permission.\n\nTo rename the default branch:\n\n* Users must have admin or owner permissions.\n* GitHub Apps must have the `administration:write` repository permission.",
  input: ReposRenameBranchInput,
  output: ReposRenameBranchOutput,
  errors: [ForbiddenError, NotFoundError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("POST", "/repos/{owner}/{repo}/branches/{branch}/rename", data) as any
  },
})
