// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const ReposGetDeploymentInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  deployment_id: z.number().int().describe("deployment_id parameter"),
})

export const ReposGetDeploymentOutput = z.object({
  created_at: z.string().datetime(),
  creator: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  description: z.string().nullable(),
  environment: z.string().describe("Name for the target deployment environment."),
  id: z.number().int().describe("Unique identifier of the deployment"),
  node_id: z.string(),
  original_environment: z.string().optional(),
  payload: z.union([z.record(z.string(), z.unknown()), z.string()]),
  performed_via_github_app: z.object({
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    created_at: z.string().datetime(),
    description: z.string().nullable(),
    events: z.array(z.string()).describe("The list of events for the GitHub app"),
    external_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the GitHub app"),
    installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
    name: z.string().describe("The name of the GitHub app"),
    node_id: z.string(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    pem: z.string().optional(),
    permissions: z.object({
      checks: z.string().optional(),
      contents: z.string().optional(),
      deployments: z.string().optional(),
      issues: z.string().optional(),
      metadata: z.string().optional(),
    }).describe("The set of permissions for the GitHub app"),
    slug: z.string().optional().describe("The slug name of the GitHub app"),
    updated_at: z.string().datetime(),
    webhook_secret: z.string().nullable().optional(),
  }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
  production_environment: z.boolean().optional().describe("Specifies if the given environment is one that end-users directly interact with. Default: false."),
  ref: z.string().describe("The ref to deploy. This can be a branch, tag, or sha."),
  repository_url: z.string().url(),
  sha: z.string(),
  statuses_url: z.string().url(),
  task: z.string().describe("Parameter to specify a task to execute"),
  transient_environment: z.boolean().optional().describe("Specifies if the given environment is will no longer exist at some point in the future. Default: false."),
  updated_at: z.string().datetime(),
  url: z.string().url(),
}).describe("A request for a specific ref(branch,sha,tag) to be deployed")

export const reposGetDeployment = pikkuSessionlessFunc({
  input: ReposGetDeploymentInput,
  output: ReposGetDeploymentOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/repos/{owner}/{repo}/deployments/{deployment_id}", data) as any
  },
})
