// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ForbiddenError, UnprocessableContentError } from '@pikku/core/errors'

export const ReposAddCollaboratorInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  username: z.string().describe("The handle for the GitHub user account."),
  permission: z.string().optional().default("push").describe("The permission to grant the collaborator. **Only valid on organization-owned repositories.** We accept the following permissions to be set: `pull`, `triage`, `push`, `maintain`, `admin` and you can also specify a custom repository role name, if the owning organization has defined any."),
})

export const ReposAddCollaboratorOutput = z.object({
  created_at: z.string().datetime(),
  expired: z.boolean().optional().describe("Whether or not the invitation has expired"),
  html_url: z.string(),
  id: z.number().int().describe("Unique identifier of the repository invitation."),
  invitee: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  inviter: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  node_id: z.string(),
  permissions: z.enum(["read", "write", "admin", "triage", "maintain"]).describe("The permission associated with the invitation."),
  repository: z.object({
    allow_forking: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean().optional(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string().optional(),
    code_of_conduct: z.object({
      body: z.string().optional(),
      html_url: z.string().url().nullable(),
      key: z.string(),
      name: z.string(),
      url: z.string().url(),
    }).optional().describe("Code Of Conduct"),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable().optional(),
    default_branch: z.string().optional(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().optional(),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int().optional(),
    forks_count: z.number().int().optional(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string().optional(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean().optional(),
    has_issues: z.boolean().optional(),
    has_pages: z.boolean().optional(),
    has_projects: z.boolean().optional(),
    has_wiki: z.boolean().optional(),
    homepage: z.string().nullable().optional(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable().optional(),
    languages_url: z.string().url(),
    license: z.object({
      key: z.string().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      spdx_id: z.string().optional(),
      url: z.string().optional(),
    }).nullable().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().nullable().optional(),
    name: z.string(),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int().optional(),
    open_issues_count: z.number().int().optional(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean().optional(),
      maintain: z.boolean().optional(),
      pull: z.boolean().optional(),
      push: z.boolean().optional(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable().optional(),
    releases_url: z.string(),
    role_name: z.string().optional(),
    security_and_analysis: z.object({
      advanced_security: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
      secret_scanning_push_protection: z.object({
        status: z.enum(["enabled", "disabled"]).optional(),
      }).optional(),
    }).nullable().optional(),
    size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    ssh_url: z.string().optional(),
    stargazers_count: z.number().int().optional(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().optional(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable().optional(),
    url: z.string().url(),
    visibility: z.string().optional(),
    watchers: z.number().int().optional(),
    watchers_count: z.number().int().optional(),
    web_commit_signoff_required: z.boolean().optional(),
  }).describe("Minimal Repository"),
  url: z.string().describe("URL for the repository invitation"),
}).describe("Repository invitations let you manage who you collaborate with.")

export const reposAddCollaborator = pikkuSessionlessFunc({
  description: "This endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in secondary rate limiting. See \"[Secondary rate limits](https://docs.github.com/rest/overview/resources-in-the-rest-api#secondary-rate-limits)\" and \"[Dealing with secondary rate limits](https://docs.github.com/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits)\" for details.\n\nAdding an outside collaborator may be restricted by enterprise administrators. For more information, see \"[Enforcing repository management policies in your enterprise](https://docs.github.com/admin/policies/enforcing-policies-for-your-enterprise/enforcing-repository-management-policies-in-your-enterprise#enforcing-a-policy-for-inviting-outside-collaborators-to-repositories).\"\n\nFor more information on permission levels, see \"[Repository permission levels for an organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization)\". There are restrictions on which permissions can be granted to organization members when an organization base role is in place. In this case, the permission being given must be equal to or higher than the org base permission. Otherwise, the request will fail with:\n\n```\nCannot assign {member} permission of {role name}\n```\n\nNote that, if you choose not to pass any parameters, you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see \"[HTTP verbs](https://docs.github.com/rest/overview/resources-in-the-rest-api#http-verbs).\"\n\nThe invitee will receive a notification that they have been invited to the repository, which they must accept or decline. They may do this via the notifications page, the email they receive, or by using the [repository invitations API endpoints](https://docs.github.com/rest/reference/repos#invitations).\n\n**Updating an existing collaborator's permission level**\n\nThe endpoint can also be used to change the permissions of an existing collaborator without first removing and re-adding the collaborator. To change the permissions, use the same endpoint and pass a different `permission` parameter. The response will be a `204`, with no other indication that the permission level changed.\n\n**Rate limits**\n\nYou are limited to sending 50 invitations to a repository per 24 hour period. Note there is no limit if you are inviting organization members to an organization repository.",
  input: ReposAddCollaboratorInput,
  output: ReposAddCollaboratorOutput,
  errors: [ForbiddenError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("PUT", "/repos/{owner}/{repo}/collaborators/{username}", data) as any
  },
})
