// repos — Interact with GitHub Repos.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { UnprocessableContentError } from '@pikku/core/errors'

export const ReposUpdatePullRequestReviewProtectionInput = z.object({
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
  branch: z.string().describe("The name of the branch. Cannot contain wildcard characters. To use wildcard characters in branch names, use [the GraphQL API](https://docs.github.com/graphql)."),
  bypass_pull_request_allowances: z.object({
  apps: z.array(z.string()).optional().describe("The list of app `slug`s allowed to bypass pull request requirements."),
  teams: z.array(z.string()).optional().describe("The list of team `slug`s allowed to bypass pull request requirements."),
  users: z.array(z.string()).optional().describe("The list of user `login`s allowed to bypass pull request requirements."),
}).optional().describe("Allow specific users, teams, or apps to bypass pull request requirements."),
  dismiss_stale_reviews: z.boolean().optional().describe("Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit."),
  dismissal_restrictions: z.object({
  apps: z.array(z.string()).optional().describe("The list of app `slug`s with dismissal access"),
  teams: z.array(z.string()).optional().describe("The list of team `slug`s with dismissal access"),
  users: z.array(z.string()).optional().describe("The list of user `login`s with dismissal access"),
}).optional().describe("Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories."),
  require_code_owner_reviews: z.boolean().optional().describe("Blocks merging pull requests until [code owners](https://docs.github.com/articles/about-code-owners/) have reviewed."),
  require_last_push_approval: z.boolean().optional().default(false).describe("Whether the most recent push must be approved by someone other than the person who pushed it. Default: `false`"),
  required_approving_review_count: z.number().int().optional().describe("Specifies the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers."),
})

export const ReposUpdatePullRequestReviewProtectionOutput = z.object({
  bypass_pull_request_allowances: z.object({
    apps: z.array(z.object({
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      events: z.array(z.string()).describe("The list of events for the GitHub app"),
      external_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the GitHub app"),
      installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
      name: z.string().describe("The name of the GitHub app"),
      node_id: z.string(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      pem: z.string().optional(),
      permissions: z.object({
        checks: z.string().optional(),
        contents: z.string().optional(),
        deployments: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
      }).describe("The set of permissions for the GitHub app"),
      slug: z.string().optional().describe("The slug name of the GitHub app"),
      updated_at: z.string().datetime(),
      webhook_secret: z.string().nullable().optional(),
    })).optional().describe("The list of apps allowed to bypass pull request requirements."),
    teams: z.array(z.object({
      description: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      members_url: z.string(),
      name: z.string(),
      node_id: z.string(),
      parent: z.object({
        description: z.string().nullable().describe("Description of the team"),
        html_url: z.string().url(),
        id: z.number().int().describe("Unique identifier of the team"),
        ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
        members_url: z.string(),
        name: z.string().describe("Name of the team"),
        node_id: z.string(),
        permission: z.string().describe("Permission that the team will have for its repositories"),
        privacy: z.string().optional().describe("The level of privacy this team should have"),
        repositories_url: z.string().url(),
        slug: z.string(),
        url: z.string().url().describe("URL for the team"),
      }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
      permission: z.string(),
      permissions: z.object({
        admin: z.boolean(),
        maintain: z.boolean(),
        pull: z.boolean(),
        push: z.boolean(),
        triage: z.boolean(),
      }).optional(),
      privacy: z.string().optional(),
      repositories_url: z.string().url(),
      slug: z.string(),
      url: z.string().url(),
    })).optional().describe("The list of teams allowed to bypass pull request requirements."),
    users: z.array(z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    })).optional().describe("The list of users allowed to bypass pull request requirements."),
  }).optional().describe("Allow specific users, teams, or apps to bypass pull request requirements."),
  dismiss_stale_reviews: z.boolean(),
  dismissal_restrictions: z.object({
    apps: z.array(z.object({
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      events: z.array(z.string()).describe("The list of events for the GitHub app"),
      external_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the GitHub app"),
      installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
      name: z.string().describe("The name of the GitHub app"),
      node_id: z.string(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      pem: z.string().optional(),
      permissions: z.object({
        checks: z.string().optional(),
        contents: z.string().optional(),
        deployments: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
      }).describe("The set of permissions for the GitHub app"),
      slug: z.string().optional().describe("The slug name of the GitHub app"),
      updated_at: z.string().datetime(),
      webhook_secret: z.string().nullable().optional(),
    })).optional().describe("The list of apps with review dismissal access."),
    teams: z.array(z.object({
      description: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      members_url: z.string(),
      name: z.string(),
      node_id: z.string(),
      parent: z.object({
        description: z.string().nullable().describe("Description of the team"),
        html_url: z.string().url(),
        id: z.number().int().describe("Unique identifier of the team"),
        ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
        members_url: z.string(),
        name: z.string().describe("Name of the team"),
        node_id: z.string(),
        permission: z.string().describe("Permission that the team will have for its repositories"),
        privacy: z.string().optional().describe("The level of privacy this team should have"),
        repositories_url: z.string().url(),
        slug: z.string(),
        url: z.string().url().describe("URL for the team"),
      }).nullable().describe("Groups of organization members that gives permissions on specified repositories."),
      permission: z.string(),
      permissions: z.object({
        admin: z.boolean(),
        maintain: z.boolean(),
        pull: z.boolean(),
        push: z.boolean(),
        triage: z.boolean(),
      }).optional(),
      privacy: z.string().optional(),
      repositories_url: z.string().url(),
      slug: z.string(),
      url: z.string().url(),
    })).optional().describe("The list of teams with review dismissal access."),
    teams_url: z.string().optional(),
    url: z.string().optional(),
    users: z.array(z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    })).optional().describe("The list of users with review dismissal access."),
    users_url: z.string().optional(),
  }).optional(),
  require_code_owner_reviews: z.boolean(),
  require_last_push_approval: z.boolean().optional().default(false).describe("Whether the most recent push must be approved by someone other than the person who pushed it."),
  required_approving_review_count: z.number().int().min(0).max(6).optional(),
  url: z.string().url().optional(),
}).describe("Protected Branch Pull Request Review")

export const reposUpdatePullRequestReviewProtection = pikkuSessionlessFunc({
  description: "Protected branches are available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.\n\nUpdating pull request review enforcement requires admin or owner permissions to the repository and branch protection to be enabled.\n\n**Note**: Passing new arrays of `users` and `teams` replaces their previous values.",
  input: ReposUpdatePullRequestReviewProtectionInput,
  output: ReposUpdatePullRequestReviewProtectionOutput,
  errors: [UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("PATCH", "/repos/{owner}/{repo}/branches/{branch}/protection/required_pull_request_reviews", data) as any
  },
})
