// search — Look for stuff on GitHub.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { UnprocessableContentError } from '@pikku/core/errors'

export const SearchReposInput = z.object({
  q: z.string().describe("The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as the web interface for GitHub. To learn more about the format of the query, see [Constructing a search query](https://docs.github.com/rest/reference/search#constructing-a-search-query). See \"[Searching for repositories](https://docs.github.com/articles/searching-for-repositories/)\" for a detailed list of qualifiers."),
  sort: z.enum(["stars", "forks", "help-wanted-issues", "updated"]).optional().describe("Sorts the results of your query by number of `stars`, `forks`, or `help-wanted-issues` or how recently the items were `updated`. Default: [best match](https://docs.github.com/rest/reference/search#ranking-search-results)"),
  order: z.enum(["desc", "asc"]).optional().default("desc").describe("Determines whether the first search result returned is the highest number of matches (`desc`) or lowest number of matches (`asc`). This parameter is ignored unless you provide `sort`."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
})

export const SearchReposOutput = z.object({
  incomplete_results: z.boolean(),
  items: z.array(z.object({
    allow_auto_merge: z.boolean().optional(),
    allow_forking: z.boolean().optional(),
    allow_merge_commit: z.boolean().optional(),
    allow_rebase_merge: z.boolean().optional(),
    allow_squash_merge: z.boolean().optional(),
    archive_url: z.string(),
    archived: z.boolean(),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string(),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime(),
    default_branch: z.string(),
    delete_branch_on_merge: z.boolean().optional(),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().describe("Returns whether or not this repository disabled."),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int(),
    forks_count: z.number().int(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string(),
    has_discussions: z.boolean().optional(),
    has_downloads: z.boolean(),
    has_issues: z.boolean(),
    has_pages: z.boolean(),
    has_projects: z.boolean(),
    has_wiki: z.boolean(),
    homepage: z.string().url().nullable(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_template: z.boolean().optional(),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable(),
    languages_url: z.string().url(),
    license: z.object({
      html_url: z.string().url().optional(),
      key: z.string(),
      name: z.string(),
      node_id: z.string(),
      spdx_id: z.string().nullable(),
      url: z.string().url().nullable(),
    }).nullable().describe("License Simple"),
    master_branch: z.string().optional(),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().url().nullable(),
    name: z.string(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int(),
    open_issues_count: z.number().int(),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean(),
      maintain: z.boolean().optional(),
      pull: z.boolean(),
      push: z.boolean(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean(),
    pulls_url: z.string(),
    pushed_at: z.string().datetime(),
    releases_url: z.string(),
    score: z.number(),
    size: z.number().int(),
    ssh_url: z.string(),
    stargazers_count: z.number().int(),
    stargazers_url: z.string().url(),
    statuses_url: z.string(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().url(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    text_matches: z.array(z.object({
      fragment: z.string().optional(),
      matches: z.array(z.object({
        indices: z.array(z.number().int()).optional(),
        text: z.string().optional(),
      })).optional(),
      object_type: z.string().nullable().optional(),
      object_url: z.string().optional(),
      property: z.string().optional(),
    })).optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime(),
    url: z.string().url(),
    visibility: z.string().optional().describe("The repository visibility: public, private, or internal."),
    watchers: z.number().int(),
    watchers_count: z.number().int(),
    web_commit_signoff_required: z.boolean().optional(),
  })),
  total_count: z.number().int(),
})

export const searchRepos = pikkuSessionlessFunc({
  description: "Find repositories via various criteria. This method returns up to 100 results [per page](https://docs.github.com/rest/overview/resources-in-the-rest-api#pagination).\n\nWhen searching for repositories, you can get text match metadata for the **name** and **description** fields when you pass the `text-match` media type. For more details about how to receive highlighted search results, see [Text match metadata](https://docs.github.com/rest/reference/search#text-match-metadata).\n\nFor example, if you want to search for popular Tetris repositories written in assembly code, your query might look like this:\n\n`q=tetris+language:assembly&sort=stars&order=desc`\n\nThis query searches for repositories with the word `tetris` in the name, the description, or the README. The results are limited to repositories where the primary language is assembly. The results are sorted by stars in descending order, so that the most popular repositories appear first in the search results.",
  input: SearchReposInput,
  output: SearchReposOutput,
  errors: [UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("GET", "/search/repositories", data) as any
  },
})
