// search — Look for stuff on GitHub.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const SearchCommitsInput = z.object({
  q: z.string().describe("The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as the web interface for GitHub. To learn more about the format of the query, see [Constructing a search query](https://docs.github.com/rest/reference/search#constructing-a-search-query). See \"[Searching commits](https://docs.github.com/search-github/searching-on-github/searching-commits)\" for a detailed list of qualifiers."),
  sort: z.enum(["author-date", "committer-date"]).optional().describe("Sorts the results of your query by `author-date` or `committer-date`. Default: [best match](https://docs.github.com/rest/reference/search#ranking-search-results)"),
  order: z.enum(["desc", "asc"]).optional().default("desc").describe("Determines whether the first search result returned is the highest number of matches (`desc`) or lowest number of matches (`asc`). This parameter is ignored unless you provide `sort`."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
})

export const SearchCommitsOutput = z.object({
  incomplete_results: z.boolean(),
  items: z.array(z.object({
    author: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    comments_url: z.string().url(),
    commit: z.object({
      author: z.object({
        date: z.string().datetime(),
        email: z.string(),
        name: z.string(),
      }),
      comment_count: z.number().int(),
      committer: z.object({
        date: z.string().optional(),
        email: z.string().optional(),
        name: z.string().optional(),
      }).nullable().describe("Metaproperties for Git author/committer information."),
      message: z.string(),
      tree: z.object({
        sha: z.string(),
        url: z.string().url(),
      }),
      url: z.string().url(),
      verification: z.object({
        payload: z.string().nullable(),
        reason: z.string(),
        signature: z.string().nullable(),
        verified: z.boolean(),
      }).optional(),
    }),
    committer: z.object({
      date: z.string().optional(),
      email: z.string().optional(),
      name: z.string().optional(),
    }).nullable().describe("Metaproperties for Git author/committer information."),
    html_url: z.string().url(),
    node_id: z.string(),
    parents: z.array(z.object({
      html_url: z.string().optional(),
      sha: z.string().optional(),
      url: z.string().optional(),
    })),
    repository: z.object({
      allow_forking: z.boolean().optional(),
      archive_url: z.string(),
      archived: z.boolean().optional(),
      assignees_url: z.string(),
      blobs_url: z.string(),
      branches_url: z.string(),
      clone_url: z.string().optional(),
      code_of_conduct: z.object({
        body: z.string().optional(),
        html_url: z.string().url().nullable(),
        key: z.string(),
        name: z.string(),
        url: z.string().url(),
      }).optional().describe("Code Of Conduct"),
      collaborators_url: z.string(),
      comments_url: z.string(),
      commits_url: z.string(),
      compare_url: z.string(),
      contents_url: z.string(),
      contributors_url: z.string().url(),
      created_at: z.string().datetime().nullable().optional(),
      default_branch: z.string().optional(),
      delete_branch_on_merge: z.boolean().optional(),
      deployments_url: z.string().url(),
      description: z.string().nullable(),
      disabled: z.boolean().optional(),
      downloads_url: z.string().url(),
      events_url: z.string().url(),
      fork: z.boolean(),
      forks: z.number().int().optional(),
      forks_count: z.number().int().optional(),
      forks_url: z.string().url(),
      full_name: z.string(),
      git_commits_url: z.string(),
      git_refs_url: z.string(),
      git_tags_url: z.string(),
      git_url: z.string().optional(),
      has_discussions: z.boolean().optional(),
      has_downloads: z.boolean().optional(),
      has_issues: z.boolean().optional(),
      has_pages: z.boolean().optional(),
      has_projects: z.boolean().optional(),
      has_wiki: z.boolean().optional(),
      homepage: z.string().nullable().optional(),
      hooks_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int(),
      is_template: z.boolean().optional(),
      issue_comment_url: z.string(),
      issue_events_url: z.string(),
      issues_url: z.string(),
      keys_url: z.string(),
      labels_url: z.string(),
      language: z.string().nullable().optional(),
      languages_url: z.string().url(),
      license: z.object({
        key: z.string().optional(),
        name: z.string().optional(),
        node_id: z.string().optional(),
        spdx_id: z.string().optional(),
        url: z.string().optional(),
      }).nullable().optional(),
      merges_url: z.string().url(),
      milestones_url: z.string(),
      mirror_url: z.string().nullable().optional(),
      name: z.string(),
      network_count: z.number().int().optional(),
      node_id: z.string(),
      notifications_url: z.string(),
      open_issues: z.number().int().optional(),
      open_issues_count: z.number().int().optional(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).describe("A GitHub user."),
      permissions: z.object({
        admin: z.boolean().optional(),
        maintain: z.boolean().optional(),
        pull: z.boolean().optional(),
        push: z.boolean().optional(),
        triage: z.boolean().optional(),
      }).optional(),
      private: z.boolean(),
      pulls_url: z.string(),
      pushed_at: z.string().datetime().nullable().optional(),
      releases_url: z.string(),
      role_name: z.string().optional(),
      security_and_analysis: z.object({
        advanced_security: z.object({
          status: z.enum(["enabled", "disabled"]).optional(),
        }).optional(),
        secret_scanning: z.object({
          status: z.enum(["enabled", "disabled"]).optional(),
        }).optional(),
        secret_scanning_push_protection: z.object({
          status: z.enum(["enabled", "disabled"]).optional(),
        }).optional(),
      }).nullable().optional(),
      size: z.number().int().optional().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
      ssh_url: z.string().optional(),
      stargazers_count: z.number().int().optional(),
      stargazers_url: z.string().url(),
      statuses_url: z.string(),
      subscribers_count: z.number().int().optional(),
      subscribers_url: z.string().url(),
      subscription_url: z.string().url(),
      svn_url: z.string().optional(),
      tags_url: z.string().url(),
      teams_url: z.string().url(),
      temp_clone_token: z.string().optional(),
      topics: z.array(z.string()).optional(),
      trees_url: z.string(),
      updated_at: z.string().datetime().nullable().optional(),
      url: z.string().url(),
      visibility: z.string().optional(),
      watchers: z.number().int().optional(),
      watchers_count: z.number().int().optional(),
      web_commit_signoff_required: z.boolean().optional(),
    }).describe("Minimal Repository"),
    score: z.number(),
    sha: z.string(),
    text_matches: z.array(z.object({
      fragment: z.string().optional(),
      matches: z.array(z.object({
        indices: z.array(z.number().int()).optional(),
        text: z.string().optional(),
      })).optional(),
      object_type: z.string().nullable().optional(),
      object_url: z.string().optional(),
      property: z.string().optional(),
    })).optional(),
    url: z.string().url(),
  })),
  total_count: z.number().int(),
})

export const searchCommits = pikkuSessionlessFunc({
  description: "Find commits via various criteria on the default branch (usually `main`). This method returns up to 100 results [per page](https://docs.github.com/rest/overview/resources-in-the-rest-api#pagination).\n\nWhen searching for commits, you can get text match metadata for the **message** field when you provide the `text-match` media type. For more details about how to receive highlighted search results, see [Text match\nmetadata](https://docs.github.com/rest/reference/search#text-match-metadata).\n\nFor example, if you want to find commits related to CSS in the [octocat/Spoon-Knife](https://github.com/octocat/Spoon-Knife) repository. Your query would look something like this:\n\n`q=repo:octocat/Spoon-Knife+css`",
  input: SearchCommitsInput,
  output: SearchCommitsOutput,
  func: async ({ github }, data) => {
    return github.call("GET", "/search/commits", data) as any
  },
})
