// search — Look for stuff on GitHub.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ForbiddenError, UnprocessableContentError } from '@pikku/core/errors'

export const SearchIssuesAndPullRequestsInput = z.object({
  q: z.string().describe("The query contains one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as the web interface for GitHub. To learn more about the format of the query, see [Constructing a search query](https://docs.github.com/rest/reference/search#constructing-a-search-query). See \"[Searching issues and pull requests](https://docs.github.com/search-github/searching-on-github/searching-issues-and-pull-requests)\" for a detailed list of qualifiers."),
  sort: z.enum(["comments", "reactions", "reactions-+1", "reactions--1", "reactions-smile", "reactions-thinking_face", "reactions-heart", "reactions-tada", "interactions", "created", "updated"]).optional().describe("Sorts the results of your query by the number of `comments`, `reactions`, `reactions-+1`, `reactions--1`, `reactions-smile`, `reactions-thinking_face`, `reactions-heart`, `reactions-tada`, or `interactions`. You can also sort results by how recently the items were `created` or `updated`, Default: [best match](https://docs.github.com/rest/reference/search#ranking-search-results)"),
  order: z.enum(["desc", "asc"]).optional().default("desc").describe("Determines whether the first search result returned is the highest number of matches (`desc`) or lowest number of matches (`asc`). This parameter is ignored unless you provide `sort`."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
})

export const SearchIssuesAndPullRequestsOutput = z.object({
  incomplete_results: z.boolean(),
  items: z.array(z.object({
    active_lock_reason: z.string().nullable().optional(),
    assignee: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
    assignees: z.array(z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    })).nullable().optional(),
    author_association: z.enum(["COLLABORATOR", "CONTRIBUTOR", "FIRST_TIMER", "FIRST_TIME_CONTRIBUTOR", "MANNEQUIN", "MEMBER", "NONE", "OWNER"]).describe("How the author is associated with the repository."),
    body: z.string().optional(),
    body_html: z.string().optional(),
    body_text: z.string().optional(),
    closed_at: z.string().datetime().nullable(),
    comments: z.number().int(),
    comments_url: z.string().url(),
    created_at: z.string().datetime(),
    draft: z.boolean().optional(),
    events_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int(),
    labels: z.array(z.object({
      color: z.string().optional(),
      default: z.boolean().optional(),
      description: z.string().nullable().optional(),
      id: z.number().int().optional(),
      name: z.string().optional(),
      node_id: z.string().optional(),
      url: z.string().optional(),
    })),
    labels_url: z.string(),
    locked: z.boolean(),
    milestone: z.object({
      closed_at: z.string().datetime().nullable(),
      closed_issues: z.number().int(),
      created_at: z.string().datetime(),
      creator: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      description: z.string().nullable(),
      due_on: z.string().datetime().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      labels_url: z.string().url(),
      node_id: z.string(),
      number: z.number().int().describe("The number of the milestone."),
      open_issues: z.number().int(),
      state: z.enum(["open", "closed"]).default("open").describe("The state of the milestone."),
      title: z.string().describe("The title of the milestone."),
      updated_at: z.string().datetime(),
      url: z.string().url(),
    }).nullable().describe("A collection of related issues and pull requests."),
    node_id: z.string(),
    number: z.number().int(),
    performed_via_github_app: z.object({
      client_id: z.string().optional(),
      client_secret: z.string().optional(),
      created_at: z.string().datetime(),
      description: z.string().nullable(),
      events: z.array(z.string()).describe("The list of events for the GitHub app"),
      external_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the GitHub app"),
      installations_count: z.number().int().optional().describe("The number of installations associated with the GitHub app"),
      name: z.string().describe("The name of the GitHub app"),
      node_id: z.string(),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().describe("A GitHub user."),
      pem: z.string().optional(),
      permissions: z.object({
        checks: z.string().optional(),
        contents: z.string().optional(),
        deployments: z.string().optional(),
        issues: z.string().optional(),
        metadata: z.string().optional(),
      }).describe("The set of permissions for the GitHub app"),
      slug: z.string().optional().describe("The slug name of the GitHub app"),
      updated_at: z.string().datetime(),
      webhook_secret: z.string().nullable().optional(),
    }).nullable().optional().describe("GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub."),
    pull_request: z.object({
      diff_url: z.string().url().nullable(),
      html_url: z.string().url().nullable(),
      merged_at: z.string().datetime().nullable().optional(),
      patch_url: z.string().url().nullable(),
      url: z.string().url().nullable(),
    }).optional(),
    reactions: z.object({
      "+1": z.number().int(),
      "-1": z.number().int(),
      confused: z.number().int(),
      eyes: z.number().int(),
      heart: z.number().int(),
      hooray: z.number().int(),
      laugh: z.number().int(),
      rocket: z.number().int(),
      total_count: z.number().int(),
      url: z.string().url(),
    }).optional(),
    repository: z.object({
      allow_auto_merge: z.boolean().optional().default(false).describe("Whether to allow Auto-merge to be used on pull requests."),
      allow_forking: z.boolean().optional().describe("Whether to allow forking this repo"),
      allow_merge_commit: z.boolean().optional().default(true).describe("Whether to allow merge commits for pull requests."),
      allow_rebase_merge: z.boolean().optional().default(true).describe("Whether to allow rebase merges for pull requests."),
      allow_squash_merge: z.boolean().optional().default(true).describe("Whether to allow squash merges for pull requests."),
      allow_update_branch: z.boolean().optional().default(false).describe("Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging."),
      anonymous_access_enabled: z.boolean().optional().describe("Whether anonymous git access is enabled for this repository"),
      archive_url: z.string(),
      archived: z.boolean().default(false).describe("Whether the repository is archived."),
      assignees_url: z.string(),
      blobs_url: z.string(),
      branches_url: z.string(),
      clone_url: z.string(),
      collaborators_url: z.string(),
      comments_url: z.string(),
      commits_url: z.string(),
      compare_url: z.string(),
      contents_url: z.string(),
      contributors_url: z.string().url(),
      created_at: z.string().datetime().nullable(),
      default_branch: z.string().describe("The default branch of the repository."),
      delete_branch_on_merge: z.boolean().optional().default(false).describe("Whether to delete head branches when pull requests are merged"),
      deployments_url: z.string().url(),
      description: z.string().nullable(),
      disabled: z.boolean().describe("Returns whether or not this repository disabled."),
      downloads_url: z.string().url(),
      events_url: z.string().url(),
      fork: z.boolean(),
      forks: z.number().int(),
      forks_count: z.number().int(),
      forks_url: z.string().url(),
      full_name: z.string(),
      git_commits_url: z.string(),
      git_refs_url: z.string(),
      git_tags_url: z.string(),
      git_url: z.string(),
      has_discussions: z.boolean().optional().default(false).describe("Whether discussions are enabled."),
      has_downloads: z.boolean().default(true).describe("Whether downloads are enabled."),
      has_issues: z.boolean().default(true).describe("Whether issues are enabled."),
      has_pages: z.boolean(),
      has_projects: z.boolean().default(true).describe("Whether projects are enabled."),
      has_wiki: z.boolean().default(true).describe("Whether the wiki is enabled."),
      homepage: z.string().url().nullable(),
      hooks_url: z.string().url(),
      html_url: z.string().url(),
      id: z.number().int().describe("Unique identifier of the repository"),
      is_template: z.boolean().optional().default(false).describe("Whether this repository acts as a template that can be used to generate new repositories."),
      issue_comment_url: z.string(),
      issue_events_url: z.string(),
      issues_url: z.string(),
      keys_url: z.string(),
      labels_url: z.string(),
      language: z.string().nullable(),
      languages_url: z.string().url(),
      license: z.object({
        html_url: z.string().url().optional(),
        key: z.string(),
        name: z.string(),
        node_id: z.string(),
        spdx_id: z.string().nullable(),
        url: z.string().url().nullable(),
      }).nullable().describe("License Simple"),
      master_branch: z.string().optional(),
      merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
      merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
      merges_url: z.string().url(),
      milestones_url: z.string(),
      mirror_url: z.string().url().nullable(),
      name: z.string().describe("The name of the repository."),
      network_count: z.number().int().optional(),
      node_id: z.string(),
      notifications_url: z.string(),
      open_issues: z.number().int(),
      open_issues_count: z.number().int(),
      organization: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).nullable().optional().describe("A GitHub user."),
      owner: z.object({
        avatar_url: z.string().url(),
        email: z.string().nullable().optional(),
        events_url: z.string(),
        followers_url: z.string().url(),
        following_url: z.string(),
        gists_url: z.string(),
        gravatar_id: z.string().nullable(),
        html_url: z.string().url(),
        id: z.number().int(),
        login: z.string(),
        name: z.string().nullable().optional(),
        node_id: z.string(),
        organizations_url: z.string().url(),
        received_events_url: z.string().url(),
        repos_url: z.string().url(),
        site_admin: z.boolean(),
        starred_at: z.string().optional(),
        starred_url: z.string(),
        subscriptions_url: z.string().url(),
        type: z.string(),
        url: z.string().url(),
      }).describe("A GitHub user."),
      permissions: z.object({
        admin: z.boolean(),
        maintain: z.boolean().optional(),
        pull: z.boolean(),
        push: z.boolean(),
        triage: z.boolean().optional(),
      }).optional(),
      private: z.boolean().default(false).describe("Whether the repository is private or public."),
      pulls_url: z.string(),
      pushed_at: z.string().datetime().nullable(),
      releases_url: z.string(),
      size: z.number().int().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
      squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
      squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
      ssh_url: z.string(),
      stargazers_count: z.number().int(),
      stargazers_url: z.string().url(),
      starred_at: z.string().optional(),
      statuses_url: z.string(),
      subscribers_count: z.number().int().optional(),
      subscribers_url: z.string().url(),
      subscription_url: z.string().url(),
      svn_url: z.string().url(),
      tags_url: z.string().url(),
      teams_url: z.string().url(),
      temp_clone_token: z.string().optional(),
      template_repository: z.object({
        allow_auto_merge: z.boolean().optional(),
        allow_merge_commit: z.boolean().optional(),
        allow_rebase_merge: z.boolean().optional(),
        allow_squash_merge: z.boolean().optional(),
        allow_update_branch: z.boolean().optional(),
        archive_url: z.string().optional(),
        archived: z.boolean().optional(),
        assignees_url: z.string().optional(),
        blobs_url: z.string().optional(),
        branches_url: z.string().optional(),
        clone_url: z.string().optional(),
        collaborators_url: z.string().optional(),
        comments_url: z.string().optional(),
        commits_url: z.string().optional(),
        compare_url: z.string().optional(),
        contents_url: z.string().optional(),
        contributors_url: z.string().optional(),
        created_at: z.string().optional(),
        default_branch: z.string().optional(),
        delete_branch_on_merge: z.boolean().optional(),
        deployments_url: z.string().optional(),
        description: z.string().optional(),
        disabled: z.boolean().optional(),
        downloads_url: z.string().optional(),
        events_url: z.string().optional(),
        fork: z.boolean().optional(),
        forks_count: z.number().int().optional(),
        forks_url: z.string().optional(),
        full_name: z.string().optional(),
        git_commits_url: z.string().optional(),
        git_refs_url: z.string().optional(),
        git_tags_url: z.string().optional(),
        git_url: z.string().optional(),
        has_downloads: z.boolean().optional(),
        has_issues: z.boolean().optional(),
        has_pages: z.boolean().optional(),
        has_projects: z.boolean().optional(),
        has_wiki: z.boolean().optional(),
        homepage: z.string().optional(),
        hooks_url: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        is_template: z.boolean().optional(),
        issue_comment_url: z.string().optional(),
        issue_events_url: z.string().optional(),
        issues_url: z.string().optional(),
        keys_url: z.string().optional(),
        labels_url: z.string().optional(),
        language: z.string().optional(),
        languages_url: z.string().optional(),
        merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
        merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
        merges_url: z.string().optional(),
        milestones_url: z.string().optional(),
        mirror_url: z.string().optional(),
        name: z.string().optional(),
        network_count: z.number().int().optional(),
        node_id: z.string().optional(),
        notifications_url: z.string().optional(),
        open_issues_count: z.number().int().optional(),
        owner: z.object({
          avatar_url: z.string().optional(),
          events_url: z.string().optional(),
          followers_url: z.string().optional(),
          following_url: z.string().optional(),
          gists_url: z.string().optional(),
          gravatar_id: z.string().optional(),
          html_url: z.string().optional(),
          id: z.number().int().optional(),
          login: z.string().optional(),
          node_id: z.string().optional(),
          organizations_url: z.string().optional(),
          received_events_url: z.string().optional(),
          repos_url: z.string().optional(),
          site_admin: z.boolean().optional(),
          starred_url: z.string().optional(),
          subscriptions_url: z.string().optional(),
          type: z.string().optional(),
          url: z.string().optional(),
        }).optional(),
        permissions: z.object({
          admin: z.boolean().optional(),
          maintain: z.boolean().optional(),
          pull: z.boolean().optional(),
          push: z.boolean().optional(),
          triage: z.boolean().optional(),
        }).optional(),
        private: z.boolean().optional(),
        pulls_url: z.string().optional(),
        pushed_at: z.string().optional(),
        releases_url: z.string().optional(),
        size: z.number().int().optional(),
        squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
        squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
        ssh_url: z.string().optional(),
        stargazers_count: z.number().int().optional(),
        stargazers_url: z.string().optional(),
        statuses_url: z.string().optional(),
        subscribers_count: z.number().int().optional(),
        subscribers_url: z.string().optional(),
        subscription_url: z.string().optional(),
        svn_url: z.string().optional(),
        tags_url: z.string().optional(),
        teams_url: z.string().optional(),
        temp_clone_token: z.string().optional(),
        topics: z.array(z.string()).optional(),
        trees_url: z.string().optional(),
        updated_at: z.string().optional(),
        url: z.string().optional(),
        use_squash_pr_title_as_default: z.boolean().optional(),
        visibility: z.string().optional(),
        watchers_count: z.number().int().optional(),
      }).nullable().optional(),
      topics: z.array(z.string()).optional(),
      trees_url: z.string(),
      updated_at: z.string().datetime().nullable(),
      url: z.string().url(),
      use_squash_pr_title_as_default: z.boolean().optional().default(false).describe("Whether a squash merge commit can use the pull request title as default. **This property has been deprecated. Please use `squash_merge_commit_title` instead."),
      visibility: z.string().optional().default("public").describe("The repository visibility: public, private, or internal."),
      watchers: z.number().int(),
      watchers_count: z.number().int(),
      web_commit_signoff_required: z.boolean().optional().default(false).describe("Whether to require contributors to sign off on web-based commits"),
    }).optional().describe("A repository on GitHub."),
    repository_url: z.string().url(),
    score: z.number(),
    state: z.string(),
    state_reason: z.string().nullable().optional(),
    text_matches: z.array(z.object({
      fragment: z.string().optional(),
      matches: z.array(z.object({
        indices: z.array(z.number().int()).optional(),
        text: z.string().optional(),
      })).optional(),
      object_type: z.string().nullable().optional(),
      object_url: z.string().optional(),
      property: z.string().optional(),
    })).optional(),
    timeline_url: z.string().url().optional(),
    title: z.string(),
    updated_at: z.string().datetime(),
    url: z.string().url(),
    user: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().describe("A GitHub user."),
  })),
  total_count: z.number().int(),
})

export const searchIssuesAndPullRequests = pikkuSessionlessFunc({
  description: "Find issues by state and keyword. This method returns up to 100 results [per page](https://docs.github.com/rest/overview/resources-in-the-rest-api#pagination).\n\nWhen searching for issues, you can get text match metadata for the issue **title**, issue **body**, and issue **comment body** fields when you pass the `text-match` media type. For more details about how to receive highlighted\nsearch results, see [Text match metadata](https://docs.github.com/rest/reference/search#text-match-metadata).\n\nFor example, if you want to find the oldest unresolved Python bugs on Windows. Your query might look something like this.\n\n`q=windows+label:bug+language:python+state:open&sort=created&order=asc`\n\nThis query searches for the keyword `windows`, within any open issue that is labeled as `bug`. The search runs across repositories whose primary language is Python. The results are sorted by creation date in ascending order, which means the oldest issues appear first in the search results.\n\n**Note:** For [user-to-server](https://docs.github.com/developers/apps/identifying-and-authorizing-users-for-github-apps#user-to-server-requests) GitHub App requests, you can't retrieve a combination of issues and pull requests in a single query. Requests that don't include the `is:issue` or `is:pull-request` qualifier will receive an HTTP `422 Unprocessable Entity` response. To get results for both issues and pull requests, you must send separate queries for issues and pull requests. For more information about the `is` qualifier, see \"[Searching only issues or pull requests](https://docs.github.com/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-only-issues-or-pull-requests).\"",
  input: SearchIssuesAndPullRequestsInput,
  output: SearchIssuesAndPullRequestsOutput,
  errors: [ForbiddenError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("GET", "/search/issues", data) as any
  },
})
