// secret-scanning — Retrieve secret scanning alerts from a repository.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { NotFoundError } from '@pikku/core/errors'

export const SecretScanningListAlertsForOrgInput = z.object({
  org: z.string().describe("The organization name. The name is not case sensitive."),
  state: z.enum(["open", "resolved"]).optional().describe("Set to `open` or `resolved` to only list secret scanning alerts in a specific state."),
  secret_type: z.string().optional().describe("A comma-separated list of secret types to return. By default all secret types are returned.\nSee \"[Secret scanning patterns](https://docs.github.com/code-security/secret-scanning/secret-scanning-patterns#supported-secrets-for-advanced-security)\"\nfor a complete list of secret types."),
  resolution: z.string().optional().describe("A comma-separated list of resolutions. Only secret scanning alerts with one of these resolutions are listed. Valid resolutions are `false_positive`, `wont_fix`, `revoked`, `pattern_edited`, `pattern_deleted` or `used_in_tests`."),
  sort: z.enum(["created", "updated"]).optional().default("created").describe("The property to sort the results by. `created` means when the alert was created. `updated` means when the alert was updated or resolved."),
  direction: z.enum(["asc", "desc"]).optional().default("desc").describe("The direction to sort the results by."),
  page: z.number().int().optional().default(1).describe("Page number of the results to fetch."),
  per_page: z.number().int().optional().default(30).describe("The number of results per page (max 100)."),
  before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/overview/resources-in-the-rest-api#link-header). If specified, the query only searches for events before this cursor. To receive an initial cursor on your first request, include an empty \"before\" query string."),
  after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/overview/resources-in-the-rest-api#link-header). If specified, the query only searches for events after this cursor.  To receive an initial cursor on your first request, include an empty \"after\" query string."),
})

export const SecretScanningListAlertsForOrgOutput = z.array(z.object({
  created_at: z.string().datetime().optional().describe("The time that the alert was created in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  html_url: z.string().url().optional().describe("The GitHub URL of the alert resource."),
  locations_url: z.string().url().optional().describe("The REST API URL of the code locations for this alert."),
  number: z.number().int().optional().describe("The security alert number."),
  push_protection_bypassed: z.boolean().nullable().optional().describe("Whether push protection was bypassed for the detected secret."),
  push_protection_bypassed_at: z.string().datetime().nullable().optional().describe("The time that push protection was bypassed in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  push_protection_bypassed_by: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().optional().describe("A GitHub user."),
  repository: z.object({
    archive_url: z.string().describe("A template for the API URL to download the repository as an archive."),
    assignees_url: z.string().describe("A template for the API URL to list the available assignees for issues in the repository."),
    blobs_url: z.string().describe("A template for the API URL to create or retrieve a raw Git blob in the repository."),
    branches_url: z.string().describe("A template for the API URL to get information about branches in the repository."),
    collaborators_url: z.string().describe("A template for the API URL to get information about collaborators of the repository."),
    comments_url: z.string().describe("A template for the API URL to get information about comments on the repository."),
    commits_url: z.string().describe("A template for the API URL to get information about commits on the repository."),
    compare_url: z.string().describe("A template for the API URL to compare two commits or refs."),
    contents_url: z.string().describe("A template for the API URL to get the contents of the repository."),
    contributors_url: z.string().url().describe("A template for the API URL to list the contributors to the repository."),
    deployments_url: z.string().url().describe("The API URL to list the deployments of the repository."),
    description: z.string().nullable().describe("The repository description."),
    downloads_url: z.string().url().describe("The API URL to list the downloads on the repository."),
    events_url: z.string().url().describe("The API URL to list the events of the repository."),
    fork: z.boolean().describe("Whether the repository is a fork."),
    forks_url: z.string().url().describe("The API URL to list the forks of the repository."),
    full_name: z.string().describe("The full, globally unique, name of the repository."),
    git_commits_url: z.string().describe("A template for the API URL to get information about Git commits of the repository."),
    git_refs_url: z.string().describe("A template for the API URL to get information about Git refs of the repository."),
    git_tags_url: z.string().describe("A template for the API URL to get information about Git tags of the repository."),
    hooks_url: z.string().url().describe("The API URL to list the hooks on the repository."),
    html_url: z.string().url().describe("The URL to view the repository on GitHub.com."),
    id: z.number().int().describe("A unique identifier of the repository."),
    issue_comment_url: z.string().describe("A template for the API URL to get information about issue comments on the repository."),
    issue_events_url: z.string().describe("A template for the API URL to get information about issue events on the repository."),
    issues_url: z.string().describe("A template for the API URL to get information about issues on the repository."),
    keys_url: z.string().describe("A template for the API URL to get information about deploy keys on the repository."),
    labels_url: z.string().describe("A template for the API URL to get information about labels of the repository."),
    languages_url: z.string().url().describe("The API URL to get information about the languages of the repository."),
    merges_url: z.string().url().describe("The API URL to merge branches in the repository."),
    milestones_url: z.string().describe("A template for the API URL to get information about milestones of the repository."),
    name: z.string().describe("The name of the repository."),
    node_id: z.string().describe("The GraphQL identifier of the repository."),
    notifications_url: z.string().describe("A template for the API URL to get information about notifications on the repository."),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    private: z.boolean().describe("Whether the repository is private."),
    pulls_url: z.string().describe("A template for the API URL to get information about pull requests on the repository."),
    releases_url: z.string().describe("A template for the API URL to get information about releases on the repository."),
    stargazers_url: z.string().url().describe("The API URL to list the stargazers on the repository."),
    statuses_url: z.string().describe("A template for the API URL to get information about statuses of a commit."),
    subscribers_url: z.string().url().describe("The API URL to list the subscribers on the repository."),
    subscription_url: z.string().url().describe("The API URL to subscribe to notifications for this repository."),
    tags_url: z.string().url().describe("The API URL to get information about tags on the repository."),
    teams_url: z.string().url().describe("The API URL to list the teams on the repository."),
    trees_url: z.string().describe("A template for the API URL to create or retrieve a raw Git tree of the repository."),
    url: z.string().url().describe("The URL to get more information about the repository from the GitHub API."),
  }).optional().describe("A GitHub repository."),
  resolution: z.union([z.literal(null), z.literal("false_positive"), z.literal("wont_fix"), z.literal("revoked"), z.literal("used_in_tests")]).nullable().optional().describe("**Required when the `state` is `resolved`.** The reason for resolving the alert."),
  resolution_comment: z.string().nullable().optional().describe("The comment that was optionally added when this alert was closed"),
  resolved_at: z.string().datetime().nullable().optional().describe("The time that the alert was resolved in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  resolved_by: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().optional().describe("A GitHub user."),
  secret: z.string().optional().describe("The secret that was detected."),
  secret_type: z.string().optional().describe("The type of secret that secret scanning detected."),
  secret_type_display_name: z.string().optional().describe("User-friendly name for the detected secret, matching the `secret_type`.\nFor a list of built-in patterns, see \"[Secret scanning patterns](https://docs.github.com/code-security/secret-scanning/secret-scanning-patterns#supported-secrets-for-advanced-security).\""),
  state: z.enum(["open", "resolved"]).optional().describe("Sets the state of the secret scanning alert. You must provide `resolution` when you set the state to `resolved`."),
  updated_at: z.string().datetime().nullable().optional().describe("The time that the alert was last updated in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ`."),
  url: z.string().url().optional().describe("The REST API URL of the alert resource."),
}))

export const secretScanningListAlertsForOrg = pikkuSessionlessFunc({
  description: "Lists secret scanning alerts for eligible repositories in an organization, from newest to oldest.\nTo use this endpoint, you must be an administrator or security manager for the organization, and you must use an access token with the `repo` scope or `security_events` scope.\nFor public repositories, you may instead use the `public_repo` scope.\n\nGitHub Apps must have the `secret_scanning_alerts` read permission to use this endpoint.",
  input: SecretScanningListAlertsForOrgInput,
  output: SecretScanningListAlertsForOrgOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/orgs/{org}/secret-scanning/alerts", data) as any
  },
})
