// teams — Interact with GitHub Teams.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'
import { NotFoundError } from '@pikku/core/errors'

export const TeamsCheckPermissionsForRepoInOrgInput = z.object({
  org: z.string().describe("The organization name. The name is not case sensitive."),
  team_slug: z.string().describe("The slug of the team name."),
  owner: z.string().describe("The account owner of the repository. The name is not case sensitive."),
  repo: z.string().describe("The name of the repository. The name is not case sensitive."),
})

export const TeamsCheckPermissionsForRepoInOrgOutput = z.object({
  allow_auto_merge: z.boolean().optional().default(false).describe("Whether to allow Auto-merge to be used on pull requests."),
  allow_forking: z.boolean().optional().default(false).describe("Whether to allow forking this repo"),
  allow_merge_commit: z.boolean().optional().default(true).describe("Whether to allow merge commits for pull requests."),
  allow_rebase_merge: z.boolean().optional().default(true).describe("Whether to allow rebase merges for pull requests."),
  allow_squash_merge: z.boolean().optional().default(true).describe("Whether to allow squash merges for pull requests."),
  archive_url: z.string(),
  archived: z.boolean().default(false).describe("Whether the repository is archived."),
  assignees_url: z.string(),
  blobs_url: z.string(),
  branches_url: z.string(),
  clone_url: z.string(),
  collaborators_url: z.string(),
  comments_url: z.string(),
  commits_url: z.string(),
  compare_url: z.string(),
  contents_url: z.string(),
  contributors_url: z.string().url(),
  created_at: z.string().datetime().nullable(),
  default_branch: z.string().describe("The default branch of the repository."),
  delete_branch_on_merge: z.boolean().optional().default(false).describe("Whether to delete head branches when pull requests are merged"),
  deployments_url: z.string().url(),
  description: z.string().nullable(),
  disabled: z.boolean().describe("Returns whether or not this repository disabled."),
  downloads_url: z.string().url(),
  events_url: z.string().url(),
  fork: z.boolean(),
  forks: z.number().int(),
  forks_count: z.number().int(),
  forks_url: z.string().url(),
  full_name: z.string(),
  git_commits_url: z.string(),
  git_refs_url: z.string(),
  git_tags_url: z.string(),
  git_url: z.string(),
  has_downloads: z.boolean().default(true).describe("Whether downloads are enabled."),
  has_issues: z.boolean().default(true).describe("Whether issues are enabled."),
  has_pages: z.boolean(),
  has_projects: z.boolean().default(true).describe("Whether projects are enabled."),
  has_wiki: z.boolean().default(true).describe("Whether the wiki is enabled."),
  homepage: z.string().url().nullable(),
  hooks_url: z.string().url(),
  html_url: z.string().url(),
  id: z.number().int().describe("Unique identifier of the repository"),
  is_template: z.boolean().optional().default(false).describe("Whether this repository acts as a template that can be used to generate new repositories."),
  issue_comment_url: z.string(),
  issue_events_url: z.string(),
  issues_url: z.string(),
  keys_url: z.string(),
  labels_url: z.string(),
  language: z.string().nullable(),
  languages_url: z.string().url(),
  license: z.object({
    html_url: z.string().url().optional(),
    key: z.string(),
    name: z.string(),
    node_id: z.string(),
    spdx_id: z.string().nullable(),
    url: z.string().url().nullable(),
  }).nullable().describe("License Simple"),
  master_branch: z.string().optional(),
  merges_url: z.string().url(),
  milestones_url: z.string(),
  mirror_url: z.string().url().nullable(),
  name: z.string().describe("The name of the repository."),
  network_count: z.number().int().optional(),
  node_id: z.string(),
  notifications_url: z.string(),
  open_issues: z.number().int(),
  open_issues_count: z.number().int(),
  owner: z.object({
    avatar_url: z.string().url(),
    email: z.string().nullable().optional(),
    events_url: z.string(),
    followers_url: z.string().url(),
    following_url: z.string(),
    gists_url: z.string(),
    gravatar_id: z.string().nullable(),
    html_url: z.string().url(),
    id: z.number().int(),
    login: z.string(),
    name: z.string().nullable().optional(),
    node_id: z.string(),
    organizations_url: z.string().url(),
    received_events_url: z.string().url(),
    repos_url: z.string().url(),
    site_admin: z.boolean(),
    starred_at: z.string().optional(),
    starred_url: z.string(),
    subscriptions_url: z.string().url(),
    type: z.string(),
    url: z.string().url(),
  }).nullable().describe("A GitHub user."),
  permissions: z.object({
    admin: z.boolean(),
    maintain: z.boolean().optional(),
    pull: z.boolean(),
    push: z.boolean(),
    triage: z.boolean().optional(),
  }).optional(),
  private: z.boolean().default(false).describe("Whether the repository is private or public."),
  pulls_url: z.string(),
  pushed_at: z.string().datetime().nullable(),
  releases_url: z.string(),
  role_name: z.string().optional(),
  size: z.number().int(),
  ssh_url: z.string(),
  stargazers_count: z.number().int(),
  stargazers_url: z.string().url(),
  statuses_url: z.string(),
  subscribers_count: z.number().int().optional(),
  subscribers_url: z.string().url(),
  subscription_url: z.string().url(),
  svn_url: z.string().url(),
  tags_url: z.string().url(),
  teams_url: z.string().url(),
  temp_clone_token: z.string().optional(),
  template_repository: z.object({
    allow_auto_merge: z.boolean().optional().default(false).describe("Whether to allow Auto-merge to be used on pull requests."),
    allow_forking: z.boolean().optional().describe("Whether to allow forking this repo"),
    allow_merge_commit: z.boolean().optional().default(true).describe("Whether to allow merge commits for pull requests."),
    allow_rebase_merge: z.boolean().optional().default(true).describe("Whether to allow rebase merges for pull requests."),
    allow_squash_merge: z.boolean().optional().default(true).describe("Whether to allow squash merges for pull requests."),
    allow_update_branch: z.boolean().optional().default(false).describe("Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging."),
    anonymous_access_enabled: z.boolean().optional().describe("Whether anonymous git access is enabled for this repository"),
    archive_url: z.string(),
    archived: z.boolean().default(false).describe("Whether the repository is archived."),
    assignees_url: z.string(),
    blobs_url: z.string(),
    branches_url: z.string(),
    clone_url: z.string(),
    collaborators_url: z.string(),
    comments_url: z.string(),
    commits_url: z.string(),
    compare_url: z.string(),
    contents_url: z.string(),
    contributors_url: z.string().url(),
    created_at: z.string().datetime().nullable(),
    default_branch: z.string().describe("The default branch of the repository."),
    delete_branch_on_merge: z.boolean().optional().default(false).describe("Whether to delete head branches when pull requests are merged"),
    deployments_url: z.string().url(),
    description: z.string().nullable(),
    disabled: z.boolean().describe("Returns whether or not this repository disabled."),
    downloads_url: z.string().url(),
    events_url: z.string().url(),
    fork: z.boolean(),
    forks: z.number().int(),
    forks_count: z.number().int(),
    forks_url: z.string().url(),
    full_name: z.string(),
    git_commits_url: z.string(),
    git_refs_url: z.string(),
    git_tags_url: z.string(),
    git_url: z.string(),
    has_discussions: z.boolean().optional().default(false).describe("Whether discussions are enabled."),
    has_downloads: z.boolean().default(true).describe("Whether downloads are enabled."),
    has_issues: z.boolean().default(true).describe("Whether issues are enabled."),
    has_pages: z.boolean(),
    has_projects: z.boolean().default(true).describe("Whether projects are enabled."),
    has_wiki: z.boolean().default(true).describe("Whether the wiki is enabled."),
    homepage: z.string().url().nullable(),
    hooks_url: z.string().url(),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the repository"),
    is_template: z.boolean().optional().default(false).describe("Whether this repository acts as a template that can be used to generate new repositories."),
    issue_comment_url: z.string(),
    issue_events_url: z.string(),
    issues_url: z.string(),
    keys_url: z.string(),
    labels_url: z.string(),
    language: z.string().nullable(),
    languages_url: z.string().url(),
    license: z.object({
      html_url: z.string().url().optional(),
      key: z.string(),
      name: z.string(),
      node_id: z.string(),
      spdx_id: z.string().nullable(),
      url: z.string().url().nullable(),
    }).nullable().describe("License Simple"),
    master_branch: z.string().optional(),
    merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
    merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
    merges_url: z.string().url(),
    milestones_url: z.string(),
    mirror_url: z.string().url().nullable(),
    name: z.string().describe("The name of the repository."),
    network_count: z.number().int().optional(),
    node_id: z.string(),
    notifications_url: z.string(),
    open_issues: z.number().int(),
    open_issues_count: z.number().int(),
    organization: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).nullable().optional().describe("A GitHub user."),
    owner: z.object({
      avatar_url: z.string().url(),
      email: z.string().nullable().optional(),
      events_url: z.string(),
      followers_url: z.string().url(),
      following_url: z.string(),
      gists_url: z.string(),
      gravatar_id: z.string().nullable(),
      html_url: z.string().url(),
      id: z.number().int(),
      login: z.string(),
      name: z.string().nullable().optional(),
      node_id: z.string(),
      organizations_url: z.string().url(),
      received_events_url: z.string().url(),
      repos_url: z.string().url(),
      site_admin: z.boolean(),
      starred_at: z.string().optional(),
      starred_url: z.string(),
      subscriptions_url: z.string().url(),
      type: z.string(),
      url: z.string().url(),
    }).describe("A GitHub user."),
    permissions: z.object({
      admin: z.boolean(),
      maintain: z.boolean().optional(),
      pull: z.boolean(),
      push: z.boolean(),
      triage: z.boolean().optional(),
    }).optional(),
    private: z.boolean().default(false).describe("Whether the repository is private or public."),
    pulls_url: z.string(),
    pushed_at: z.string().datetime().nullable(),
    releases_url: z.string(),
    size: z.number().int().describe("The size of the repository. Size is calculated hourly. When a repository is initially created, the size is 0."),
    squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
    squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
    ssh_url: z.string(),
    stargazers_count: z.number().int(),
    stargazers_url: z.string().url(),
    starred_at: z.string().optional(),
    statuses_url: z.string(),
    subscribers_count: z.number().int().optional(),
    subscribers_url: z.string().url(),
    subscription_url: z.string().url(),
    svn_url: z.string().url(),
    tags_url: z.string().url(),
    teams_url: z.string().url(),
    temp_clone_token: z.string().optional(),
    template_repository: z.object({
      allow_auto_merge: z.boolean().optional(),
      allow_merge_commit: z.boolean().optional(),
      allow_rebase_merge: z.boolean().optional(),
      allow_squash_merge: z.boolean().optional(),
      allow_update_branch: z.boolean().optional(),
      archive_url: z.string().optional(),
      archived: z.boolean().optional(),
      assignees_url: z.string().optional(),
      blobs_url: z.string().optional(),
      branches_url: z.string().optional(),
      clone_url: z.string().optional(),
      collaborators_url: z.string().optional(),
      comments_url: z.string().optional(),
      commits_url: z.string().optional(),
      compare_url: z.string().optional(),
      contents_url: z.string().optional(),
      contributors_url: z.string().optional(),
      created_at: z.string().optional(),
      default_branch: z.string().optional(),
      delete_branch_on_merge: z.boolean().optional(),
      deployments_url: z.string().optional(),
      description: z.string().optional(),
      disabled: z.boolean().optional(),
      downloads_url: z.string().optional(),
      events_url: z.string().optional(),
      fork: z.boolean().optional(),
      forks_count: z.number().int().optional(),
      forks_url: z.string().optional(),
      full_name: z.string().optional(),
      git_commits_url: z.string().optional(),
      git_refs_url: z.string().optional(),
      git_tags_url: z.string().optional(),
      git_url: z.string().optional(),
      has_downloads: z.boolean().optional(),
      has_issues: z.boolean().optional(),
      has_pages: z.boolean().optional(),
      has_projects: z.boolean().optional(),
      has_wiki: z.boolean().optional(),
      homepage: z.string().optional(),
      hooks_url: z.string().optional(),
      html_url: z.string().optional(),
      id: z.number().int().optional(),
      is_template: z.boolean().optional(),
      issue_comment_url: z.string().optional(),
      issue_events_url: z.string().optional(),
      issues_url: z.string().optional(),
      keys_url: z.string().optional(),
      labels_url: z.string().optional(),
      language: z.string().optional(),
      languages_url: z.string().optional(),
      merge_commit_message: z.enum(["PR_BODY", "PR_TITLE", "BLANK"]).optional().describe("The default value for a merge commit message.\n\n- `PR_TITLE` - default to the pull request's title.\n- `PR_BODY` - default to the pull request's body.\n- `BLANK` - default to a blank commit message."),
      merge_commit_title: z.enum(["PR_TITLE", "MERGE_MESSAGE"]).optional().describe("The default value for a merge commit title.\n\n- `PR_TITLE` - default to the pull request's title.\n- `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name)."),
      merges_url: z.string().optional(),
      milestones_url: z.string().optional(),
      mirror_url: z.string().optional(),
      name: z.string().optional(),
      network_count: z.number().int().optional(),
      node_id: z.string().optional(),
      notifications_url: z.string().optional(),
      open_issues_count: z.number().int().optional(),
      owner: z.object({
        avatar_url: z.string().optional(),
        events_url: z.string().optional(),
        followers_url: z.string().optional(),
        following_url: z.string().optional(),
        gists_url: z.string().optional(),
        gravatar_id: z.string().optional(),
        html_url: z.string().optional(),
        id: z.number().int().optional(),
        login: z.string().optional(),
        node_id: z.string().optional(),
        organizations_url: z.string().optional(),
        received_events_url: z.string().optional(),
        repos_url: z.string().optional(),
        site_admin: z.boolean().optional(),
        starred_url: z.string().optional(),
        subscriptions_url: z.string().optional(),
        type: z.string().optional(),
        url: z.string().optional(),
      }).optional(),
      permissions: z.object({
        admin: z.boolean().optional(),
        maintain: z.boolean().optional(),
        pull: z.boolean().optional(),
        push: z.boolean().optional(),
        triage: z.boolean().optional(),
      }).optional(),
      private: z.boolean().optional(),
      pulls_url: z.string().optional(),
      pushed_at: z.string().optional(),
      releases_url: z.string().optional(),
      size: z.number().int().optional(),
      squash_merge_commit_message: z.enum(["PR_BODY", "COMMIT_MESSAGES", "BLANK"]).optional().describe("The default value for a squash merge commit message:\n\n- `PR_BODY` - default to the pull request's body.\n- `COMMIT_MESSAGES` - default to the branch's commit messages.\n- `BLANK` - default to a blank commit message."),
      squash_merge_commit_title: z.enum(["PR_TITLE", "COMMIT_OR_PR_TITLE"]).optional().describe("The default value for a squash merge commit title:\n\n- `PR_TITLE` - default to the pull request's title.\n- `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit)."),
      ssh_url: z.string().optional(),
      stargazers_count: z.number().int().optional(),
      stargazers_url: z.string().optional(),
      statuses_url: z.string().optional(),
      subscribers_count: z.number().int().optional(),
      subscribers_url: z.string().optional(),
      subscription_url: z.string().optional(),
      svn_url: z.string().optional(),
      tags_url: z.string().optional(),
      teams_url: z.string().optional(),
      temp_clone_token: z.string().optional(),
      topics: z.array(z.string()).optional(),
      trees_url: z.string().optional(),
      updated_at: z.string().optional(),
      url: z.string().optional(),
      use_squash_pr_title_as_default: z.boolean().optional(),
      visibility: z.string().optional(),
      watchers_count: z.number().int().optional(),
    }).nullable().optional(),
    topics: z.array(z.string()).optional(),
    trees_url: z.string(),
    updated_at: z.string().datetime().nullable(),
    url: z.string().url(),
    use_squash_pr_title_as_default: z.boolean().optional().default(false).describe("Whether a squash merge commit can use the pull request title as default. **This property has been deprecated. Please use `squash_merge_commit_title` instead."),
    visibility: z.string().optional().default("public").describe("The repository visibility: public, private, or internal."),
    watchers: z.number().int(),
    watchers_count: z.number().int(),
    web_commit_signoff_required: z.boolean().optional().default(false).describe("Whether to require contributors to sign off on web-based commits"),
  }).nullable().optional().describe("A repository on GitHub."),
  topics: z.array(z.string()).optional(),
  trees_url: z.string(),
  updated_at: z.string().datetime().nullable(),
  url: z.string().url(),
  visibility: z.string().optional().default("public").describe("The repository visibility: public, private, or internal."),
  watchers: z.number().int(),
  watchers_count: z.number().int(),
  web_commit_signoff_required: z.boolean().optional().default(false).describe("Whether to require contributors to sign off on web-based commits"),
}).describe("A team's access to a repository.")

export const teamsCheckPermissionsForRepoInOrg = pikkuSessionlessFunc({
  description: "Checks whether a team has `admin`, `push`, `maintain`, `triage`, or `pull` permission for a repository. Repositories inherited through a parent team will also be checked.\n\nYou can also get information about the specified repository, including what permissions the team grants on it, by passing the following custom [media type](https://docs.github.com/rest/overview/media-types/) via the `application/vnd.github.v3.repository+json` accept header.\n\nIf a team doesn't have permission for the repository, you will receive a `404 Not Found` response status.\n\n**Note:** You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/{org_id}/team/{team_id}/repos/{owner}/{repo}`.",
  input: TeamsCheckPermissionsForRepoInOrgInput,
  output: TeamsCheckPermissionsForRepoInOrgOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}", data) as any
  },
})
