// teams — Interact with GitHub Teams.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { ForbiddenError, UnprocessableContentError } from '@pikku/core/errors'

export const TeamsCreateInput = z.object({
  org: z.string().describe("The organization name. The name is not case sensitive."),
  description: z.string().optional().describe("The description of the team."),
  maintainers: z.array(z.string()).optional().describe("List GitHub IDs for organization members who will become team maintainers."),
  name: z.string().describe("The name of the team."),
  parent_team_id: z.number().int().optional().describe("The ID of a team to set as the parent team."),
  permission: z.enum(["pull", "push"]).optional().default("pull").describe("**Deprecated**. The permission that new repositories will be added to the team with when none is specified."),
  privacy: z.enum(["secret", "closed"]).optional().describe("The level of privacy this team should have. The options are:  \n**For a non-nested team:**  \n * `secret` - only visible to organization owners and members of this team.  \n * `closed` - visible to all members of this organization.  \nDefault: `secret`  \n**For a parent or child team:**  \n * `closed` - visible to all members of this organization.  \nDefault for child team: `closed`"),
  repo_names: z.array(z.string()).optional().describe("The full name (e.g., \"organization-name/repository-name\") of repositories to add the team to."),
})

export const TeamsCreateOutput = z.object({
  created_at: z.string().datetime(),
  description: z.string().nullable(),
  html_url: z.string().url(),
  id: z.number().int().describe("Unique identifier of the team"),
  ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
  members_count: z.number().int(),
  members_url: z.string(),
  name: z.string().describe("Name of the team"),
  node_id: z.string(),
  organization: z.object({
    avatar_url: z.string(),
    billing_email: z.string().email().nullable().optional(),
    blog: z.string().url().optional(),
    collaborators: z.number().int().nullable().optional(),
    company: z.string().optional(),
    created_at: z.string().datetime(),
    default_repository_permission: z.string().nullable().optional(),
    description: z.string().nullable(),
    disk_usage: z.number().int().nullable().optional(),
    email: z.string().email().optional(),
    events_url: z.string().url(),
    followers: z.number().int(),
    following: z.number().int(),
    has_organization_projects: z.boolean(),
    has_repository_projects: z.boolean(),
    hooks_url: z.string(),
    html_url: z.string().url(),
    id: z.number().int(),
    is_verified: z.boolean().optional(),
    issues_url: z.string(),
    location: z.string().optional(),
    login: z.string(),
    members_allowed_repository_creation_type: z.string().optional(),
    members_can_create_internal_repositories: z.boolean().optional(),
    members_can_create_pages: z.boolean().optional(),
    members_can_create_private_pages: z.boolean().optional(),
    members_can_create_private_repositories: z.boolean().optional(),
    members_can_create_public_pages: z.boolean().optional(),
    members_can_create_public_repositories: z.boolean().optional(),
    members_can_create_repositories: z.boolean().nullable().optional(),
    members_can_fork_private_repositories: z.boolean().nullable().optional(),
    members_url: z.string(),
    name: z.string().optional(),
    node_id: z.string(),
    owned_private_repos: z.number().int().optional(),
    plan: z.object({
      filled_seats: z.number().int().optional(),
      name: z.string(),
      private_repos: z.number().int(),
      seats: z.number().int().optional(),
      space: z.number().int(),
    }).optional(),
    private_gists: z.number().int().nullable().optional(),
    public_gists: z.number().int(),
    public_members_url: z.string(),
    public_repos: z.number().int(),
    repos_url: z.string().url(),
    total_private_repos: z.number().int().optional(),
    twitter_username: z.string().nullable().optional(),
    two_factor_requirement_enabled: z.boolean().nullable().optional(),
    type: z.string(),
    updated_at: z.string().datetime(),
    url: z.string().url(),
    web_commit_signoff_required: z.boolean().optional(),
  }).describe("Team Organization"),
  parent: z.object({
    description: z.string().nullable().describe("Description of the team"),
    html_url: z.string().url(),
    id: z.number().int().describe("Unique identifier of the team"),
    ldap_dn: z.string().optional().describe("Distinguished Name (DN) that team maps to within LDAP environment"),
    members_url: z.string(),
    name: z.string().describe("Name of the team"),
    node_id: z.string(),
    permission: z.string().describe("Permission that the team will have for its repositories"),
    privacy: z.string().optional().describe("The level of privacy this team should have"),
    repositories_url: z.string().url(),
    slug: z.string(),
    url: z.string().url().describe("URL for the team"),
  }).nullable().optional().describe("Groups of organization members that gives permissions on specified repositories."),
  permission: z.string().describe("Permission that the team will have for its repositories"),
  privacy: z.enum(["closed", "secret"]).optional().describe("The level of privacy this team should have"),
  repos_count: z.number().int(),
  repositories_url: z.string().url(),
  slug: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url().describe("URL for the team"),
}).describe("Groups of organization members that gives permissions on specified repositories.")

export const teamsCreate = pikkuSessionlessFunc({
  description: "To create a team, the authenticated user must be a member or owner of `{org}`. By default, organization members can create teams. Organization owners can limit team creation to organization owners. For more information, see \"[Setting team creation permissions](https://docs.github.com/articles/setting-team-creation-permissions-in-your-organization).\"\n\nWhen you create a new team, you automatically become a team maintainer without explicitly adding yourself to the optional array of `maintainers`. For more information, see \"[About teams](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/about-teams)\".",
  input: TeamsCreateInput,
  output: TeamsCreateOutput,
  errors: [ForbiddenError, UnprocessableContentError],
  func: async ({ github }, data) => {
    return github.call("POST", "/orgs/{org}/teams", data) as any
  },
})
