// users — Interact with and view information about users and also current user.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { NotFoundError } from '@pikku/core/errors'

export const UsersGetByUsernameInput = z.object({
  username: z.string().describe("The handle for the GitHub user account."),
})

export const UsersGetByUsernameOutput = z.union([z.object({
  avatar_url: z.string().url(),
  bio: z.string().nullable(),
  blog: z.string().nullable(),
  business_plus: z.boolean().optional(),
  collaborators: z.number().int(),
  company: z.string().nullable(),
  created_at: z.string().datetime(),
  disk_usage: z.number().int(),
  email: z.string().email().nullable(),
  events_url: z.string(),
  followers: z.number().int(),
  followers_url: z.string().url(),
  following: z.number().int(),
  following_url: z.string(),
  gists_url: z.string(),
  gravatar_id: z.string().nullable(),
  hireable: z.boolean().nullable(),
  html_url: z.string().url(),
  id: z.number().int(),
  ldap_dn: z.string().optional(),
  location: z.string().nullable(),
  login: z.string(),
  name: z.string().nullable(),
  node_id: z.string(),
  organizations_url: z.string().url(),
  owned_private_repos: z.number().int(),
  plan: z.object({
    collaborators: z.number().int(),
    name: z.string(),
    private_repos: z.number().int(),
    space: z.number().int(),
  }).optional(),
  private_gists: z.number().int(),
  public_gists: z.number().int(),
  public_repos: z.number().int(),
  received_events_url: z.string().url(),
  repos_url: z.string().url(),
  site_admin: z.boolean(),
  starred_url: z.string(),
  subscriptions_url: z.string().url(),
  suspended_at: z.string().datetime().nullable().optional(),
  total_private_repos: z.number().int(),
  twitter_username: z.string().nullable().optional(),
  two_factor_authentication: z.boolean(),
  type: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url(),
}), z.object({
  avatar_url: z.string().url(),
  bio: z.string().nullable(),
  blog: z.string().nullable(),
  collaborators: z.number().int().optional(),
  company: z.string().nullable(),
  created_at: z.string().datetime(),
  disk_usage: z.number().int().optional(),
  email: z.string().email().nullable(),
  events_url: z.string(),
  followers: z.number().int(),
  followers_url: z.string().url(),
  following: z.number().int(),
  following_url: z.string(),
  gists_url: z.string(),
  gravatar_id: z.string().nullable(),
  hireable: z.boolean().nullable(),
  html_url: z.string().url(),
  id: z.number().int(),
  location: z.string().nullable(),
  login: z.string(),
  name: z.string().nullable(),
  node_id: z.string(),
  organizations_url: z.string().url(),
  owned_private_repos: z.number().int().optional(),
  plan: z.object({
    collaborators: z.number().int(),
    name: z.string(),
    private_repos: z.number().int(),
    space: z.number().int(),
  }).optional(),
  private_gists: z.number().int().optional(),
  public_gists: z.number().int(),
  public_repos: z.number().int(),
  received_events_url: z.string().url(),
  repos_url: z.string().url(),
  site_admin: z.boolean(),
  starred_url: z.string(),
  subscriptions_url: z.string().url(),
  suspended_at: z.string().datetime().nullable().optional(),
  total_private_repos: z.number().int().optional(),
  twitter_username: z.string().nullable().optional(),
  type: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url(),
})])

export const usersGetByUsername = pikkuSessionlessFunc({
  description: "Provides publicly available information about someone with a GitHub account.\n\nGitHub Apps with the `Plan` user permission can use this endpoint to retrieve information about a user's GitHub plan. The GitHub App must be authenticated as a user. See \"[Identifying and authorizing users for GitHub Apps](https://docs.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/)\" for details about authentication. For an example response, see 'Response with GitHub plan information' below\"\n\nThe `email` key in the following response is the publicly visible email address from your GitHub [profile page](https://github.com/settings/profile). When setting up your profile, you can select a primary email address to be “public” which provides an email entry for this endpoint. If you do not set a public email address for `email`, then it will have a value of `null`. You only see publicly visible email addresses when authenticated with GitHub. For more information, see [Authentication](https://docs.github.com/rest/overview/resources-in-the-rest-api#authentication).\n\nThe Emails API enables you to list all of your email addresses, and toggle a primary email to be visible publicly. For more information, see \"[Emails API](https://docs.github.com/rest/reference/users#emails)\".",
  input: UsersGetByUsernameInput,
  output: UsersGetByUsernameOutput,
  errors: [NotFoundError],
  func: async ({ github }, data) => {
    return github.call("GET", "/users/{username}", data) as any
  },
})
