// users — Interact with and view information about users and also current user.

import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { UnauthorizedError, ForbiddenError } from '@pikku/core/errors'

export const UsersGetAuthenticatedOutput = z.union([z.object({
  avatar_url: z.string().url(),
  bio: z.string().nullable(),
  blog: z.string().nullable(),
  business_plus: z.boolean().optional(),
  collaborators: z.number().int(),
  company: z.string().nullable(),
  created_at: z.string().datetime(),
  disk_usage: z.number().int(),
  email: z.string().email().nullable(),
  events_url: z.string(),
  followers: z.number().int(),
  followers_url: z.string().url(),
  following: z.number().int(),
  following_url: z.string(),
  gists_url: z.string(),
  gravatar_id: z.string().nullable(),
  hireable: z.boolean().nullable(),
  html_url: z.string().url(),
  id: z.number().int(),
  ldap_dn: z.string().optional(),
  location: z.string().nullable(),
  login: z.string(),
  name: z.string().nullable(),
  node_id: z.string(),
  organizations_url: z.string().url(),
  owned_private_repos: z.number().int(),
  plan: z.object({
    collaborators: z.number().int(),
    name: z.string(),
    private_repos: z.number().int(),
    space: z.number().int(),
  }).optional(),
  private_gists: z.number().int(),
  public_gists: z.number().int(),
  public_repos: z.number().int(),
  received_events_url: z.string().url(),
  repos_url: z.string().url(),
  site_admin: z.boolean(),
  starred_url: z.string(),
  subscriptions_url: z.string().url(),
  suspended_at: z.string().datetime().nullable().optional(),
  total_private_repos: z.number().int(),
  twitter_username: z.string().nullable().optional(),
  two_factor_authentication: z.boolean(),
  type: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url(),
}), z.object({
  avatar_url: z.string().url(),
  bio: z.string().nullable(),
  blog: z.string().nullable(),
  collaborators: z.number().int().optional(),
  company: z.string().nullable(),
  created_at: z.string().datetime(),
  disk_usage: z.number().int().optional(),
  email: z.string().email().nullable(),
  events_url: z.string(),
  followers: z.number().int(),
  followers_url: z.string().url(),
  following: z.number().int(),
  following_url: z.string(),
  gists_url: z.string(),
  gravatar_id: z.string().nullable(),
  hireable: z.boolean().nullable(),
  html_url: z.string().url(),
  id: z.number().int(),
  location: z.string().nullable(),
  login: z.string(),
  name: z.string().nullable(),
  node_id: z.string(),
  organizations_url: z.string().url(),
  owned_private_repos: z.number().int().optional(),
  plan: z.object({
    collaborators: z.number().int(),
    name: z.string(),
    private_repos: z.number().int(),
    space: z.number().int(),
  }).optional(),
  private_gists: z.number().int().optional(),
  public_gists: z.number().int(),
  public_repos: z.number().int(),
  received_events_url: z.string().url(),
  repos_url: z.string().url(),
  site_admin: z.boolean(),
  starred_url: z.string(),
  subscriptions_url: z.string().url(),
  suspended_at: z.string().datetime().nullable().optional(),
  total_private_repos: z.number().int().optional(),
  twitter_username: z.string().nullable().optional(),
  type: z.string(),
  updated_at: z.string().datetime(),
  url: z.string().url(),
})])

export const usersGetAuthenticated = pikkuSessionlessFunc({
  description: "If the authenticated user is authenticated through basic authentication or OAuth with the `user` scope, then the response lists public and private profile information.\n\nIf the authenticated user is authenticated through OAuth without the `user` scope, then the response lists only public profile information.",
  output: UsersGetAuthenticatedOutput,
  errors: [UnauthorizedError, ForbiddenError],
  func: async ({ github }) => {
    return github.call("GET", "/user") as any
  },
})
