export { mysqlSecretsSchema, type MysqlSecrets } from './mysql.secret.js'

export { WhereCondition, WhereClause, OrderByClause, escapeIdentifier, buildWhereClause, buildOrderByClause } from './shared.js'

export { executeQuery, ExecuteQueryInput, ExecuteQueryOutput } from './functions/database/execute-query.function.js'
export { select, SelectInput, SelectOutput } from './functions/database/select.function.js'
export { insert, InsertInput, InsertOutput } from './functions/database/insert.function.js'
export { insertMany, InsertManyInput, InsertManyOutput } from './functions/database/insert-many.function.js'
export { update, UpdateInput, UpdateOutput } from './functions/database/update.function.js'
export { deleteRows, DeleteInput, DeleteOutput } from './functions/database/delete.function.js'
export { truncate, TruncateInput, TruncateOutput } from './functions/database/truncate.function.js'
export { upsert, UpsertInput, UpsertOutput } from './functions/database/upsert.function.js'
export { dropTable, DropTableInput, DropTableOutput } from './functions/database/drop-table.function.js'
export { count, CountInput, CountOutput } from './functions/database/count.function.js'
export { describeTable, DescribeTableInput, DescribeTableOutput, ColumnInfo } from './functions/database/describe-table.function.js'
export { listTables, ListTablesInput, ListTablesOutput } from './functions/database/list-tables.function.js'
export { transaction, TransactionInput, TransactionOutput } from './functions/database/transaction.function.js'
