import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const ListCustomRolesOutput = z.object({
  custom_roles: z.array(z.object({
    configuration: z.object({
      actions_access: z.string().optional().describe("What level of actions access the agent has. Allowed values: \"none\", \"workflows_and_zendesk\", \"all\""),
      assign_tickets_to_any_group: z.boolean().optional().describe("Whether or not the agent can assign tickets to any group"),
      capacity_rules_access: z.string().optional().describe("What the agent can do with capacity rules. Allowed values: \"none\", \"all\", \"view-and-assign\""),
      chat_access: z.boolean().optional().describe("Whether or not the agent has access to Chat"),
      end_user_list_access: z.string().optional().describe("Whether or not the agent can view lists of user profiles. Allowed values: \"full\", \"none\""),
      end_user_profile_access: z.string().optional().describe("What the agent can do with end-user profiles. Allowed values: \"edit\", \"edit-within-org\", \"full\", \"readonly\""),
      execute_it_asset_management_actions: z.boolean().optional().describe("Whether or not the agent can execute IT asset management actions"),
      explore_access: z.string().optional().describe("Allowed values: \"edit\", \"full\", \"none\", \"readonly\""),
      export_views: z.boolean().optional().describe("Whether or not the agent can export views"),
      forum_access: z.string().optional().describe("The kind of access the agent has to Guide. Allowed values: \"edit-topics\", \"full\", \"readonly\""),
      forum_access_restricted_content: z.boolean().optional(),
      group_access: z.boolean().optional().describe("Whether or not the agent can add or modify groups"),
      light_agent: z.boolean().optional(),
      macro_access: z.string().optional().describe("What the agent can do with macros. Allowed values: \"full\", \"manage-group\", \"manage-personal\", \"readonly\""),
      manage_api_credentials: z.boolean().optional().describe("Whether the agent can manage API credentials"),
      manage_business_rules: z.boolean().optional().describe("Whether or not the agent can manage business rules"),
      manage_contextual_workspaces: z.boolean().optional().describe("Whether or not the agent can view, add, and edit contextual workspaces"),
      manage_dynamic_content: z.boolean().optional().describe("Whether or not the agent can access dynamic content"),
      manage_extensions_and_channels: z.boolean().optional().describe("Whether or not the agent can manage channels and extensions"),
      manage_facebook: z.boolean().optional().describe("Whether or not the agent can manage Facebook pages"),
      manage_organization_fields: z.boolean().optional().describe("Whether or not the agent can create and manage organization fields"),
      manage_ticket_fields: z.boolean().optional().describe("Whether or not the agent can create and manage ticket fields"),
      manage_ticket_forms: z.boolean().optional().describe("Whether or not the agent can create and manage ticket forms"),
      manage_ticket_settings: z.boolean().optional().describe("Whether or not the agent can manage ticket settings such as comments, attachments, followers, assignments, and notifications"),
      manage_user_fields: z.boolean().optional().describe("Whether or not the agent can create and manage user fields"),
      manage_user_own_contacts: z.boolean().optional().describe("Whether or not the agent can manage their own contact information"),
      manage_user_own_forwarding_numbers: z.boolean().optional().describe("Whether or not the agent can manage their own forwarding numbers"),
      manage_user_own_photo: z.boolean().optional().describe("Whether or not the agent can manage their own profile photo"),
      moderate_forums: z.boolean().optional(),
      modify_closed_tickets: z.boolean().optional().describe("Whether or not the agent can modify closed tickets"),
      organization_editing: z.boolean().optional().describe("Whether or not the agent can add or modify organizations"),
      organization_notes_editing: z.boolean().optional().describe("Whether or not the agent can add or modify organization notes"),
      report_access: z.string().optional().describe("What the agent can do with reports. Allowed values: \"full\", \"none\", \"readonly\""),
      side_conversation_create: z.boolean().optional().describe("Whether or not the agent can contribute to side conversations"),
      ticket_access: z.string().optional().describe("What kind of tickets the agent can access. Allowed values: \"all\", \"assigned-only\", \"within-groups\", \"within-groups-and-public-groups\", \"within-organization\""),
      ticket_comment_access: z.string().optional().describe("What type of comments the agent can make. Allowed values: \"public\", \"none\""),
      ticket_deletion: z.boolean().optional().describe("Whether or not the agent can delete tickets"),
      ticket_editing: z.boolean().optional().describe("Whether or not the agent can edit ticket properties"),
      ticket_merge: z.boolean().optional().describe("Whether or not the agent can merge tickets"),
      ticket_tag_editing: z.boolean().optional().describe("Whether or not the agent can edit ticket tags"),
      twitter_search_access: z.boolean().optional(),
      update_user_own_alias: z.boolean().optional().describe("Whether or not the agent can update their own alias"),
      update_user_own_name: z.boolean().optional().describe("Whether or not the agent can update their own name"),
      update_user_own_signature: z.boolean().optional().describe("Whether or not the agent can update their own signature"),
      user_view_access: z.string().optional().describe("What the agent can do with customer lists. Allowed values: \"full\", \"manage-group\", \"manage-personal\", \"none\", \"readonly\""),
      view_access: z.string().optional().describe("What the agent can do with views. Allowed values: \"full\", \"manage-group\", \"manage-personal\", \"playonly\", \"readonly\""),
      view_access_logs: z.boolean().optional().describe("Whether or not the agent can view access logs."),
      view_audit_logs: z.boolean().optional().describe("Whether or not the agent can view audit logs."),
      view_deleted_tickets: z.boolean().optional().describe("Whether or not the agent can view deleted tickets"),
      view_filter_tickets: z.boolean().optional().describe("Whether or not the agent can view and apply filters to tickets"),
      voice_access: z.boolean().optional().describe("Whether or not the agent can answer and place calls to end users"),
      voice_dashboard_access: z.boolean().optional().describe("Whether or not the agent can view details about calls on the Talk dashboard"),
    }).optional().describe("Configuration settings for the role. See [Configuration](#configuration)"),
    created_at: z.string().datetime().optional().describe("The time the record was created"),
    description: z.string().optional().describe("A description of the role"),
    id: z.number().int().optional().describe("Automatically assigned on creation"),
    name: z.string().describe("Name of the custom role"),
    role_type: z.number().int().describe("The user's role. 0 stands for a custom agent, 1 for a light agent, 2 for a chat agent, 3 for a contributor, 4 for an admin and 5 for a billing admin. See [Understanding standard agent roles in Zendesk Support](https://support.zendesk.com/hc/en-us/articles/4409155971354-Understanding-standard-agent-roles-in-Zendesk-Support) in Zendesk help"),
    team_member_count: z.number().int().optional().describe("The number of team members assigned to this role"),
    updated_at: z.string().datetime().optional().describe("The time the record was last updated"),
  })).optional(),
})

export const listCustomRoles = pikkuSessionlessFunc({
  description: "#### Availability\n\n* Accounts on the Enterprise plan or above\n\n#### Allowed For\n\n* Agents",
  output: ListCustomRolesOutput,
  func: async ({ zendesk }) => {
    return zendesk.call("GET", "/api/v2/custom_roles") as any
  },
})
