import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'
import { NotFoundError } from '@pikku/core/errors'

export const ShowTicketByMessagingConversationIdInput = z.object({
  conversation_id: z.string().describe("The id of the Sunshine Conversations conversation."),
})

export const ShowTicketByMessagingConversationIdOutput = z.object({
  ticket: z.object({
    additional_collaborators: z.array(z.object({
      email: z.string().email().optional(),
      name: z.string().optional(),
    })).optional().describe("Write only. An array of numeric IDs, emails, or objects containing name and email properties. See [Setting Collaborators](/api-reference/ticketing/tickets/tickets/#setting-collaborators). An email notification is sent to them when the ticket is updated"),
    allow_attachments: z.boolean().optional().describe("Permission for agents to add add attachments to a comment. Defaults to true"),
    allow_channelback: z.boolean().optional().describe("Is false if channelback is disabled, true otherwise. Only applicable for channels framework ticket"),
    assignee_email: z.string().email().optional().describe("Write only. The email address of the agent to assign the ticket to"),
    assignee_id: z.number().int().nullable().optional().describe("The agent currently assigned to the ticket"),
    attribute_value_ids: z.array(z.number().int()).optional().describe("Write only. An array of the IDs of attribute values to be associated with the ticket"),
    brand_id: z.number().int().nullable().optional().describe("The id of the brand this ticket is associated with. See [Setting up multiple brands](https://support.zendesk.com/hc/en-us/articles/4408829476378)"),
    collaborator_ids: z.array(z.number().int()).optional().describe("The ids of users currently CC'ed on the ticket"),
    collaborators: z.array(z.object({
      email: z.string().email().optional(),
      name: z.string().optional(),
    })).optional().describe("Write only. Users to add as cc's when creating a ticket. See [Setting Collaborators](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#setting-collaborators)"),
    comment: z.object({
      add_short_url: z.boolean().optional().describe("Internal flag for adding short URLs to the comment"),
      attachments: z.array(z.object({
        content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
        content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
        deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
        file_name: z.string().optional().describe("The name of the image file"),
        height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
        id: z.number().int().optional().describe("Automatically assigned when created"),
        inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
        malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
        malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
        mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
        size: z.number().int().optional().describe("The size of the image file in bytes"),
        url: z.string().optional().describe("A URL to access the attachment details"),
        width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
        thumbnails: z.array(z.object({
          content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
          content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
          deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
          file_name: z.string().optional().describe("The name of the image file"),
          height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
          id: z.number().int().optional().describe("Automatically assigned when created"),
          inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
          malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
          malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
          mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
          size: z.number().int().optional().describe("The size of the image file in bytes"),
          url: z.string().optional().describe("A URL to access the attachment details"),
          width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
        })).optional().describe("An array of attachment objects. Note that photo thumbnails do not have thumbnails"),
      })).optional().describe("Attachments, if any. See [Attachment](/api-reference/ticketing/tickets/ticket-attachments/)"),
      audit_id: z.number().int().optional().describe("The id of the ticket audit record. See [Show Audit](/api-reference/ticketing/tickets/ticket_audits/#show-audit)"),
      author_id: z.number().int().nullable().optional().describe("The id of the comment author. If null or omitted on create, defaults to the authenticated user. See [Author id](#author-id)"),
      body: z.string().optional().describe("The comment string. See [Bodies](#bodies)"),
      channel_back: z.string().optional().describe("Internal channel back identifier for the comment"),
      channel_source_id: z.string().nullable().optional().describe("Internal channel source identifier for the comment"),
      created_at: z.string().datetime().optional().describe("The time the comment was created"),
      html_body: z.string().optional().describe("The comment formatted as HTML. See [Bodies](#bodies)"),
      id: z.number().int().optional().describe("Automatically assigned when the comment is created"),
      metadata: z.record(z.string(), z.unknown()).optional().describe("System information (web client, IP address, etc.) and comment flags, if any. See [Comment flags](#comment-flags)"),
      plain_body: z.string().optional().describe("The comment presented as plain text. See [Bodies](#bodies)"),
      public: z.boolean().optional().describe("true if a public comment; false if an internal note. The initial value set on ticket creation persists for any additional comment unless you change it"),
      translate_to: z.string().nullable().optional().describe("The locale code to translate the comment body to."),
      type: z.string().optional().describe("`Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)"),
      uploads: z.array(z.string()).optional().describe("List of tokens received from [uploading files](/api-reference/ticketing/tickets/ticket-attachments/#upload-files) for comment attachments. The files are attached by creating or updating tickets with the tokens. See [Attaching files](/api-reference/ticketing/tickets/tickets/#attaching-files) in Tickets"),
      via: z.object({
        channel: z.string().optional().describe("This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\""),
        source: z.record(z.string(), z.unknown()).optional().describe("For some channels a source object gives more information about how or why the ticket or event was created"),
      }).optional().describe("Describes how the object was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)"),
    }).optional(),
    created_at: z.string().datetime().optional().describe("When this record was created"),
    custom_fields: z.array(z.object({
      id: z.number().int().describe("The ID of the custom field"),
      value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional().describe("The value to assign to the custom field.\nType depends on the field configuration:\n- Text/textarea: string\n- Checkbox: boolean or \"true\"/\"false\" string\n- Dropdown/tagger: string or array of strings (multi-select)\n- Number/decimal: number or string representation\n- Date: string (ISO 8601 format)\n"),
    })).optional().describe("Custom field values to set on the ticket.\nEach entry specifies a field ID and its value.\nSee [Setting custom field values](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#setting-custom-field-values)\n"),
    custom_status_id: z.number().int().nullable().optional().describe("The custom ticket status id of the ticket. See [custom ticket statuses](#custom-ticket-statuses)"),
    description: z.string().optional().describe("The first comment on the ticket. When [creating a ticket](#create-ticket), use `comment` to set the description.\nSee [Description and first comment](#description-and-first-comment).\nOn create, can be set directly as an alternative to `comment`. Silently ignored on update.\n"),
    due_at: z.string().datetime().nullable().optional().describe("If this is a ticket of type \"task\" it has a due date.  Due date format uses [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) format"),
    email_cc_ids: z.array(z.number().int()).optional().describe("The ids of agents or end users currently CC'ed on the ticket. See [CCs and followers resources](https://support.zendesk.com/hc/en-us/articles/4408822451482) in the Support Help Center"),
    email_ccs: z.array(z.object({
      action: z.enum(["put", "delete"]).optional(),
      user_email: z.string().optional(),
      user_id: z.number().int().optional(),
      user_name: z.string().optional(),
    })).nullable().optional().describe("Write only. An array of objects that represent agent or end users email CCs to add or delete from the ticket. See [Setting email CCs](/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#setting-email-ccs). Ignored when [CCs and followers](https://support.zendesk.com/hc/en-us/articles/4408822451482) is not enabled"),
    encoded_id: z.string().optional().describe("An encoded string representing the ticket's unique identifier"),
    external_id: z.string().nullable().optional().describe("An id you can use to link Zendesk Support tickets to local records"),
    fields: z.array(z.object({
      id: z.number().int().describe("The ID of the custom field"),
      value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional().describe("The value to assign to the custom field.\nType depends on the field configuration:\n- Text/textarea: string\n- Checkbox: boolean or \"true\"/\"false\" string\n- Dropdown/tagger: string or array of strings (multi-select)\n- Number/decimal: number or string representation\n- Date: string (ISO 8601 format)\n"),
    })).optional().describe("Alias for custom_fields. Custom field values to set on the ticket.\nEach entry specifies a field ID and its value.\n"),
    follower_ids: z.array(z.number().int()).optional().describe("The ids of agents currently following the ticket. Ignored when [CCs and followers](https://support.zendesk.com/hc/en-us/articles/4408822451482) is not enabled"),
    followers: z.array(z.object({
      action: z.enum(["put", "delete"]).optional(),
      user_email: z.string().email().optional(),
      user_id: z.number().int().optional(),
      user_name: z.string().nullable().optional(),
    })).optional().describe("Write only. An array of objects that represents agent followers to add or delete from the ticket. See [Setting followers](/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#setting-followers). Ignored when [CCs and followers](https://support.zendesk.com/hc/en-us/articles/4408822451482) is not enabled"),
    followup_ids: z.array(z.number().int()).optional().describe("The ids of the followups created from this ticket. Ids are only visible once the ticket is closed"),
    forum_topic_id: z.number().int().optional().describe("The topic in the Zendesk Web portal this ticket originated from, if any. The Web portal is deprecated"),
    from_messaging_channel: z.boolean().optional().describe("If true, the ticket's [via type](/documentation/ticketing/reference-guides/via-object-reference/) is a messaging channel."),
    generated_timestamp: z.number().int().optional().describe("A Unix timestamp that represents the most accurate reading of when this record was last updated. It is updated for all ticket updates, including system updates"),
    group_id: z.number().int().nullable().optional().describe("The group this ticket is assigned to"),
    has_incidents: z.boolean().optional().describe("Is true if a ticket is a problem type and has one or more incidents linked to it. Otherwise, the value is false."),
    id: z.number().int().optional().describe("Automatically assigned when the ticket is created"),
    is_public: z.boolean().optional().describe("Is true if any comments are public, false otherwise"),
    macro_id: z.number().int().optional().describe("Write only. A single macro ID to be recorded in the ticket audit"),
    macro_ids: z.array(z.number().int()).optional().describe("Write only. List of macro IDs to be recorded in the ticket audit"),
    metadata: z.record(z.string(), z.unknown()).optional().describe("Write only. Metadata for the audit. In the `audit` object, the data is specified in the `custom` property of the `metadata` object. See [Setting Metadata](/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#setting-metadata)"),
    organization_id: z.number().int().nullable().optional().describe("The organization of the requester. You can only specify the ID of an organization associated with the requester. See [Organization Memberships](/api-reference/ticketing/organizations/organization_memberships/)"),
    origin_zrn: z.string().optional().describe("Write only. The Zendesk Resource Name (ZRN) of the origin for this ticket"),
    priority: z.enum(["urgent", "high", "normal", "low"]).nullable().optional().describe("The urgency with which the ticket should be addressed"),
    problem_id: z.number().int().nullable().optional().describe("For tickets of type \"incident\", the ID of the problem the incident is linked to"),
    raw_subject: z.string().optional().describe("The dynamic content placeholder, if present, or the \"subject\" value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/).\nWhen set on create or update, overrides the `subject` field.\n"),
    recipient: z.string().optional().describe("The original recipient e-mail address of the ticket. Notification emails for the ticket are sent from this address"),
    requester: z.union([z.string(), z.number().int(), z.object({
      email: z.string().email().optional().describe("The user's primary email address"),
      locale: z.string().optional().describe("The user's locale (e.g., \"en-US\")"),
      locale_id: z.number().int().optional().describe("The user's locale ID"),
      name: z.string().optional().describe("The user's name"),
      organization_id: z.number().int().optional().describe("The organization ID to associate with the user"),
      role: z.string().optional().describe("The user's role (e.g., \"end-user\", \"agent\", \"admin\")"),
      verified: z.boolean().optional().describe("Whether the user's email is verified"),
    })]).optional().describe("Write only. Alternative to requester_id for specifying the ticket requester.\n\nCan be provided as:\n- Email string: \"user@example.com\"\n- User ID integer: 12345\n- User object: {name: \"John Doe\", email: \"john@example.com\"}\n\nIf both requester and requester_id are provided, requester_id takes precedence.\n\nWhen creating a ticket, if the user doesn't exist, they may be created\nautomatically depending on account settings.\n"),
    requester_id: z.number().int().nullable().optional().describe("The user who requested this ticket"),
    safe_update: z.boolean().optional().describe("Write only. Optional boolean. When true and an `updated_stamp` date is included, protects against ticket update collisions and returns a message to let you know if one occurs. See [Protecting against ticket update collisions](/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#protecting-against-ticket-update-collisions). A value of false has the same effect as true. Omit the property to force the updates to not be safe"),
    satisfaction_probability: z.number().optional().describe("The predicted satisfaction probability score"),
    satisfaction_rating: z.record(z.string(), z.unknown()).optional().describe("The satisfaction rating of the ticket, if it exists, or the state of satisfaction, \"offered\" or \"unoffered\". The value is null for plan types that don't support CSAT"),
    sharing_agreement_ids: z.array(z.number().int()).optional().describe("An array of the numeric IDs of sharing agreements. Note that this replaces any existing agreements"),
    sharing_agreements: z.union([z.object({
      custom_fields: z.array(z.object({
        id: z.number().int().describe("The ID of the custom field"),
        value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional().describe("The value to assign to the custom field.\nType depends on the field configuration:\n- Text/textarea: string\n- Checkbox: boolean or \"true\"/\"false\" string\n- Dropdown/tagger: string or array of strings (multi-select)\n- Number/decimal: number or string representation\n- Date: string (ISO 8601 format)\n"),
      })).optional(),
      id: z.number().int().optional().describe("The ID of the sharing agreement"),
    }), z.array(z.object({
      custom_fields: z.array(z.object({
        id: z.number().int().describe("The ID of the custom field"),
        value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional().describe("The value to assign to the custom field.\nType depends on the field configuration:\n- Text/textarea: string\n- Checkbox: boolean or \"true\"/\"false\" string\n- Dropdown/tagger: string or array of strings (multi-select)\n- Number/decimal: number or string representation\n- Date: string (ISO 8601 format)\n"),
      })).optional(),
      id: z.number().int().optional().describe("The ID of the sharing agreement"),
    }))]).optional().describe("Write only. Sharing agreement configuration for the ticket.\nAccepts a single object or an array of objects.\n"),
    status: z.enum(["new", "open", "pending", "hold", "solved", "closed"]).optional().describe("The state of the ticket.\n\nIf your account has activated custom ticket statuses, this is the ticket's\nstatus category. See [custom ticket statuses](#custom-ticket-statuses)\n"),
    subject: z.string().nullable().optional().describe("The value of the subject field for this ticket. See [Subject](/api-reference/ticketing/tickets/tickets/#subject)\n"),
    submitter_id: z.number().int().nullable().optional().describe("The user who submitted the ticket. The submitter always becomes the\nauthor of the first comment on the ticket.\n\nIf not specified, defaults to the authenticated user.\n"),
    support_type: z.enum(["agent", "ai_agent"]).nullable().optional().describe("The type of support that handled the ticket"),
    suspended_ticket_id: z.number().int().optional().describe("Write only. The ID of the suspended ticket being recovered"),
    suspension_type_id: z.number().int().optional().describe("Write only. The suspension type ID when recovering a suspended ticket"),
    system_metadata: z.object({
      client: z.string().optional(),
      ip_address: z.string().optional(),
    }).optional().describe("Write only. System metadata for the ticket, typically set by internal clients"),
    tags: z.union([z.array(z.string()), z.string()]).optional().describe("The tags applied to this ticket. Unless otherwise specified, the [set tag](/api-reference/ticketing/ticket-management/tags/#set-tags) behavior is used, which overwrites and replaces existing tags"),
    tde_workspace: z.object({
      previous_workspace: z.object({
        id: z.number().int().optional(),
        title: z.string().optional(),
      }).optional(),
      type: z.enum(["ADD", "CHANGE", "DELETE"]).optional(),
      workspace: z.object({
        id: z.number().int().optional(),
        title: z.string().optional(),
      }).optional(),
    }).optional().describe("Write only. TDE workspace information for the ticket"),
    ticket_form_id: z.number().int().nullable().optional().describe("Enterprise only. The id of the ticket form to render for the ticket"),
    tpe_voice_comment: z.object({
      agent_id: z.number().int().nullable().optional(),
      answering_machine_detection_status: z.string().nullable().optional(),
      app_id: z.number().int().optional(),
      app_name: z.string().nullable().optional(),
      author_id: z.number().int().optional(),
      call_connected_at: z.string().datetime().nullable().optional(),
      call_disposition: z.string().nullable().optional(),
      call_ended_at: z.string().datetime().nullable().optional(),
      call_id: z.number().int().optional(),
      call_recording_consent: z.string().nullable().optional(),
      call_recording_consent_action: z.string().nullable().optional(),
      call_recording_consent_keypress: z.string().nullable().optional(),
      call_started_at: z.string().datetime().optional(),
      call_type: z.string().nullable().optional(),
      callback_number: z.string().nullable().optional(),
      callback_requested_at: z.string().datetime().nullable().optional(),
      completion_status: z.string().nullable().optional(),
      connection_attempts: z.number().int().nullable().optional(),
      consultation_time: z.number().int().nullable().optional(),
      direction: z.string().optional(),
      disconnection_reason: z.string().nullable().optional(),
      dnis: z.string().nullable().optional(),
      duration: z.number().int().nullable().optional(),
      end_user_id: z.number().int().nullable().optional(),
      end_user_location: z.string().nullable().optional(),
      exceeded_queue_time: z.boolean().nullable().optional(),
      extension: z.string().nullable().optional(),
      external_id: z.string().optional(),
      from_line: z.string().optional(),
      from_line_nickname: z.string().nullable().optional(),
      hold_time: z.number().int().nullable().optional(),
      intent: z.string().nullable().optional(),
      ivr_destination_group_name: z.string().nullable().optional(),
      ivr_time_spent: z.number().int().nullable().optional(),
      language: z.string().nullable().optional(),
      line_type: z.string().optional(),
      longest_hold_time: z.number().int().nullable().optional(),
      number_of_holds: z.number().int().nullable().optional(),
      outside_business_hours: z.boolean().nullable().optional(),
      overflowed_to: z.string().nullable().optional(),
      phone_name: z.string().nullable().optional(),
      public: z.boolean().optional(),
      quality_score: z.number().int().nullable().optional(),
      queue_name: z.string().nullable().optional(),
      queue_time: z.number().int().nullable().optional(),
      recorded: z.boolean().optional(),
      recording_time: z.number().int().nullable().optional(),
      recording_type: z.string().optional(),
      recording_url: z.string().nullable().optional(),
      sentiment_agent: z.string().nullable().optional(),
      sentiment_call: z.string().nullable().optional(),
      sentiment_customer: z.string().nullable().optional(),
      sentiment_trend: z.string().nullable().optional(),
      short_summary: z.string().nullable().optional(),
      summary: z.string().nullable().optional(),
      talk_time: z.number().int().nullable().optional(),
      time_to_answer: z.number().int().nullable().optional(),
      title: z.string().optional(),
      to_line: z.string().optional(),
      to_line_nickname: z.string().nullable().optional(),
      transcript: z.string().nullable().optional(),
      via_id: z.number().int().optional(),
      video_recording_url: z.string().nullable().optional(),
      voicemail: z.boolean().nullable().optional(),
      voicemail_requested_at: z.string().datetime().nullable().optional(),
      wait_time: z.number().int().nullable().optional(),
    }).optional().describe("Write only. A TPE voice comment for Talk Partner Edition tickets"),
    type: z.enum(["problem", "incident", "question", "task"]).nullable().optional().describe("The type of this ticket"),
    updated_at: z.string().datetime().optional().describe("When this record last got updated. It is updated only if the update generates a [ticket event](#incremental-ticket-event-export)"),
    updated_stamp: z.string().datetime().optional().describe("Write only. Datetime of last update received from API. See the `safe_update` property"),
    url: z.string().optional().describe("The API url of this ticket"),
    via: z.object({
      channel: z.union([z.string(), z.number().int()]).optional().describe("This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\".\nMay be a string name or an integer channel ID.\n"),
      source: z.object({
        from: z.object({
          address: z.string().nullable().optional(),
          id: z.number().int().nullable().optional(),
          name: z.string().nullable().optional(),
          title: z.string().nullable().optional(),
        }).optional(),
        rel: z.string().nullable().optional(),
        to: z.object({
          address: z.string().optional(),
          name: z.string().optional(),
        }).optional(),
      }).optional().describe("For some channels a source object gives more information about how or why the ticket or event was created\n"),
    }).optional().describe("An object explaining how the ticket was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)\n"),
    via_followup_source_id: z.number().int().optional().describe("Write only. The id of a closed ticket when creating a follow-up ticket. See [Creating a follow-up ticket](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#creating-a-follow-up-ticket)"),
    via_id: z.number().int().optional().describe("Write only. For more information, see the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference/)"),
    voice_comment: z.object({
      answered_by_id: z.number().int().nullable().optional().describe("The agent who answered the call"),
      call_duration: z.number().int().optional().describe("Duration of the call in seconds"),
      from: z.string().optional().describe("Incoming phone number"),
      location: z.string().nullable().optional().describe("Location of the caller"),
      recording_url: z.string().nullable().optional().describe("URL of the recording"),
      to: z.string().optional().describe("Dialed phone number"),
      transcription_text: z.string().nullable().optional().describe("Transcription of the call"),
    }).optional().describe("Write only. A voice comment for Talk tickets. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets/)"),
  }).optional(),
})

export const showTicketByMessagingConversationId = pikkuSessionlessFunc({
  description: "Returns the active ticket associated with the given Sunshine Conversations conversation id.\n\nA ticket is considered active when it's open and the messaging session is still in progress.\nA ticket becomes inactive when any of the following occur:\n\n* The ticket is closed\n* An agent ends the messaging session\n* A trigger ends the messaging session\n\n#### Allowed For\n* Agents with the `view_private_content` permission",
  input: ShowTicketByMessagingConversationIdInput,
  output: ShowTicketByMessagingConversationIdOutput,
  errors: [NotFoundError],
  func: async ({ zendesk }, data) => {
    return zendesk.call("GET", "/api/v2/tickets/messaging/conversations/{conversation_id}/ticket", data) as any
  },
})
