import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const TicketBulkImportInput = z.object({
  archive_immediately: z.boolean().optional().describe("If `true`, any ticket created with a `closed` status bypasses the normal ticket lifecycle and will be created directly in your ticket archive"),
  tickets: z.array(z.object({
  assignee_id: z.number().int().optional().describe("The agent currently assigned to the ticket"),
  brand_id: z.number().int().nullable().optional().describe("The id of the brand this ticket is associated with. If not specified, the ticket is assigned to the default brand"),
  collaborators: z.array(z.object({
    email: z.string().email().optional(),
    name: z.string().optional(),
  })).optional().describe("Users to add as cc's when creating a ticket. See [Setting Collaborators](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#setting-collaborators)"),
  comment: z.object({
    value: z.string().optional().describe("The comment string value"),
    add_short_url: z.boolean().optional().describe("Internal flag for adding short URLs to the comment"),
    attachments: z.array(z.object({
      content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
      content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
      deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
      file_name: z.string().optional().describe("The name of the image file"),
      height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
      id: z.number().int().optional().describe("Automatically assigned when created"),
      inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
      malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
      malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
      mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
      size: z.number().int().optional().describe("The size of the image file in bytes"),
      url: z.string().optional().describe("A URL to access the attachment details"),
      width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      thumbnails: z.array(z.object({
        content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
        content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
        deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
        file_name: z.string().optional().describe("The name of the image file"),
        height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
        id: z.number().int().optional().describe("Automatically assigned when created"),
        inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
        malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
        malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
        mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
        size: z.number().int().optional().describe("The size of the image file in bytes"),
        url: z.string().optional().describe("A URL to access the attachment details"),
        width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      })).optional().describe("An array of attachment objects. Note that photo thumbnails do not have thumbnails"),
    })).optional().describe("Attachments, if any. See [Attachment](/api-reference/ticketing/tickets/ticket-attachments/)"),
    audit_id: z.number().int().optional().describe("The id of the ticket audit record. See [Show Audit](/api-reference/ticketing/tickets/ticket_audits/#show-audit)"),
    author_id: z.number().int().nullable().optional().describe("The id of the comment author. If null or omitted on create, defaults to the authenticated user. See [Author id](#author-id)"),
    body: z.string().optional().describe("The comment string. See [Bodies](#bodies)"),
    channel_back: z.string().optional().describe("Internal channel back identifier for the comment"),
    channel_source_id: z.string().nullable().optional().describe("Internal channel source identifier for the comment"),
    created_at: z.string().datetime().optional().describe("The time the comment was created"),
    html_body: z.string().optional().describe("The comment formatted as HTML. See [Bodies](#bodies)"),
    id: z.number().int().optional().describe("Automatically assigned when the comment is created"),
    metadata: z.record(z.string(), z.unknown()).optional().describe("System information (web client, IP address, etc.) and comment flags, if any. See [Comment flags](#comment-flags)"),
    plain_body: z.string().optional().describe("The comment presented as plain text. See [Bodies](#bodies)"),
    public: z.boolean().optional().describe("true if a public comment; false if an internal note. The initial value set on ticket creation persists for any additional comment unless you change it"),
    translate_to: z.string().nullable().optional().describe("The locale code to translate the comment body to."),
    type: z.string().optional().describe("`Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)"),
    uploads: z.array(z.string()).optional().describe("List of tokens received from [uploading files](/api-reference/ticketing/tickets/ticket-attachments/#upload-files) for comment attachments. The files are attached by creating or updating tickets with the tokens. See [Attaching files](/api-reference/ticketing/tickets/tickets/#attaching-files) in Tickets"),
    via: z.object({
      channel: z.string().optional().describe("This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\""),
      source: z.record(z.string(), z.unknown()).optional().describe("For some channels a source object gives more information about how or why the ticket or event was created"),
    }).optional().describe("Describes how the object was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)"),
  }).optional(),
  comments: z.array(z.object({
    value: z.string().optional().describe("The comment string value"),
    add_short_url: z.boolean().optional().describe("Internal flag for adding short URLs to the comment"),
    attachments: z.array(z.object({
      content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
      content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
      deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
      file_name: z.string().optional().describe("The name of the image file"),
      height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
      id: z.number().int().optional().describe("Automatically assigned when created"),
      inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
      malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
      malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
      mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
      size: z.number().int().optional().describe("The size of the image file in bytes"),
      url: z.string().optional().describe("A URL to access the attachment details"),
      width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      thumbnails: z.array(z.object({
        content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
        content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
        deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
        file_name: z.string().optional().describe("The name of the image file"),
        height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
        id: z.number().int().optional().describe("Automatically assigned when created"),
        inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
        malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
        malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
        mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
        size: z.number().int().optional().describe("The size of the image file in bytes"),
        url: z.string().optional().describe("A URL to access the attachment details"),
        width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      })).optional().describe("An array of attachment objects. Note that photo thumbnails do not have thumbnails"),
    })).optional().describe("Attachments, if any. See [Attachment](/api-reference/ticketing/tickets/ticket-attachments/)"),
    audit_id: z.number().int().optional().describe("The id of the ticket audit record. See [Show Audit](/api-reference/ticketing/tickets/ticket_audits/#show-audit)"),
    author_id: z.number().int().nullable().optional().describe("The id of the comment author. If null or omitted on create, defaults to the authenticated user. See [Author id](#author-id)"),
    body: z.string().optional().describe("The comment string. See [Bodies](#bodies)"),
    channel_back: z.string().optional().describe("Internal channel back identifier for the comment"),
    channel_source_id: z.string().nullable().optional().describe("Internal channel source identifier for the comment"),
    created_at: z.string().datetime().optional().describe("The time the comment was created"),
    html_body: z.string().optional().describe("The comment formatted as HTML. See [Bodies](#bodies)"),
    id: z.number().int().optional().describe("Automatically assigned when the comment is created"),
    metadata: z.record(z.string(), z.unknown()).optional().describe("System information (web client, IP address, etc.) and comment flags, if any. See [Comment flags](#comment-flags)"),
    plain_body: z.string().optional().describe("The comment presented as plain text. See [Bodies](#bodies)"),
    public: z.boolean().optional().describe("true if a public comment; false if an internal note. The initial value set on ticket creation persists for any additional comment unless you change it"),
    translate_to: z.string().nullable().optional().describe("The locale code to translate the comment body to."),
    type: z.string().optional().describe("`Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)"),
    uploads: z.array(z.string()).optional().describe("List of tokens received from [uploading files](/api-reference/ticketing/tickets/ticket-attachments/#upload-files) for comment attachments. The files are attached by creating or updating tickets with the tokens. See [Attaching files](/api-reference/ticketing/tickets/tickets/#attaching-files) in Tickets"),
    via: z.object({
      channel: z.string().optional().describe("This tells you how the ticket or event was created. Examples: \"web\", \"mobile\", \"rule\", \"system\""),
      source: z.record(z.string(), z.unknown()).optional().describe("For some channels a source object gives more information about how or why the ticket or event was created"),
    }).optional().describe("Describes how the object was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)"),
  })).optional().describe("The conversation between requesters, collaborators, and agents"),
  created_at: z.string().datetime().optional().describe("The time the ticket was created (for historical imports)"),
  custom_fields: z.array(z.object({
    id: z.number().int().describe("The ID of the custom field"),
    value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional().describe("The value to assign to the custom field.\nType depends on the field configuration:\n- Text/textarea: string\n- Checkbox: boolean or \"true\"/\"false\" string\n- Dropdown/tagger: string or array of strings (multi-select)\n- Number/decimal: number or string representation\n- Date: string (ISO 8601 format)\n"),
  })).optional().describe("Custom field values to set on the ticket.\nEach entry specifies a field ID and its value.\n"),
  custom_status_id: z.number().int().optional().describe("The custom ticket status id of the ticket"),
  description: z.string().optional().describe("Read-only first comment on the ticket. When [creating a ticket](#create-ticket), use `comment` to set the description. See [Description and first comment](#description-and-first-comment)"),
  email_ccs: z.array(z.object({
    action: z.enum(["put", "delete"]).optional(),
    user_email: z.string().optional(),
    user_id: z.number().int().optional(),
    user_name: z.string().optional(),
  })).nullable().optional().describe("An array of objects that represent agent or end users email CCs to add or delete from the ticket. See [Setting email CCs](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#setting-email-ccs)"),
  external_id: z.string().optional().describe("An id you can use to link Zendesk Support tickets to local records"),
  followers: z.array(z.object({
    action: z.enum(["put", "delete"]).optional(),
    user_email: z.string().email().optional(),
    user_id: z.number().int().optional(),
    user_name: z.string().nullable().optional(),
  })).optional().describe("An array of objects that represent agent followers to add or delete from the ticket. See [Setting followers](/documentation/ticketing/managing-tickets/creating-and-updating-tickets#setting-followers)"),
  group_id: z.number().int().optional().describe("The group this ticket is assigned to"),
  priority: z.enum(["urgent", "high", "normal", "low"]).optional().describe("The urgency with which the ticket should be addressed."),
  recipient: z.string().optional().describe("The original recipient e-mail address of the ticket"),
  requester_id: z.number().int().optional().describe("The user who requested this ticket"),
  solved_at: z.string().datetime().optional().describe("The time the ticket was solved (for historical imports)"),
  status: z.enum(["new", "open", "pending", "hold", "solved", "closed"]).optional().describe("The state of the ticket"),
  subject: z.string().optional().describe("The value of the subject field for this ticket"),
  tags: z.array(z.string()).optional().describe("The array of tags applied to this ticket"),
  updated_at: z.string().datetime().optional().describe("The time the ticket was last updated (for historical imports)"),
  via: z.object({
    channel: z.string().optional().describe("This tells you how the ticket or event was created"),
    source: z.record(z.string(), z.unknown()).optional().describe("For some channels a source object gives more information about how or why the ticket or event was created"),
  }).optional().describe("An object explaining how the ticket was created. See the [Via object reference](/documentation/ticketing/reference-guides/via-object-reference)\n"),
})).optional(),
})

export const TicketBulkImportOutput = z.object({
  job_status: z.object({
    id: z.string().optional().describe("Automatically assigned when the job is queued"),
    job_type: z.string().optional().describe("The type of the job"),
    message: z.string().nullable().optional().describe("Message from the job worker, if any"),
    progress: z.number().int().nullable().optional().describe("Number of tasks that have already been completed"),
    results: z.union([z.array(z.union([z.object({
      id: z.number().int().describe("the id of the new resource"),
      index: z.number().int().describe("the index number of the resul"),
    }), z.object({
      action: z.string().describe("the action the job attempted (`\"action\": \"update\"`)\n"),
      id: z.number().int().describe("the id of the resource the job attempted to update"),
      status: z.string().describe("the status (`\"status\": \"Updated\"`)\n"),
      success: z.boolean().describe("whether the action was successful or not (`\"success\": true`)\n"),
    }), z.object({
      action: z.string().describe("The action the job attempted (`\"action\": \"update\"`)"),
      details: z.string().describe("The details of the error"),
      error: z.string().describe("The error message"),
      id: z.number().int().describe("The id of the resource the job attempted to update"),
      success: z.boolean().describe("Whether the action was successful or not (`\"success\": true`)"),
    })])), z.object({
      success: z.boolean().describe("Whether the action was successful or not"),
    })]).optional().describe("Result data from processed tasks. See [Results](#results) below"),
    status: z.string().optional().describe("The current status. One of the following: \"queued\", \"working\", \"failed\", \"completed\""),
    total: z.number().int().nullable().optional().describe("The total number of tasks this job is batching through"),
    url: z.string().optional().describe("The URL to poll for status updates"),
  }).optional(),
})

export const ticketBulkImport = pikkuSessionlessFunc({
  description: "Accepts an array of up to 100 ticket objects.\n\n#### Allowed For\n\n* Admins",
  input: TicketBulkImportInput,
  output: TicketBulkImportOutput,
  func: async ({ zendesk }, data) => {
    return zendesk.call("POST", "/api/v2/imports/tickets/create_many", data) as any
  },
})
