import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const UpdateAccountSettingsOutput = z.object({
  settings: z.object({
    active_features: z.object({
      agent_forwarding: z.boolean().optional(),
      allow_ccs: z.boolean().optional(),
      allow_email_template_customization: z.boolean().optional(),
      automatic_answers: z.boolean().optional(),
      bcc_archiving: z.boolean().optional(),
      benchmark_opt_out: z.boolean().optional(),
      business_hours: z.boolean().optional(),
      chat: z.boolean().optional(),
      chat_about_my_ticket: z.boolean().optional(),
      csat_reason_code: z.boolean().optional(),
      custom_dkim_domain: z.boolean().optional(),
      customer_context_as_default: z.boolean().optional(),
      customer_satisfaction: z.boolean().optional(),
      customer_satisfaction_survey: z.boolean().optional(),
      dynamic_contents: z.boolean().optional(),
      explore: z.boolean().optional(),
      explore_on_support_ent_plan: z.boolean().optional(),
      explore_on_support_pro_plan: z.boolean().optional(),
      facebook: z.boolean().optional(),
      facebook_login: z.boolean().optional(),
      fallback_composer: z.boolean().optional(),
      forum_analytics: z.boolean().optional(),
      good_data_and_explore: z.boolean().optional(),
      google_login: z.boolean().optional(),
      is_abusive: z.boolean().optional(),
      light_agents: z.boolean().optional(),
      markdown: z.boolean().optional(),
      on_hold_status: z.boolean().optional(),
      organization_access_enabled: z.boolean().optional(),
      rich_content_in_emails: z.boolean().optional(),
      sandbox: z.boolean().optional(),
      satisfaction_prediction: z.boolean().optional(),
      suspended_ticket_notification: z.boolean().optional(),
      ticket_forms: z.boolean().optional(),
      ticket_tagging: z.boolean().optional(),
      topic_suggestion: z.boolean().optional(),
      twitter: z.boolean().optional(),
      twitter_login: z.boolean().optional(),
      user_org_fields: z.boolean().optional(),
      user_tagging: z.boolean().optional(),
      voice: z.boolean().optional(),
    }).optional().describe("The active features for an account. See [Active Features](#active-features)"),
    agents: z.object({
      agent_home: z.boolean().optional(),
      agent_workspace: z.boolean().optional(),
      aw_self_serve_migration_enabled: z.boolean().optional(),
      focus_mode: z.boolean().optional(),
      idle_timeout_enabled: z.boolean().optional(),
      unified_agent_statuses: z.boolean().optional(),
    }).optional().describe("Configuration for the agent workspace. See [Agents](#agents)"),
    api: z.object({
      accepted_api_agreement: z.boolean().optional(),
      api_password_access_end_users: z.boolean().optional(),
      api_token_access: z.string().optional(),
    }).optional().describe("API configuration options. See [API](#api)"),
    apps: z.object({
      create_private: z.boolean().optional(),
      create_public: z.boolean().optional(),
      use: z.boolean().optional(),
    }).optional().describe("Apps configuration options. See [Apps](#apps)"),
    billing: z.object({
      backend: z.string().optional(),
    }).optional().describe("Billing configuration options. See [Billing](#billing)"),
    branding: z.object({
      favicon_url: z.string().nullable().optional(),
      header_color: z.string().optional(),
      header_logo_url: z.string().nullable().optional(),
      page_background_color: z.string().optional(),
      tab_background_color: z.string().optional(),
      text_color: z.string().optional(),
    }).optional().describe("Branding settings. See [Branding](#branding)"),
    brands: z.object({
      default_brand_id: z.number().int().optional(),
      end_user_across_brand_requests: z.boolean().optional(),
      end_user_upgrade_brand_association_behavior: z.string().optional().describe("Controls how end users are associated with brands when upgraded to agents."),
      new_agent_brand_association_behavior: z.string().optional().describe("Controls how new agents are associated with brands. Determines the default brand assignment for newly created agents."),
      require_brand_on_new_tickets: z.boolean().optional(),
    }).optional().describe("Brand settings. See [Brands](#brands)"),
    cdn: z.object({
      cdn_provider: z.string().optional(),
      fallback_cdn_provider: z.string().optional(),
      hosts: z.array(z.object({
        name: z.string().optional(),
        url: z.string().optional(),
      })).optional(),
    }).optional().describe("CDN settings"),
    chat: z.object({
      available: z.boolean().optional(),
      enabled: z.boolean().optional(),
      integrated: z.boolean().optional(),
      maximum_request_count: z.number().int().optional(),
      welcome_message: z.string().optional(),
    }).optional().describe("Zendesk Chat settings. See [Chat](#chat)"),
    cross_sell: z.object({
      show_chat_tooltip: z.boolean().optional(),
      xsell_source: z.string().nullable().optional(),
    }).optional().describe("Cross Sell settings"),
    device_metadata: z.object({
      enabled: z.boolean().optional(),
      hide_ip: z.boolean().optional(),
      hide_location: z.boolean().optional(),
    }).optional().describe("End user device settings. See [Device Metadata](#device-metadata)"),
    email: z.object({
      accept_wildcard_emails: z.boolean().optional(),
      custom_dkim_domain: z.boolean().optional(),
      email_sender_authentication: z.boolean().optional().describe("Whether incoming email is subjected to sender authentication checks (SPF, DKIM). This setting is deprecated and will be removed soon. It can still be turned on, but after it's on you can't turn it off"),
      email_sender_authentication_profile: z.enum(["default", "enhanced"]).optional().describe("The sender authentication profile in use."),
      email_status: z.boolean().optional().describe("Whether email status and delivery information is shown in the Agent Workspace"),
      email_template_photos: z.boolean().optional(),
      email_template_selection: z.boolean().optional(),
      gmail_actions: z.boolean().optional(),
      html_mail_template: z.string().optional(),
      mail_delimiter: z.string().optional(),
      modern_email_template: z.boolean().optional(),
      multi_recipient_email_tickets: z.boolean().optional(),
      no_mail_delimiter: z.boolean().optional(),
      personalized_replies: z.boolean().optional(),
      rich_content_in_emails: z.boolean().optional(),
      send_gmail_messages_via_gmail: z.boolean().optional(),
      text_mail_template: z.string().optional(),
    }).optional().describe("Email settings"),
    google_apps: z.object({
      has_google_apps: z.boolean().optional(),
      has_google_apps_admin: z.boolean().optional(),
    }).optional().describe("Google Apps configuration. See [G Suite](#g-suite)"),
    groups: z.object({
      check_group_name_uniqueness: z.boolean().optional(),
    }).optional().describe("Group configuration"),
    knowledge: z.object({
      default_search_filters_brands: z.string().optional(),
      default_search_filters_categories: z.string().optional(),
      default_search_filters_external_content_sources: z.string().optional(),
      default_search_filters_locales: z.string().optional(),
      default_search_filters_sections: z.string().optional(),
      generative_answers: z.boolean().optional(),
      require_article_templates: z.boolean().optional(),
      search_articles: z.boolean().optional(),
      search_community_posts: z.boolean().optional(),
      search_external_content: z.boolean().optional(),
    }).optional().describe("Account's knowledge management and search capabilities. See [Knowledge](#knowledge)"),
    limits: z.object({
      attachment_size: z.number().int().optional(),
    }).optional().describe("Account limits configuration. See [Limits](#limits)"),
    localization: z.object({
      locale_ids: z.array(z.number().int()).optional(),
    }).optional().describe("Internationalization configuration settings. See [Localization](#localization)"),
    lotus: z.object({
      pod_id: z.number().int().optional(),
      prefer_lotus: z.boolean().optional(),
      reporting: z.boolean().optional(),
    }).optional().describe("Support UI settings. See [Lotus](#lotus)"),
    messaging_inactivity: z.object({
      default_localized_messages: z.object({
        pre_solved_message_1: z.string().optional().describe("The first pre-solved message"),
        pre_solved_message_2: z.string().optional().describe("The second pre-solved message"),
        solved_message: z.string().optional().describe("The solved message"),
      }).optional(),
      enabled: z.boolean().optional().describe("Whether the messaging inactivity feature is enabled"),
      end_session: z.boolean().optional().describe("Whether messaging session should end with the final reminder"),
      reminders: z.array(z.object({
        message: z.string().describe("Mandatory message for the reminder"),
        tags: z.array(z.string()).optional().describe("Array of strings, tags added to ticket with each reminder. Can be empty"),
        ticket_status_id: z.number().int().nullable().optional().describe("Ticket status id, available and mandatory for the 2nd and 3rd reminders, if the reminder is configured. The field can be null to indicate no status change"),
        timeout: z.number().int().nullable().optional().describe("Reminder timeout in seconds, available and mandatory for the 2nd and 3rd reminders, if the reminder is configured"),
      })).optional(),
      ticket_status_id: z.number().int().optional().describe("Ticket status id to apply on the ticket when it is marked as inactive"),
      timeout: z.number().int().optional().describe("Timeout in minutes after which the ticket will be marked as inactive"),
    }).optional().describe("Auto-release capacity settings. See [Messaging inactivity](#messaging-inactivity)"),
    metrics: z.object({
      account_size: z.string().optional(),
    }).optional().describe("Account metrics settings. See [Metrics](#metrics)"),
    onboarding: z.object({
      checklist_onboarding_version: z.number().int().optional(),
      onboarding_segments: z.string().nullable().optional(),
      product_sign_up: z.string().nullable().optional(),
    }).optional().describe("Onboarding settings"),
    routing: z.object({
      autorouting_tag: z.string().optional(),
      enabled: z.boolean().optional(),
      max_email_capacity: z.number().int().optional(),
      max_messaging_capacity: z.number().int().optional(),
      reassignment_messaging_enabled: z.boolean().optional(),
      reassignment_messaging_timeout: z.number().int().optional(),
      reassignment_talk_timeout: z.number().int().optional(),
    }).optional().describe("Configuration for routing. See [Routing](#routing)"),
    rule: z.object({
      macro_most_used: z.boolean().optional(),
      macro_order: z.string().optional(),
      skill_based_filtered_views: z.array(z.record(z.string(), z.unknown())).optional(),
      using_skill_based_routing: z.boolean().optional(),
    }).optional().describe("Rules settings for triggers, macros, views, and automations. See [Rules](#rules)"),
    side_conversations: z.object({
      email_channel: z.boolean().optional(),
      msteams_channel: z.boolean().optional(),
      show_in_context_panel: z.boolean().optional(),
      slack_channel: z.boolean().optional(),
      tickets_channel: z.boolean().optional(),
    }).optional().describe("Side conversations settings"),
    statistics: z.object({
      forum: z.boolean().optional(),
      rule_usage: z.boolean().optional(),
      search: z.boolean().optional(),
    }).optional().describe("Account statistics settings. See [Statistics](#statistics)"),
    ticket_form: z.object({
      raw_ticket_forms_instructions: z.string().optional(),
      ticket_forms_instructions: z.string().optional(),
    }).optional().describe("Ticket form settings. See [Ticket Form](#ticket-form)"),
    tickets: z.object({
      accepted_new_collaboration_tos: z.boolean().optional(),
      agent_collision: z.boolean().optional(),
      agent_invitation_enabled: z.boolean().optional(),
      agent_ticket_deletion: z.boolean().optional(),
      allow_group_reset: z.boolean().optional(),
      assign_default_organization: z.boolean().optional(),
      assign_tickets_upon_solve: z.boolean().optional(),
      auto_translation_enabled: z.boolean().optional(),
      auto_updated_ccs_followers_rules: z.boolean().optional(),
      chat_sla_enablement: z.boolean().optional(),
      collaboration: z.boolean().optional(),
      comments_public_by_default: z.boolean().optional(),
      default_solved_ticket_reassignment_strategy: z.string().optional(),
      default_to_draft_mode: z.boolean().optional(),
      email_attachments: z.boolean().optional(),
      emoji_autocompletion: z.boolean().optional(),
      follower_and_email_cc_collaborations: z.boolean().optional(),
      has_color_text: z.boolean().optional(),
      is_first_comment_private_enabled: z.boolean().optional(),
      light_agent_email_ccs_allowed: z.boolean().optional(),
      list_empty_views: z.boolean().optional(),
      list_newest_comments_first: z.boolean().optional(),
      markdown_ticket_comments: z.boolean().optional(),
      maximum_personal_views_to_list: z.number().int().optional(),
      modern_ticket_reassignment: z.boolean().optional(),
      private_attachments: z.boolean().optional(),
      rich_text_comments: z.boolean().optional(),
      show_modern_ticket_reassignment: z.boolean().optional(),
      status_hold: z.boolean().optional(),
      tagging: z.boolean().optional(),
      using_skill_based_routing: z.boolean().optional(),
    }).optional().describe("Ticket settings. See [Tickets](#tickets)"),
    twitter: z.object({
      shorten_url: z.string().optional(),
    }).optional().describe("X (formerly Twitter) settings. See [X](#x-formerly-twitter)"),
    user: z.object({
      agent_created_welcome_emails: z.boolean().optional(),
      end_user_phone_number_validation: z.boolean().optional(),
      have_gravatars_enabled: z.boolean().optional(),
      language_selection: z.boolean().optional(),
      multiple_organizations: z.boolean().optional(),
      tagging: z.boolean().optional(),
      time_zone_selection: z.boolean().optional(),
    }).optional().describe("User settings. See [Users](#users)"),
    voice: z.object({
      agent_confirmation_when_forwarding: z.boolean().optional(),
      agent_wrap_up_after_calls: z.boolean().optional(),
      enabled: z.boolean().optional(),
      logging: z.boolean().optional(),
      maximum_queue_size: z.number().int().optional(),
      maximum_queue_wait_time: z.number().int().optional(),
      only_during_business_hours: z.boolean().optional(),
      outbound_enabled: z.boolean().optional(),
      recordings_public: z.boolean().optional(),
      uk_mobile_forwarding: z.boolean().optional(),
    }).optional().describe("Zendesk Talk settings. See [Voice](#voice)"),
  }).optional(),
})

export const updateAccountSettings = pikkuSessionlessFunc({
  description: "Updates settings for the account. See [JSON Format](#json-format) above for the settings you can update.\n\n#### Allowed For\n\n* Admins",
  output: UpdateAccountSettingsOutput,
  func: async ({ zendesk }) => {
    return zendesk.call("PUT", "/api/v2/account/settings") as any
  },
})
