import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku/addon/function'

export const UpdateManyUsersInput = z.object({
  ids: z.string().optional().describe("Id of the users to update. Comma separated. Example: \"1,2,3\""),
  external_ids: z.string().optional().describe("External Id of the users to update. Comma separated. Example: \"abc,def,ghi\""),
  brand_id: z.number().int().optional().describe("Scopes the bulk update of users matched by `external_ids` to a specific brand\nor to account-scoped (brand-less) users. Only applicable when the account\nhas brand separation enabled (`brand_user_separation_eap`). Ignored\notherwise so existing numeric callers continue to behave as before.\n\nAccepted values:\n\n* 0 — restrict the lookup to account-scoped (brand-less) users only.\n* A numeric brand id — restrict to that brand. Brands without\n  `user_separation` enabled collapse to account scope (0).\n\nRejected with \"400 Bad Request\":\n\n* \"all\" — cross-brand bulk update is not supported on this endpoint.\n* Any other non-numeric string.\n* A numeric brand id that does not exist on the account.\n* Combining `brand_id` with `ids` (use `external_ids` instead — `ids` are\n  globally unique so brand scoping is meaningless).\n\nWhen `external_ids` is provided without `brand_id`, the request defaults\nto account scope (0).\n. Example: 0"),
  body: z.union([z.object({
  user: z.object({
    agent_brand_ids: z.array(z.number().int()).nullable().optional().describe("The IDs of the brands the agent is assigned to"),
    alias: z.string().nullable().optional().describe("An alias displayed to end users"),
    custom_role_id: z.number().int().nullable().optional().describe("A custom role if the user is an agent on the Enterprise plan or above"),
    default_group_id: z.number().int().nullable().optional().describe("The id of the user's default group"),
    details: z.string().nullable().optional().describe("Any details you want to store about the user, such as an address"),
    email: z.string().optional().describe("The user's primary email address"),
    external_id: z.string().nullable().optional().describe("A unique identifier from another system"),
    group_id: z.number().int().nullable().optional().describe("The id of the user's default group. Alias for default_group_id"),
    identities: z.array(z.object({
      primary: z.boolean().optional().describe("If the identity is the primary identity. Writable only when creating, not when updating."),
      type: z.enum(["email", "twitter", "facebook", "google", "phone_number", "agent_forwarding", "any_channel", "foreign", "sdk", "messaging"]),
      value: z.string(),
      verification_method: z.enum(["none", "low", "sso", "embed", "full"]).optional().describe("Indicates the state of user identity verification."),
      verified: z.boolean().optional().describe("If the identity has been verified. Deprecated. Use `verification_method` as a more accurate representation of a user's state of verification."),
    })).optional(),
    language: z.string().nullable().optional().describe("The user's language preference. Alias for locale."),
    locale: z.string().nullable().optional().describe("The user's locale. A BCP-47 compliant tag for the locale. If both \"locale\" and \"locale_id\" are present on create or update, \"locale_id\" is ignored and only \"locale\" is used."),
    locale_id: z.number().int().nullable().optional().describe("The user's language identifier"),
    moderator: z.boolean().nullable().optional().describe("Designates whether the user has forum moderation capabilities"),
    name: z.string().optional().describe("The user's name"),
    notes: z.string().nullable().optional().describe("Any notes you want to store about the user"),
    only_private_comments: z.boolean().nullable().optional().describe("true if the user can only create private comments"),
    organization_id: z.number().int().nullable().optional().describe("The id of the user's organization"),
    organization_ids: z.array(z.number().int()).nullable().optional().describe("The ids of the user's organizations"),
    phone: z.string().nullable().optional().describe("The user's primary phone number"),
    photo: z.record(z.string(), z.unknown()).nullable().optional().describe("The user's profile picture"),
    remote_photo_url: z.string().nullable().optional().describe("A URL pointing to the user's profile picture"),
    role: z.string().optional().describe("The user's role"),
    shared_phone_number: z.boolean().nullable().optional().describe("Whether the phone number is shared or not"),
    signature: z.string().nullable().optional().describe("The user's signature. Only agents and admins can have signatures"),
    skip_verify_email: z.boolean().nullable().optional().describe("If true, the user won't receive a verification email"),
    suspended: z.boolean().nullable().optional().describe("If the user is suspended"),
    tags: z.array(z.string()).nullable().optional().describe("The user's tags"),
    ticket_restriction: z.string().nullable().optional().describe("Specifies which tickets the user has access to"),
    time_zone: z.string().nullable().optional().describe("The user's time zone"),
    user_fields: z.record(z.string(), z.unknown()).nullable().optional().describe("Values of custom fields in the user's profile"),
    verified: z.boolean().nullable().optional().describe("Any of the user's identities is verified"),
  }).describe("Input schema for updating a user. All fields are optional - only include\nthe fields you want to update.\n"),
}), z.object({
  users: z.array(z.union([z.object({
    active_brand_id: z.number().int().nullable().optional().describe("The id of the brand to assign to the user"),
    agent_brand_ids: z.array(z.number().int()).optional(),
    alias: z.string().nullable().optional().describe("An alias displayed to end users"),
    custom_role_id: z.number().int().nullable().optional().describe("A custom role if the user is an agent on the Enterprise plan or above"),
    default_group_id: z.number().int().nullable().optional().describe("The id of the user's default group"),
    details: z.string().nullable().optional().describe("Any details you want to store about the user, such as an address"),
    email: z.string().optional(),
    external_id: z.string().nullable().optional().describe("A unique identifier from another system"),
    group_id: z.number().int().nullable().optional().describe("The id of the user's default group. Alias for default_group_id"),
    group_ids: z.array(z.number().int()).optional().describe("The ids of the groups to assign to the user"),
    identities: z.array(z.object({
      primary: z.boolean().optional().describe("If the identity is the primary identity. Writable only when creating, not when updating."),
      type: z.enum(["email", "twitter", "facebook", "google", "phone_number", "agent_forwarding", "any_channel", "foreign", "sdk", "messaging"]),
      value: z.string(),
      verification_method: z.enum(["none", "low", "sso", "embed", "full"]).optional().describe("Indicates the state of user identity verification."),
      verified: z.boolean().optional().describe("If the identity has been verified. Deprecated. Use `verification_method` as a more accurate representation of a user's state of verification."),
    })).optional(),
    language: z.string().nullable().optional().describe("The user's language preference. Alias for locale."),
    locale: z.string().nullable().optional().describe("The user's locale. A BCP-47 compliant tag for the locale. If both \"locale\" and \"locale_id\" are present on create or update, \"locale_id\" is ignored and only \"locale\" is used."),
    locale_id: z.number().int().nullable().optional().describe("The user's language identifier"),
    moderator: z.boolean().nullable().optional().describe("Designates whether the user has forum moderation capabilities"),
    name: z.string(),
    notes: z.string().nullable().optional().describe("Any notes you want to store about the user"),
    only_private_comments: z.boolean().nullable().optional().describe("true if the user can only create private comments"),
    organization: z.object({
      name: z.string(),
    }).optional(),
    organization_id: z.number().int().nullable().optional().describe("The id of the user's organization"),
    organization_ids: z.array(z.number().int()).nullable().optional().describe("The ids of the user's organizations"),
    organization_name: z.string().nullable().optional().describe("The name of the user's organization (deprecated, use organization object instead)"),
    password: z.string().optional().describe("The user's password"),
    phone: z.string().nullable().optional().describe("The user's primary phone number"),
    remote_photo_url: z.string().nullable().optional().describe("A URL pointing to the user's profile picture"),
    role: z.string().optional(),
    separation: z.union([z.object({
      scope: z.literal("account"),
    }), z.object({
      brand_id: z.number().int().describe("The id of the brand to scope the end user to."),
      scope: z.literal("brand"),
    })]).optional().describe("Assigns the end user to a specific brand when brand separation is enabled.\nOnly applicable to end users (not agents or admins). Immutable after creation.\n"),
    shared_phone_number: z.boolean().nullable().optional().describe("Whether the phone number is shared or not"),
    signature: z.string().nullable().optional().describe("The user's signature. Only agents and admins can have signatures"),
    skip_verify_email: z.boolean().nullable().optional().describe("If true, the user won't receive a verification email"),
    suspended: z.boolean().nullable().optional().describe("If the user is suspended"),
    tags: z.array(z.string()).nullable().optional().describe("The user's tags"),
    ticket_restriction: z.string().nullable().optional().describe("Specifies which tickets the user has access to"),
    time_zone: z.string().nullable().optional().describe("The user's time zone"),
    user_fields: z.record(z.string(), z.unknown()).nullable().optional().describe("Values of custom fields in the user's profile"),
    verified: z.boolean().nullable().optional().describe("Any of the user's identities is verified"),
  }), z.object({
    active_brand_id: z.number().int().nullable().optional(),
    agent_brand_ids: z.array(z.number().int()).optional(),
    alias: z.string().nullable().optional(),
    custom_role_id: z.number().int().nullable().optional(),
    default_group_id: z.number().int().nullable().optional(),
    details: z.string().nullable().optional(),
    email: z.string().optional(),
    external_id: z.string().nullable().optional(),
    group_id: z.number().int().nullable().optional(),
    group_ids: z.array(z.number().int()).optional(),
    id: z.number().int().optional().describe("The user's id"),
    identities: z.array(z.object({
      primary: z.boolean().optional().describe("If the identity is the primary identity. Writable only when creating, not when updating."),
      type: z.enum(["email", "twitter", "facebook", "google", "phone_number", "agent_forwarding", "any_channel", "foreign", "sdk", "messaging"]),
      value: z.string(),
      verification_method: z.enum(["none", "low", "sso", "embed", "full"]).optional().describe("Indicates the state of user identity verification."),
      verified: z.boolean().optional().describe("If the identity has been verified. Deprecated. Use `verification_method` as a more accurate representation of a user's state of verification."),
    })).optional(),
    language: z.string().nullable().optional(),
    locale: z.string().nullable().optional(),
    locale_id: z.number().int().nullable().optional(),
    moderator: z.boolean().nullable().optional(),
    name: z.string().optional(),
    notes: z.string().nullable().optional(),
    only_private_comments: z.boolean().nullable().optional(),
    organization: z.object({
      name: z.string(),
    }).optional(),
    organization_id: z.number().int().nullable().optional(),
    organization_ids: z.array(z.number().int()).nullable().optional(),
    organization_name: z.string().nullable().optional(),
    password: z.string().optional().describe("The user's password"),
    phone: z.string().nullable().optional(),
    remote_photo_url: z.string().nullable().optional(),
    role: z.string().optional(),
    shared_phone_number: z.boolean().nullable().optional(),
    signature: z.string().nullable().optional(),
    skip_verify_email: z.boolean().nullable().optional(),
    suspended: z.boolean().nullable().optional(),
    tags: z.array(z.string()).nullable().optional(),
    ticket_restriction: z.string().nullable().optional(),
    time_zone: z.string().nullable().optional(),
    user_fields: z.record(z.string(), z.unknown()).nullable().optional().describe("Values of custom fields in the user's profile"),
    verified: z.boolean().nullable().optional(),
  })])),
})]),
})

export const UpdateManyUsersOutput = z.object({
  job_status: z.object({
    id: z.string().optional().describe("Automatically assigned when the job is queued"),
    job_type: z.string().optional().describe("The type of the job"),
    message: z.string().nullable().optional().describe("Message from the job worker, if any"),
    progress: z.number().int().nullable().optional().describe("Number of tasks that have already been completed"),
    results: z.union([z.array(z.union([z.object({
      id: z.number().int().describe("the id of the new resource"),
      index: z.number().int().describe("the index number of the resul"),
    }), z.object({
      action: z.string().describe("the action the job attempted (`\"action\": \"update\"`)\n"),
      id: z.number().int().describe("the id of the resource the job attempted to update"),
      status: z.string().describe("the status (`\"status\": \"Updated\"`)\n"),
      success: z.boolean().describe("whether the action was successful or not (`\"success\": true`)\n"),
    }), z.object({
      action: z.string().describe("The action the job attempted (`\"action\": \"update\"`)"),
      details: z.string().describe("The details of the error"),
      error: z.string().describe("The error message"),
      id: z.number().int().describe("The id of the resource the job attempted to update"),
      success: z.boolean().describe("Whether the action was successful or not (`\"success\": true`)"),
    })])), z.object({
      success: z.boolean().describe("Whether the action was successful or not"),
    })]).optional().describe("Result data from processed tasks. See [Results](#results) below"),
    status: z.string().optional().describe("The current status. One of the following: \"queued\", \"working\", \"failed\", \"completed\""),
    total: z.number().int().nullable().optional().describe("The total number of tasks this job is batching through"),
    url: z.string().optional().describe("The URL to poll for status updates"),
  }).optional(),
})

export const updateManyUsers = pikkuSessionlessFunc({
  input: UpdateManyUsersInput,
  output: UpdateManyUsersOutput,
  func: async ({ zendesk }, data) => {
    return zendesk.call("PUT", "/api/v2/users/update_many", data) as any
  },
})
