import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const UpdateCustomObjectFieldInput = z.object({
  custom_object_key: z.string().describe("The key of a custom object. Example: \"car\""),
  custom_object_field_key_or_id: z.string().describe("The key or id of a custom object field. Example: \"make\""),
})

export const UpdateCustomObjectFieldOutput = z.object({
  custom_object_field: z.object({
    active: z.boolean().optional().describe("If true, this field is available for use"),
    created_at: z.string().datetime().optional().describe("The time the field was created"),
    custom_field_options: z.array(z.object({
      allow_solving: z.boolean().optional().describe("Whether selecting this option allows solving the ticket when the field is required to solve"),
      id: z.number().int().optional().describe("Automatically assigned upon creation"),
      name: z.string().describe("Name of the dropdown option"),
      position: z.number().int().optional().describe("Position of the dropdown option"),
      raw_name: z.string().optional().describe("Raw name of the dropdown option"),
      url: z.string().optional().describe("URL of the dropdown option"),
      value: z.string().describe("Value of the dropdown option"),
    })).optional().describe("Required and presented for a custom field of type \"dropdown\". Each option is represented by an object with a `name` and `value` property"),
    description: z.string().optional().describe("User-defined description of this field's purpose"),
    id: z.number().int().optional().describe("Automatically assigned upon creation"),
    key: z.string().describe("A unique key that identifies this custom field. This is used for updating the field and referencing in placeholders. The key must consist of only letters, numbers, and underscores. It can't be only numbers"),
    position: z.number().int().optional().describe("Ordering of the field relative to other fields"),
    raw_description: z.string().optional().describe("The dynamic content placeholder, if present, or the `description` value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)"),
    raw_title: z.string().optional().describe("The dynamic content placeholder, if present, or the `title` value, if not. See [Dynamic Content Items](/api-reference/ticketing/ticket-management/dynamic_content/)"),
    regexp_for_validation: z.string().nullable().optional().describe("Regular expression field only. The validation pattern for a field value to be deemed valid"),
    relationship_filter: z.record(z.string(), z.unknown()).optional().describe("A filter definition that allows your autocomplete to filter down results"),
    system: z.boolean().optional().describe("If true, only active and position values of this field can be changed"),
    tag: z.string().optional().describe("Optional for custom field of type \"checkbox\"; not presented otherwise."),
    title: z.string().describe("The title of the custom field"),
    type: z.string().describe("The custom field type: \"checkbox\", \"currency\", \"date\", \"decimal\", \"dropdown\", \"integer\", [\"lookup\"](/api-reference/ticketing/lookup_relationships/lookup_relationships/), \"multiselect\", [\"parent\"](/api-reference/custom-data/custom-objects/custom_object_fields/#about-parent-relationship-fields) (custom objects only), \"regexp\", \"text\", or \"textarea\""),
    updated_at: z.string().datetime().optional().describe("The time of the last update of the field"),
    url: z.string().optional().describe("The URL for this resource"),
    properties: z.object({
      allowed_currencies: z.array(z.string()).optional().describe("An array containing exactly one [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code (for example, [\"USD\"]). The currency code can't be changed after the field is created."),
      autoincrement_enabled: z.boolean().optional().describe("Turns autonumbering on or off"),
      autoincrement_next_sequence: z.number().int().optional().describe("The next number in the autonumbering sequence. It can't be negative or less than the current autonumbering value"),
      autoincrement_padding: z.number().int().optional().describe("Sets the number of digits for autogenerated numbers. Valid values are 0-9"),
      autoincrement_prefix: z.string().optional().describe("A prefix to autogenerated numbers that can't exceed 30 characters"),
      cascade_permissions_enabled: z.boolean().optional().describe("Parent fields only. If true, permissions for the child object's records cascade from the parent record. When enabled, agents must provide a parent record context to list or search child records. Only one parent field per child object can have this setting enabled. Default: false."),
      is_unique: z.boolean().optional().describe("Turns uniqueness on or off"),
      rollup_aggregated_field: z.string().nullable().optional().describe("Roll-up fields only. The key of the field on the child object to aggregate. Not required for COUNT"),
      rollup_aggregated_field_title: z.string().optional().describe("Roll-up fields only. Read-only. The display title of the aggregated child field"),
      rollup_aggregation_type: z.enum(["COUNT", "SUM", "MIN", "MAX"]).optional().describe("Roll-up fields only. The aggregation operation to apply to child records. One of: \"COUNT\", \"SUM\", \"MIN\", \"MAX\""),
      rollup_child_object: z.string().optional().describe("Roll-up fields only. The Zendesk resource name (ZRN) of the child object whose records are aggregated. Example: \"zen:custom_object:order_item\". The child object must have a parent-child relationship with this field's object"),
      rollup_filter_criteria: z.record(z.string(), z.unknown()).nullable().optional().describe("Roll-up fields only. Optional filter conditions (using `all`/`any` arrays) to restrict which child records are included in the aggregation. Uses the same DSL as lookup relationship filters"),
    }).optional().describe("A set of field-specific properties. For the standard::name field, this includes autonumbering and uniqueness settings (which can't be used together). For currency fields, this includes the allowed currency code. For parent fields, includes the `cascade_permissions_enabled` setting. For roll-up summary fields, includes the aggregation configuration."),
    readonly: z.boolean().optional().describe("If true, the field value cannot be set or updated by API consumers. Currently only applies to roll-up summary fields, where the value is computed automatically."),
    relationship_target_type: z.string().optional().describe("A representation of what type of object the field references. For lookup fields, options are \"zen:user\", \"zen:organization\", \"zen:ticket\", \"zen:article\", \"zen:brand\", and \"zen:custom_object:{key}\" where key is a custom object key. For example \"zen:custom_object:apartment\". For parent fields, valid options are \"zen:user\", \"zen:organization\", \"zen:ticket\", and \"zen:custom_object:{key}\". Cannot be changed after creation."),
    required: z.boolean().optional().describe("If true, the field must have a value when creating or updating custom object records."),
  }).optional(),
})

export const updateCustomObjectField = pikkuSessionlessFunc({
  description: "Updates individual custom object fields. The updating rules are as follows:\n* Takes a `custom_object_field` object that specifies the properties to update.\n* The `key` property cannot be updated.\n* If updating a standard field, only the `title`, `description`, and `properties` attributes can be updated.\n* Standard name field is always required. Therefore, the `required` property for standard name field isn't editable.\n* The `properties` parameter is comprised of four parts and can't be changed if any records exist for the object.\n    * `autoincrement_enabled`: A Boolean that enables and disables autonumbering. Must be false if is_unique is true.\n    * `autoincrement_prefix`: A string value that is used as a prefix to the autogenerated numbers. It can't exceed 30 characters.\n    * `autoincrement_padding`: An integer specifying the starting number of digits in the autogenerated numbers. This value may be between 0-9. However, if you create records in excess of of these digits, additional digits are added as necessary.\n    * `autoincrement_next_sequence`: An integer that will be used as the next number in the autonumbering sequence. It can't be negative or less than the current autonumbering value.\n    * `is_unique`: A Boolean that enforces uniqueness for manually entered record names. When true, custom object record names must be unique. Must be false if autoincrement_enabled is true.\n\n#### Updating drop-down field options\n\nYou can also use the update endpoint to add, update, or remove options in a drop-down custom field. Updating field options for multi-select fields works exactly the same as drop-down field options.\n\n**Important**: Unless you want to remove some options, you must specify all existing options in any update request. Omitting an option removes it from the drop-down field, which removes its values from any tickets or macros.\n\nUse the `custom_field_options` attribute to update the options. The attribute consists of an array of option objects, with each object consisting of an `id`, `name`, and `value` property. The name and value properties correspond to the \"Title\" and \"Tag\" text boxes in the admin interface respectively. For new drop-down options, specify `\"id\":\"null\"`. Example request body:\n\n```json\n{\"custom_object_field\": {\n    \"custom_field_options\": [\n      {\"id\": \"null\", \"name\": \"Apple Pie\", \"value\": \"apple\"},\n      {\"id\": \"null\", \"name\": \"Pecan Pie\", \"value\": \"pecan\"}\n    ]\n  }\n}\n```\n\n#### Example Request\n\n```bash\ncurl https://{subdomain}.zendesk.com/api/v2/custom_objects/{custom_object_key}/fields/{custom_object_field_key_or_id}\n  -d '{\"ticket_field\": {\"custom_field_options\": [{\"name\": \"Apple Pie\", \"value\": \"apple\"}, {\"name\": \"Pecan Pie\", \"value\": \"pecan\"}]}}' \\\n  -H \"Content-Type: application/json\" -X PUT \\\n  -v -u {email_address}/token:{api_token}\n```\n#### Allowed For\n* Admins",
  input: UpdateCustomObjectFieldInput,
  output: UpdateCustomObjectFieldOutput,
  func: async ({ zendesk }, data) => {
    return zendesk.call("PATCH", "/api/v2/custom_objects/{custom_object_key}/fields/{custom_object_field_key_or_id}", data) as any
  },
})
