import { z } from 'zod'
import { pikkuSessionlessFunc } from '#pikku'

export const UpdateBrandInput = z.object({
  brand_id: z.number().int().describe("The ID of the brand. Example: 360002783572"),
  brand: z.object({
  active: z.boolean().optional().describe("If the brand is set as active"),
  brand_url: z.string().optional().describe("The url of the brand"),
  created_at: z.string().datetime().optional().describe("The time the brand was created"),
  default: z.boolean().optional().describe("Is the brand the default brand for this account"),
  has_help_center: z.boolean().optional().describe("If the brand has a Help Center"),
  help_center_state: z.enum(["enabled", "disabled", "restricted"]).optional().describe("The state of the Help Center"),
  host_mapping: z.string().optional().describe("The hostmapping to this brand, if any. Only admins view this property."),
  id: z.number().int().optional().describe("The ID automatically assigned when the brand is created"),
  is_deleted: z.boolean().optional().describe("If the brand object is deleted or not"),
  logo: z.object({
    content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
    content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
    deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
    file_name: z.string().optional().describe("The name of the image file"),
    height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
    id: z.number().int().optional().describe("Automatically assigned when created"),
    inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
    malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
    malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
    mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
    size: z.number().int().optional().describe("The size of the image file in bytes"),
    url: z.string().optional().describe("A URL to access the attachment details"),
    width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
    thumbnails: z.array(z.object({
      content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
      content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
      deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
      file_name: z.string().optional().describe("The name of the image file"),
      height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
      id: z.number().int().optional().describe("Automatically assigned when created"),
      inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
      malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
      malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
      mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
      size: z.number().int().optional().describe("The size of the image file in bytes"),
      url: z.string().optional().describe("A URL to access the attachment details"),
      width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
    })).optional().describe("An array of attachment objects. Note that photo thumbnails do not have thumbnails"),
  }).optional().describe("A file represented as an [Attachment](/api-reference/ticketing/tickets/ticket-attachments/) object"),
  name: z.string().describe("The name of the brand"),
  signature_template: z.string().optional().describe("The signature template for a brand"),
  subdomain: z.string().describe("The subdomain of the brand"),
  ticket_form_ids: z.array(z.number().int()).optional().describe("The ids of ticket forms that are available for use by a brand"),
  updated_at: z.string().datetime().optional().describe("The time of the last update of the brand"),
  url: z.string().optional().describe("The API url of this brand"),
  user_separation: z.enum(["account", "brand"]).optional().describe("The user separation scope for the brand. When set to \"brand\", users created on this brand are isolated to it. When set to \"account\", users are shared across all account-scoped brands."),
}).optional(),
})

export const UpdateBrandOutput = z.object({
  brand: z.object({
    active: z.boolean().optional().describe("If the brand is set as active"),
    brand_url: z.string().optional().describe("The url of the brand"),
    created_at: z.string().datetime().optional().describe("The time the brand was created"),
    default: z.boolean().optional().describe("Is the brand the default brand for this account"),
    has_help_center: z.boolean().optional().describe("If the brand has a Help Center"),
    help_center_state: z.enum(["enabled", "disabled", "restricted"]).optional().describe("The state of the Help Center"),
    host_mapping: z.string().optional().describe("The hostmapping to this brand, if any. Only admins view this property."),
    id: z.number().int().optional().describe("The ID automatically assigned when the brand is created"),
    is_deleted: z.boolean().optional().describe("If the brand object is deleted or not"),
    logo: z.object({
      content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
      content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
      deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
      file_name: z.string().optional().describe("The name of the image file"),
      height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
      id: z.number().int().optional().describe("Automatically assigned when created"),
      inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
      malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
      malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
      mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
      size: z.number().int().optional().describe("The size of the image file in bytes"),
      url: z.string().optional().describe("A URL to access the attachment details"),
      width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      thumbnails: z.array(z.object({
        content_type: z.string().optional().describe("The content type of the image. Example value: \"image/png\""),
        content_url: z.string().optional().describe("A full URL where the attachment image file can be downloaded. The file may be hosted externally so take care not to inadvertently send Zendesk authentication credentials. See [Working with url properties](/documentation/api-basics/best-practices/working-with-url-properties/)"),
        deleted: z.boolean().optional().describe("If true, the attachment has been deleted"),
        file_name: z.string().optional().describe("The name of the image file"),
        height: z.number().int().optional().describe("The height of the image file in pixels. If height is unknown, returns null"),
        id: z.number().int().optional().describe("Automatically assigned when created"),
        inline: z.boolean().optional().describe("If true, the attachment is excluded from the attachment list and the attachment's URL\ncan be referenced within the comment of a ticket. Default is false\n"),
        malware_access_override: z.boolean().optional().describe("If true, you can download an attachment flagged as malware. If false, you can't download such an attachment."),
        malware_scan_result: z.string().optional().describe("The result of the malware scan. There is a delay between the time the attachment is uploaded and when the malware scan is completed. Usually the scan is done within a few seconds, but high load conditions can delay the scan results. Possible values: \"malware_found\", \"malware_not_found\", \"failed_to_scan\", \"not_scanned\""),
        mapped_content_url: z.string().optional().describe("The URL the attachment image file has been mapped to"),
        size: z.number().int().optional().describe("The size of the image file in bytes"),
        url: z.string().optional().describe("A URL to access the attachment details"),
        width: z.number().int().optional().describe("The width of the image file in pixels. If width is unknown, returns null"),
      })).optional().describe("An array of attachment objects. Note that photo thumbnails do not have thumbnails"),
    }).optional().describe("A file represented as an [Attachment](/api-reference/ticketing/tickets/ticket-attachments/) object"),
    name: z.string().describe("The name of the brand"),
    signature_template: z.string().optional().describe("The signature template for a brand"),
    subdomain: z.string().describe("The subdomain of the brand"),
    ticket_form_ids: z.array(z.number().int()).optional().describe("The ids of ticket forms that are available for use by a brand"),
    updated_at: z.string().datetime().optional().describe("The time of the last update of the brand"),
    url: z.string().optional().describe("The API url of this brand"),
    user_separation: z.enum(["account", "brand"]).optional().describe("The user separation scope for the brand. When set to \"brand\", users created on this brand are isolated to it. When set to \"account\", users are shared across all account-scoped brands."),
  }).optional(),
})

export const updateBrand = pikkuSessionlessFunc({
  description: "Returns an updated brand.\n\n#### Allowed for\n* Admins\n\n#### Updating a Brand's Image\nUse `PUT /api/v2/brands/{brand_id}/logo` to set or replace the brand logo,\nand `DELETE /api/v2/brands/{brand_id}/logo` to remove it.",
  input: UpdateBrandInput,
  output: UpdateBrandOutput,
  func: async ({ zendesk }, data) => {
    return zendesk.call("PUT", "/api/v2/brands/{brand_id}", data) as any
  },
})
